package.json

upgrade project version from 1.18.0 to 1.19.0
No
No
<hr />

[NO-ISSUE] chore: upgrade project version from 1.18.0 to 1.19.0

---

.github/workflows/deploy-production.yml

updated version azion cli to version 1.34.1 in workflow
NO
NO
<hr />

[NO-ISSUE] chore: updated version azion cli to version 1.34.1 in workflow

---

.github/workflows/deploy-production.yml
.github/workflows/deploy-stage.yml

update Azion CLI to version 1.34.2 in deployment workflows
<hr />

[NO-ISSUE] chore: update Azion CLI to version 1.34.2 in deployment workflows

---

README.md
src/plugins/factories/stripe-integration-factory.js
src/tests/plugins/factories/stripe-integration-factory.test.js

* renamed to standardize with other stripe variable names
<hr />

[UXE-4303] chore: rename dev stripe token env var

---

package.json

Upgrade project version from 1.19.0 to 1.19.1
No
No
<hr />

[NO-ISSUE] chore: upgrade project version from 1.19.0 to 1.19.1

---

src/services/waf-rules-services/create-waf-rules-allowed-tuning-service.js
src/services/waf-rules-services/list-waf-rules-tuning-service.js
src/templates/list-table-block/index.vue
src/tests/services/waf-rules-services/create-waf-rules-allowed-tuning-service.test.js
src/tests/services/waf-rules-services/list-waf-rules-tuning-service.test.js
src/views/WafRules/ListWafRulesTuning.vue

[UXE-4204] fix:  waf tunning does not display attack logs
https://github.com/user-attachments/assets/db0eb4ed-348e-41e5-ba2d-eaa708d49289
<hr />
[UXE-4204]: https://aziontech.atlassian.net/browse/UXE-4204?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[UXE-4204] fix:  waf tunning does not display attack logs

---

src/templates/sidebar-block/index.vue

* added middle mouse click in sidebar products to open in another tabs
no
no
<hr />

[UXE-1872] feat: added middle mouse click in sidebar products

---

.github/workflows/pre-merge.yml
sonar-project.properties

Activate sonarcloud on workflow
No
No
<hr />

[QA-2093] feat: activate sonarcloud on workflow

---

.github/workflows/deploy-stage.yml
src/tests/services/billing-services/load-your-service-plan-service.test.js

fix: renaming the recaptcha key for the stage environment and adding dynamic date in the test
<hr />

[UXE-4334] fix: renaming the recaptcha key for the stage environment and adding dynamic date in the test

---

src/services/billing-services/list-service-and-products-changes.js
src/services/billing-services/load-invoice-data-service.js

Refined the query to support both billID and invoiceNumber, ensuring correct type handling for each parameter.
NO
NO
<hr />

[UXE-4348] feat: refined the query to handle billID and invoiceNumber with correct typing

---

src/tests/services/billing-services/load-your-service-plan-service.test.js
src/views/Domains/CreateView.vue
src/views/Domains/EditView.vue
src/views/Domains/FormFields/FormFieldsCreateDomains.vue
src/views/Domains/FormFields/FormFieldsEditDomains.vue

* added loading boolean to edge applications selector in create domains - fixed infinite loading
https://github.com/user-attachments/assets/cd5b633c-c2a8-4925-93d3-5bf794af634e
<hr />

[UXE-4333] refactor: loading to edge application selector in domains

---

src/helpers/convert-number.js
src/helpers/index.js
src/services/billing-services/list-payment-methods-service.js
src/services/billing-services/list-service-and-products-changes.js
src/services/billing-services/load-current-invoice-service.js
src/services/billing-services/load-invoice-data-service.js
src/services/billing-services/load-your-service-plan-service.js
src/tests/helpers/convert-number.test.js
src/tests/services/billing-services/list-service-and-products-changes.test.js
src/tests/services/billing-services/load-your-service-plan-service.test.js
src/views/Billing/InvoiceDetailsView.vue
src/views/Billing/TabsView.vue

- add format currency and unit value in table services and products in invoice datails.
- add skelleton in card invoice details
<hr />

[UXE-4369] feat: add formart currency and unit value in bill details

---

package.json

Upgrade project version from 1.19.0 to 1.19.1
No
No
<hr />

[NO-ISSUE] chore: upgrade project version from 1.19.1 to 1.20.0

---

src/services/variables-services/create-variables-service.js

Redirect to list instead of edit page when a secret is created in variables
<hr />

[NO-ISSUE] fix: redirect user to list when a secret is created

---

src/router/hooks/afterEachRoute.js

* track "Page Loaded" event if user is authenticated
no
<hr />

[UXE-4357] fix: added auth verification to page loaded track event

---

cypress/e2e/variables/create-secret.cy.js
cypress/e2e/variables/create-variable.cy.js

Add test case to create an secret and remove edition of secrets from variables tests
<hr />

[UXE-4039] test: change variables test to not support edit a secret

---

cypress/support/commands.js
src/templates/sign-in-block/index.vue

* autofocus in password and email login steps
* test assertion - be.focused input password in login flow
https://github.com/user-attachments/assets/0298871d-b5f2-498b-8d3d-553526ab138f
<hr />

[UXE-4208] feat: added autofocus on password and email input in login screen

---

src/templates/sign-in-block/index.vue

* use vue lifecycle instead of the nextick function to autofocus - signin fields
https://github.com/user-attachments/assets/0298871d-b5f2-498b-8d3d-553526ab138f
<hr />

[UXE-4208] refactor: autofocus on password and email input in login screen

---

.github/workflows/deploy-production.yml
.github/workflows/deploy-stage.yml
README.md
src/plugins/AnalyticsTrackerAdapterPlugin.js
src/plugins/analytics/AnalyticsTrackerAdapter.js
src/plugins/factories/analytics-tracking-factory.js
src/plugins/factories/segment-handler-token-factory.js
src/tests/plugins/analytics/AnalyticsTrackerAdapter.test.js
src/tests/plugins/factories/analytics-tracking-factory.test.js
src/tests/plugins/factories/segment-handler-token-factory.test.js

feat: add secrets segment variables in the workflows
<hr />

[UXE-4356] feat: add secrets segment variables in the workflows

---

package.json

updated project version from 1.20.0 to 1.20.1

[NO-ISSUE] chore: updated version package json from 1.20.0 to 1.20.1

---

src/helpers/get-csv-cell-content-from-row-data.js
src/helpers/index.js
src/templates/list-table-block/index.vue
src/tests/helpers/get-csv-cell-content-from-row-data.test.js
src/views/RealTimeEventsActivityHistory/ListView.vue
src/views/RealTimeEventsDataStream/ListView.vue
src/views/RealTimeEventsEdgeDNS/ListView.vue
src/views/RealTimeEventsEdgeFunctions/ListView.vue
src/views/RealTimeEventsEdgeFunctionsConsole/ListView.vue
src/views/RealTimeEventsHTTPRequests/ListView.vue
src/views/RealTimeEventsImageProcessor/ListView.vue
src/views/RealTimeEventsTieredCache/ListView.vue
src/views/RealTimeMetrics/RealTimeMetricsView.vue

This PR introduces new functionality to the list-table-block. Users will now be able to export the data currently shown in the list, reflecting the applied filters and column order.
Developer can create custom csv mappers to inject on each Product List, also this feature is optional to every Product List.
Yes
https://github.com/user-attachments/assets/a860d9c7-7135-4160-886f-73735a76469d
No. The following image was used as reference:
<hr />

[UXE-4375] feat: add export  to CSV support in list table block

---

src/views/Variables/FormFields/FormFieldsVariables.vue

Change inline message text in variables form
<hr />

[UXE-4506] fix: change variables form inline message text

---

src/services/network-lists-services/list-network-list-service.js
src/tests/services/network-lists-services/list-network-list-service.test.js
src/views/EdgeFirewallRulesEngine/FormFields/FormFieldsEdgeFirewallRulesEngine.vue

adjust load data in dropdown network list
loading the data selected in the dropdown
https://github.com/user-attachments/assets/b21a1434-8bce-4561-a008-10d655fb889c
<hr />

[UXE-4291] fix: adjust load data in dropdown network list

---

package.json

updated version package json from 1.20.1 to 1.20.2
<hr />

[NO-ISSUE] chore: updated version package json from 1.20.1 to 1.20.2

---

src/templates/list-table-block/index.vue

list items do not have hover behavior
https://github.com/user-attachments/assets/4532f3f3-d6f9-4bed-85fa-79e19b098c56
<hr />

[UXE-4484] fix: list items that do not have hover behavior

---

src/templates/advanced-filter/dialog-filter.vue
src/templates/list-table-block/index.vue
src/views/RealTimeEvents/TabsView.vue
src/views/RealTimeEvents/blocks/content-filter-block.vue
src/views/RealTimeEvents/blocks/interval-filter-block.vue
src/views/RealTimeEventsActivityHistory/ListView.vue
src/views/RealTimeEventsDataStream/ListView.vue
src/views/RealTimeEventsEdgeDNS/ListView.vue
src/views/RealTimeEventsEdgeFunctions/ListView.vue
src/views/RealTimeEventsEdgeFunctionsConsole/ListView.vue
src/views/RealTimeEventsHTTPRequests/ListView.vue
src/views/RealTimeEventsImageProcessor/ListView.vue
src/views/RealTimeEventsTieredCache/ListView.vue

- Improvement in the table to have a customized header
- Adjustments in the advanced filter
- Advanced filter added to the events view
- Adjusted rendering of the events view
<hr />

[UXE-4371] feat: add filter advanced in view realTime Events

---

package.json
yarn.lock

feat: upgrade azion theme to 1.5.6 version
<hr />

[UXE-4484] feat: upgrade azion theme to 1.5.6 version

---

src/router/hooks/afterEachRoute.js

Block page loaded event tacker when route change is blocked 
<hr />

[UXE-4471] fix: block page loaded event tracker when change route is blocked

---

cypress/e2mock/teams-permissions.cy.js

Add dev2 tag to team permissions 2mock spec 
<hr />

[NO-ISSUE] test: add dev2 tag to team permissions e2mock spec

---

src/services/team-permission/load-team-permission-service.js
src/tests/services/team-permission-services/load-team-permission-service.test.js

Fix error message parser
<hr />

[UXE-4473] fix: change error message parser to dont get error key

---

src/services/digital-certificates-services/delete-digital-certificates-service.js
src/tests/services/digital-certificates-services/delete-digital-certificates-service.test.js

[UXE-4543] fix: show response when deleting a digital certificate thats being used

---

src/helpers/convert-gql.js
src/helpers/hash-route.js
src/helpers/index.js
src/services/real-time-events-service/activity-history/load-activity-history.js
src/services/real-time-events-service/data-stream/load-data-stream.js
src/services/real-time-events-service/edge-dns/load-edge-dns.js
src/services/real-time-events-service/edge-functions-console/load-edge-functions-console.js
src/services/real-time-events-service/edge-functions/load-edge-functions.js
src/services/real-time-events-service/http-request/load-http-request.js
src/services/real-time-events-service/image-processor/load-image-processor.js
src/services/real-time-events-service/tiered-cache/load-tiered-cache.js
src/templates/advanced-filter/advanced-filter-no-hash.vue
src/templates/advanced-filter/dialog-filter.vue
src/templates/list-table-block/index.vue
src/tests/helpers/convert-gql.test.js
src/tests/helpers/hash-route.test.js
src/views/RealTimeEvents/TabsView.vue
src/views/RealTimeEvents/blocks/content-filter-block.vue
src/views/RealTimeEvents/blocks/interval-filter-block.vue
src/views/RealTimeEventsActivityHistory/ListView.vue
src/views/RealTimeEventsDataStream/ListView.vue
src/views/RealTimeEventsEdgeDNS/ListView.vue
src/views/RealTimeEventsEdgeFunctions/ListView.vue
src/views/RealTimeEventsEdgeFunctionsConsole/ListView.vue
src/views/RealTimeEventsHTTPRequests/ListView.vue
src/views/RealTimeEventsImageProcessor/ListView.vue
src/views/RealTimeEventsTieredCache/ListView.vue
src/views/RealTimeMetrics/blocks/content-filter-block.vue

applied advanced filter query to view realtime events
https://github.com/user-attachments/assets/d53f0127-561c-4cb5-9e03-f48ec1f50518
NO<hr />

[UXE-4372] feat: applied advanced filter query to view realtime events

---

src/views/Domains/CreateView.vue
src/views/Domains/FormFields/FormFieldsCreateDomains.vue

* conditional loading added to trsuted ca field
<hr />

[UXE-4533] refactor: added loading conditional to trusted CA fields in domains screen

---

cypress/e2mock/teams-permissions.cy.js

[NO-ISSUE] test: fix expected error message in team permissions spec assertion

---

.github/workflows/deploy-production.yml
.github/workflows/deploy-stage.yml
azion/stage/azion.json

Sync stage rules engine on azion.json
<hr />

[NO-ISSUE] fix: sync stage rules engine on azion.json

---

src/views/EdgeApplicationsRulesEngine/FormFields/FormFieldsEdgeApplicationsRulesEngine.vue

Add accordion to each criteria in edge application rules engine
<hr />

[UXE-3308] feat: add accordion to edge application rules engine criterias 

---

src/services/edge-application-rules-engine-services/create-rules-engine-service.js
src/services/edge-application-rules-engine-services/edit-rules-engine-service.js
src/services/edge-application-rules-engine-services/helper-behavior.js
src/services/edge-application-rules-engine-services/load-rules-engine-service.js
src/tests/services/edge-application-rules-engine-services/create-rules-engine-service.test.js
src/tests/services/edge-application-rules-engine-services/edit-rules-engine-service.test.js
src/tests/services/edge-application-rules-engine-services/helper-behavior.test.js
src/tests/services/edge-application-rules-engine-services/load-rules-engine-service.test.js
src/views/EdgeApplicationsRulesEngine/Drawer/index.vue
src/views/EdgeApplicationsRulesEngine/FormFields/FormFieldsEdgeApplicationsRulesEngine.vue

[UXE-4458]
reworked the behavior logic on the rule engine screen in edge app 
https://github.com/user-attachments/assets/1c8c46f1-baac-463e-9862-8ffe051cfc25
<hr />
[UXE-4458]: https://aziontech.atlassian.net/browse/UXE-4458?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[UXE-4458] fix: reworked the behavior logic on the rule engine screen in edge app

---

src/templates/create-modal-block/index.vue

Adjust the label in a link that appears in Create>Recommended, after a search returns no results.
<hr />

[UXE-4507] refactor: adjust label in link - Create>Recommended

---

.github/workflows/deploy-production.yml
.github/workflows/deploy-stage.yml
azion.config.cjs

Edge as the origin of all APIs. Also, included the headers to know the user real IP.
To support the new configurations I've tested uploading a stage version of this [here](https://w0xuyabjpt.map.azionedge.net/)
No
No
<hr />

[NO-ISSUE] feat: Access Restrictions by IP

---

azion/stage/azion.json

[NO-ISSUE] chore: manual sync with stage

---

.github/workflows/dev-e2e-tests.yml

Cypress's E2E testing workflow will run all groups of tests, even if some of them fail. This will allow you to identify and analyze any errors encountered during execution, enabling a better understanding of the health of the system and more efficient troubleshooting.
No
No
<hr />

[QA-2169] test: add fail-fast in workflow

---

src/views/RealTimeEvents/Blocks/content-filter-block.vue
src/views/RealTimeMetrics/blocks/content-filter-block.vue

-update label for GraphQL Playground button in RealTimeEvents and RealTimeMetrics
<hr />

[NO-ISSUE] feat: update label for GraphQL Playground button in RealTimeEvents and RealTimeMetrics

---

src/services/edge-firewall-services/list-edge-firewall-service.js
src/tests/services/edge-firewall-services/list-edge-firewall-service.test.js
src/views/EdgeFirewall/ListView.vue

Remove column domains in edge firewall list.
<hr />

[UXE-4589] fix: remove column domains in table edge firewall list

---

src/views/EdgeApplicationsRulesEngine/FormFields/FormFieldsEdgeApplicationsRulesEngine.vue

Reverts aziontech/azion-console-kit#1648

[NO-ISSUE] revert: open accordion when there is error in fields inside it"

---

src/views/EdgeApplicationsRulesEngine/FormFields/FormFieldsEdgeApplicationsRulesEngine.vue

Reverts aziontech/azion-console-kit#1631

[UXE-3308] revert: add accordion to edge application rules engine criterias

---

package.json

Updated project version from 1.20.2 to 1.21.0

[NO-ISSUE] chore: updated version package json from 1.20.2 to 1.21.0

---

src/templates/navbar-block/index.vue
src/views/Domains/FormFields/FormFieldsCreateDomains.vue

- remove refs azion copilot
<hr />

[NO-ISSUE] fix: remove aicomponent fro navbar and gethelp

---

src/modules/real-time-metrics/MOCK_METRICS_DATA.js
src/modules/real-time-metrics/reports/convert-beholder-to-chart.js
src/tests/modules/real-time-metrics/constants/reports.test.js

feat: add gauge chart

---

src/modules/real-time-metrics/MOCK_METRICS_DATA.js
src/modules/real-time-metrics/reports/convert-beholder-to-chart.js
src/templates/graphs-card-block/components/chart/stacked-bar-chart.vue
src/templates/graphs-card-block/index.vue
src/tests/modules/real-time-metrics/constants/reports.test.js
src/views/Playground/PlaygroundView.vue

Stacked bar chart

---

azion/production/azion.json

[NO-ISSUE] chore: Manual sync of Rules Engine on prod

---

azion/production/azion.json
src/templates/navbar-block/index.vue
src/views/Domains/FormFields/FormFieldsCreateDomains.vue

-[NO-ISSUE] fix: remove aicomponent fro navbar and gethelp
-[NO-ISSUE] chore : sync main to dev after deploy 1.20.2 to 1.21.0
-[NO-ISSUE] chore: Manual sync of Rules Engine on prod
<hr />

DEPLOY 2024.09.02 #2

---

src/modules/real-time-metrics/MOCK_METRICS_DATA.js
src/modules/real-time-metrics/reports/convert-beholder-to-chart.js
src/templates/graphs-card-block/components/chart/stacked-area-chart.vue
src/templates/graphs-card-block/index.vue
src/tests/modules/real-time-metrics/constants/reports.test.js
src/views/Playground/PlaygroundView.vue

* stacked area chart (no more stacked line)
<hr />

[UXE-4690] feat: integrate new stacked area chart to metrics

---

cypress/e2e/edge-firewall/create-edge-firewall-network-list.cy.js
cypress/e2e/edge-firewall/create-edge-firewall-waf.cy.js

Changes on edge firewall tests to wait for api response instead of arbitrary timer
<hr />

[UXE-4772] test: change tests to wait for api response instead of arbitrary time

---

src/views/EdgeApplicationsRulesEngine/FormFields/FormFieldsEdgeApplicationsRulesEngine.vue

Add accordions to control criterias in edge application rules engine
<hr />

[UXE-3308] feat: add accordions to fit rules engine criterias

---

.github/workflows/deploy-stage.yml
.github/workflows/dev-e2e-tests.yml

Also bump the github action version for the tests (clean up warnings)
<hr />

[NO-ISSUE] chore: Limit 1 deploy at a time to stage

---

.github/workflows/dev-e2e-tests.yml

[NO-ISSUE] chore: fix coverage files upload

---

azion.config.cjs
src/router/hooks/redirectToManager.js
src/services/account-services/index.js
src/services/account-services/list-client-ids-released-for-console-service.js
src/services/users-services/index.js
src/tests/services/account-services/list-client-ids-released-for-console-service.test.js
vite.config.js

allow accounts access from a list to console
no
<hr />

[UXE-4708] feat: allow accounts access from a list to console

---

src/views/EdgeApplications/TabsView.vue
src/views/EdgeApplicationsErrorResponses/EditView.vue

* added track events to error responses -> 
* failed to edit
* click to edit
* edited
no
no
<hr />

[UXE-2057] feat: added edit track events in edge applications error responses

---

azion/stage/azion.json

[NO-ISSUE] chore: Sync stage IaC

---

src/views/EdgeApplicationsCacheSettings/Drawer/index.vue

* create and edit track events in cache settings
* also "failed to" events
Create:
Edit:
Failed to create:
Failed to edit:
<hr />

[UXE-2061] feat: added create and edit track events in edge applications cache settings

---

azion.config.cjs

adjust rules azion config
No
<hr />

[NO-ISSUE] fix: adjust rules azion config

---

src/templates/list-table-block/index.vue

Add error validation inside list table block to render proper error message in toast
<hr />

[UXE-4768] fix: resolve toast message content in list-table-block

---

src/views/EdgeApplicationsRulesEngine/ListView.vue
src/views/EdgeFirewallRulesEngine/ListView.vue

add tracker clicked to create and clicked to edit events in edge application and edge firewall rules engine
<hr />

[UXE-2072] feat: add tracker clicked to create and clicked to edit events in rules engine

---

package.json
src/helpers/azion-documentation-window-opener.js
src/tests/helpers/azion-documentation-window-opener.test.js

The project was renamed in the GitHub but does not updated inside project. This does not affect the existent code.

[NO-ISSUE] chore: adjust project name based on github

---

azion/production/azion.json

Add new Origin and Rule to access client list

[NO-ISSUE] chore: Sync IaC Production

---

azion.config.cjs

remove https origin azion config
NO
<hr />

[NO-ISSUE] fix: remove https origin azion config

---

src/views/WafRules/EditView.vue

add WAF Rules  edited and failed to edit events to tracker
<hr />

[UXE-4888] feat: add WAF Rules  edited and failed to edit events to tracker

---

src/views/WafRules/ListView.vue

add clicked to create and clicked to edit event to waf rules 
<hr />

[UXE-4884] feat: add clicked to create and clicked to edit event to waf rules 

---

src/views/WafRules/CreateView.vue

add WAF Rules created and failed to create events to tracker
<hr />

[UXE-4885] feat: add WAF Rules created and failed to create events to tracker

---

src/views/EdgeApplicationsRulesEngine/Drawer/index.vue

add failed to edit and failed to create edge firewall and edge application rules engine events to tracker
<hr />

[UXE-2073] feat: add failed to edit and failed to create rules engine events to tracker

---

src/templates/navbar-block/feedback.vue

remove icon github e add new icon send to feedback
no
<hr />

feat: remove icon github e add new icon send to feedback

---

azion/stage/azion.json

[NO-ISSUE] chore: Sync stage Origin/Rule Engine on IaC

---

src/views/NetworkLists/ListView.vue

add clicked to create and clicked to edit network lists events
<hr />

[UXE-4869] feat: add clicked to create and clicked to edit network lists events

---

src/views/EdgeApplicationsCacheSettings/Drawer/index.vue
src/views/EdgeApplicationsDeviceGroups/Drawer/index.vue
src/views/EdgeApplicationsErrorResponses/EditView.vue
src/views/EdgeApplicationsFunctions/Drawer/index.vue
src/views/EdgeApplicationsRulesEngine/Drawer/index.vue

* all events of functions instance
* added missing edit events in edge app products
no
<hr />

[UXE-1908] feat: added create and edit track events in edge applications functions instance

---

src/views/Users/ListView.vue

add new tracker event to click to create user and ed
<hr />

[UXE-4926] feat: add new tracker event to click to create user and edit

---

src/views/NetworkLists/EditView.vue

add network lists edited and failed to edit events to tracker
<hr />

[UXE-4873] feat: add network lists edited and failed to edit events to tracker

---

package.json

Upgrade version to 1.22.0
No
No
<hr />

[NO-ISSUE] chore: update project version to 1.22.0

---

src/views/Users/CreateView.vue
src/views/Users/EditView.vue

add tracker events when it is created and edited user
<hr />

feat: add tracker events when it is created and edited user

---

azion/production/azion.json

[NO-ISSUES] chore: Sync Prod IaC

---

src/services/edge-firewall-rules-engine-services/make-edge-firewall-rules-engine-reorder-base-url.js
src/services/edge-firewall-rules-engine-services/reorder-edge-firewall-rules-engine-service.js
src/templates/list-table-block/index.vue
src/tests/services/edge-firewall-rules-engine-services/make-edge-firewall-rules-engine-base-url.test.js

the reordering of rules engine edge firewall was corrected, the correct behavior and that when reordering the api it works
https://jam.dev/c/3422fa20-53d1-4cee-b9e1-373149155f28
<hr />

[NO-ISSUE] fix: reorder rules engine edge firewall and change api contract

---

src/services/edge-application-error-responses-services/make-edge-application-error-responses-base-url.js
src/tests/services/edge-application-error-responses/edit-error-responses-services.test.js
src/tests/services/edge-application-error-responses/list-error-responses-service.test.js
src/views/Users/CreateView.vue
src/views/Users/EditView.vue

add failed create user and edit tracker event
<hr />

[UXE-4928] feat: add failed create user and edit tracker event

---

src/views/WafRules/ListWafRulesAllowed.vue

Add waf allowed rules clicked to create, clicked to edit, created, failed to create, edited and failed to edit events to tracker
- [ x] No
<hr />

[UXE-4912] feat: add WAF Allowed rules events to tracker

---

src/views/RealTimePurge/Dialog/index.vue
src/views/RealTimePurge/ListView.vue

console re purge toast shown without confirm click
<hr />

[UXE-4767] fix: console re purge toast shown without confirm click

---

src/views/AccountSettings/AccountSettingsView.vue

[UXE-4923] feat: add account settings events to tracker

---

src/modules/real-time-metrics/constants/reports.js
src/modules/real-time-metrics/reports/convert-beholder-to-chart.js
src/modules/real-time-metrics/reports/load-report-variation.js
src/templates/graphs-card-block/components/chart/big-numbers-chart.vue
src/tests/modules/real-time-metrics/constants/reports.test.js
src/tests/modules/real-time-metrics/reports/fixtures/gql-fixtures.js

- change filters names to match new API filters
- add rule to change botCaptcha reports series names as requested by the PM
- set variation to 0 when there is no previous value
Yes, but only a label
No
<hr />

[NO-ISSUE] refactor: general changes in bot manager reports

---

package.json

Update project version to 1.22.2
No
No
<hr />

chore: update project version to 1.22.2

---

src/plugins/analytics/AnalyticsTrackerAdapter.js
src/plugins/analytics/trackers/ProductTracker.js
src/plugins/analytics/trackers/WafRulesTracker.js
src/plugins/analytics/trackers/index.js
src/tests/plugins/analytics/AnalyticsTrackerAdapter.test.js
src/views/WafRules/Dialog/index.vue
src/views/WafRules/ListWafRulesAllowed.vue
src/views/WafRules/ListWafRulesTuning.vue

* added allow rules track events in waf tuning list
no
<hr />

[UXE-4967] feat: added allow rules track events in waf tuning

---

src/modules/real-time-metrics/constants/reports.js
src/tests/modules/real-time-metrics/constants/reports.test.js

[EDU-5386] chore: adjust Bot graphs names

---

src/views/YourSettings/EditView.vue

add edited and failed to edit your settings events to tracker
add edited and failed to edit your settings events to tracker
<hr />

[UXE-5021] feat: add edited and failed to edit your settings events to tracker

---

src/views/EdgeApplicationsRulesEngine/Drawer/index.vue
src/views/EdgeFirewallRulesEngine/Drawer/index.vue

Add rules engine create and failed to create events and change events name from rules engine to rules
<hr />

[UXE-2072] feat: add rules engine created and failed to created events and fixed event name

---

src/templates/edit-form-block/index.vue
src/views/TeamsPermissions/CreateView.vue
src/views/TeamsPermissions/EditView.vue
src/views/TeamsPermissions/ListView.vue

add tracking events to teams permissions
no
<hr />

[UXE-5025] feat: add tracking events to teams permissions

---

vite.config.js

remove unused API endpoint for allowed accounts
no
<hr />

[UXE-5123] fix: remove unused API endpoint for allowed accounts

---

src/stores/table-definitions.js
src/templates/list-table-block/index.vue

persist number of records per page on list screens
https://jam.dev/c/ca9a493e-acdf-4530-98b3-7c4e6953e010
no
<hr />

[UXE-4813] feat: persist number of records per page on list screens

---

package.json

Update project version to 1.22.2
No
No
<hr />

chore: update project version to 1.22.3

---

src/modules/real-time-metrics/constants/help-center-urls.js
src/plugins/analytics/AnalyticsTrackerAdapter.js
src/plugins/analytics/trackers/ProductTracker.js
src/plugins/analytics/trackers/RealTimeMetricsTracker.js
src/plugins/analytics/trackers/index.js
src/templates/graphs-card-block/components/more-options-menu.vue
src/templates/graphs-card-block/index.vue
src/tests/modules/real-time-metrics/constants/reports.test.js
src/views/RealTimeMetrics/RealTimeMetricsView.vue
src/views/RealTimeMetrics/blocks/content-filter-block.vue
src/views/RealTimeMetrics/blocks/dashboard-panel-block.vue
src/views/RealTimeMetrics/blocks/interval-filter-block.vue

implements events in real time metrics
<hr />

[UXE-5064] feat: implements events in real time metrics

---

package.json

Update project version from 1.22.3 to 1.22.4
no
no
<hr />

chore: update project version from 1.22.3 to 1.22.4

---

src/views/EdgeApplicationsFunctions/ListView.vue

* Events: clicked to edit and create - Functions Instances
no
<hr />

[NO-ISSUE] feat: added clicked to create and edit track events in functions instances

---

src/modules/real-time-metrics/constants/help-center-urls.js
src/services/edge-node-services/edit-edge-node-service.js
src/services/edge-node-services/load-edge-node-service.js
src/templates/form-fields-inputs/fieldSwitchBlock.vue
src/templates/selector-block/index.vue
src/tests/modules/real-time-metrics/constants/reports.test.js
src/tests/services/edge-node-services/edit-edge-node-services.test.js
src/tests/services/edge-node-services/load-edge-node-service.test.js
src/views/EdgeNode/EditView.vue
src/views/EdgeNode/FormFields/FormFieldsEdgeNode.vue

[UXE-4898] fix: add input add on service in the edge node
<hr />
[UXE-4898]: https://aziontech.atlassian.net/browse/UXE-4898?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[UXE-4898] fix: add input add on service in the edge node

---

src/plugins/analytics/trackers/RealTimeMetricsTracker.js
src/plugins/analytics/trackers/index.js
src/services/real-time-metrics-services/index.js
src/views/CompareWithAzion/blocks/retry-message.vue
src/views/Variables/CreateView.vue
src/views/Variables/EditView.vue
src/views/Variables/ListView.vue

[UXE-5130] feat: add variable tracker event
<hr />
[UXE-5130]: https://aziontech.atlassian.net/browse/UXE-5130?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[UXE-5130] feat: add variable tracker event

---

src/modules/real-time-metrics/constants/help-center-urls.js
src/modules/real-time-metrics/constants/reports-texts.js
src/modules/real-time-metrics/constants/reports.js
src/modules/real-time-metrics/reports/convert-beholder-to-chart.js
src/templates/graphs-card-block/components/map/constants/color-scheme.js
src/templates/graphs-card-block/components/map/utils/features-handler.js
src/tests/modules/real-time-metrics/constants/reports.test.js
src/tests/modules/real-time-metrics/reports/fixtures/gql-fixtures.js

- Simple code adjustments required in code review to improve readability
- Rename chart and change url as requested by PM
No
<hr />

[NO-ISSUE] refactor: adjustments in code readability in rtmetrics

---

src/router/hooks/beforeEachRoute.js
src/router/hooks/guards/accountGuard.js
src/router/hooks/guards/billingGuard.js
src/router/hooks/guards/logoutGuard.js
src/router/hooks/guards/themeGuard.js
src/router/hooks/redirectToManager.js
src/router/index.js
src/tests/router/hooks/redirectToManager.test.js

Unit tests for the redirectToManager guard were added, and the router guards were refactored to accept routerHandler and dependencies as parameters, improving dependency injection across the guards.
NO
NO
<hr />

[UXE-4954] test: add coverage for redirectToManager guard and update router guards

---

src/views/EdgeServices/CreateView.vue
src/views/EdgeServices/EditView.vue
src/views/EdgeServices/ListView.vue

implements tracking events in edge services
no
<hr />

[UXE-5134] feat: implements tracking events in edge services

---

src/router/hooks/beforeEachRoute.js
src/router/hooks/guards/accountGuard.js
src/router/hooks/guards/billingGuard.js
src/router/hooks/guards/index.js
src/router/hooks/guards/loadingGuard.js
src/router/hooks/guards/logoutGuard.js
src/router/hooks/guards/redirectGuard.js
src/router/hooks/guards/redirectToManagerGuard.js
src/router/hooks/guards/themeGuard.js
src/router/index.js
src/tests/router/hooks/guards/redirectToManagerGuard.test.js
src/tests/router/hooks/redirectToManager.test.js

This pull request includes significant changes to the routing guards in the application to improve code clarity and maintainability. The most important changes involve refactoring the guards to use a consistent dependency injection pattern and simplifying the guard logic.
* [`src/router/hooks/beforeEachRoute.js`](diffhunk://#diff-2ede22aba8c8d9df7d4835ed8c2f75b5bf8a18ee9c8baebb7e707209fa6377d4L1-R33): Refactored to import individual guards directly and execute them in sequence, returning early if any guard returns a result.
* [`src/router/hooks/guards/accountGuard.js`](diffhunk://#diff-d6c67445f7ab12da8b36580e1f485839d1beb84970ecd9a47afb675a9d620122L6-R6): Updated `accountGuard` to use a destructured object for parameters and simplified the return logic. …

[NO-ISSUE] fix: adjustment to the route guards to standardize execution and dependency injection as parameters.

---

src/views/DigitalCertificates/CreateView.vue
src/views/DigitalCertificates/EditView.vue
src/views/DigitalCertificates/ListView.vue

implements tracking events in digital certificate
no
<hr />

[UXE-5136] feat: implements tracking events in digital certificate

---

src/templates/create-drawer-block/index.vue
src/views/EdgeDNS/EditView.vue

feat: implements tacking events in records
no
<hr />

[UXE-5132] feat: implements events in records

---

src/services/waf-rules-services/list-waf-rules-tuning-service.js
src/tests/services/waf-rules-services/list-waf-rules-tuning-service.test.js

Add error message parser to waf tuning list service
<hr />

[UXE-5039] feat: fix error message parser in waf tuning load

---

src/services/edge-node-service-services/create-service-edge-node-service.js
src/services/edge-node-service-services/load-service-edge-node-service.js
src/tests/services/edge-node-service-services/create-service-edge-node-service.test.js
src/tests/services/edge-node-service-services/load-service-edge-node-service.test.js
src/views/EdgeNode/Drawer/index.vue
src/views/EdgeNode/FormFields/FormFieldsDrawerService.vue

fix: service keeps loading when there is no service registered
https://github.com/user-attachments/assets/0424aa4a-ea71-4b17-8c52-76d781a39b50
<hr />

[UXE-5149] fix: service keeps loading when there is no service registered

---

src/views/RealTimeEvents/Blocks/constants/tabs-events.js

fix: incorrect ordering in real time events in the ts field
<hr />

[UXE-5007] fix: incorrect ordering in real time events in the ts field

---

src/views/EdgeFirewall/FormFields/FormFieldsEdgeFirewall.vue

- Adjust the DDoS card description on the Edge Firewall page.
<hr />

[EDU-5476] refactor: Adjust DDoS card description

---

src/App.vue
src/plugins/analytics/AnalyticsTrackerAdapter.js
src/router/hooks/guards/accountGuard.js
src/router/hooks/guards/logoutGuard.js
src/router/index.js
src/templates/profile-block/index.vue
src/tests/plugins/analytics/AnalyticsTrackerAdapter.test.js

This pull request includes several changes to improve user tracking and state management in the application. The most important changes involve updating the tracking traits, adding a reset method to the analytics tracker, and ensuring the tracker is reset during specific navigation events.
* **Updated tracking traits in `src/App.vue`**: Modified the `updateTrackingTraits` function to include `user_id` and `account_id` in the default traits and updated the `identify` call to use `userID` instead of `clientId`.
* **Added reset method to `AnalyticsTrackerAdapter` in `src/plugins/analytics/AnalyticsTrackerAdapter.js`**: Introduced a `reset` method to clear internal state and reset the analytics client.
* **Reset tracker during account and logout guard events in …

[UXE-5180] feat: enhance AnalyticsTrackerAdapter refine identify method and introduce reset method

---

src/modules/real-time-metrics/constants/dashboards.js
src/modules/real-time-metrics/constants/reports.js
src/services/billing-services/index.js
src/templates/graphs-card-block/big-numbers-card.vue
src/tests/modules/real-time-metrics/constants/dashboards.test.js
src/tests/modules/real-time-metrics/constants/reports.test.js
src/tests/modules/real-time-metrics/reports/fixtures/gql-fixtures.js
src/tests/plugins/analytics/AnalyticsTrackerAdapter.test.js
src/views/RealTimeMetrics/blocks/dashboard-panel-block.vue

adjust to pass group data props and change dataset and new properties
No
<hr />

[NO-ISSUE] fix: adjust to pass group data props and change dataset

---

.github/workflows/local-prod-e2e-tests.yml

refactoring in grepTags in local-prod-e2e-tests workflow
No
No
<hr />

[NO-ISSUE] refactoring: grepTags in local-prod-e2e-tests workflow

---

cypress/e2e/edge-firewall/create-edge-firewall-function.cy.js
cypress/support/selectors/product-selectors/edge-firewall.js
src/views/EdgeFirewallFunctions/Drawer/index.vue
src/views/EdgeFirewallFunctions/FormFields/FormFieldsEdgeApplicationsFunctions.vue

Add functions drawer to edge firewall functions instance form
<hr />

[UXE-5193] feat: add functions drawer to edge firewall functions instace form

---

src/services/waf-rules-services/create-waf-rules-allowed-service.js
src/services/waf-rules-services/create-waf-rules-allowed-tuning-service.js
src/services/waf-rules-services/delete-waf-rules-allowed-service.js
src/services/waf-rules-services/edit-waf-rules-allowed-service.js
src/services/waf-rules-services/list-waf-rules-allowed-service.js
src/services/waf-rules-services/load-waf-rules-allowed-service.js
src/services/waf-rules-services/make-waf-rules-allowed-base-url.js
src/tests/services/waf-rules-services/create-waf-rules-allowed-service.test.js
src/tests/services/waf-rules-services/create-waf-rules-allowed-tuning-service.test.js
src/tests/services/waf-rules-services/delete-waf-rules-allowed-service.test.js
src/tests/services/waf-rules-services/edit-waf-rules-allowed-service.test.js
src/tests/services/waf-rules-services/list-waf-rules-allowed-service.test.js
src/tests/services/waf-rules-services/load-waf-rules-allowed-sevice.test.js
src/tests/services/waf-rules-services/make-waf-rules-allowed.test.js

[UXE-5244] feat: update url waf allowed rules
https://github.com/user-attachments/assets/dc73e87a-614a-43a5-8766-6b7fb8927d20
<hr />
[UXE-5244]: https://aziontech.atlassian.net/browse/UXE-5244?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[UXE-5244] feat: update url waf allowed rules

---

cypress/e2e/edge-application/rules-engine/create-rule-engine-set-function.cy.js
cypress/e2e/edge-application/rules-engine/create-rule-engine-set-origin.cy.js
cypress/support/selectors/product-selectors/edge-application.js
src/views/EdgeApplications/TabsView.vue
src/views/EdgeApplicationsFunctions/Drawer/index.vue
src/views/EdgeApplicationsOrigins/Drawer/index.vue
src/views/EdgeApplicationsRulesEngine/Drawer/index.vue
src/views/EdgeApplicationsRulesEngine/FormFields/FormFieldsEdgeApplicationsRulesEngine.vue
src/views/EdgeApplicationsRulesEngine/ListView.vue

[UXE-5194] feat: add origin and function instance drawers to rules engine page

---

src/modules/azion-ai-chat/azion-ai-chat-block.vue

Reverts aziontech/azion-console-kit#1818

Revert "[NO-ISSUE] feat: add credentials option to DEEP_CHAT_CONFIG_REQUEST"

---

src/helpers/real-time-filters-rules.js
src/modules/real-time-metrics/constants/reports.js
src/modules/real-time-metrics/constants/services-operator-in.js
src/modules/real-time-metrics/filters/extract-filters-and-variables.js
src/modules/real-time-metrics/index.js
src/services/real-time-metrics-services/index.js
src/services/real-time-metrics-services/search-classified-service.js
src/templates/advanced-filter/component/display/chips-default-display.vue
src/templates/advanced-filter/component/fields/select-filter.vue
src/templates/advanced-filter/component/index.js
src/templates/advanced-filter/dialog-filter.vue
src/templates/advanced-filter/index.vue
src/tests/helpers/realt-time-filter-rules.test.js
src/tests/modules/real-time-metrics/constants/map-services-operator-in.test.js
src/tests/modules/real-time-metrics/constants/reports.test.js
src/tests/modules/real-time-metrics/reports/fixtures/gql-fixtures.js
src/views/RealTimeMetrics/blocks/content-filter-block.vue

add filter challenge solved in breakdown dashboards
https://jam.dev/c/c84da39d-09a4-4b4c-be37-4e666c2380f7
no
<hr />

[UXE-5271] feat: add filter challenge solved in breakdown dashboards

---

package.json
src/services/edge-service-services/create-edge-service-services.js
src/templates/create-drawer-block/index.vue
src/views/EdgeNode/Drawer/index.vue
src/views/EdgeNode/FormFields/FormFieldsDrawerService.vue
src/views/EdgeServices/CreateEdgeServiceDrawer/index.vue
src/views/EdgeServices/FormFields/FormFieldsEdgeService.vue

add edge services drawer to edge nodes services form
<hr />

[UXE-5197] feat: add edge services drawer to edge nodes services form

---

cypress/e2e/edge-application/rules-engine/create-rule-engine-set-function.cy.js
cypress/e2e/edge-application/rules-engine/create-rule-engine-set-origin.cy.js
cypress/support/selectors/product-selectors/edge-application.js
src/views/EdgeApplications/TabsView.vue
src/views/EdgeApplicationsFunctions/Drawer/index.vue
src/views/EdgeApplicationsOrigins/Drawer/index.vue
src/views/EdgeApplicationsRulesEngine/Drawer/index.vue
src/views/EdgeApplicationsRulesEngine/FormFields/FormFieldsEdgeApplicationsRulesEngine.vue
src/views/EdgeApplicationsRulesEngine/ListView.vue

add create cache settings, create origin and create function drawers to rules engine page (This pull request was already merged once but we had to revert to do the deploy to prod, so im merging it again)
<hr />

[UXE-5194] feat: add create cache settings, create origin and create function drawers to rules engine page

---

src/helpers/real-time-filters-rules.js
src/modules/real-time-events/filters/index.js
src/modules/real-time-events/filters/relevant-fields.js
src/tests/helpers/realt-time-filter-rules.test.js
src/views/RealTimeEvents/TabsView.vue
src/views/RealTimeMetrics/blocks/content-filter-block.vue

[UXE-4771] feat: implement a feature to display the 5 most used fields
https://github.com/user-attachments/assets/690f0cbd-d075-419a-a784-cb2ce1e664f3
<hr />
[UXE-4771]: https://aziontech.atlassian.net/browse/UXE-4771?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[UXE-4771] feat: implement a feature to display the 5 most used fields

---

src/helpers/real-time-filters-rules.js
src/modules/real-time-metrics/constants/dashboards.js
src/modules/real-time-metrics/constants/services-operator-in.js
src/services/real-time-metrics-services/index.js
src/services/real-time-metrics-services/search-action-service.js
src/services/real-time-metrics-services/search-challenge-solved-service.js
src/services/real-time-metrics-services/search-classified-service.js
src/templates/advanced-filter/component/display/chips-default-display.vue
src/templates/advanced-filter/component/index.js
src/templates/advanced-filter/dialog-filter.vue
src/tests/helpers/realt-time-filter-rules.test.js
src/tests/modules/real-time-metrics/constants/dashboards.test.js
src/tests/modules/real-time-metrics/constants/map-services-operator-in.test.js
src/views/RealTimeMetrics/blocks/content-filter-block.vue

add filters in list format
https://jam.dev/c/eede8c83-934d-46e5-84f8-9ac8a95f5db4
no
<hr />

[UXE-5298] feat: add filters in list format

---

.gitignore
src/services/domains-services/create-domain-service.js
src/services/domains-services/load-domain-service.js
src/templates/edit-form-block/index.vue
src/tests/services/domains-services/create-domain-service.test.js
src/tests/services/domains-services/load-domain-service.test.js
src/views/Domains/CreateView.vue
src/views/Domains/EditView.vue
src/views/Domains/FormFields/FormFieldsCreateDomains.vue
src/views/Domains/FormFields/FormFieldsEditDomains.vue

feat: add preview input on the domain page
https://github.com/user-attachments/assets/c2e9207d-1866-4a62-9aa3-179c48b4aacd
<hr />

[UXE-5269] feat: add preview input on the domain page

---

src/helpers/real-time-filters-rules.js
src/services/real-time-metrics-services/search-action-service.js
src/services/real-time-metrics-services/search-classified-service.js
src/templates/info-drawer-block/info-labels/big-number.vue
src/tests/helpers/realt-time-filter-rules.test.js
src/views/RealTimeEvents/Drawer/httpRequests.vue
src/views/RealTimeEvents/Drawer/tieredCache.vue

fix: adjust units big numbers in real time events
big numbers need to be in seconds and not milliseconds
https://jam.dev/c/e21b5a3f-83c6-48ab-92fd-328c1620568f
<hr />

[UXE-5233] fix: adjust units big numbers in real time events

---

.gitignore
src/helpers/real-time-filters-rules.js
src/services/real-time-metrics-services/search-action-service.js
src/services/real-time-metrics-services/search-classified-service.js
src/stores/account.js
src/tests/helpers/realt-time-filter-rules.test.js
src/views/DataStream/FormFields/FormFieldsDataStream.vue

feat: disable eye if user does not have edit permission
https://github.com/user-attachments/assets/afcefbe2-3f41-41cd-b97a-8bbfdf3435ae
<hr />

[UXE-5235] feat: disable eye if user does not have edit permission

---

src/helpers/real-time-filters-rules.js
src/services/real-time-metrics-services/search-action-service.js
src/services/real-time-metrics-services/search-classified-service.js
src/services/waf-rules-services/list-waf-rules-domain-service.js
src/tests/helpers/realt-time-filter-rules.test.js
src/tests/services/waf-rules-services/list-waf-rules-domain-service.test.js

[UXE-5055] fix: add page size params in the domains request
https://github.com/user-attachments/assets/10838a35-3214-4d99-973c-ff6951c3716f
<hr />
[UXE-5055]: https://aziontech.atlassian.net/browse/UXE-5055?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[UXE-5055] fix: add page size params in the domains request

---

src/services/waf-rules-services/list-waf-rules-tuning-attacks-service.js
src/services/waf-rules-services/list-waf-rules-tuning-service.js
src/tests/services/waf-rules-services/list-waf-rules-tuning-service.test.js

error when rendering tuning tab
should render the tuning tab
https://jam.dev/c/e43be537-2b1a-4f30-8bea-791017318e80
<hr />

[UXE-5427] fix: error when rendering tuning tab

---

src/router/hooks/beforeEachRoute.js
src/router/hooks/guards/SSOManagementGuard.js
src/router/hooks/guards/index.js
src/stores/account.js
src/templates/profile-block/index.vue
src/views/IdentityProviders/ListView.vue

Add SSO Management option to profile menu and add route guard to block users that dont have access
<hr />

[UXE-5417] feat: add SSO Management menu option and route guard to users that don't have federated_auth flag

---

src/views/Users/FormsFields/FormFieldsUsers.vue

adjust text in Social Login field
<hr />

[UXE-5179] chore: adjust text in Social Login field

---

src/services/waf-rules-services/list-waf-rules-tuning-service.js
src/views/DataStream/FormFields/FormFieldsDataStream.vue

[UXE-5235] feat: disable viewing sensitive data on the data stream
https://github.com/user-attachments/assets/8890060d-acfd-491b-9750-a3c30cf435b6
<hr />
[UXE-5235]: https://aziontech.atlassian.net/browse/UXE-5235?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[UXE-5235] feat: disable viewing sensitive data

---

azion/stage/azion.json

[NO-ISSUE] chore: Update IaC stage

---

src/views/IdentityProviders/ListView.vue

Block editing Azion SSO
<hr />

[NO-ISSUE] fix: block editing azion sso

---

src/router/hooks/beforeEachRoute.js
src/router/hooks/guards/SSOManagementGuard.js

This pull request includes changes to the route guards in the `src/router/hooks` directory to improve the handling of the SSO management guard and ensure proper order of execution.
Improvements to route guards:
* [`src/router/hooks/beforeEachRoute.js`](diffhunk://#diff-2ede22aba8c8d9df7d4835ed8c2f75b5bf8a18ee9c8baebb7e707209fa6377d4L23-R26): Reordered the `ssoManagementGuard` to ensure it runs before the `redirectToManagerGuard`.
* [`src/router/hooks/guards/SSOManagementGuard.js`](diffhunk://#diff-e4e38a45ae7557dae9fc4171a4d0ecbdb8b9832492043785eb99e8e515e75bbaL4-L10): Simplified the conditional logic in the `ssoManagementGuard` function to improve readability and maintainability.
NO
<hr />

[NO-ISSUE] fix: reorder guards in beforeEachRoute.js and simplify ssoManagementGuard

---

src/services/identity-providers-services/list-identity-providers-service.js
src/tests/services/identity-providers-services/list-identity-providers-service.test.js
src/views/IdentityProviders/ListView.vue

[UXE-5392] fix: order by name and load without permissions

---

src/services/identity-providers-services/create-saml-identity-provider-service.js
src/tests/services/identity-providers-services/create-saml-identity-provider-service.test.js
vite.config.js

* saml create redirect to edit
<hr />

[UXE-5390] fix: create saml redirect url

---

src/views/EdgeApplications/FormFields/FormFieldsCreateEdgeApplications.vue

* added new custom ports to edge application form
<hr />

[UXE-5525] feat: added new custom ports to edge application form

---

src/router/hooks/afterEachRoute.js

enabling the identify event at each page change for appcues flow loading
no
no
<hr />

[UXE-5515] feat: enable identify event on each page change for appcues flow

---

azion/production/azion.json

[NO-ISSUE] chore: Update IaC for production

---

src/router/routes/edge-application-routes/index.js
src/services/edge-application-cache-settings-services/v4/list-cache-settings-service.js
src/tests/services/edge-application-cache-settings-services/v4/list-cache-settings-service.test.js
src/views/EdgeApplicationsCacheSettings/ListView.vue

[UXE-5283] feat: migrate cache setting v4
https://github.com/user-attachments/assets/7ed7489a-486c-49cc-bb7d-a036982caf57
<hr />
[UXE-5283]: https://aziontech.atlassian.net/browse/UXE-5283?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[UXE-5283] feat: migrate cache setting v4

---

src/router/routes/edge-functions-routes/index.js
src/services/edge-functions-services/v4/index.js
src/services/edge-functions-services/v4/list-edge-functions-service.js
src/services/edge-functions-services/v4/make-edge-functions-base-url.js
src/tests/services/edge-functions-services/v4/list-edge-functions-service.test.js
src/tests/services/edge-functions-services/v4/make-edge-functions-base-url.test.js
src/views/EdgeFunctions/ListView.vue

feat: migrate functions to v4
https://github.com/user-attachments/assets/0660d33c-a959-4f84-a246-9ecea6bf7225
<hr />

[UXE-5289] feat: migrate functions to v4

---

src/views/EdgeApplicationsCacheSettings/FormFields/FormFieldsEdgeApplicationCacheSettings.vue

* added no cache browser option to cache settings
* the flag does not exist anymore
<hr />

[UXE-5554] feat: added no cache browser option to cache settings

---

src/services/data-stream-services/load-data-stream-service.js
src/stores/account.js
src/views/DataStream/FormFields/FormFieldsDataStream.vue

Add sampling behavior to users with client flag activated
<hr />

[UXE-5553] feat: add sampling behavior to datastream form

---

src/templates/list-table-block/with-fetch-ordering-and-pagination.vue

[NO-ISSUE] fix: fix search on the table
<hr />

[NO-ISSUE] fix: fix search on the table

---

src/router/routes/digital-certificates-routes/index.js
src/services/digital-certificates-services/v4/index.js
src/services/digital-certificates-services/v4/list-digital-certificates-service.js
src/services/digital-certificates-services/v4/make-digital-certificates-base-url.js
src/tests/services/digital-certificates-services/v4/list-digital-certificates-service.test.js
src/tests/services/digital-certificates-services/v4/make-digital-certificates-base-url.test.js
src/views/DigitalCertificates/ListView.vue

[UXE-5558] feat: migrate digital certificate to v4
https://github.com/user-attachments/assets/1ff2c488-1f3b-43a3-bd42-3ddd4b5acea0
<hr />
[UXE-5558]: https://aziontech.atlassian.net/browse/UXE-5558?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[UXE-5558] feat: migrate digital certificate to v4

---

src/helpers/convert-date.js
src/router/routes/edge-firewall-routes/index.js
src/services/edge-firewall-functions-services/list-edge-firewall-functions-service.js
src/services/edge-firewall-functions-services/v4/index.js
src/services/edge-firewall-functions-services/v4/list-functions-service.js
src/services/edge-firewall-rules-engine-services/v4/index.js
src/services/edge-firewall-rules-engine-services/v4/list-edge-firewall-rules-engine-service.js
src/services/edge-firewall-services/v4/index.js
src/services/edge-firewall-services/v4/list-edge-firewall-service.js
src/services/edge-firewall-services/v4/make-edge-firewall-base-url.js
src/tests/helpers/convert-date.test.js
src/tests/services/edge-firewall-functions-services/v4/list-functions-service.test.js
src/tests/services/edge-firewall-rules-engine-services/v4/list-edge-firewall-rules-engine-service.test.js
src/tests/services/edge-firewall-services/v4/list-edge-firewall-service.test.js
src/tests/services/edge-firewall-services/v4/make-edge-firewall-base-url.test.js
src/views/EdgeFirewall/ListView.vue
src/views/EdgeFirewallFunctions/ListView.vue
src/views/EdgeFirewallRulesEngine/ListView.vue

[UXE-5291] feat: migrate edge firewall to v4
https://github.com/user-attachments/assets/a9a15f3b-ed9d-4039-a878-9c3528d8b57e
<hr />
[UXE-5291]: https://aziontech.atlassian.net/browse/UXE-5291?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[UXE-5291] feat: migrate edge firewall to v4

---

src/router/routes/network-lists-routes/index.js
src/services/network-lists-services/v4/index.js
src/services/network-lists-services/v4/list-network-list-service.js
src/services/network-lists-services/v4/make-network-list-service.js
src/tests/services/network-lists-services/v4/list-network-list-service.test.js
src/tests/services/network-lists-services/v4/make-network-list-base-url.test.js
src/views/NetworkLists/ListView.vue

[UXE-5555] feat: migrate network list to v4
https://github.com/user-attachments/assets/f961645a-c894-4097-ab62-bdcfe9afeed9
<hr />
[UXE-5555]: https://aziontech.atlassian.net/browse/UXE-5555?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[UXE-5555] feat: migrate network list to v4

---

src/services/waf-rules-services/list-waf-rules-allowed-service.js
src/tests/services/waf-rules-services/list-waf-rules-allowed-service.test.js
src/views/WafRules/ListWafRulesAllowed.vue

[UXE-5297] feat: migrate allowed rules to v4
https://github.com/user-attachments/assets/2fb20ed6-0426-43aa-8052-05539c4a2d65
<hr />
[UXE-5297]: https://aziontech.atlassian.net/browse/UXE-5297?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[UXE-5297] feat: migrate allowed rules to v4

---

src/router/hooks/guards/domainsLimitGuard.js

Change route guard to requenst workloads just to the necessary route
<hr />

[NO-ISSUE] fix: request workloads just when target route is data stream

---

src/templates/profile-block/index.vue

Add profile menu options to manage accounts of the level below its type
<hr />

[UXE-5576] feat: add menu option to manage accounts depending on the account type

---

src/helpers/make-list-service-query-params.js
src/router/index.js
src/router/routes/client-management-routes/index.js
src/router/routes/group-management-routes/index.js
src/router/routes/reseller-management-routes/index.js
src/services/accounts-management-services/index.js
src/services/accounts-management-services/list-accounts-service.js
src/services/accounts-management-services/make-accounts-management-base-url.js
src/services/axios/AxiosHttpClientAdapter.js
src/services/real-time-metrics-services/search-workloads-service.js
src/templates/list-table-block/with-fetch-ordering-and-pagination.vue
src/templates/profile-block/index.vue
src/tests/services/accounts-management-services/list-accounts-service.test.js
src/tests/services/accounts-management-services/make-accounts-management-base-url.test.js
src/views/ClientManagement/ListView.vue
src/views/GroupManagement/ListView.vue
src/views/ResellerManagement/ListView.vue

add reseller, group and client management list views
<hr />

[UXE-5580] feat: add reseller, group and client management list views

---

src/router/routes/domains-routes/index.js
src/services/domains-services/v4/index.js
src/services/domains-services/v4/list-domain-service.js
src/services/domains-services/v4/make-domains-service.js
src/tests/services/domains-services/v4/list-domain-service.test.js
src/tests/services/domains-services/v4/make-domains-base-url.test.js
src/views/Domains/ListView.vue

[UXE-5585] feat: migrate domains to v4
https://github.com/user-attachments/assets/f97c8fd0-a96b-4d7b-bd63-615080cff4fa
<hr />
[UXE-5585]: https://aziontech.atlassian.net/browse/UXE-5585?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[UXE-5585] feat: migrate domains to v4

---

src/services/edge-application-services/v4/clone-edge-application-service.js
src/services/edge-application-services/v4/index.js
src/services/edge-application-services/v4/list-edge-applications-service.js
src/tests/services/edge-application-services/v4/clone-edge-applications-service.test.js
src/tests/services/edge-application-services/v4/list-edge-applications-service.test.js
src/views/EdgeApplications/Dialog/Clone.vue
src/views/EdgeApplications/ListView.vue

[UXE-5583] feat: add behavior to clone edge app
https://github.com/user-attachments/assets/ef3f5029-710d-4bd3-a0c5-c8f1529d50fe
<hr />
[UXE-5583]: https://aziontech.atlassian.net/browse/UXE-5583?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[UXE-5583] feat: add behavior to clone edge app

---

azion.config.cjs
src/helpers/payment-history.js
src/router/hooks/guards/billingGuard.js
src/services/billing-services/index.js
src/services/billing-services/list-payment-history-service.js
src/services/billing-services/list-service-and-products-changes-accounting-service.js
src/services/billing-services/load-current-invoice-service.js
src/services/billing-services/load-invoice-data-service.js
src/services/billing-services/make-accounting-base-url.js
src/services/contract-services/load-contract-service-plan.js
src/services/real-time-metrics-services/search-workloads-service.js
src/stores/account.js
src/tests/helpers/payment-history.test.js
src/tests/services/billing-services/list-payment-history-service.test.js
src/tests/services/billing-services/list-service-and-products-changes-accounting-service.test.js
src/tests/services/contract-services/load-contract-service-plan.test.js
src/views/Billing/BillsView.vue
src/views/Billing/InvoiceDetailsView.vue
src/views/Billing/TabsView.vue
src/views/Billing/components/table-services-products.vue
vite.config.js

use new accounting endpoint for regular clients
no
<hr />

[UXE-4355] feat: use new accounting endpoint for regular clients

---

src/services/sidebar-menus-services/menus.js

[UXE-5544] fix: Bot Manager (Radware) URL

---

azion/stage/azion.json

[NO-ISSUE] chore: Update IaC for Stage env

---

src/services/edge-application-services/load-edge-application-service.js
src/tests/services/edge-application-error-responses/edit-error-responses-services.test.js
src/tests/services/edge-application-services/load-edge-application-service.test.js
src/tests/services/network-lists-services/edit-network-list-service.test.js
src/views/EdgeApplications/FormFields/FormFieldsCreateEdgeApplications.vue

Add to the console and test flag-exclusive ports on other accounts
https://github.com/user-attachments/assets/031bc4c0-805b-4ebf-a081-0717f5cf72ca
<hr />

[UXE-5525] fix: Some custom ports not selecting when editing Edge App

---

src/router/routes/clients-management-routes/index.js
src/router/routes/groups-management-routes/index.js
src/services/accounts-management-services/create-account-by-type-service.js
src/services/accounts-management-services/edit-account-service.js
src/templates/profile-block/index.vue
src/views/GroupsManagement/CreateView.vue
src/views/GroupsManagement/EditView.vue
src/views/GroupsManagement/FormFields/FormFieldsCreateGroups.vue
src/views/GroupsManagement/ListView.vue

[UXE-5624] feat: add groups edit and create pages

---

src/services/edge-firewall-services/v4/clone-edge-firewall-service.js
src/services/edge-firewall-services/v4/index.js
src/services/edge-firewall-services/v4/list-edge-firewall-service.js
src/services/real-time-metrics-services/search-workloads-service.js
src/tests/services/edge-firewall-services/v4/clone-edge-firewall-service.test.js
src/tests/services/edge-firewall-services/v4/list-edge-firewall-service.test.js
src/views/EdgeFirewall/Dialog/Clone.vue
src/views/EdgeFirewall/ListView.vue

[UXE-5587] feat: clone behavior edge firewall
https://github.com/user-attachments/assets/ef0eab69-6842-4367-9d12-64d52fc9b05e
<hr />
[UXE-5587]: https://aziontech.atlassian.net/browse/UXE-5587?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[UXE-5587] feat: clone behavior edge firewall

---

src/services/edge-application-services/v4/clone-edge-application-service.js
src/services/edge-application-services/v4/list-edge-applications-service.js
src/tests/services/edge-application-services/v4/clone-edge-applications-service.test.js
src/tests/services/edge-application-services/v4/list-edge-applications-service.test.js
src/views/EdgeApplications/Dialog/Clone.vue

[NO-ISSUE] Fix: clone edge app
<hr />

[NO-ISSUE] fix: clone edge app

---

src/tests/helpers/convert-date.test.js
src/tests/services/accounts-management-services/list-accounts-service.test.js

[NO-ISSUE] test: adjust account and convert date test

---

src/services/edge-application-rules-engine-services/helper-behavior.js
src/tests/services/edge-application-rules-engine-services/load-rules-engine-service.test.js

[UXE-5621] fix: Origin not loading in behavior
<hr />
[UXE-5621]: https://aziontech.atlassian.net/browse/UXE-5621?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[UXE-5621] fix: Origin not loading in Edge App Rules Engine set origin behavior

---

src/services/edge-application-services/load-edge-application-service.js

[UXE-5525] fix: select saved ports on edit page 

---

src/views/NetworkLists/ListView.vue

[UXE-5555] fix: last modified sort field
<hr />
[UXE-5555]: https://aziontech.atlassian.net/browse/UXE-5555?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[UXE-5555] fix: last modified sort field on Network Lists screen

---

src/views/EdgeFirewallFunctions/ListView.vue

[UXE-5292] fix: last modified field
[UXE-5292] fix: last modified field
<hr />
[UXE-5292]: https://aziontech.atlassian.net/browse/UXE-5292?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[UXE-5292]: https://aziontech.atlassian.net/browse/UXE-5292?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[UXE-5292] fix: Edge Firewall Function Instances ordering

---

src/views/Domains/ListView.vue

[UXE-5585] fix sort field domain
<hr />
[UXE-5585]: https://aziontech.atlassian.net/browse/UXE-5585?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[UXE-5585] fix: Domain/Workloads sort columns issues

---

src/views/EdgeFirewall/ListView.vue

[UXE-5291] fix: fix sort field last modified
<hr />
[UXE-5291]: https://aziontech.atlassian.net/browse/UXE-5291?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[UXE-5291] fix: Edge Firewall List sort

---

cypress/e2e/edge-application/add-error-response.cy.js
cypress/e2e/edge-application/rules-engine/create-rule-engine-set-function.cy.js
cypress/e2e/edge-application/rules-engine/edit-rule-engine.cy.js

* xfail to tests with bug in api v4
<hr />

[NO-ISSUE] test: added xfail in some edge application tests

---

src/services/edge-application-cache-settings-services/v4/list-cache-settings-service.js

* formated no-cache in cache settings list
<hr />

[UXE-5554] fix: added no cache parse in api v4 for cache settings edge app

---

src/views/WafRules/ListView.vue

[UXE-5286] refactor: fix sort field waf
<hr />
[UXE-5286]: https://aziontech.atlassian.net/browse/UXE-5286?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[UXE-5286] refactor: fix sort field waf

---

src/services/waf-rules-services/create-waf-rules-allowed-service.js
src/services/waf-rules-services/edit-waf-rules-allowed-service.js
src/services/waf-rules-services/list-waf-rules-allowed-service.js
src/services/waf-rules-services/load-waf-rules-allowed-service.js
src/tests/services/waf-rules-services/create-waf-rules-allowed-service.test.js
src/tests/services/waf-rules-services/edit-waf-rules-allowed-service.test.js
src/tests/services/waf-rules-services/list-waf-rules-allowed-service.test.js
src/tests/services/waf-rules-services/load-waf-rules-allowed-sevice.test.js
src/views/WafRules/FormFields/FormFieldsAllowed.vue
src/views/WafRules/ListWafRulesAllowed.vue

[UXE-5297] fix: fix sort field and change field from description to name
<hr />
[UXE-5297]: https://aziontech.atlassian.net/browse/UXE-5297?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[UXE-5297] fix: WAF Allowed rules - sort field and change field from description to name

---

src/views/EdgeApplicationsFunctions/ListView.vue

[UXE-ISSUE] fix: sort field function in edge app
<hr />

[NO-ISSUE] fix: sort field function in edge app function instances

---

cypress/e2e/domains/edit-domain.cy.js
cypress/e2e/edge-dns/create-edge-dns-zone.cy.js
cypress/e2e/edge-dns/create-record-type-a.cy.js
cypress/e2e/edge-dns/create-record-type-aaaa.cy.js
cypress/e2e/edge-dns/create-record-type-aname.cy.js
cypress/e2e/edge-dns/create-record-type-caa.cy.js
cypress/e2e/edge-dns/create-record-type-cname.cy.js
cypress/e2e/edge-dns/create-record-type-ds.cy.js
cypress/e2e/edge-dns/create-record-type-mx.cy.js
cypress/e2e/edge-dns/create-record-type-ns.cy.js
cypress/e2e/edge-dns/create-record-type-ptr.cy.js
cypress/e2e/edge-dns/create-record-type-srv.cy.js
cypress/e2e/edge-dns/create-record-type-txt.cy.js
cypress/e2e/edge-firewall/create-edge-firewall-function.cy.js
cypress/e2e/edge-firewall/create-edge-firewall-network-list.cy.js
cypress/e2e/edge-firewall/create-edge-firewall-rule-engine-header-criteria.cy.js
cypress/e2e/personal-token/create-personal-token.cy.js

* added hit enter in search inputs v4
<hr />

[NO-ISSUE] test: added hit enter in search inputs v4

---

package.json

[NO-ISSUE] chore: update project version to 1.29.0
N/A
N/A
<hr />

[NO-ISSUE] chore: update project version to 1.29.0

---

src/helpers/real-time-filters-rules.js
src/templates/advanced-filter/component/fields/multiselect-lazy-loader-filter.vue
src/templates/advanced-filter/component/index.js
src/tests/helpers/realt-time-filter-rules.test.js

creating domains component to have lazy loader
https://jam.dev/c/f6ae3062-3b93-4e8d-a55c-4147750543b3
<hr />

[UXE-5541] feat: creating domains component to have lazy loader

---

src/templates/page-heading-block/index.vue

* remove space inside element
<hr />

[UXE-5718] test: removed wrong spaccing in page title element

---

azion/production/azion.json

[NO-ISSUE] chore: Remove rules from IaC

---

cypress/e2mock/edge-application/list-edge-applications.cy.js
cypress/fixtures/edge-application/edge-applications-paginated.json
cypress/support/selectors/block-selectors/list-table-block.js

test: add e2e test cases to lazy loading table pagination

---

src/router/routes/edge-firewall-routes/index.js
src/services/edge-firewall-services/v4/create-edge-firewall-service.js
src/services/edge-firewall-services/v4/index.js
src/tests/services/edge-firewall-services/v4/create-edge-firewall-service.test.js
src/views/EdgeFirewall/Drawer/index.vue

* migrate post method to v4 in edge firewall
* added unit tests
<hr />

[UXE-5742] feat: migrate create edge firewall post method to v4

---

src/templates/content-block/banner.vue

reopening to dev the same fix of: https://github.com/aziontech/azion-console-kit/pull/1956

[UXE-5748] fix: Marketplace view

---

src/services/digital-certificates-services/v4/delete-digital-certificates-service.js
src/services/edge-application-cache-settings-services/v4/index.js
src/tests/services/digital-certificates-services/v4/delete-digital-certificates-service.test.js

[NO-ISSUE] fix: show error message when deleting
<hr />

[NO-ISSUE] fix: show error message when deleting Digital Certificates

---

cypress/e2e/edge-application/create-device-groups.cy.js
src/router/routes/edge-application-routes/index.js
src/services/edge-application-device-groups-services/v4/create-device-groups-service.js
src/services/edge-application-device-groups-services/v4/index.js
src/tests/services/edge-application-device-groups-services/v4/create-device-groups-service.test.js

migrate edge application device groups creation to api v4
migrate edge application device groups creation to api v4
<hr />

[UXE-5711] feat: migrate edge application device groups creation to api v4

---

src/router/routes/edge-firewall-routes/index.js
src/services/edge-firewall-services/v4/edit-edge-firewall-service.js
src/services/edge-firewall-services/v4/index.js
src/tests/services/edge-firewall-services/v4/edit-edge-firewall-service.test.js

added edge firewall patch test case
<hr />

[UXE-5742] feat: migrated edge firewall edit page to api v4

---

src/router/routes/edge-application-routes/index.js
src/services/edge-application-device-groups-services/v4/edit-device-groups-service.js
src/services/edge-application-device-groups-services/v4/index.js
src/services/edge-application-device-groups-services/v4/load-device-group-service.js
src/tests/services/edge-application-device-groups-services/v4/edit-device-groups-service.test.js
src/tests/services/edge-application-device-groups-services/v4/load-device-group-service.test.js

migrate edge application device groups edit and load services to api v4
<hr />

[UXE-5712] feat: migrate edge application device groups edit page to api v4

---

src/router/routes/edge-firewall-routes/index.js
src/services/edge-firewall-services/v4/index.js
src/services/edge-firewall-services/v4/load-edge-firewall-service.js
src/tests/services/edge-firewall-services/v4/load-edge-firewall-service.test.js

* migrated edge firewall load to api v4
<hr />

[UXE-5742] feat: migrated edge firewall load to api v4

---

src/router/routes/edge-firewall-routes/index.js
src/services/edge-firewall-functions-services/v4/create-function-service.js
src/services/edge-firewall-functions-services/v4/index.js
src/tests/services/edge-firewall-functions-services/v4/create-edge-firewall-functions-service.test.js
vite.config.js

* migrated edge firewall create function to api v4
<hr />

[UXE-5755] feat: migrated edge firewall create function to api v4

---

src/router/routes/edge-application-routes/index.js
src/services/edge-application-device-groups-services/v4/delete-device-group-service.js
src/services/edge-application-device-groups-services/v4/edit-device-groups-service.js
src/services/edge-application-device-groups-services/v4/index.js
src/tests/services/edge-application-device-groups-services/v4/delete-device-group-service.test.js
src/tests/services/edge-application-device-groups-services/v4/edit-device-groups-service.test.js

migrate device groupt delete service to api v4
<hr />

[UXE-5713] feat: migrate device group delete service to api v4

---

src/views/EdgeApplications/Dialog/Clone.vue
src/views/EdgeFirewall/Dialog/Clone.vue
src/views/WafRules/Dialog/Clone.vue

[UXE-5747] fix: layout clone modal
https://github.com/user-attachments/assets/c5f6af36-5b7f-46f7-96ac-26801cd3c95b
<hr />
[UXE-5747]: https://aziontech.atlassian.net/browse/UXE-5747?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[UXE-5747] fix: layout clone modal for Edge App/Edge Firewall/WAF

---

src/router/routes/edge-application-routes/index.js
src/services/edge-application-device-groups-services/v4/index.js
src/services/edge-application-services/v4/delete-edge-application-service.js
src/services/edge-application-services/v4/index.js
src/tests/services/edge-application-services/v4/delete-edge-application-service.test.js
src/tests/services/edge-firewall-services/v4/load-edge-firewall-service.test.js

migrate edge application delete to api v4
<hr />

[UXE-5705] feat: migrate edge application delete to api v4

---

cypress/e2e/domains/create-domain-edge-application.cy.js
cypress/e2e/domains/create-domain-lets-encrypt.cy.js
cypress/e2e/domains/create-domain-mtls.cy.js
cypress/support/selectors/product-selectors/domains.js
src/helpers/make-list-service-query-params.js
src/router/routes/domains-routes/index.js
src/services/digital-certificates-services/list-digital-certificates-service.js
src/services/digital-certificates-services/v4/index.js
src/services/digital-certificates-services/v4/list-digital-certificates-dropdown-service.js
src/services/digital-certificates-services/v4/list-digital-certificates-service.js
src/services/digital-certificates-services/v4/load-digital-certificates-service.js
src/templates/form-fields-inputs/fieldDropdownLazyLoader.vue
src/tests/services/digital-certificates-services/v4/list-digital-certificates-dropdown-service.test.js
src/tests/services/digital-certificates-services/v4/load-digital-certificates-service.test.js
src/views/Domains/CreateView.vue
src/views/Domains/EditView.vue
src/views/Domains/FormFields/FormFieldsCreateDomains.vue
src/views/Domains/FormFields/FormFieldsEditDomains.vue

add dropdown lazy loader in digital certificate and trusted certificate
No
<hr />

[UXE-5810] feat: lazy load digital certificate in Add/Edit Domain screen

---

src/router/routes/edge-application-routes/index.js
src/services/edge-application-functions-services/v4/create-function-service.js
src/services/edge-application-functions-services/v4/index.js
src/tests/services/edge-application-functions-services/v4/edge-function-service.test.js

migrate edge application functions instance creation to api v4
<hr />

[UXE-5803] feat: migrate edge application functions instance creation to api v4

---

src/services/domains-services/v4/list-domain-service.js
src/tests/services/domains-services/v4/list-domain-service.test.js
src/views/Domains/ListView.vue

feat: remove edge application column from domains table
no
<hr />

[UXE-5817] feat: remove edge application column from domains table

---

src/router/routes/edge-application-routes/index.js
src/services/edge-application-functions-services/v4/edit-function-instance-service.js
src/services/edge-application-functions-services/v4/index.js
src/services/edge-application-functions-services/v4/load-function-instance-service.js
src/tests/services/edge-application-functions-services/v4/edit-function-instance-service.test.js
src/tests/services/edge-application-functions-services/v4/load-function-instance-service.test.js
src/tests/services/edge-firewall-services/v4/load-edge-firewall-service.test.js

migrate edge application function instances edit page to api v4
<hr />

[UXE-5804] feat: migrate edge application function instances edit page to api v4

---

src/services/accounts-management-services/list-accounts-service.js
src/tests/services/accounts-management-services/list-accounts-service.test.js
src/tests/services/edge-firewall-services/v4/load-edge-firewall-service.test.js

[UXE-5776] fix: incorrect error handling when managing accounts
<hr />
[UXE-5776]: https://aziontech.atlassian.net/browse/UXE-5776?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[UXE-5776] fix: incorrect error handling when managing accounts

---

cypress/e2e/edge-application/create-function-instance.cy.js
cypress/e2e/edge-application/edit-function-instance.cy.js
cypress/support/selectors/product-selectors/edge-application.js
src/router/routes/edge-application-routes/index.js
src/views/EdgeApplications/TabsView.vue
src/views/EdgeApplicationsFunctions/Drawer/index.vue
src/views/EdgeApplicationsFunctions/FormFields/FormFieldsEdgeApplicationsFunctions.vue
src/views/EdgeApplicationsFunctions/ListView.vue

feat implements lazy loader dropdown function instance edge app
No
<hr />

[UXE-5851] feat: implements lazy loader dropdown function instance edge app

---

.github/workflows/local-prod-e2e-tests.yml

[NO-ISSUE] chore: Add new time to e2e tests

---

src/modules/real-time-metrics/constants/reports.js
src/modules/real-time-metrics/reports/convert-beholder-to-chart.js
src/modules/real-time-metrics/reports/load-report-with-meta.js
src/tests/modules/real-time-metrics/constants/reports.test.js
src/tests/modules/real-time-metrics/reports/fixtures/gql-fixtures.js

update report dataset and data handling in real-time metrics module
no
no
<hr />

[UXE-5701] feat: update report dataset and data handling in real-time metrics

---

index.html

Site/Docs/LP já entrou:
https://github.com/aziontech/site/commit/50288276c22efd6e7c41e0cb7d818859a248d95e
O que é esperado pode ser visto nas imagens desse merge. Nele contem as imagens do devtools na aba network
https://github.com/aziontech/azion-theme/pull/31

[NO-ISSUE] chore:  adjust preload font-face

---

src/templates/form-fields-inputs/fieldDropdownLazyLoader.vue

fix: prevent duplicate options in dropdown by checking for existing values
no
<hr />

[UXE-5904] fix: prevent duplicate options in dropdown by checking for existing values

---

src/router/routes/waf-rules-routes/index.js
src/services/waf-rules-services/v4/edit-waf-rules-service.js
src/services/waf-rules-services/v4/index.js
src/services/waf-rules-services/v4/load-waf-rules-service.js
src/tests/services/waf-rules-services/v4/edit-waf-rules-service.test.js
src/tests/services/waf-rules-services/v4/load-waf-rules-service.test.js

[UXE-5888] refactor: update WAF rules services to use API v4 for editing and loading rules

---

cypress/e2e/edge-application/function-instance/edit-function-instance.cy.js
src/views/EdgeApplicationsFunctions/Drawer/index.vue

[UXE-5921] fix: remove back to list button from edge application function instances

---

src/router/routes/edge-dns-routes/index.js
src/services/edge-dns-services/index.js
src/services/edge-dns-services/v4/index.js
src/services/edge-dns-services/v4/list-edge-dns-service.js
src/services/edge-dns-services/v4/make-edge-dns-base-url.js
src/tests/services/edge-dns-services/v4/list-edge-dns-service.test.js
src/tests/services/edge-dns-services/v4/make-edge-dns-base-url.test.js
src/views/EdgeDNS/ListView.vue

[NO-ISSUE] Fix: rename dns endpoint and change code to match project standard and add the test 
<hr />

[UXE-5923] fix: rename Edge DNS endpoint and change code to match project standard

---

package.json

[NO-ISSUE] chore: update project version to 1.31.0
N/A
<hr />

[NO-ISSUE] chore: update version to 1.31.0

---

cypress/e2e/edge-firewall/create-edge-firewall-rule-engine-rate-limit.cy.js
cypress/support/selectors/product-selectors/edge-firewall.js
src/services/edge-firewall-rules-engine-services/v4/create-edge-firewall-rules-engine-service.js
src/services/edge-firewall-rules-engine-services/v4/edit-edge-firewall-rules-engine-service.js
src/tests/services/edge-firewall-rules-engine-services/v4/create-edge-firewall-rules-engine-service.test.js

* edge firewall behavior handling with new rate limit properties and selectors
* test e2e
<hr />

[UXE-5952] fix: edge firewall behavior handling with new rate limit properties and selectors

---

package.json

update version to 1.31.1
NO
NO
<hr />

[NO-ISSUE] chore: update version to 1.31.1

---

cypress/e2e/domains/create-domain-mtls.cy.js

Remove unused assert causing errors in domains tests
<hr />

[UXE-5981] test: remove unused assert from domains test

---

cypress/e2e/edge-functions/create-edge-function.cy.js
src/router/routes/edge-functions-routes/index.js
src/services/edge-functions-services/v4/delete-edge-function-service.js
src/services/edge-functions-services/v4/index.js
src/templates/list-table-block/dialog/delete-dialog.vue
src/tests/services/edge-functions-services/v4/delete-edge-function-service.test.js

migrate edge function delete to api v4
<hr />

[UXE-5892] feat: migrate edge function delete to api v4

---

src/views/EdgeApplicationsRulesEngine/Drawer/index.vue

prevent drawer closure after edge application rules engine edition fail
<hr />

[UXE-5951] fix: prevent drawer closure after edge application rules engine edition fail

---

src/templates/mfa-authenticate-block/index.vue

Adicionado auto focus ao input do MFA
No
No
<hr />

[UXE-5631] feat: auto focus input to mfa/authentication page

---

cypress.config.js
cypress/e2e/edge-pulse/copy-tags-edge-pulse.cy.js

remove clipboard asserts from edge pulse test
<hr />

[UXE-5981] test: remove clipboard asserts from edge pulse test

---

src/helpers/azion-documentation-window-opener.js
src/helpers/index.js
src/router/routes/marketplace-routes/index.js
src/tests/helpers/azion-documentation-window-opener.test.js
src/tests/services/edge-application-rules-engine-services/v4/edit-rules-engine-service.test.js
src/views/Marketplace/SolutionView.vue

https://github.com/user-attachments/assets/04403b44-5beb-4cab-ab2d-595edf5017f9
<hr />

[UXE-5005] fix: empty links integrations marketplace

---

src/views/EdgeApplicationsFunctions/Drawer/index.vue
src/views/EdgeApplicationsFunctions/FormFields/FormFieldsEdgeApplicationsFunctions.vue
src/views/EdgeFirewallFunctions/Drawer/index.vue
src/views/EdgeFirewallFunctions/FormFields/FormFieldsEdgeApplicationsFunctions.vue
src/views/EdgeFunctions/components/code-editor.vue

Check before submitting if the arguments payload is invalid on function instance pages
<hr />

[UXE-5802] fix: add json validation to edge application and edge firewall function instance arguments field

---

cypress/e2e/edge-application/rules-engine/create-rule-engine-set-origin.cy.js

add wait for api response before clicking in origins dropdown
<hr />

[NO-ISSUE] test: add wait for api response before clicking in origins dropdown

---

cypress/e2e/edge-firewall/create-edge-firewall-function.cy.js
cypress/e2e/edge-firewall/create-edge-firewall-rule-engine-header-criteria.cy.js

[NO-ISSUE] chore: Remove xfail from Edge Firewall tests

---

cypress/e2e/account-settings/update-address.cy.js
cypress/e2e/your-settings/edit-user-phone.cy.js
cypress/support/selectors/view-selectors/account-settings.js

remove wait for api respose and use assert in loading state instead
<hr />

[UXE-5935] test: remove wait for api respose and use assert in loading state instead

---

cypress/e2e/account-settings/update-address.cy.js
cypress/e2e/edge-firewall/create-edge-firewall-function.cy.js
cypress/e2e/edge-firewall/create-edge-firewall-rule-engine-header-criteria.cy.js
cypress/e2e/your-settings/edit-user-phone.cy.js
cypress/support/selectors/view-selectors/account-settings.js
src/helpers/get-static-urls-by-environment.js
src/plugins/analytics/trackers/ProductTracker.js
src/tests/helpers/get-static-urls-by-environment.test.js
src/tests/plugins/analytics/AnalyticsTrackerAdapter.test.js
src/views/Home/HomeView.vue

Deploy 2025-01-15

---

src/helpers/account-handler.js
src/router/routes/switch-account-routes/index.js

This pull request updates the `switchAccountFromSocialIdp` method in the `AccountHandler` class and its usage in the `switchAccountRoutes` object. The changes introduce a new parameter, `EnableSocialLogin`, to handle social login functionality. 
**Correct Behavior:**  
The `EnableSocialLogin` parameter ensures the `switchAccountFromSocialIdp` method correctly manages the flow for accounts using social login, improving conditional checks and maintaining flexibility in account switching scenarios.
No UI changes are introduced by this pull request.
<hr />

[UXE-5342] fix: adjust social login redirection to bypass MFA prompt for accounts using social login

---

src/stores/account.js
src/views/DataStream/EditView.vue
src/views/DataStream/FormFields/FormFieldsDataStream.vue
src/views/DataStream/ListView.vue

* edit data stream in account owner
* fixed edit data stream form submit
<hr />

[UXE-6073] fix: edit data stream in account owner

---

package.json

update version to 1.31.2
NO
NO
<hr />

[NO-ISSUE] chore: update version to 1.31.2

---

src/views/Home/HomeView.vue

This pull request includes a small change to the `src/views/Home/HomeView.vue` file. The change modifies the URL used for redirection to include a query parameter to disable redirects.
* [`src/views/Home/HomeView.vue`](diffhunk://#diff-01d730d78411fcdbec8996b9983bfe06336d59183f2b15c6b2e1b1f2cc123e70L121-R121): Updated the `openRTM` function to append `?disableRedirect=true` to the `urlEOL` before setting `window.location.href`.
<hr />

[UXE-6014] feat: add query for disabled redirect to console

---

package.json
src/views/Home/HomeView.vue

- updated URL to redirect to manager.azion.com with a query parameter for disabling the redirect console
<hr />

DEPLOY 2025-01-23

---

cypress/e2e/edge-application/edit-origin.cy.js
cypress/support/selectors/product-selectors/edge-application.js
src/views/EdgeApplicationsOrigins/FormFields/FormFieldsEdgeApplicationsOrigins.vue

send payload correctly when change from load balancer to single origin
<hr />

[UXE-6071] fix: send payload correctly when change from load balancer to single origin

---

src/router/routes/network-lists-routes/index.js
src/services/network-lists-services/v4/delete-network-list-service.js
src/services/network-lists-services/v4/index.js
src/tests/services/network-lists-services/v4/delete-network-list-service.test.js
src/tests/services/network-lists-services/v4/list-network-list-service.test.js

[UXE-6003] feat: migrate network list delete to v4
https://github.com/user-attachments/assets/1076befd-510d-4c6e-8108-37691cf1d2e3
<hr />
[UXE-6003]: https://aziontech.atlassian.net/browse/UXE-6003?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[UXE-6003] feat: migrate network list delete to v4

---

src/services/edge-application-services/load-edge-application-service.js

fix: handle optional body results to resolved error toast false
no
<hr />

[UXE-6086] fix: handle optional body results to resolved error toast false

---

src/views/EdgeApplicationsRulesEngine/FormFields/FormFieldsEdgeApplicationsRulesEngine.vue

fix: adjust placeholder to correct format in edge app rules engine
<hr />

[UXE-6067] fix: adjust placeholder to correct format in edge app rules engine

---

src/services/data-stream-services/list-data-stream-service.js
src/tests/services/data-stream-services/list-data-stream-service.test.js

fix: improve status parsing and handle optional results in list data stream
https://jam.dev/c/8d117706-05f0-418f-b5fb-13ad436cd264
<hr />

[UXE-6102] fix: improve status parsing and handle optional results in list data stream

---

src/stores/account.js
src/templates/create-modal-block/index.vue

* add hide create options flag to create modal block
https://github.com/user-attachments/assets/c0062233-bf0f-4e40-a76f-a95ecab6c725
<hr />

[UXE-6148] feat: add hide create options flag to create modal block

---

src/services/edge-dns-records-services/list-records-service.js
src/tests/services/edge-dns-records-services/list-records-service.test.js

workaround to list more than 200 edge dns records
<hr />

[UXE-6155] fix: list more than 200 edge dns records

---

src/services/data-stream-services/list-data-stream-service.js
src/services/digital-certificates-services/v4/list-digital-certificates-service.js
src/services/edge-dns-records-services/list-records-service.js
src/tests/services/digital-certificates-services/v4/list-digital-certificates-service.test.js
src/tests/services/edge-dns-records-services/list-records-service.test.js

- fix: list more than 200 edge dns records
- fix: checking if the fields exist in the edge certificates return
<hr />

DEPLOY 2025-01-29 2

---

src/router/routes/domains-routes/index.js
src/services/domains-services/v4/delete-domain-service.js
src/services/domains-services/v4/index.js
src/tests/services/domains-services/v4/delete-domain-service.test.js

[UXE-6011] feat: migrate delete domain to v4 api
<hr />
[UXE-6011]: https://aziontech.atlassian.net/browse/UXE-6011?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[UXE-6011] feat: migrate delete domain to v4 api

---

package.json
src/templates/form-fields-inputs/fieldDropdownLazyLoader.vue

Fix: 
[UXE-6217] fix: arguments were not being loaded in edge application and edge firewall
<hr />
[UXE-6217]: https://aziontech.atlassian.net/browse/UXE-6217?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEPLOY 2025-01-30

---

src/services/domains-services/v4/create-domain-service.js
src/services/domains-services/v4/edit-domain-service.js
src/services/domains-services/v4/load-domain-service.js
src/tests/services/domains-services/v4/create-domain-service.test.js
src/tests/services/domains-services/v4/edit-domain-service.test.js

[UXE-6010] fix: create and edit workload after validation
N/A
<hr />
[UXE-6010]: https://aziontech.atlassian.net/browse/UXE-6010?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[UXE-6010] fix: create and edit workload after validation

---

src/helpers/account-data.js
src/router/hooks/guards/accountGuard.js
src/router/hooks/guards/billingGuard.js
src/templates/add-payment-method-block/index.vue
src/views/AccountSettings/AccountSettingsView.vue
src/views/Billing/Drawer/DrawerPaymentMethod.vue

[UXE-6007] fix: add message to alert the user who needs to complete address in payment method
should show message to add adress
<hr />
[UXE-6007]: https://aziontech.atlassian.net/browse/UXE-6007?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[UXE-6007] fix: Billing/Payment - add message to alert user to complete address

---

src/router/routes/edge-dns-routes/index.js
src/services/data-stream-services/list-data-stream-service.js
src/services/edge-dns-services/v4/delete-edge-dns-zone-service.js
src/services/edge-dns-services/v4/index.js
src/tests/services/edge-dns-services/v4/delete-edge-dns-zone-service.test.js

migrate edge dns zone deletion to api v4
<hr />

[UXE-5765] feat: migrate edge dns zone deletion to api v4

---

src/layout/components/menu-production/index.vue
src/services/sidebar-menus-services/menus.js

add menu siem to clients bb
NO
<hr />

[UXE-6220] feat: add menu siem to clients bb

---

src/modules/real-time-metrics/constants/dashboards.js
src/modules/real-time-metrics/constants/help-center-urls.js
src/modules/real-time-metrics/constants/reports.js
src/tests/modules/real-time-metrics/constants/dashboards.test.js
src/tests/modules/real-time-metrics/constants/reports.test.js
src/tests/modules/real-time-metrics/reports/fixtures/gql-fixtures.js

[UXE-6127] feat: add chart top waf threat request by ip
<hr />
[UXE-6127]: https://aziontech.atlassian.net/browse/UXE-6127?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[UXE-6127] feat: add chart top waf threat request by ip

---

src/router/routes/edge-node-routes/index.js
src/services/edge-node-services/v4/index.js
src/services/edge-node-services/v4/list-edge-node-service.js
src/services/edge-node-services/v4/make-edge-node-base-url.js
src/tests/services/edge-node-services/v4/list-edge-node-service.test.js
src/views/EdgeNode/ListView.vue

* removed Group column
* added test to new v4 service
<hr />

[UXE-5459] feat: update edge node list view and service import to v4

---

src/router/routes/waf-rules-routes/index.js
src/services/domains-services/v4/index.js
src/services/domains-services/v4/list-domain-service.js
src/services/domains-services/v4/load-domain-service.js
src/services/waf-rules-services/v4/index.js
src/services/waf-rules-services/v4/list-network-list-service.js
src/services/waf-rules-services/v4/load-network-list-service.js
src/templates/advanced-filter/component/fields/multiselect-lazy-loader-filter.vue
src/templates/advanced-filter/dialog-filter.vue
src/templates/form-fields-inputs/fieldDropdownLazyLoader.vue
src/templates/form-fields-inputs/fieldMultiselectLazyLoader.vue
src/tests/services/domains-services/v4/list-domain-service.test.js
src/tests/services/domains-services/v4/load-domain-service.test.js
src/views/WafRules/ListWafRulesTuning.vue
src/views/WafRules/TabsView.vue

* migrate network lists and domains dropdown in waf rules tuning
* create a fieldMultiselectLazyLoader component
* test case to new v4 service
* v4 migrate get by ID domain and network list
<hr />

[UXE-5889] feat: migrate network lists/domains filters in WAF Tunning for API v4

---

.github/workflows/local-prod-e2e-tests.yml

[NO-ISSUE] fix: Slack action version

---

src/services/edge-dns-services/v4/create-edge-dns-zones-service.js
src/tests/services/edge-dns-services/v4/create-edge-dns-zones-service.test.js

change success status in edge dns create api response
<hr />

[NO-ISSUE] fix: change success status in edge dns create api response

---

cypress/e2e/domains/create-domain-edge-application.cy.js
cypress/e2e/domains/create-domain-lets-encrypt.cy.js
cypress/e2e/domains/edit-domain.cy.js
cypress/e2e/edge-application/create-device-groups.cy.js
cypress/e2e/edge-application/function-instance/create-function-instance.cy.js
cypress/e2e/edge-application/function-instance/edit-function-instance.cy.js
cypress/e2e/edge-application/rules-engine/create-rule-engine-set-function.cy.js
cypress/e2e/edge-application/rules-engine/edit-rule-engine.cy.js
src/router/routes/domains-routes/index.js
src/router/routes/edge-application-routes/index.js
src/services/edge-application-services/v4/edit-edge-application-service.js
src/services/edge-application-services/v4/index.js
src/services/edge-application-services/v4/load-edge-application-service-dropdown.js
src/services/edge-application-services/v4/load-edge-application-service.js
src/tests/services/edge-application-services/v4/create-edge-applications-service.test.js
src/tests/services/edge-application-services/v4/edit-edge-applications-service.test.js
src/tests/services/edge-application-services/v4/load-edge-application-dropdown-service.test.js
src/tests/services/edge-application-services/v4/load-edge-applications-service.test.js
src/views/EdgeApplications/Config/ConfigView.vue
src/views/EdgeApplications/Drawer/index.vue
src/views/EdgeApplications/EditView.vue
src/views/EdgeApplications/FormFields/FormFieldsEditEdgeApplications.vue
src/views/EdgeApplications/TabsView.vue
src/views/EdgeApplicationsOrigins/Drawer/index.vue
src/views/EdgeApplicationsOrigins/ListView.vue
src/views/EdgeApplicationsRulesEngine/Drawer/index.vue
src/views/EdgeApplicationsRulesEngine/FormFields/FormFieldsEdgeApplicationsRulesEngine.vue
src/views/EdgeApplicationsRulesEngine/ListView.vue

feat: migrate edit edge application to v4
<hr />

[UXE-5704] feat: migrate edit edge application to v4

---

src/modules/real-time-metrics/constants/help-center-urls.js
src/modules/real-time-metrics/constants/reports.js
src/tests/modules/real-time-metrics/constants/reports.test.js
src/tests/modules/real-time-metrics/reports/fixtures/gql-fixtures.js

feat: add chart request by scheme
NO
<hr />

[UXE-6221] feat: add chart request by scheme

---

src/modules/real-time-metrics/constants/reports.js
src/tests/modules/real-time-metrics/constants/reports.test.js
src/tests/modules/real-time-metrics/reports/fixtures/gql-fixtures.js

feat: add chart top waf request by family attack
NO
<hr />

[UXE-6224] feat: add chart top waf request by family attack

---

src/modules/real-time-metrics/chart/format-c3-graph-props.js
src/modules/real-time-metrics/constants/reports.js
src/templates/graphs-card-block/components/chart/line-chart.vue
src/tests/modules/real-time-metrics/constants/reports.test.js
src/tests/modules/real-time-metrics/reports/fixtures/gql-fixtures.js

feat: add chart top waf request by host
NO
<hr />

[UXE-6225] feat: add chart top waf request by host

---

src/modules/real-time-metrics/constants/help-center-urls.js
src/modules/real-time-metrics/constants/reports.js
src/tests/modules/real-time-metrics/constants/reports.test.js
src/tests/modules/real-time-metrics/reports/fixtures/gql-fixtures.js

feat: add chart top bot traffic
NO
<hr />

[UXE-6227] feat: add chart top bot traffic

---

src/router/routes/edge-application-routes/index.js
src/services/edge-application-cache-settings-services/v4/create-cache-settings-service.js
src/services/edge-application-origins-services/create-origin-service.js
src/tests/services/edge-application-cache-settings-services/v4/create-cache-settings-service.test.js
src/views/EdgeApplications/Config/CacheEdgeApplication.vue
src/views/EdgeApplications/Config/ConfigView.vue
src/views/EdgeApplications/Config/OriginEdgeApplcation.vue

- Now, when a new Edge App is created with all configurations, the behaviors are automatically added to the Rules Engine.
<hr />

[NO-ISSUE] fix: Improvements in Edge App Editing After Code Review

---

src/modules/azion-ai-chat/services/chat-service.js

Reverts aziontech/azion-console-kit#2146

Revert "chore: include credentials in chat service request for improved security"

---

src/router/routes/edge-dns-routes/index.js
src/services/edge-dns-records-services/v4/delete-record-service.js
src/services/edge-dns-records-services/v4/index.js
src/services/edge-dns-records-services/v4/make-edge-dns-records-base-url.js
src/tests/services/edge-dns-records-services/v4/delete-record-service.test.js

migrate edge dns records deletion to api v4
<hr />

[UXE-6337] feat: migrate edge dns records deletion to api v4

---

src/modules/real-time-metrics/constants/reports-texts.js
src/modules/real-time-metrics/constants/reports.js
src/tests/modules/real-time-metrics/constants/reports.test.js
src/tests/modules/real-time-metrics/reports/fixtures/gql-fixtures.js

feat: updated chart request by method
NO
<hr />

[UXE-6228] feat: updated chart request by method

---

package.json

chore: upgrade version to 1.31.5

---

src/modules/real-time-metrics/constants/reports-texts.js
src/modules/real-time-metrics/constants/reports.js
src/modules/real-time-metrics/reports/convert-beholder-to-chart.js
src/templates/graphs-card-block/components/chart/pie-chart.vue
src/tests/modules/real-time-metrics/constants/reports.test.js

fix: implements filter empty values and filter attack chart label
NO
<hr />

[NO-ISSUE] fix: implements filter empty values and filter attack chart label

---

package.json
src/views/RealTimeMetrics/blocks/content-filter-block.vue
yarn.lock

[UXE-5228] chore: upgrade vue version

---

.github/workflows/pre-merge.yml

[NO-ISSUE] chore: Run tests on every open Pull Request

---

azion.config.cjs

[NO-ISSUE] fix: rm cache for marketplace

---

azion.config.cjs
azion/stage/azion.json

[NO-ISSUE] chore: Update IaC for stage

---

.github/workflows/deploy-production.yml
.github/workflows/deploy-stage.yml

Update Azion CLI version to 2.5.3 in deployment workflows
NO
NO
<hr />

[UXE-5949] chore: update Azion CLI version to 2.5.3 in deployment workflows

---

src/templates/advanced-filter/dialog-filter.vue

fix: adjust filter to support contains and not contains metrics filte
NO
<hr />

[NO-ISSUE] fix: adjust filter to support contains and not contains metrics filter

---

src/modules/real-time-metrics/constants/chart-rules.js
src/modules/real-time-metrics/constants/dashboards.js
src/modules/real-time-metrics/constants/reports-texts.js
src/modules/real-time-metrics/constants/reports.js
src/modules/real-time-metrics/reports/convert-beholder-to-chart.js
src/tests/modules/real-time-metrics/constants/chart-rules.test.js
src/tests/modules/real-time-metrics/constants/dashboards.test.js
src/tests/modules/real-time-metrics/constants/reports.test.js
src/tests/modules/real-time-metrics/reports/fixtures/gql-fixtures.js

- Added request breakdown table graphic
<hr />

[UXE-6226] feat: Added request breakdown table graphic

---

src/modules/real-time-metrics/constants/chart-rules.js
src/modules/real-time-metrics/constants/reports.js
src/tests/modules/real-time-metrics/constants/chart-rules.test.js
src/tests/modules/real-time-metrics/constants/reports.test.js
src/tests/modules/real-time-metrics/reports/fixtures/gql-fixtures.js

[UXE-6226] feat: add region column table graphic
<hr />
[UXE-6226]: https://aziontech.atlassian.net/browse/UXE-6226?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[UXE-6226] feat: add region column table graphic

---

src/modules/real-time-metrics/constants/reports.js
src/tests/modules/real-time-metrics/constants/reports.test.js

updated description charts
NO
NO
<hr />

[NO-ISSUE] chore: updated description charts

---

.github/workflows/pre-merge.yml

Reverts aziontech/azion-console-kit#2161

Revert "[NO-ISSUE] chore: Run tests on every open Pull Request"

---

src/modules/azion-ai-chat/services/chat-service.js

This pull request includes a small but important change to the `chatService` function in `src/modules/azion-ai-chat/services/chat-service.js`. The change ensures that credentials are included in the request.
* [`src/modules/azion-ai-chat/services/chat-service.js`](diffhunk://#diff-9ada71ff2f2f23554f4aacffbc5575a04296212a41d7cd909f1de3762bbe0d54L18-R19): Added the `credentials: 'include'` option to the fetch request to ensure that credentials are sent with the request.
NO
NO
<hr />

[UXE-6402] chore: include credentials in chat service request for improved security

---

package.json

update version to 1.31.6
NO
NO
<hr />

[NO-ISSUE] chore: update version to 1.31.6

---

azion/production/azion.json

[NO-ISSUE] chore: Update IaC for prod

---

azion/stage/azion.json

[NO-ISSUE] chore: Update IaC stage regarding cookies

---

azion/stage/azion.json

[NO-ISSUE] chore: Working around CLI issue

---

src/helpers/convert-gql.js
src/tests/helpers/convert-gql.test.js

fix: improve GraphQL type handling for complex filter queries
<hr />

[UXE-6214] fix: improve GraphQL type handling for complex filter queries

---

src/services/version-control-system-integration-services/post-callback-url-service.js
src/templates/template-engine-block/index.vue

parse correctly git hub installation callback post errors
<hr />

[UXE-5920] fix: parse correctly git hub installation callback post errors

---

package.json

update version to 1.31.7
NO
NO
<hr />

[NO-ISSUE] chore: bump version to 1.31.7

---

src/views/Domains/DeploymentView.vue
src/views/Domains/TabsView.vue

[UXE-6407] fix: redirect to list page when click on the cancel button
https://github.com/user-attachments/assets/6db5957a-80a8-4f12-b369-4ed07369e711
<hr />
[UXE-6407]: https://aziontech.atlassian.net/browse/UXE-6407?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[UXE-6407] fix: redirect to list page when click on the cancel button

---

src/templates/form-fields-inputs/fieldText.vue
src/views/EdgeApplications/FormFields/FormFieldsCreateEdgeApplications.vue

[UXE-6404] fix: ao click enter e recarregado a pagina em create edge app
https://github.com/user-attachments/assets/6ba68e21-bffa-41a0-8341-580d50f2de56
<hr />
[UXE-6404]: https://aziontech.atlassian.net/browse/UXE-6404?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[UXE-6404] fix: reload edge application create page when enter key is pressed

---

src/views/Home/HomeView.vue
vulcan.config.js

This pull request includes changes to the `HomeView.vue` file and the removal of a configuration file. The main focus is on cleaning up unused imports, removing deprecated features, and eliminating unnecessary code.
Code cleanup and removal of deprecated features:
* [`src/views/Home/HomeView.vue`](diffhunk://#diff-01d730d78411fcdbec8996b9983bfe06336d59183f2b15c6b2e1b1f2cc123e70L15-L17): Removed unused imports, including `InlineMessage` and `getStaticUrlsByEnvironment`.
* [`src/views/Home/HomeView.vue`](diffhunk://#diff-01d730d78411fcdbec8996b9983bfe06336d59183f2b15c6b2e1b1f2cc123e70L45-R42): Removed `isBannerVisible` from the destructured `useAccountStore` return object.
* [`src/views/Home/HomeView.vue`](diffhunk://#diff-01d730d78411fcdbec8996b9983bfe06336d59183f2b15c6b2e1b1f2cc123e70L119- …

[NO-ISSUE] refactor: remove banner for redirect rtm

---

cypress/support/selectors/block-selectors/list-table-block.js

[UXE-6422] test: fix digital certificate status flag assertion selector

---

azion/production/azion.json
cypress/support/selectors/block-selectors/list-table-block.js
package.json
src/helpers/convert-gql.js
src/modules/real-time-metrics/chart/format-c3-graph-props.js
src/services/version-control-system-integration-services/post-callback-url-service.js
src/templates/graphs-card-block/components/chart/line-chart.vue
src/templates/template-engine-block/index.vue
src/tests/helpers/convert-gql.test.js
src/views/Home/HomeView.vue
vulcan.config.js

- Improved GraphQL type handling for complex filter queries [(#2182)](https://github.com/aziontech/azion-console-kit/pull/2182)
- Correctly parse GitHub installation callback post errors [(#2179)](https://github.com/aziontech/azion-console-kit/pull/2179)
- Fixed digital certificate status flag assertion selector [(#2200)](https://github.com/aziontech/azion-console-kit/pull/2200)
- Bumped version to 1.31.7 [(#2198)](https://github.com/aziontech/azion-console-kit/pull/2198)
- Removed banner for redirect RTM [(#2202)](https://github.com/aziontech/azion-console-kit/pull/2202)
- Added rules engine manually in IAC [(#2203)](https://github.com/aziontech/azion-console-kit/pull/2203)
- Improved data volume formatting with new calculation method …

DEPLOY 2025-02-20

---

azion/production/azion.json

DEPLOY 2025-02-21 2

---

azion/production/azion.json

[NO-ISSUE] refactor: remove obsolete gzip enable rules from configuration

---

azion/production/azion.json

DEPLOY 2025-02-21 3

---

scripts/cleanup.js

(Parece que eu alterei um monte de coisa, mas grande parte é linter, unica inclusão de linhas foi o objeto de variables na lista de entidades)
Add variables deletion to cleanup action
<hr />

[UXE-6422] chore: add variables deletion to cleanup action

---

src/services/edge-application-services/edit-edge-application-service.js
src/services/edge-functions-services/edit-edge-functions-service.js

This pull request includes updates to error handling in two service files to provide more specific error messages related to WebSocket support.
Error handling improvements:
* [`src/services/edge-application-services/edit-edge-application-service.js`](diffhunk://#diff-60876543dba6a322c222e63de0020ea4c9094fea2c6b904d5c58deab674adfc2L80-R85): Modified the `extractErrorKey` function to check if the error message includes 'Websocket' and provide a more specific error message for WebSocket support issues.
* [`src/services/edge-functions-services/edit-edge-functions-service.js`](diffhunk://#diff-1efc3dd04f9c51ead454bd249d627cfc58d79b331c2896eafc9321427b02975dL23-R28): Updated the `extractErrorKey` function similarly to check for 'Websocket' in the error message and return a specific message for …

[NO-ISSUE] fix: enhance messaging for product access with WebSocket support

---

scripts/cleanup.js
src/router/hooks/guards/billingGuard.js
src/services/edge-application-services/edit-edge-application-service.js
src/services/edge-functions-services/edit-edge-functions-service.js

- Enhanced error messaging for user product access with WebSocket support details [(#2214)](https://github.com/aziontech/azion-console-kit/pull/2214)
- Allowed account settings access during payment review [(#2215)](https://github.com/aziontech/azion-console-kit/pull/2215)
- Added variables deletion to cleanup action [(#2208)](https://github.com/aziontech/azion-console-kit/pull/2208)
<hr />

DEPLOY 2025-02-21 (4)

---

src/views/WafRules/ListWafRulesTuning.vue

Reset total records value when domain is removed
<hr />

[UXE-6354] fix: reset total records value when there is no domain selected

---

src/helpers/convert-gql.js

[UXE-6335] fix: fix format filter paramenter
<hr />
[UXE-6335]: https://aziontech.atlassian.net/browse/UXE-6335?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[UXE-6335] fix: fix format filter paramenter

---

package.json
src/tests/services/real-time-events-service/get-total-records.test.js

chore: upgrade from version-1.31.9 to version-1.32.0

---

azion/stage/azion.json

This pull request includes changes to the `azion/stage/azion.json` file. The most important changes involve modifying the environment configuration and adding a new routing rule.
Configuration updates:
* Removed the `mode` attribute from the environment configuration.
Routing rules:
* Added a new routing rule for "API Version 4 Routing" with an ID of 371432 in the request phase.

[NO-ISSUE] chore: sync with azion cli for iac update

---

scripts/cleanup.js

fix clean up action timeout to be executed between resources delete
<hr />

[NO-ISSUE] chore: fix clean up action timeout to be executed between resources delete

---

src/services/real-time-events-service/data-stream/list-data-stream.js
src/services/real-time-events-service/data-stream/load-data-stream.js
src/services/real-time-events-service/edge-dns/list-edge-dns.js
src/services/real-time-events-service/edge-dns/load-edge-dns.js
src/services/real-time-events-service/edge-functions-console/list-edge-functions-console.js
src/services/real-time-events-service/edge-functions-console/load-edge-functions-console.js
src/services/real-time-events-service/edge-functions/list-edge-functions.js
src/services/real-time-events-service/edge-functions/load-edge-functions.js
src/services/real-time-events-service/tiered-cache/list-tiered-cache.js
src/services/real-time-events-service/tiered-cache/load-tiered-cache.js
src/tests/services/real-time-events-service/data-stream/list-data-stream.test.js
src/tests/services/real-time-events-service/edge-dns/list-edge-dns.test.js
src/tests/services/real-time-events-service/edge-functions-console/list-edge-functions-console.test.js
src/tests/services/real-time-events-service/edge-functions/list-edge-functions.test.js
src/tests/services/real-time-events-service/tiered-cache/list-tiered-cache.test.js

Refactor: Remove source fields on the real time events
N/A
<hr />

Refactor: Remove source fields on the real time events

---

src/services/real-time-events-service/activity-history/list-activity-history.js
src/services/real-time-events-service/data-stream/list-data-stream.js
src/services/real-time-events-service/edge-dns/list-edge-dns.js
src/services/real-time-events-service/edge-functions-console/list-edge-functions-console.js
src/services/real-time-events-service/edge-functions/list-edge-functions.js
src/services/real-time-events-service/http-request/list-http-request.js
src/services/real-time-events-service/image-processor/list-image-processor.js
src/services/real-time-events-service/tiered-cache/list-tiered-cache.js
src/tests/services/real-time-events-service/activity-history/list-activity-history.test.js
src/tests/services/real-time-events-service/data-stream/list-data-stream.test.js
src/tests/services/real-time-events-service/edge-dns/list-edge-dns.test.js
src/tests/services/real-time-events-service/edge-functions-console/list-edge-functions-console.test.js
src/tests/services/real-time-events-service/edge-functions/list-edge-functions.test.js
src/tests/services/real-time-events-service/http-request/list-http-request.test.js
src/tests/services/real-time-events-service/image-processor/list-image-processor.test.js
src/tests/services/real-time-events-service/tiered-cache/list-tiered-cache.test.js

[NO-ISSUE] refactor: order by desc real-time events
<hr />

[NO-ISSUE] refactor: order by desc real-time events

---

src/services/real-time-purge/list-real-time-purge-service.js
src/tests/services/real-time-purge/list-real-time-purge.test.js
src/views/RealTimePurge/ListView.vue

fix: disabled button re-purge to rows with request data null
<hr />

[UXE-6706] fix: disabled button re-purge to rows with request data null

---

src/services/real-time-events-service/get-total-records.js

[UXE-6732] Fix: show the actual query made in the real-time events
https://github.com/user-attachments/assets/4efc82e7-71ac-4b35-ad61-43261d2994b2
<hr />
- [] New tests are added to prevent the same issue from happening again
[UXE-6732]: https://aziontech.atlassian.net/browse/UXE-6732?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[UXE-6732] fix: Show correct query from real-time events in GQL Playground

---

src/helpers/azion-documentation-window-opener.js
src/layout/components/sidebar/helper.vue

[UXE-6708] feat: update link for opening tickets in the console
https://github.com/user-attachments/assets/b9da3e48-adfa-467c-8048-18669a1458df
<hr />
[UXE-6708]: https://aziontech.atlassian.net/browse/UXE-6708?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[UXE-6708] feat: update link for opening tickets in the console

---

src/services/real-time-events-service/activity-history/list-activity-history.js
src/services/real-time-events-service/data-stream/list-data-stream.js
src/services/real-time-events-service/edge-dns/list-edge-dns.js
src/services/real-time-events-service/edge-functions-console/list-edge-functions-console.js
src/services/real-time-events-service/edge-functions/list-edge-functions.js
src/services/real-time-events-service/http-request/list-http-request.js
src/services/real-time-events-service/image-processor/list-image-processor.js
src/services/real-time-events-service/tiered-cache/list-tiered-cache.js
src/tests/services/real-time-events-service/activity-history/list-activity-history.test.js
src/tests/services/real-time-events-service/data-stream/list-data-stream.test.js
src/tests/services/real-time-events-service/edge-dns/list-edge-dns.test.js
src/tests/services/real-time-events-service/edge-functions-console/list-edge-functions-console.test.js
src/tests/services/real-time-events-service/edge-functions/list-edge-functions.test.js
src/tests/services/real-time-events-service/http-request/list-http-request.test.js
src/tests/services/real-time-events-service/image-processor/list-image-processor.test.js
src/tests/services/real-time-events-service/tiered-cache/list-tiered-cache.test.js
src/views/RealTimeEvents/Blocks/constants/date-time-interval.js
src/views/RealTimeEvents/Blocks/interval-filter-block.vue

[UXE-6740] Feat: add a new option to the time filter
https://github.com/user-attachments/assets/f688855b-f692-4202-97bd-5c94d951df05
<hr />
[UXE-6740]: https://aziontech.atlassian.net/browse/UXE-6740?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[UXE-6740] feat: add 5 minutes option to Real Time Events filter

---

package.json

chore: Bump project version

---

.github/workflows/ai-review.yml
.github/workflows/complexity_check.yml
package.json
src/helpers/azion-documentation-window-opener.js
src/services/real-time-events-service/activity-history/list-activity-history.js
src/services/real-time-events-service/data-stream/list-data-stream.js
src/services/real-time-events-service/edge-dns/list-edge-dns.js
src/services/real-time-events-service/edge-functions-console/list-edge-functions-console.js
src/services/real-time-events-service/edge-functions/list-edge-functions.js
src/services/real-time-events-service/get-total-records.js
src/services/real-time-events-service/http-request/list-http-request.js
src/services/real-time-events-service/image-processor/list-image-processor.js
src/services/real-time-events-service/tiered-cache/list-tiered-cache.js
src/services/real-time-purge/list-real-time-purge-service.js
src/tests/services/real-time-events-service/activity-history/list-activity-history.test.js
src/tests/services/real-time-events-service/data-stream/list-data-stream.test.js
src/tests/services/real-time-events-service/edge-dns/list-edge-dns.test.js
src/tests/services/real-time-events-service/edge-functions-console/list-edge-functions-console.test.js
src/tests/services/real-time-events-service/edge-functions/list-edge-functions.test.js
src/tests/services/real-time-events-service/http-request/list-http-request.test.js
src/tests/services/real-time-events-service/image-processor/list-image-processor.test.js
src/tests/services/real-time-events-service/tiered-cache/list-tiered-cache.test.js
src/tests/services/real-time-purge/list-real-time-purge.test.js
src/views/RealTimeEvents/Blocks/constants/date-time-interval.js
src/views/RealTimeEvents/Blocks/interval-filter-block.vue
src/views/RealTimePurge/ListView.vue

Deploy 2025-03-11

---

src/services/domains-services/create-domain-service.js
src/services/domains-services/edit-domain-service.js
src/services/edge-firewall-services/v4/list-edge-firewall-service.js
src/templates/form-fields-inputs/fieldDropdownLazyLoader.vue
src/views/Domains/FormFields/FormFieldsCreateDomains.vue
src/views/Domains/FormFields/FormFieldsEditDomains.vue

handle domains page to users withous view access in edge firewall 
<hr />

[UXE-6026] fix: hide Edge Firewall field for users without view permission on Add/Edit Domain page

---

src/services/real-time-events-service/http-request/list-http-request.js
src/services/real-time-events-service/http-request/load-http-request.js
src/tests/services/real-time-events-service/http-request/list-http-request.test.js

[UXE-6744] fix: removed added filters in the event filter when searching for specific events
https://github.com/user-attachments/assets/4c441de5-10ce-4fb2-a02f-056c891e7b4a
<hr />
[UXE-6744]: https://aziontech.atlassian.net/browse/UXE-6744?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[UXE-6744] fix: Events drawer not displaying data for specific events

---

src/services/billing-services/list-service-and-products-changes-accounting-service.js
src/services/billing-services/load-current-invoice-service.js

adjust divergent data between rtm and console
the edge application data needs to be the same as the rtm
NO
<hr />

[UXE-6650] fix: Adjust Billing values between rtm and console (Tiered Cache)

---

package.json
src/helpers/azion-information-texts.js
src/helpers/index.js
src/router/routes/domains-routes/index.js
src/router/routes/edge-application-routes/index.js
src/services/billing-services/list-service-and-products-changes-accounting-service.js
src/services/domains-services/create-domain-service.js
src/services/domains-services/edit-domain-service.js
src/services/edge-application-services/v4/check-edge-application-locked-service.js
src/services/edge-application-services/v4/clone-edge-application-service.js
src/services/edge-application-services/v4/index.js
src/services/edge-firewall-services/v4/list-edge-firewall-service.js
src/services/real-time-events-service/http-request/list-http-request.js
src/services/real-time-events-service/http-request/load-http-request.js
src/services/workloads-services/check-workload-locked-service.js
src/services/workloads-services/index.js
src/services/workloads-services/makeWorkloadsBaseUrl.js
src/templates/form-fields-inputs/fieldDropdownLazyLoader.vue
src/templates/form-fields-inputs/fieldDropdownLazyLoaderDinaminc.vue
src/tests/services/edge-application-services/v4/clone-edge-applications-service.test.js
src/tests/services/real-time-events-service/http-request/list-http-request.test.js
src/views/Domains/EditView.vue
src/views/Domains/FormFields/FormFieldsCreateDomains.vue
src/views/Domains/FormFields/FormFieldsEditDomains.vue
src/views/EdgeApplications/Dialog/Clone.vue
src/views/EdgeApplications/TabsView.vue
src/views/EdgeFirewallRulesEngine/Drawer/index.vue
src/views/EdgeFirewallRulesEngine/FormFields/FormFieldsEdgeFirewallRulesEngine.vue

Deploy 2025-03-13

---

azion.config.mjs
src/helpers/get-static-urls-by-environment.js
src/helpers/go-to-classic-interface.js
src/services/billing-services/list-payment-history-service.js
src/tests/helpers/get-static-urls-by-environment.test.js
src/tests/services/billing-services/list-payment-history-service.test.js
src/views/Home/HomeView.vue
vite.config.js

Changing proxies to no longer use manager.azion.com domain
<hr />

[UXE-6709] refactor: remove references to manager.azion.com

---

src/views/EdgeFirewallRulesEngine/Drawer/index.vue
src/views/EdgeFirewallRulesEngine/FormFields/FormFieldsEdgeFirewallRulesEngine.vue

remove error message when user has no access to edge functions and disable selector
<hr />

[UXE-6484] fix: remove error message when user has no access to edge functions and disable selector

---

src/views/RealTimeEvents/Blocks/constants/filter-time.js
src/views/RealTimeEvents/Blocks/content-filter-block.vue
src/views/RealTimeEvents/Blocks/interval-filter-block.vue

[UXE-6612] feat: updated time filter on the real-time events
N/A
<hr />
[UXE-6612]: https://aziontech.atlassian.net/browse/UXE-6612?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[UXE-6612] fix: update time filter on the Real-Time Events for each request

---

azion/stage/azion.json

[NO-ISSUE] chore: Delete origin from IaC

---

src/helpers/convert-date.js
src/helpers/index.js
src/services/real-time-events-service/activity-history/list-activity-history.js
src/services/real-time-events-service/activity-history/load-activity-history.js
src/services/real-time-events-service/data-stream/list-data-stream.js
src/services/real-time-events-service/data-stream/load-data-stream.js
src/services/real-time-events-service/edge-dns/list-edge-dns.js
src/services/real-time-events-service/edge-functions-console/list-edge-functions-console.js
src/services/real-time-events-service/edge-functions-console/load-edge-functions-console.js
src/services/real-time-events-service/edge-functions/list-edge-functions.js
src/services/real-time-events-service/edge-functions/load-edge-functions.js
src/services/real-time-events-service/get-timezone.js
src/services/real-time-events-service/http-request/list-http-request.js
src/services/real-time-events-service/http-request/load-http-request.js
src/services/real-time-events-service/image-processor/list-image-processor.js
src/services/real-time-events-service/image-processor/load-image-processor.js
src/services/real-time-events-service/tiered-cache/list-tiered-cache.js
src/services/real-time-events-service/tiered-cache/load-tiered-cache.js

adjust timezone in requests to real time events
must add the timezone selected by the user in real time events
<hr />

[UXE-6641] fix: adjust timezone in requests to real time events

---

azion.config.mjs

[UXE-6704] feat: Add Rules on IaC for billing PDF

---

azion/stage/azion.json

[NO-ISSUE] chore: Update IaC for billing stage

---

src/services/billing-services/list-service-and-products-changes-accounting-service.js

fix: adjustment in the ordering of billing regions
should render regions in alphabetical order
<hr />

[UXE-6703] fix: ordering billing regions A->Z

---

src/services/billing-services/list-service-and-products-changes-accounting-service.js
src/services/billing-services/list-service-and-products-changes.js

[UXE-6779] chore: remove edge storage billing page
N/A
<hr />
[UXE-6779]: https://aziontech.atlassian.net/browse/UXE-6779?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[UXE-6779] chore: remove edge storage billing page

---

src/views/EdgeApplicationsRulesEngine/FormFields/FormFieldsEdgeApplicationsRulesEngine.vue

[UXE-6312] fix: added some variables that were missing in Criteria
https://github.com/user-attachments/assets/070e7690-d82a-4a3a-b318-f1eb59def182
<hr />
[UXE-6725]: https://aziontech.atlassian.net/browse/UXE-6725?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[UXE-6312]: https://aziontech.atlassian.net/browse/UXE-6312?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[UXE-6312] fix: add missing Criteria variables in edge application rules engine

---

src/helpers/account-timezone.js
src/helpers/index.js
src/services/digital-certificates-services/v4/list-digital-certificates-service.js
src/services/real-time-events-service/activity-history/list-activity-history.js
src/services/real-time-events-service/activity-history/load-activity-history.js
src/services/real-time-events-service/data-stream/list-data-stream.js
src/services/real-time-events-service/data-stream/load-data-stream.js
src/services/real-time-events-service/edge-dns/list-edge-dns.js
src/services/real-time-events-service/edge-functions-console/list-edge-functions-console.js
src/services/real-time-events-service/edge-functions-console/load-edge-functions-console.js
src/services/real-time-events-service/edge-functions/list-edge-functions.js
src/services/real-time-events-service/edge-functions/load-edge-functions.js
src/services/real-time-events-service/get-timezone.js
src/services/real-time-events-service/http-request/list-http-request.js
src/services/real-time-events-service/http-request/load-http-request.js
src/services/real-time-events-service/image-processor/list-image-processor.js
src/services/real-time-events-service/image-processor/load-image-processor.js
src/services/real-time-events-service/tiered-cache/list-tiered-cache.js
src/services/real-time-events-service/tiered-cache/load-tiered-cache.js
src/tests/helpers/account-timezone.test.js
src/tests/services/digital-certificates-services/v4/list-digital-certificates-service.test.js

[UXE-6072] fix: format the date with the correct timezone digital certificates
<hr />
[UXE-6072]: https://aziontech.atlassian.net/browse/UXE-6072?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[UXE-6072] fix: format the date with the correct timezone digital certificates

---

src/templates/list-table-block/index.vue

fix: ensure summary values are converted to strings to CSV formating
should correctly export http without errors for status 200
<hr />

[UXE-6790] fix: ensure summary values are converted to strings to CSV formating

---

package.json

chore: bump project version to 1.33.4

---

src/modules/real-time-metrics/constants/help-center-urls.js
src/modules/real-time-metrics/constants/reports.js
src/tests/modules/real-time-metrics/constants/reports.test.js

fix: update help center URLs in reports
should render url correct to help center
NO
<hr />

[UXE-6424] fix: update help center URLs in reports

---

src/views/EdgeApplications/Dialog/Clone.vue

fix: adjust clone edge application
<hr />

[NO-ISSUE] fix: adjust clone edge application

---

cypress.config.js
cypress.config.prod.js
cypress/e2e/edge-services/edit-edge-service-resource.cy.js

disable temporarily the edge service resource test
<hr />

[UXE-6422] test: disable temporarily the edge service resource test

---

src/layout/components/menu-production/index.vue

By adding the href attribute to menu links, this enables the native browser context menu with "Open in New Tab" functionality.
<hr />

[NO-ISSUE] feat: Enable products menu to open on new tab

---

package.json

Chore: updated project version to 1.33.5
N/A
<hr />

Chore: updated project version to 1.33.5

---

azion.config.mjs

Remove space in config rule engine for azsid

[UXE-6834] chore: remove space in config max-age

---

.github/workflows/deploy-production.yml
.github/workflows/deploy-stage.yml
azion.config.mjs
cypress.config.js
cypress.config.prod.js
cypress/e2e/edge-services/edit-edge-service-resource.cy.js
src/helpers/convert-gql.js
src/layout/components/menu-production/index.vue
src/services/edge-firewall-rules-engine-services/v4/list-edge-firewall-rules-engine-service.js
src/services/waf-rules-services/list-waf-rules-service.js
src/tests/services/edge-firewall-rules-engine-services/v4/list-edge-firewall-rules-engine-service.test.js
src/tests/services/waf-rules-services/list-waf-rules-service.test.js
src/views/EdgeApplications/Dialog/Clone.vue
src/views/EdgeApplicationsCacheSettings/FormFields/FormFieldsEdgeApplicationCacheSettings.vue
src/views/EdgeApplicationsRulesEngine/FormFields/FormFieldsEdgeApplicationsRulesEngine.vue
src/views/WafRules/ListWafRulesTuning.vue

- [UXE-6731] Fix: Displays domain names in the details area in WAF Tuning
- [UXE-6405] Fix: Remove template literal in cache policy to properly catch errors
- [UXE-6406] Fix: Corrects incorrect sending of Maximum TTL in cache settings
- [UXE-6797] Fix: Applies timezone to the last modified column in Edge Firewall Rules Engine
- [UXE-6870] Fix: Increases WAF rules page limit to 2000 to display all rules
- [UXE-6834] Fix: Adjust rule that incorrectly overrides Azion cookies' Max Age
<hr />
[UXE-6731]: https://aziontech.atlassian.net/browse/UXE-6731?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[UXE-6405]: https://aziontech.atlassian.net/browse/UXE-6405?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ …

DEPLOY 2025-03-25

---

src/services/version-control-system-integration-services/list-integrations-service.js
src/services/version-control-system-integration-services/list-platforms-service.js
src/services/version-control-system-integration-services/list-repositories-service.js
src/tests/services/version-control-system-integration-services/list-integrations-service.test.js
src/tests/services/version-control-system-integration-services/list-platforms-service.test.js
src/tests/services/version-control-system-integration-services/list-repositories-service.test.js

[UXE-6848] feat: vcs api v4 urls updates
https://github.com/user-attachments/assets/fd5002bf-a39b-4c6b-bc84-ece0a5897864
<hr />
[UXE-6848]: https://aziontech.atlassian.net/browse/UXE-6848?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[UXE-6848] feat: vcs api v4 urls updates

---

src/views/RealTimeEvents/Blocks/azion-query-language.js
src/views/RealTimeEvents/Blocks/azion-query-language.vue
src/views/RealTimeEvents/Blocks/content-filter-block.vue

fix: displaying error when typing expression without space between operator
should not allow the user to enter queries without spaces
NO
<hr />

[UXE-6733] fix: Real Time Events advanced filter - incorrect results due to space in query

---

src/views/RealTimeEvents/Blocks/azion-query-language.js

feat: add support between operation in filter advanced real time events
NO
NO
<hr />

[UXE-6734] feat: add support between operation in filter advanced real time events

---

package.json

Chore: updated project version to 1.34.0
N/A
<hr />

Chore: updated project version to 1.34.0

---

src/services/edge-application-rules-engine-services/v4/helper-behavior.js

…tring
change edge application rules behaviors to parse number ids to string
<hr />

[UXE-6904] fix: change edge application rules behaviors to parse number ids to string

---

cypress/e2mock/delete-account.cy.js
cypress/support/selectors/view-selectors/account-settings.js
src/services/account-services/delete-account-service.js
src/services/account-services/index.js
src/services/account-services/make-account-delete-base-url.js
src/templates/create-form-block/form-horizontal.vue
src/templates/list-table-block/dialog/delete-dialog.vue
src/views/AccountSettings/FormFields/FormFieldsAccountSettings.vue

https://ks18tz07zg.map.azionedge.net/
OBS: UI change already validated with design team
add delete account option in account settings page
<hr />

[UXE-5991] feat: add delete account option in account settings page

---

package.json

[NO-ISSUE] chore: bump project version to 1.35.0

---

src/services/data-stream-services/edit-data-stream-service.js
src/tests/services/data-stream-services/edit-data-stream-service.test.js

[UXE-6259] fix: added the active value to the data stream put request
N/A
<hr />
[UXE-6259]: https://aziontech.atlassian.net/browse/UXE-6259?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[UXE-6259] fix: added the active value to the data stream put request

---

src/services/users-services/create-users-service.js
src/services/users-services/edit-another-user-service.js
src/views/Users/CreateView.vue
src/views/Users/FormsFields/FormFieldsUsers.vue

[UXE-6097] feat: enable switch to activate and deactivate user
https://github.com/user-attachments/assets/c4ce6a41-824a-410e-b9c5-a1d951a08920
<hr />
[UXE-6097]: https://aziontech.atlassian.net/browse/UXE-6097?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[UXE-6097] feat: enable switch to activate and deactivate user

---

cypress/support/commands.js
src/helpers/convert-date.js
src/layout/components/menu-profile/index.vue
src/layout/components/navbar/switch-account.vue
src/services/billing-services/list-payment-history-service.js
src/services/billing-services/list-service-and-products-changes-accounting-service.js
src/services/billing-services/list-service-and-products-changes.js
src/services/billing-services/load-invoice-data-service.js
src/tests/helpers/convert-date.test.js
src/views/Billing/InvoiceDetailsView.vue

[UXE-6853] Fix: billing screen adjustments
<hr />
[UXE-6853]: https://aziontech.atlassian.net/browse/UXE-6853?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[UXE-6853] fix: billing screen adjustments

---

src/templates/advanced-filter/advanced-filter-no-hash.vue
src/views/RealTimeEvents/Blocks/azion-query-language.js
src/views/RealTimeEvents/Blocks/azion-query-language.vue
src/views/RealTimeEvents/Blocks/content-filter-block.vue

feat: save filters change tabs in real time events
NO
NO
<hr />

[UXE-5820] feat: save filters change tabs in real time events

---

package.json

Chore: updated project version to 1.36.0
N/A
<hr />

chore: updated project version to 1.36.0

---

cypress/support/commands.js
package.json
src/helpers/convert-date.js
src/layout/components/menu-profile/index.vue
src/layout/components/navbar/switch-account.vue
src/services/billing-services/list-payment-history-service.js
src/services/billing-services/list-service-and-products-changes-accounting-service.js
src/services/billing-services/list-service-and-products-changes.js
src/services/billing-services/load-invoice-data-service.js
src/services/data-stream-services/edit-data-stream-service.js
src/services/users-services/create-users-service.js
src/services/users-services/edit-another-user-service.js
src/templates/advanced-filter/advanced-filter-no-hash.vue
src/tests/helpers/convert-date.test.js
src/tests/services/data-stream-services/edit-data-stream-service.test.js
src/views/Billing/InvoiceDetailsView.vue
src/views/RealTimeEvents/Blocks/azion-query-language.js
src/views/RealTimeEvents/Blocks/azion-query-language.vue
src/views/RealTimeEvents/Blocks/content-filter-block.vue
src/views/Users/CreateView.vue
src/views/Users/FormsFields/FormFieldsUsers.vue

- [UXE-6259] Fix: Include active value in Data Stream update request
- [UXE-6853] Fix: Billing screen adjustments for improved usability
- [UXE-6733] Fix: Prevent execution of queries with errors
- [UXE-6097] Feature: Enable switch to activate and deactivate users
- [UXE-5820] Feature: Save filters when switching tabs in Real Time Events
<hr />
[UXE-6259]: https://aziontech.atlassian.net/browse/UXE-6259?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[UXE-6853]: https://aziontech.atlassian.net/browse/UXE-6853?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[UXE-6733]: https://aziontech.atlassian.net/browse/UXE-6733?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU …

DEPLOY 2025-04-01

---

cypress/e2e/billing/list-payments.cy.js
cypress/support/selectors/product-selectors/billing.js
src/services/billing-services/list-payment-history-service.js

[UXE-6853] fix: remove current payment
<hr />
[UXE-6853]: https://aziontech.atlassian.net/browse/UXE-6853?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[UXE-6853] fix: remove current month bill from list

---

cypress/e2mock/waf-rules/waf-rules-tuning.cy.js
cypress/fixtures/waf-rules/tuning/available-domains.json
cypress/fixtures/waf-rules/tuning/details.json
cypress/fixtures/waf-rules/tuning/tuning-list.json
cypress/fixtures/waf-rules/waf-list.json
cypress/fixtures/waf-rules/waf-main-settings.json
cypress/support/selectors.js
cypress/support/selectors/product-selectors/waf-tuning.js
src/services/waf-rules-services/create-waf-rules-allowed-tuning-service.js
src/templates/list-table-block/with-selection-behavior.vue
src/views/WafRules/Dialog/index.vue
src/views/WafRules/Drawer/index.vue
src/views/WafRules/ListWafRulesTuning.vue

send allow rule payload correctly to attacks with ruleId 11
<hr />

[UXE-6858] fix: send allow rule payload correctly to attacks with ruleId 11

---

src/views/RealTimeEvents/Blocks/azion-query-language.js
src/views/RealTimeEvents/Blocks/azion-query-language.vue
src/views/RealTimeEvents/Blocks/content-editable.vue

feat: implements highlight syntax in filter advanced
NO
<hr />

[UXE-6736] feat: implements highlight syntax in filter advanced

---

package.json

Chore: updated project version to 1.36.1
N/A
<hr />

chore: updated project version to 1.36.1

---

package.json

Update project version to 1.36.2
No
No
<hr />

[NO-ISSUE] chore: update project version to 1.36.2

---

cypress/e2e/domains/edit-domain.cy.js
cypress/support/selectors/product-selectors/domains.js
src/services/domains-services/edit-domain-service.js
src/templates/form-fields-inputs/fieldDropdownLazyLoader.vue
src/tests/services/domains-services/edit-domain-service.test.js
src/views/Domains/FormFields/FormFieldsCreateDomains.vue
src/views/Domains/FormFields/FormFieldsEditDomains.vue

Allow to remove selected edge firewall in domains edit page
<hr />

[UXE-6939] fix: allow to remove selected edge firewall in domains edit page

---

src/templates/list-table-block/dialog/delete-dialog.vue
src/views/AccountSettings/FormFields/FormFieldsAccountSettings.vue

Update delete account service to use async/await for improved handling
NO<hr />

[UXE-5991] fix: update delete account service to use async/await for improved handling

---

cypress/e2e/domains/edit-domain.cy.js
cypress/e2mock/delete-account.cy.js
cypress/e2mock/edge-firewall/rules-engine/network-in-list.cy.js
cypress/e2mock/feedback.cy.js
cypress/support/commands.js
cypress/support/selectors.js
cypress/support/selectors/block-selectors/header-block.js
cypress/support/selectors/product-selectors/domains.js
cypress/support/selectors/product-selectors/edge-firewall.js
cypress/support/selectors/view-selectors/account-settings.js
package.json
src/layout/components/navbar/feedback.vue
src/services/account-services/delete-account-service.js
src/services/account-services/index.js
src/services/account-services/make-account-delete-base-url.js
src/services/domains-services/edit-domain-service.js
src/templates/create-form-block/form-horizontal.vue
src/templates/form-fields-inputs/fieldDropdownLazyLoader.vue
src/templates/form-fields-inputs/fieldDropdownLazyLoaderDinaminc.vue
src/templates/list-table-block/dialog/delete-dialog.vue
src/tests/services/domains-services/edit-domain-service.test.js
src/views/AccountSettings/FormFields/FormFieldsAccountSettings.vue
src/views/Domains/FormFields/FormFieldsCreateDomains.vue
src/views/Domains/FormFields/FormFieldsEditDomains.vue

- Add delete account option in account settings page
- Fix edge firewall rule with network lists criteria not loading correctly
- Fix allow to remove selected edge firewall in domains edit page
- Fix Clear form fields after submission feedback
- Update project version to 1.36.2
<hr />

DEPLOY 2025-04-10

---

src/helpers/convert-gql.js
src/templates/advanced-filter/component/index.js
src/views/RealTimeEvents/Blocks/azion-query-language.js
src/views/RealTimeEvents/Blocks/azion-query-language.vue
src/views/RealTimeEvents/Blocks/content-editable.vue

the correct validations must take place
NO
<hr />

[UXE-6931] fix: enhance AQL operator error handling and update advanced filter mappings

---

cypress/e2e/edge-application/edit-cache-setting.cy.js
cypress/support/selectors/product-selectors/edge-application.js
src/views/EdgeApplicationsCacheSettings/FormFields/FormFieldsEdgeApplicationCacheSettings.vue

allow to disable large file optimization in tiered cache settings
<hr />

[UXE-6729] fix: allow to disable large file optimization in tiered cache settings

---

src/services/edge-application-origins-services/create-origin-service.js
src/services/edge-application-origins-services/edit-origin-service.js
src/tests/services/edge-application-origins-services/create-origin-service.test.js
src/tests/services/edge-application-origins-services/edit-origin-service.test.js

Remove unused connection timeout and byte timeout from origin 
NO
<hr />

[UXE-6908] refactor: remove unused connection timeout and byte timeout from origin 

---

cypress/e2e/data-stream/delete-data-stream-s3.cy.js
cypress/support/commands.js
src/router/routes/data-stream-routes/index.js
src/services/data-stream-services/v4/delete-data-stream-service.js
src/services/data-stream-services/v4/index.js
src/services/data-stream-services/v4/make-data-stream-base-url.js
src/tests/services/data-stream-services/v4/delete-data-stream-service.test.js
src/tests/services/data-stream-services/v4/make-data-stream-base-url.test.js

[UXE-6980] feat: migrate delete data stream to v4
https://github.com/user-attachments/assets/f7663027-eeb7-4fdf-84ea-16fc020d2ec0
<hr />
[UXE-6980]: https://aziontech.atlassian.net/browse/UXE-6980?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[UXE-6980] feat: migrate delete data stream to v4

---

src/services/billing-services/load-current-invoice-service.js
src/templates/list-table-block/dialog/delete-dialog.vue

remove toast error message 'false' when deliting an entity
<hr />

[NO ISSUE] fix: remove toast error message 'false' when deleting an entity

---

.github/workflows/cleanup-e2e-tests.yml

chore: Clean up every 1h

---

cypress/e2mock/real-time-events/http-requests.cy.js
cypress/fixtures/real-time-events/list-http-requests.json
cypress/fixtures/real-time-events/load-http-requests-second.json
cypress/fixtures/real-time-events/load-http-requests.json
src/services/real-time-events-service/http-request/load-http-request.js
src/tests/services/real-time-events-service/http-request/load-http-request.test.js
src/views/RealTimeEvents/Blocks/tab-panel-block.vue
src/views/RealTimeEvents/Drawer/tableEvents.vue

feat: add button copy to field wafEvheaders
YES
https://www.figma.com/design/0TY2pcUTBsndMlrs0ZUvQf/Console-UI?node-id=18930-6844&t=XEHINRqs7Cn3VTIi-0
<hr />

[UXE-6854] feat: add wafEvheaders field to Real Time Events drawer

---

src/helpers/local-storage-manager.js
src/helpers/redirect-cli.js
src/router/hooks/guards/loadingGuard.js
src/router/hooks/guards/redirectGuard.js
src/tests/helpers/local-storage-manager.test.js

Implement CLI login support with create personal token
https://github.com/user-attachments/assets/6cec9095-6649-4cfe-b2e7-a1d1200f1206
NO
<hr />

[UXE-6990] feat: implement CLI login support with create personal token

---

src/services/billing-services/list-payment-history-service.js
src/tests/services/billing-services/list-payment-history-service.test.js

update payment history to conditionally remove current payment for regular accounts
<hr />

[UXE-7147] fix: update current payment for online users in payment history

---

src/composables/user-flag.js
src/router/hooks/beforeEachRoute.js
src/router/hooks/guards/flagGuard.js
src/router/hooks/guards/index.js
src/stores/account.js

feat: add user flag functionality and integrate flag guard in routing
NO
NO
<hr />

[NO-ISSUE] feat: add user flag functionality and integrate flag guard in routing

---

src/helpers/azion-documentation-catalog.js
src/router/index.js
src/router/routes/edge-connectors-routes/index.js
src/services/edge-connectors/index.js
src/services/edge-connectors/list-edge-connectors-service.js
src/services/edge-connectors/make-edge-connectors-base-url.js
src/views/EdgeConnectors/ListView.vue

add edge connectors routes and services
NO
NO
<hr />

[UXE-7095] feat: add edge connectors routes and services

---

cypress/e2mock/teams-permissions.cy.js

fixed test Teams Permissions to correctly mock the listing #2377
NO
NO
<hr />

[NO-ISSUE] test: fixed test Teams Permissions to correctly mock the listing

---

src/helpers/azion-documentation-catalog.js
src/router/index.js
src/router/routes/custom-pages-routes/index.js
src/services/custom-pages-services/v4/delete-custom-pages-service.js
src/services/custom-pages-services/v4/index.js
src/services/custom-pages-services/v4/list-custom-pages-service.js
src/services/custom-pages-services/v4/make-custom-pages-base-url.js
src/services/sidebar-menus-services/menus.js
src/views/CustomPages/ListView.vue

Adds custom pages delete and get services.
Adds custom pages routes and menu.
Integrates custom pages into routing and sidebar configurations,
enabling navigation to personalized content.
no
<hr />

[UXE-7130] feat: new custom pages get and delete features

---

cypress/e2e/domains/create-domain-edge-application.cy.js
src/services/domains-services/create-domain-service.js

add validation for invalid CNAME format during domain creation and enhance error handling in domain services
<hr />

[UXE-6924] fix: add validation for invalid CNAME format during domain creation

---

cypress/e2e/domains/create-domain-mtls.cy.js

Reverts aziontech/azion-console-kit#2369

Revert "chore: Skip domain with a mTLS certificate test"

---

cypress/e2e/domains/edit-domain.cy.js
src/services/domains-services/edit-domain-service.js

improve error handling in edit domain by cnames
<hr />

[UXE-6924] refactor: improve error handling in edit domain by cnames

---

package.json

Update project version to 1.38.0
No
No
<hr />

[NO-ISSUE] chore: update project version to 1.38.0

---

src/router/routes/edge-connectors-routes/index.js
src/services/edge-connectors/create-edge-connectors-service.js
src/services/edge-connectors/index.js
src/tests/services/sidebar-menus-services/list-sidebar-menus-service.test.js
src/views/EdgeConnectors/CreateView.vue
src/views/EdgeConnectors/FormFields/FormFieldsEdgeConnectors.vue
src/views/EdgeConnectors/ListView.vue

feat: add new edge connectors
NO
NO
<hr />

[UXE-7098] feat: add new edge connectors

---

src/router/routes/custom-pages-routes/index.js
src/services/edge-connectors/index.js
src/services/edge-connectors/list-edge-connectors-service.js
src/services/edge-connectors/make-edge-connectors-base-url.js
src/views/CustomPages/CreateView.vue
src/views/CustomPages/EditView.vue
src/views/CustomPages/FormFields/FormFieldsCustomPages.vue

* added list edge connectors in custom pages form
<hr />

[UXE-7132] feat: added list edge connectors in custom pages form

---

cypress/e2e/real-time-events/advanced-filter.cy.js
cypress/e2mock/waf-rules/waf-rules-tuning.cy.js
src/services/waf-rules-services/create-waf-rules-allowed-tuning-service.js

fix in creating WAF rules without more details and path
<hr />

[UXE-7181] fix: adjustment in creating WAF rules without further details and path

---

src/views/CustomPages/FormFields/FormFieldsCustomPages.vue

Eliminates the unsupported "425: Too Early" code from custom page configurations,
streamlining error responses.
no
no
<hr />

[UXE-7132] refactor: removes outdated status code entry

---

cypress/e2e/real-time-events/advanced-filter.cy.js
cypress/e2mock/waf-rules/waf-rules-tuning.cy.js
package.json
src/services/waf-rules-services/create-waf-rules-allowed-tuning-service.js

- [UXE-7181] fix: adjustment in creating WAF rules without further details and path
<hr />
[UXE-7181]: https://aziontech.atlassian.net/browse/UXE-7181?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEPLOY 2025-05-06

---

src/router/routes/workload-routes/index.js
src/services/custom-pages-services/v4/index.js
src/services/custom-pages-services/v4/list-custom-pages-service.js
src/services/custom-pages-services/v4/load-custom-pages-services.js
src/services/custom-pages-services/v4/make-custom-pages-base-url.js
src/services/workload-deployment-service/edit-workload-deployment-service.js
src/services/workload-deployment-service/list-workload-deployment-service.js
src/views/RealTimeEvents/Blocks/constants/query-fields.js
src/views/Workload/DeploymentView.vue
src/views/Workload/FormFields/FormFieldsEditWorkload.vue
src/views/Workload/TabsView.vue

Adds lazy dropdown to workloads deployment.
Extends workload deployment mapping to include custom page bindings.
https://github.com/user-attachments/assets/98666360-5352-424e-8b14-3392b396cc58
no
<hr />

[UXE-7150] feat: add custom pages dropdown to workloads form

---

cypress/e2e/users-management/create-user-owner.cy.js
src/views/Users/FormsFields/FormFieldsUsers.vue

[UXE-7057] fix: difficulty in making the user the owner of the account
<hr />
[UXE-7057]: https://aziontech.atlassian.net/browse/UXE-7057?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[UXE-7057] fix: difficulty in making the user the owner of the account

---

package.json

feat: Update package.json

---

cypress/e2e/real-time-events/advanced-filter.cy.js
cypress/e2mock/waf-rules/waf-rules-tuning.cy.js
package.json
src/services/billing-services/index.js
src/services/billing-services/list-service-and-products-changes-accounting-service.js
src/services/edge-application-functions-services/list-edge-application-functions-service.js
src/services/edge-application-functions-services/v4/list-edge-functions-service.js
src/services/real-time-purge/list-real-time-purge-service.js
src/services/waf-rules-services/create-waf-rules-allowed-tuning-service.js
src/tests/services/billing-services/list-service-and-products-changes-accounting-service.test.js
src/tests/services/edge-application-functions-services/list-edge-application-functions-service.test.js
src/tests/services/edge-application-functions-services/list-edge-functions-service.test.js
src/tests/services/edge-application-functions-services/list-functions-service.test.js
src/tests/services/edge-application-functions-services/load-function-service.test.js
src/tests/services/edge-application-functions-services/v4/list-edge-functions-service.test.js
src/tests/services/edge-firewall-functions-services/list-functions-service.test.js
src/tests/services/edge-firewall-functions-services/load-function-service.test.js
src/tests/services/edge-firewall-functions-services/v4/load-function-service.test.js
src/tests/services/real-time-purge/list-real-time-purge.test.js
src/views/EdgeApplicationsFunctions/ListView.vue

Deploy 2025-05-09

---

src/composables/user-flag.js
src/helpers/azion-documentation-catalog.js
src/router/hooks/guards/flagGuard.js
src/router/routes/edge-connectors-routes/index.js
src/services/edge-connectors/create-edge-connectors-service.js
src/services/edge-connectors/edit-edge-connectors-service.js
src/services/edge-connectors/list-edge-connectors-service.js
src/services/edge-connectors/load-edge-connectors-service.js
src/views/EdgeConnectors/CreateView.vue
src/views/EdgeConnectors/EditView.vue
src/views/EdgeConnectors/FormFields/FormFieldsEdgeConnectors.vue
src/views/EdgeConnectors/ListView.vue

fix: adjustments found in validation
NO
<hr />

[UXE-7095] fix: adjustments found in validation

---

cypress/e2e/edge-application/rules-engine/account-info-data.js
cypress/e2e/edge-application/rules-engine/create-rule-engine-set-edge-connectors.cy.js
cypress/e2e/edge-application/rules-engine/edge-connectors-data.js
cypress/support/selectors/product-selectors/edge-application.js
src/services/edge-application-rules-engine-services/v4/helper-behavior.js
src/views/EdgeApplicationsRulesEngine/FormFields/FormFieldsEdgeApplicationsRulesEngine.vue

feat: add account info and edge connectors data for rule engine tests and add new behavior in rules engine
<hr />

[UXE-7128] feat: add new behavior in rules engine edge application and adjustments tests

---

src/views/EdgeApplicationsRulesEngine/FormFields/FormFieldsEdgeApplicationsRulesEngine.vue

feat: refactor behavior options to use dynamic function for origin and edge connectors
NO
NO
<hr />

[UXE-7128] feat: refactor behavior options to use dynamic function

---

src/services/custom-pages-services/v4/list-custom-pages-service.js
src/views/Workload/FormFields/FormFieldsEditWorkload.vue

[UXE-7150] feat: add Custom Pages selector in Workload Deployments screen

---

cypress/e2mock/edge-connectors/create-edge-connectors.cy.js
cypress/support/selectors/product-selectors/edge-connectors.js
src/views/EdgeConnectors/CreateView.vue
src/views/EdgeConnectors/EditView.vue
src/views/EdgeConnectors/FormFields/FormFieldsEdgeConnectors.vue

refactor: adjust validation name in vee validade schema
NO
NO
<hr />

[NO-ISSUE] refactor: Edge Connector - adjust validations

---

src/helpers/build-summary.js
src/views/RealTimeEvents/Drawer/tableEvents.vue

[UXE-6925] feat: add format json in the stacktrace and requestData field
<hr />
[UXE-6925]: https://aziontech.atlassian.net/browse/UXE-6925?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[UXE-6925] feat: Real-Time Events - format json in the stacktrace and requestData fields

---

src/services/vulcan-services/list-vulcan-presets-service.js
src/services/vulcan-services/make-project-samples-base-url.js
src/views/ImportGitHub/FormFields/FormFieldsImportGithub.vue

[UXE-7182] feat: update preset automatically on the import github page
https://github.com/user-attachments/assets/cf26d4d8-69ce-49d3-ab60-f519407d73cc
<hr />
[UXE-7182]: https://aziontech.atlassian.net/browse/UXE-7182?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[UXE-7182] feat: update preset automatically on the import github page

---

src/views/MFAManagement/ListView.vue

- Before: Users without names were not showing properly in the list
- After: Now all users show their email, even when they don't have a name
NO
<hr />

[UXE-7415] hotfix: fix display user email when name is not available

---

src/layout/components/menu-production/index.vue
src/services/sidebar-menus-services/menus.js
src/views/Home/HomeView.vue

New re-organization and tag style on sidebar menu. (Alphabetical order in subgroups)
https://www.figma.com/design/m1ZkbEPzLlbA2bb5G0erZX/UI-Refinement--Workloads-Migration?node-id=2450-22125&t=RkM2BRfOXpwUUJNh-4
<hr />

[UXE-7317] feat: reorganized menu options and new tag color applied for preview.

---

src/services/v2/adapters/edge-function-adapter.js
src/services/v2/edge-application-functions-service.js
src/services/v2/edge-function-service.js
src/views/EdgeApplicationsFunctions/ListView.vue

perf: performance improvements in edge function
NO
NO
<hr />

[UXE-7334] perf: performance improvements in edge function

---

src/services/v2/adapters/edge-dns-adapter.js
src/services/v2/edge-dns-service.js
src/templates/form-fields-inputs/fieldTextIcon.vue
src/views/EdgeDNS/FormFields/FormFieldsEditEdgeDns.vue

fix: adjust view edge dns required in ui validation
<hr />

[UXE-7331] fix: adjust view edge dns required in ui validation

---

src/templates/form-fields-inputs/fieldDropdownMultiSelectLazyLoader.vue

feat: implements new component dropdown multi select lazy loader
NO
NO
<hr />

[UXE-7458] feat: implements new component dropdown multi select lazy loader

---

src/services/v2/adapters/edge-firewall-adapter.js
src/services/v2/adapters/edge-firewall-function-adapter.js
src/views/EdgeFirewall/EditView.vue
src/views/EdgeFirewall/FormFields/FormFieldsEdgeFirewall.vue
src/views/EdgeFirewallFunctions/ListView.vue
src/views/EdgeFirewallRulesEngine/Drawer/index.vue

[UXE-7503] feat: adjustments api v4 function instances
<hr />
[UXE-7503]: https://aziontech.atlassian.net/browse/UXE-7503?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[UXE-7503] feat: adjustments api v4 Edge FW function instances

---

src/services/v2/adapters/edge-function-adapter.js
src/views/EdgeFunctions/ListView.vue

* update vendor and icon display fallbacks in edge functions
<hr />

[UXE-7504] feat: update vendor and icon display fallbacks in edge functions

---

src/services/real-time-purge/list-real-time-purge-service.js
src/tests/services/real-time-purge/list-real-time-purge.test.js
src/views/RealTimePurge/Dialog/index.vue
src/views/RealTimePurge/FormFields/FormFieldsCreateRealTimePurge.vue
src/views/RealTimePurge/ListView.vue

[UXE-7506] feat: purge ui general adjustments
<hr />
[UXE-7506]: https://aziontech.atlassian.net/browse/UXE-7506?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[UXE-7506] feat: purge ui general adjustments

---

src/services/v2/adapters/digital-certificates-csr-adapter.js
src/views/DigitalCertificates/CreateView.vue
src/views/DigitalCertificates/FormFields/blocks/ImportServerCertificate.vue
src/views/DigitalCertificates/FormFields/blocks/RequestCertificate.vue
src/views/DigitalCertificates/FormFields/composables/certificate.js
src/views/DigitalCertificates/FormFields/composables/validation.js
src/views/DigitalCertificates/ListView.vue

feat: enhance digital certificate forms with dynamic titles and placeholders based on certificate type
NO
https://www.figma.com/design/m1ZkbEPzLlbA2bb5G0erZX/UI-Refinement--Workloads-Migration?node-id=2580-26985&m=dev
<hr />

[UXE-7481] feat: enhance digital certificate forms with dynamic titles and placeholders based on certificate type

---

src/views/CustomPages/Blocks/responseDetailsBlock.vue
src/views/CustomPages/ConfigForm/listStatusCode.js

[UXE-7485] refactor: ajusted drawer custom page for type default

---

src/services/v2/adapters/custom-page-adapter.js
src/services/v2/custom-page-service.js
src/services/v2/utils/buildQueryParams.js
src/templates/form-fields-inputs/fieldTextArea.vue
src/views/CustomPages/Blocks/responseDetailsBlock.vue
src/views/CustomPages/Blocks/statusCodeBlock.vue
src/views/CustomPages/Blocks/statusConfigurationBlock.vue
src/views/CustomPages/ConfigForm/listStatusCode.js
src/views/CustomPages/ConfigForm/validationSchema.js
src/views/CustomPages/FormFields/CustomPages.vue
src/views/CustomPages/View.vue

[UXE-7485] refactor: update custom page service and ui

---

src/services/v2/edge-application-functions-service.js

[UXE-7596] fix: show all edge functions instance on the edge app
<hr />
[UXE-7596]: https://aziontech.atlassian.net/browse/UXE-7596?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[UXE-7596] fix: show all edge functions instance on the edge app

---

src/services/v2/adapters/edge-app-adapter.js
src/views/EdgeApplications/ListView.vue

[NO-ISSUE] feat: add status column on the edge app page
<hr />

[NO-ISSUE] feat: add status column on the Edge App list page

---

src/helpers/helper-behavior.js
src/services/v2/adapters/edge-app-rules-engine-adapter.js
src/services/v2/edge-app-rules-engine-service.js
src/templates/list-table-block/v2/index.vue
src/views/EdgeApplicationsRulesEngine/Dialog/components/ReorderedRules.vue
src/views/EdgeApplicationsRulesEngine/Dialog/components/RuleChangeDetail.vue
src/views/EdgeApplicationsRulesEngine/Dialog/order-dialog.vue
src/views/EdgeApplicationsRulesEngine/Drawer/index.vue
src/views/EdgeApplicationsRulesEngine/ListView.vue

UI Review
API Improvements
NO
https://www.figma.com/design/m1ZkbEPzLlbA2bb5G0erZX/UI-Refinement--Workloads-Migration?node-id=5-98&p=f&m=dev
<hr />

[UXE-7594] feat: rules engine ui review and api improvements

---

src/services/v2/adapters/edge-connectors-adapter.js
src/views/EdgeConnectors/CreateView.vue
src/views/EdgeConnectors/FormFields/blocks/Address.vue
src/views/EdgeConnectors/composables/validation.js

[UXE-7521] fix: update Edge Connectors address management and data adapters to handle load balancer configuration

---

src/helpers/helper-behavior.js
src/services/v2/adapters/edge-connectors-adapter.js
src/services/v2/adapters/edge-storage-adapter.js
src/views/EdgeApplicationsRulesEngine/Drawer/index.vue
src/views/EdgeConnectors/composables/validation.js

fix: improve error handling and adjusts returns in adapters
<hr />

[NO-ISSUE] fix: Edge Connectors - improve error handling and adjusts returns in adapters

---

src/services/v2/adapters/digital-certificates-crl-adapter.js
src/services/v2/adapters/edge-app-adapter.js
src/services/v2/adapters/edge-firewall-adapter.js
src/services/v2/adapters/workload-adapter.js
src/services/v2/base/httpService.js
src/services/v2/digital-certificates-service.js
src/services/v2/edge-app-service.js
src/services/v2/edge-firewall-service.js
src/services/v2/utils/errorHandler.js
src/services/v2/utils/hasAnyFieldChanged.js
src/services/v2/workload-service.js
src/templates/form-fields-inputs/fieldDropdownLazyLoaderWithFilter.vue
src/views/Workload/FormFields/blocks/deploymentSettingsBlock.vue
src/views/Workload/FormFields/blocks/domainsBlock.vue
src/views/Workload/FormFields/blocks/mutualAuthenticationSettingsBlock.vue
src/views/Workload/ListView.vue

[NO-ISSUE] feat: Dealing with the error when trying to create a let encrypt
<hr />

[NO-ISSUE] feat: Dealing with the error when trying to create a let encrypt

---

src/services/v2/edge-app-rules-engine-service.js
src/templates/list-table-block/v2/index.vue
src/views/EdgeApplicationsCacheSettings/ListView.vue
src/views/EdgeApplicationsRulesEngine/ListView.vue

fix: optimize rules engine position swapping and remove cancel button
<hr />

[NO-ISSUE] fix: optimize rules engine position swapping and remove cancel button

---

src/services/marketplace-services/load-solution-service.js
src/views/ImportGitHub/FormFields/FormFieldsImportGithub.vue
src/views/ImportGitHub/ImportGithubView.vue
src/views/WafRules/FormFields/FormFieldsAllowed.vue

[NO-ISSUE] fix: small UI adjustments waf and custom page

---

src/services/v2/adapters/edge-connectors-adapter.js
src/services/v2/utils/adapter/parse-status-utils.js
src/views/EdgeConnectors/CreateView.vue
src/views/EdgeConnectors/FormFields/blocks/Address.vue
src/views/EdgeConnectors/FormFields/blocks/ConnectorType.vue
src/views/EdgeConnectors/FormFields/blocks/hmac.vue
src/views/EdgeConnectors/composables/validation.js

fix: fix: disable connector type field in edit mode and improve address block UI
<hr />

[NO-ISSUE] fix: disable connector type field in edit mode and improve address block UI

---

src/services/v2/adapters/digital-certificates-adapter.js
src/templates/list-table-block/columns/column-builder.js
src/templates/list-table-block/columns/expand-text-column.vue
src/views/DigitalCertificates/EditView.vue
src/views/DigitalCertificates/FormFields/FormFieldsEditDigitalCertificates.vue
src/views/DigitalCertificates/FormFields/blocks/ImportServerCertificate.vue
src/views/DigitalCertificates/FormFields/composables/validation.js
src/views/DigitalCertificates/ListView.vue
src/views/EdgeFirewallRulesEngine/ListView.vue
src/views/PersonalTokens/ListView.vue

[NO-ISSUE] feat: adjustment on the digital certificate page
<hr />

[NO-ISSUE] feat: adjustment on the digital certificate page

---

src/services/v2/adapters/data-stream-adapter.js

[NO-ISSUE] fix: adjusting template duplication in data stream
<hr />

[NO-ISSUE] fix: adjusting template duplication in data stream

---

package.json
src/helpers/azion-documentation-catalog.js
src/views/EdgeConnectors/FormFields/blocks/Address.vue
src/views/EdgeConnectors/FormFields/blocks/ConnectionOptions.vue
src/views/EdgeDNS/FormFields/FormFieldsEdgeDns.vue
yarn.lock

fix: adjust edge connectors and improvements description inputs
<hr />

[NO-ISSUE] fix: adjust edge connectors and improvements description inputs

---

src/views/EdgeFirewallRulesEngine/FormFields/FormFieldsEdgeFirewallRulesEngine.vue
src/views/EdgeFirewallRulesEngine/ListView.vue

[NO-ISSUE] feat: remove dropdown on criteria and add trash button
<hr />

[NO-ISSUE] feat: remove dropdown on criteria and add trash button

---

src/views/EdgeDNS/EditView.vue
src/views/EdgeDNS/ListView.vue

[NO-ISSUE] refactor: show edge dns name on the edit page
<hr />

[NO-ISSUE] refactor: show edge dns name on the edit page

---

src/templates/edit-form-block/index.vue
src/templates/form-fields-inputs/fieldTextIcon.vue
src/views/DataStream/FormFields/blocks/OutputSection.vue
src/views/DataStream/FormFields/blocks/TransformSection.vue
src/views/DataStream/FormFields/composables/validation.js
src/views/DataStream/ListView.vue
src/views/DigitalCertificates/ListView.vue
src/views/EdgeApplications/ListView.vue
src/views/EdgeApplicationsCacheSettings/FormFields/blocks/ApplicationAccelerator.vue
src/views/EdgeConnectors/ListView.vue
src/views/EdgeDNS/EditView.vue
src/views/EdgeDNS/FormFields/FormFieldsRecords.vue
src/views/EdgeFirewall/ListView.vue
src/views/Workload/ListView.vue

[NO-ISSUE] refactor: minor adjustments after pm review
<hr />

[NO-ISSUE] refactor: minor adjustments after pm review

---

src/helpers/azion-contact-sales-window-opener.js
src/helpers/index.js
src/services/v2/adapters/edge-app-adapter.js
src/services/v2/edge-app-service.js
src/views/EdgeApplications/CreateView.vue
src/views/EdgeApplications/Drawer/index.vue
src/views/EdgeApplications/FormFields/FormFieldsCreateEdgeApplications.vue
src/views/EdgeApplications/FormFields/FormFieldsEditEdgeApplications.vue
src/views/EdgeApplications/FormFields/block/debugEdgeApp.vue
src/views/EdgeApplications/FormFields/block/generalEdgeApp.vue
src/views/EdgeApplications/FormFields/block/moduleEdgeApp.vue
src/views/EdgeApplications/FormFields/block/statusEdgeApp.vue
src/views/EdgeConnectors/FormFields/blocks/Address.vue

[NO-ISSUE] feat: add modules on the create page edge application
<hr />

[NO-ISSUE] feat: add modules on the create page edge application

---

src/services/v2/adapters/edge-connectors-adapter.js
src/views/EdgeConnectors/CreateView.vue
src/views/EdgeConnectors/FormFields/blocks/Address.vue
src/views/EdgeConnectors/FormFields/blocks/ConnectionOptions.vue
src/views/EdgeConnectors/FormFields/blocks/LoadBalancerConfiguration.vue
src/views/EdgeConnectors/composables/validation.js

[NO-ISSUE] fix: setting http and https address values on edge connectors
<hr />

[NO-ISSUE] fix: setting http and https address values on edge connectors

---

src/views/EdgeApplicationsRulesEngine/FormFields/FormFieldsEdgeApplicationsRulesEngine.vue

[UXE-7702] feat: Prevent saving Rule without a name
<hr />
[UXE-7702]: https://aziontech.atlassian.net/browse/UXE-7702?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[UXE-7702] feat: Prevent saving Rule without a name

---

src/views/EdgeApplicationsDeviceGroups/ListView.vue
src/views/WafRules/ListWafRulesAllowed.vue

[UXE-7721] fix: adjusted collumn in waf allow rules

---

src/services/v2/adapters/digital-certificates-adapter.js

[UXE-7720] fix: fix let encrypt on domain page
<hr />
[UXE-7720]: https://aziontech.atlassian.net/browse/UXE-7720?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[UXE-7720] fix: let's encrypt on domain page

---

src/services/sidebar-menus-services/menus.js

[UXE-7734] feat: update siem link
<hr />
[UXE-7734]: https://aziontech.atlassian.net/browse/UXE-7734?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[UXE-7734] feat: update siem link

---

src/views/Billing/PaymentListView.vue

[NO-ISSUE] fix: invert isDeveloperSupportPlan flag to correctly check support

---

src/views/DigitalCertificates/FormFields/blocks/General.vue
src/views/DigitalCertificates/FormFields/blocks/ImportServerCertificate.vue

[UXE-7740] feat: allow CSR creation in Digital Certificates section of Console
<hr />
[UXE-7740]: https://aziontech.atlassian.net/browse/UXE-7740?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[UXE-7740] feat: allow CSR creation in Digital Certificates section of Console

---

src/services/domains-services/create-domain-service.js
src/services/domains-services/edit-domain-service.js

[UXE-7741] fix: ensure Trusted CA field validation only applies when toggle is active
<hr />
[UXE-7741]: https://aziontech.atlassian.net/browse/UXE-7741?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[UXE-7741] fix: ensure Trusted CA field validation only applies when toggle is active

---

src/templates/add-payment-method-block/add-address.vue
src/templates/add-payment-method-block/index.vue

[UXE-7743] refactor: improve address form initialization and validation using resetForm

---

src/services/v2/adapters/edge-app-cache-settings-adapter.js

[UXE-7214] fix: correct max-age behavior when saving Cache Settings with Honor Cache
<hr />
[UXE-7214]: https://aziontech.atlassian.net/browse/UXE-7214?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[UXE-7214] fix: correct max-age behavior when saving Cache Settings with Honor 

---

src/views/EdgeFunctions/FormFields/FormFieldsCreateEdgeFunctions.vue
src/views/EdgeFunctions/FormFields/FormFieldsEditEdgeFunctions.vue

[UXE-7742] refactor: update Edge Functions field names according to new API 
<hr />
[UXE-7742]: https://aziontech.atlassian.net/browse/UXE-7742?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[UXE-7742] refactor: update Edge Functions field names according to new API 

---

src/views/CustomPages/ListView.vue
src/views/DataStream/ListView.vue
src/views/DigitalCertificates/ListView.vue
src/views/EdgeApplications/ListView.vue
src/views/EdgeApplicationsCacheSettings/ListView.vue
src/views/EdgeApplicationsFunctions/ListView.vue
src/views/EdgeApplicationsRulesEngine/ListView.vue
src/views/EdgeConnectors/ListView.vue
src/views/EdgeDNS/EditView.vue
src/views/EdgeDNS/ListView.vue
src/views/EdgeFirewall/ListView.vue
src/views/EdgeFirewallFunctions/ListView.vue
src/views/EdgeFirewallRulesEngine/ListView.vue
src/views/EdgeFunctions/ListView.vue
src/views/EdgeServices/ListView.vue
src/views/NetworkLists/ListView.vue
src/views/WafRules/ListView.vue
src/views/Workload/ListView.vue

[UXE-7759] feat: add ID column to all list views in the console
<hr />
[UXE-7759]: https://aziontech.atlassian.net/browse/UXE-7759?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[UXE-7759] feat: add ID column to all list views in the console

---

src/views/CustomPages/ListView.vue
src/views/DataStream/ListView.vue
src/views/DigitalCertificates/ListView.vue
src/views/EdgeApplications/ListView.vue
src/views/EdgeApplicationsCacheSettings/ListView.vue
src/views/EdgeApplicationsFunctions/ListView.vue
src/views/EdgeApplicationsRulesEngine/ListView.vue
src/views/EdgeConnectors/ListView.vue
src/views/EdgeDNS/EditView.vue
src/views/EdgeDNS/ListView.vue
src/views/EdgeFirewall/ListView.vue
src/views/EdgeFirewallFunctions/ListView.vue
src/views/EdgeFirewallRulesEngine/ListView.vue
src/views/EdgeFunctions/ListView.vue
src/views/EdgeServices/ListView.vue
src/views/NetworkLists/ListView.vue
src/views/WafRules/ListView.vue
src/views/Workload/ListView.vue

Reverts aziontech/azion-console-kit#2579

Revert "[UXE-7759] feat: add ID column to all list views in the console"

---

src/views/EdgeApplicationsRulesEngine/Drawer/index.vue

[UXE-7785] hotfix: increase page size to 200 when fetching edge application functions

---

src/views/NetworkLists/EditView.vue

[UXE-7788] fix: network lists country type not saving
<hr />
[UXE-7788]: https://aziontech.atlassian.net/browse/UXE-7788?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[UXE-7788] fix: network lists country type not saving

---

package.json

Chore: bump project version to 1.40.0
N/A
<hr />

chore: bump project version to 1.40.0

---

src/templates/list-table-block/with-fetch-ordering-and-pagination.vue
src/views/DigitalCertificates/FormFields/composables/certificate.js
src/views/DigitalCertificates/ListView.vue

[UXE-7725]
https://github.com/user-attachments/assets/3c4e288a-b775-43b0-9afc-ebc3bf144786
<hr />
[UXE-7725]: https://aziontech.atlassian.net/browse/UXE-7725?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[UXE-7725] fix: Fixing the digital certificates table when the process of creating a new certificate is closed

---

src/views/WafRules/ListWafRulesAllowed.vue

Adjusted validation in field waf allow rule.
<hr />

[UXE-7804] fix: add validation schema for WAF rule conditions with required fields

---

src/views/WafRules/ListWafRulesAllowed.vue

- Updated WAF rules in allowed to validation schema for conditions without value 
<hr />

[UXE-7804] fix: updated WAF rules in allowed to validation schema for conditions without value 

---

src/services/v2/adapters/waf-adapter.js

[NO-ISSUE] fix: adjusted WAF rule for match Value null

---

src/layout/components/menu-profile/index.vue

[UXE-7430] feat: activity history page not displaying records in console
<hr />
[UXE-7430]: https://aziontech.atlassian.net/browse/UXE-7430?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[UXE-7430] feat: activity history page not displaying records in console

---

package.json
yarn.lock

[UXE-7092] feat: upgrade azion-theme version
<hr />
[UXE-7092]: https://aziontech.atlassian.net/browse/UXE-7092?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[UXE-7092] feat: upgrade azion-theme version

---

src/services/v2/adapters/data-stream-adapter.js
src/templates/edit-form-block/index.vue
src/templates/form-fields-inputs/fieldGroupRadio.vue
src/views/DataStream/CreateView.vue
src/views/DataStream/EditView.vue
src/views/DataStream/FormFields/FormFieldsDataStream.vue
src/views/DataStream/FormFields/blocks/OutputSection.vue
src/views/DataStream/FormFields/blocks/TransformSection.vue
src/views/DataStream/FormFields/composables/validation.js

[UXE-7817] fix: resolve issue with disappearing custom headers in Console
<hr />
[UXE-7817]: https://aziontech.atlassian.net/browse/UXE-7817?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[UXE-7817] fix: resolve issue with disappearing custom headers in Console

---

package.json
yarn.lock

[NO-ISSUE] feat: update azion-theme version
<hr />

[NO-ISSUE] feat: update azion-theme version

---

src/templates/list-table-block/index.vue

[NO-ISSUE] fix: delete dialog bypass

---

src/services/v2/adapters/edge-connectors-adapter.js

[UXE-7834] fix: prevent error when editing Edge Connector with null or undefined
<hr />
[UXE-7834]: https://aziontech.atlassian.net/browse/UXE-7834?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[UXE-7834] fix: prevent error when editing Edge Connector with null or undefined

---

src/composables/useEdgeStorage.js
src/services/v2/edge-storage-service.js
src/views/EdgeStorage/FormFields/FormFieldsEdgeStorage.vue
src/views/EdgeStorage/View.vue

[UXE-7357](https://aziontech.atlassian.net/browse/UXE-7357)
[UXE-7869](https://aziontech.atlassian.net/browse/UXE-7869)
- Add api integration with bucket settings
https://github.com/user-attachments/assets/b0c55062-8162-439f-8a65-e885809b65a5
<hr />
[UXE-7357]: https://aziontech.atlassian.net/browse/UXE-7357?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[UXE-7869]: https://aziontech.atlassian.net/browse/UXE-7869?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[UXE-7357] feat: integrating bucket settings with API

---

src/views/EdgeApplicationsCacheSettings/FormFields/blocks/EdgeCache.vue

[UXE-7873] fix: correct cache settings override display when editing
<hr />
[UXE-7873]: https://aziontech.atlassian.net/browse/UXE-7873?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[UXE-7873] fix: correct cache settings override display when editing

---

src/composables/useEdgeStorage.js
src/helpers/azion-documentation-catalog.js
src/services/v2/edge-storage-service.js
src/views/EdgeStorage/FormFields/FormFieldsEdgeStorage.vue
src/views/EdgeStorage/ListView.vue
src/views/EdgeStorage/View.vue

- Fix Learn more link
- Inputs validations
- After the bucket is created, it is already selected by default
- Fix Write Only
<hr />

[UXE-7356] fix: Create bucket

---

src/composables/useEdgeStorage.js
src/services/v2/edge-storage-service.js
src/views/EdgeStorage/ListView.vue
src/views/EdgeStorage/components/DragAndDrop.vue
src/views/EdgeStorage/components/UploadCard.vue

[UXE-7359](https://aziontech.atlassian.net/browse/UXE-7359)
- implement upload files by drag and drop with API
<hr />
[UXE-7359]: https://aziontech.atlassian.net/browse/UXE-7359?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[UXE-7359] feat: implement file upload by drag and drop

---

src/views/EdgeStorage/ListView.vue

[UXE-7357](https://aziontech.atlassian.net/browse/UXE-7357)
- Fix responsiveness 
- Add skeleton to list of buckets
<hr />
[UXE-7357]: https://aziontech.atlassian.net/browse/UXE-7357?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[UXE-7357] fix: fix responsiveness and add skeleton

---

src/layout/components/menu-profile/index.vue

[UXE-7907][Patterns Fix] Profile Menu
Just turn de logout button smaller.
After:
Before:
<hr />
[UXE-7907]: https://aziontech.atlassian.net/browse/UXE-7907?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[UXE-7907] fix: button size logout to small

---

src/composables/useEdgeStorage.js
src/services/v2/edge-storage-service.js
src/views/EdgeStorage/ListView.vue
src/views/EdgeStorage/components/DragAndDrop.vue

[UXE-7360](https://aziontech.atlassian.net/browse/UXE-7360)
- Add folder upload
https://github.com/user-attachments/assets/a69c582a-eb12-450f-872f-de8d0f84dc9f
https://www.figma.com/design/ttDDXp0Qwx9G0TZjYd1YKB/-UXE-1649--UI-Edge-Storage?node-id=73-8701&m=dev
<hr />
[UXE-7360]: https://aziontech.atlassian.net/browse/UXE-7360?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[UXE-7360] feat: add folder upload

---

src/composables/useEdgeStorage.js
src/views/EdgeConnectors/FormFields/blocks/ConnectionOptions.vue
src/views/EdgeStorage/Drawer/index.vue
src/views/EdgeStorage/View.vue

[UXE-7364](http://aziontech.atlassian.net/browse/UXE-7364)
- Add drawer to create a bucket in edge connectors
https://github.com/user-attachments/assets/ce152f20-d3f7-4f09-aca6-76ce483a9fb4
https://www.figma.com/design/ttDDXp0Qwx9G0TZjYd1YKB/-UXE-1649--UI-Edge-Storage?node-id=114-6514&m=dev
<hr />
- [] Application responsiveness was tested to different screen sizes
[UXE-7364]: https://aziontech.atlassian.net/browse/UXE-7364?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[UXE-7364] feat: add edge storage bucket creation through drawer in edge connectors

---

src/services/v2/adapters/digital-certificates-adapter.js
src/services/v2/digital-certificates-service.js
src/templates/form-fields-inputs/fieldDropdownLazyLoader.vue
src/views/Workload/FormFields/blocks/protocolSettingsBlock.vue

[UXE-7833] fix: display associated digital certificate when present
<hr />
[UXE-7833]: https://aziontech.atlassian.net/browse/UXE-7833?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[UXE-7833] fix: display associated digital certificate when present

---

.dockerignore
Dockerfile
docker-compose.yml

Use docker image locally.
<hr />

[NO-ISSUE] chore: using container for local development

---

src/templates/create-modal-block/index.vue

[UXE-7886] feat: list Edge Connectors and Custom Pages in resource creation screen
<hr />
[UXE-7886]: https://aziontech.atlassian.net/browse/UXE-7886?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[UXE-7886] feat: list Edge Connectors and Custom Pages in resource creation screen

---

src/views/Workload/FormFields/blocks/protocolSettingsBlock.vue

refactor: change the message about pending and failed certificates
<hr />

[UXE-7833] refactor: change the message about pending and failed certificates

---

src/views/EdgeApplicationsCacheSettings/Drawer/index.vue
src/views/EdgeApplicationsCacheSettings/FormFields/blocks/EdgeCache.vue

[UXE-7932] refactor: rename setting to behavior
<hr />
[UXE-7932]: https://aziontech.atlassian.net/browse/UXE-7932?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[UXE-7932] refactor: rename setting to behavior

---

src/templates/list-table-block/folder-list.vue
src/views/EdgeStorage/ListView.vue

[UXE-7363](https://aziontech.atlassian.net/browse/UXE-7363)
- Add file search
- fix drag and drop on file table border color 
https://github.com/user-attachments/assets/a6f36e53-d4b1-4799-81bf-a21270676561
<hr />
[UXE-7363]: https://aziontech.atlassian.net/browse/UXE-7363?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[UXE-7363] feat: add files search

---

src/services/domains-services/create-domain-service.js
src/services/domains-services/edit-domain-service.js
src/services/v2/adapters/digital-certificates-adapter.js
src/services/v2/digital-certificates-service.js
src/templates/create-modal-block/index.vue
src/tests/services/domains-services/create-domain-service.test.js
src/tests/services/domains-services/edit-domain-service.test.js
src/views/Domains/FormFields/FormFieldsCreateDomains.vue

Deploy 2025-08-19

---

src/helpers/account-handler.js
src/helpers/oauth-security.js
src/templates/sign-in-block/index.vue
src/templates/social-idps-block/index.vue

fix(security): improve OAuth security guard to allow legitimate authentication flows
<hr />

[UXE-7952] fix: improve OAuth security guard to allow legitimate authentication flows

---

.github/workflows/deploy-production.yml
.github/workflows/deploy-stage.yml

Reverts aziontech/azion-console-kit#2671

Revert "[NO-ISSUE] chore: Bump CLI version to 4.0.0"

---

azion/production/azion.json

[NO-ISSUE] chore: update azion.json with new origins and routing rules

---

src/services/network-lists-services/make-network-list-base-url.js

[UXE-7888] refactor: remove unused network list base URL helper function

---

src/views/EdgeApplications/TabsView.vue
src/views/EdgeApplicationsRulesEngine/Drawer/index.vue
src/views/EdgeApplicationsRulesEngine/FormFields/FormFieldsEdgeApplicationsRulesEngine.vue
src/views/EdgeApplicationsRulesEngine/ListView.vue

[UXE-7723](https://aziontech.atlassian.net/browse/UXE-7723)
<hr />
[UXE-7723]: https://aziontech.atlassian.net/browse/UXE-7723?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[UXE-7723] feat: add warn and navigation to Application Accelerator module from Rules Engine

---

.github/workflows/deploy-production.yml
.github/workflows/deploy-stage.yml
azion/production/azion.json
azion/stage/azion.json

[NO-ISSUE] chore: update CLI version and azion.json with new origins and rules

---

src/services/v2/adapters/edge-sql-adapter.js
src/services/v2/edge-sql-service.js
src/views/EdgeSQL/DatabaseView.vue
src/views/EdgeSQL/components/RowFormDrawer.vue

[UXE-8943] feat: edge sql insert data drawer
https://github.com/user-attachments/assets/e16ce200-5074-41e3-8e44-e31267c517ec
<hr />
[UXE-8943]: https://aziontech.atlassian.net/browse/UXE-8943?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[UXE-8943] feat: edge sql insert data drawer

---

azion/production/azion.json

[NO-ISSUE] chore: Update IaC after recent deploy

---

azion/production/azion.json
src/services/v2/adapters/digital-certificates-adapter.js
src/views/Domains/FormFields/FormFieldsCreateDomains.vue
src/views/Domains/FormFields/FormFieldsEditDomains.vue

[UXE-8949] fix: ensure certificates are properly displayed in domain list and mTLS
[NO-ISSUE] chore: Update IaC after recent deploy
<hr />
[UXE-8949]: https://aziontech.atlassian.net/browse/UXE-8949?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEPLOY 2025-08-28 

---

src/views/EdgeApplications/TabsView.vue

Deploy 2025-08-28 2

---

src/services/v2/adapters/edge-firewall-adapter.js
src/services/v2/adapters/edge-firewall-function-adapter.js
src/services/v2/edge-firewall-function-service.js
src/views/EdgeFirewallFunctions/ListView.vue

refactor: remove _edge in edge firewall
<hr />

[UXE-7937] refactor: remove _edge in edge firewall

---

src/services/v2/edge-dns-records-service.js
src/services/v2/edge-dns-service.js

[UXE-7942] feat: remove edge_ prefix from endpoints
<hr />
[UXE-7942]: https://aziontech.atlassian.net/browse/UXE-7942?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[UXE-7942] feat: remove edge_ prefix from endpoints

---

src/views/EdgeApplicationsCacheSettings/Drawer/index.vue

[UXE-8956] fix: resolve error when creating Cache Settings
<hr />
[UXE-8956]: https://aziontech.atlassian.net/browse/UXE-8956?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[UXE-8956] fix: resolve error when creating Cache Settings

---

src/services/v2/edge-connectors-service.js

fix: update baseURL for edge connectors service
must contain the url of production edge connectors
<hr />

[NO-ISSUE] fix: update baseURL for edge connectors service

---

.github/workflows/deploy-production.yml
.github/workflows/deploy-stage.yml

[NO-ISSUE] chore: upgrade azion cli version
<hr />

[NO-ISSUE] chore: upgrade azion cli version

---

src/views/EdgeApplications/TabsView.vue

[NO-ISSUE] fix: reordering edge app tabs when edge functions are disabled

---

src/helpers/edge-function-hello-world.js

fix/ 
* adding the addEventListener into the edge function hello world
* add comment for Edge Firewall functions to use 'firewall' instead of 'fetch'

fix: adding the addEventListener into the edge function hello world

---

src/services/v2/adapters/edge-connectors-adapter.js
src/views/EdgeConnectors/Config/validation.js
src/views/EdgeConnectors/FormFields/blocks/Address.vue
src/views/EdgeConnectors/FormFields/blocks/LoadBalancerConfiguration.vue

[UXE-8974] fix: correct disabling of configuration fields and validation
<hr />
[UXE-8974]: https://aziontech.atlassian.net/browse/UXE-8974?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[UXE-8974] fix: correct disabling of configuration fields and validation

---

src/views/CustomPages/Blocks/pagesCodeBlock.vue
src/views/CustomPages/Config/listStatusCode.js

- Fix table order 
- Rename Table columns header
<hr />

[UXE-7761] refactor: update status code headers and sort order in custom pages UI

---

src/services/v2/adapters/digital-certificates-adapter.js

[UXE-8984] fix: resolve 400 error when updating Trusted CA certificate
https://github.com/user-attachments/assets/213caf4d-2459-474b-9ca8-d923f0f44322
<hr />
[UXE-8984]: https://aziontech.atlassian.net/browse/UXE-8984?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[UXE-8984] fix: resolve 400 error when updating Trusted CA certificate

---

package.json
yarn.lock

feat: pin vulnerable npm packages to safe versions
<hr />

feat: pin vulnerable npm packages to safe versions

---

src/services/waf-rules-services/list-waf-rules-domain-service.js
src/views/WafRules/Drawer/index.vue
src/views/WafRules/ListWafRulesTuning.vue

fix: add cnames to WAF rules domain service and update component ListWafRulesTuning to include cnames in selected filters
<hr />

[UXE-5287] fix: add cnames to WAF Tunning

---

src/stores/account.js
src/views/WafRules/Drawer/index.vue

[UXE-9048] feat: enable save/cancel actions with client flag
<hr />
[UXE-9048]: https://aziontech.atlassian.net/browse/UXE-9048?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[UXE-9048] feat: enable save/cancel for WAF Tuning details using client flag

---

src/stores/account.js
src/views/WafRules/Drawer/index.vue

Deploy 2025-09-17

---

src/views/EdgeApplicationsFunctions/Drawer/index.vue
src/views/EdgeFirewallFunctions/Drawer/index.vue
src/views/EdgeFunctions/Drawer/index.vue

[UXE-9035] fix: resolve unexpected error when selecting newly created function 
<hr />
[UXE-9035]: https://aziontech.atlassian.net/browse/UXE-9035?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[UXE-9035] fix: resolve unexpected error when selecting newly created function from drawer

---

src/views/EdgeApplicationsCacheSettings/Drawer/index.vue
src/views/EdgeApplicationsCacheSettings/FormFields/blocks/EdgeCache.vue

[UXE-7975] feat: applying a handle to Honor Cache behavior
<hr />
[UXE-7975]: https://aziontech.atlassian.net/browse/UXE-7975?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[UXE-7975] feat: Cache Settings - applying a handle to Honor Cache behavior

---

package.json
yarn.lock

Referente ao update no azion-theme:
https://github.com/aziontech/azion-theme/commit/9e335b0f353272a3af37ecff2983279f84b55068

[UXE-9036] fix: azion-theme warning flex-end and support to jsonforms checkbox stylesheet

---

src/helpers/account-handler.js
src/layout/components/navbar/create.vue
src/router/hooks/guards/accountGuard.js
src/router/hooks/guards/logoutGuard.js
src/services/v2/base/query/queryClient.js

[NO-ISSUE] fix: ajusted in logout and switch account for performance

---

src/services/v2/workload/workload-deployments-service.js
src/services/v2/workload/workload-service.js

fix: adjust import for workload deployment and add parameter workload id
<hr />

fix: adjust import for workload deployment and add parameter workload id

---

src/composables/user-flag.js
src/helpers/account-data.js
src/router/hooks/guards/flagGuard.js
src/router/routes/edge-storage/index.js
src/services/sidebar-menus-services/menus.js
src/tests/services/sidebar-menus-services/list-sidebar-menus-service.test.js

- Restrict access for object storage only for azion`s email users
<hr />

[UXE-9078] feat: restrict object storage access to Azion email users

---

azion.config.mjs

- Download, upload and delete working for png, jpg, pdf, html ... files 
-  Edge for validation: https://pkvbo2u3dk.map.azionedge.net/
https://github.com/user-attachments/assets/f89f9c1e-f65d-4800-a6e8-8cb0663f8a81
<hr />

[UXE-9072] feat: update rules engine for ignore edge_storage routes

---

src/templates/form-fields-inputs/fieldText.vue
src/views/WafRules/Config/regexValidator.js
src/views/WafRules/Drawer/allowedRules.vue
src/views/WafRules/Drawer/components/regexExamples.vue
src/views/WafRules/Drawer/components/topPaths.vue
src/views/WafRules/Drawer/index.vue

feat: enhance WAF rules drawer with regex validation and examples
NO
NO
<hr />

feat: enhance WAF rules drawer with regex validation and examples

---

src/services/v2/utils/adapter/domainAdapter.js
src/templates/list-table-block/index.vue
src/views/Billing/BillsView.vue
src/views/Workload/Config/validation.js

hotfix: fix wildcard domain parsing and action rendering across tables and billing
<hr />

[NO-ISSUE] hotfix: fix wildcard domain parsing and action rendering across tables and billing

---

.github/workflows/cleanup-e2e-tests.yml
.github/workflows/failed-e2e-tests.yml
.github/workflows/local-prod-e2e-tests.yml
.github/workflows/manual-e2e-tests.yml
cypress.config.js

[NO-ISSUE] test: update specPattern in Cypress configuration to include .skip files

---

.github/workflows/pre-merge.yml

[NO-ISSUE] chore: disable E2E tests and related coverage reporting in pre-merge

---

src/services/v2/base/query/cacheStore.js

[NO-ISSUE] fix: add error handling to encoding and decoding functions in cacheStore

---

src/services/v2/base/query/config.js

System was making automatic refetches every 5 minutes, generating unnecessary requests.
- Disabled automatic refetch (`refetchInterval: NO_REFETCH`)
- Optimized garbage collection (30min → 1h)

[NO-ISSUE] fix: disable auto-refetch and optimize garbage collection

---

src/services/v2/edge-app/edge-app-cache-settings-adapter.js

[NO-ISSUE] fix: remove prefix edge from edge_cache
