aziontech/azion-console-kit

src/assets/themes/scss/themes/azion-dark/_extensions.scss
src/assets/themes/scss/themes/azion-dark/extended-components/_multiselect.scss
src/assets/themes/scss/themes/azion-light/_extensions.scss
src/assets/themes/scss/themes/azion-light/extended-components/_multiselect.scss

Ajusta tamanhos dos itens e tamanho das fonts

[UXE-1406] Fix multi select theme

---

src/router/routes/real-time-purge/index.js
src/services/real-time-purge/contact-sales-service.js
src/services/real-time-purge/index.js
src/tests/services/real-time-purge/contact-sales-service.test.js
src/views/RealTimePurge/CreateView.vue
src/views/RealTimePurge/FormFields/FormFieldsCreateRealTimePurge.vue

https://github.com/aziontech/azion-console-kit/assets/92529166/04ea3261-b37a-437d-9fa5-edc9423f7744

[NO-ISSUE] feat: migrate block real time purge

---

.github/workflows/deploy-production.yml
.github/workflows/deploy-stage.yml
.github/workflows/pre-merge.yml

Update deploy to avoid private runners.

[NO-ISSUE] chore: update deploy files

---

src/assets/themes/scss/themes/azion-dark/extended-components/_multiselect.scss
src/assets/themes/scss/themes/azion-light/extended-components/_multiselect.scss
src/router/routes/edge-application-routes/index.js
src/services/edge-application-origins-services/list-origins-service.js
src/services/edge-application-services/contact-sales-service.js
src/services/edge-application-services/index.js
src/templates/list-table-block/no-header.vue
src/tests/services/edge-application-origins-services/list-origins-service.test.js
src/tests/services/edge-application-services/contact-sales-service.test.js
src/views/EdgeApplications/EditView.vue
src/views/EdgeApplications/FormFields/FormFieldsCreateEdgeApplications.vue
src/views/EdgeApplications/TabsView.vue
src/views/EdgeApplicationsOrigins/FormFields/FormFieldsEdgeApplicationsOrigins.vue
src/views/EdgeApplicationsOrigins/ListView.vue

[ENG-28814] fix post validation UI adjustment

---

.github/workflows/deploy-production.yml
.github/workflows/deploy-stage.yml

Update deploy workflow to production.

[NO-ISSUE] feat: update production deploy workflow

---

src/assets/themes/scss/themes/azion-dark/extended-components/_multiselect.scss
src/assets/themes/scss/themes/azion-light/extended-components/_multiselect.scss
src/views/Marketplace/MarketplaceHomeView.vue

Removed counters from Categories list in Marketplace side menu.
After:
Before:

[NO-ISSUE] feat: remove marketplace counters

---

src/services/users-services/list-users-service.js
src/tests/services/users-services/list-users-service.test.js
src/views/Users/FormsFields/FormFieldsUsers.vue
src/views/Users/ListView.vue
src/views/YourSettings/FormFields/FormFieldsYourSettings.vue

[NO-ISSUE] feat: added tags and option label at dropdown components in users forms

---

src/views/Users/CreateView.vue
src/views/Users/EditView.vue
src/views/Users/FormsFields/FormFieldsUsers.vue
src/views/Users/ListView.vue
src/views/YourSettings/EditView.vue
src/views/YourSettings/FormFields/FormFieldsYourSettings.vue

Modified:
* Your Settings labels, descriptions, placeholders, and helper texts.
* Users Management labels, descriptions, placeholders, and helper texts.

[EDU-2952] refactor: uxw review your settings and users management

---

src/services/sidebar-menus-services/menus.js
src/views/RealTimePurge/FormFields/FormFieldsCreateRealTimePurge.vue
src/views/RealTimePurge/ListView.vue

Modified:
* Real-Time Purge labels, descriptions, placeholders, and helper texts.
* Added - for two items in Products menu.

[EDU-2962] refactor: purge texts

---

src/assets/themes/scss/themes/azion-dark/extended-components/_divider.scss
src/assets/themes/scss/themes/azion-light/extended-components/_divider.scss
src/views/EdgeApplicationsOrigins/FormFields/FormFieldsEdgeApplicationsOrigins.vue

- Field method description removed.
- Adjusted the 'divider' component to display correctly in both dark and light versions when it's of the dashed type.

[ENG-28869] fix: adjustments to the drawer edge application origins

---

src/templates/form-fields-inputs/fieldTextArea.vue

- added props to the fieldtextArea component to set col and row, thus staying within the display pattern

[ENG-28869] feat: add props in component field textarea

---

src/services/edge-application-origins-services/delete-origin-service.js
src/templates/list-table-block/dialog/delete-dialog.vue
src/tests/services/edge-application-origins-services/delete-origin-service.test.js

- Adjusted table delete dialog
- Adjusted Origins delete service

[ENG-28869] fix: adjusted table delete dialog

---

src/templates/empty-results-block/index.vue
src/templates/list-table-block/no-header.vue

fix on empty component, to enable to toggle the use of border in the component, by a property.

[ENG-28869] fix: bug fix on empty component border

---

src/templates/create-modal-block/index.vue
src/templates/navbar-block/create.vue

Apenas adiciona classes Tailwind para overflow-auto. https://aziontech.atlassian.net/jira/software/c/projects/UXE/boards/296?assignee=60de3ead70941d00691951f1&selectedIssue=UXE-1524

[UXE-1524] Apply overflow-auto for Create Dialog

---

package.json

change project version from 1.6.1 to 1.6.2.

[NO-ISSUE] chore: upgrade project version from 1.6.1 to 1.6.2

---

src/services/edge-firewall-services/list-edge-firewall-service.js
src/tests/services/edge-firewall-services/list-edge-firewall-service.test.js
src/views/EdgeFirewall/ListView.vue

[ENG-28752] refactor: adjusted ui table in edge firewall

---

src/templates/content-block/banner.vue
src/templates/content-block/index.vue

Modified:
* Banner text in homepage to fit current release stage.

[EDU-3838] refactor: uxw adjust preview banner text

---

src/router/routes/login-routes/index.js
src/router/routes/signup-routes/index.js
src/services/social-idps-services/index.js
src/services/social-idps-services/list-social-idps-service.js
src/services/social-idps-services/make-list-social-idps-base-url.js
src/templates/sign-in-block/index.vue
src/templates/signup-block/social-signup-block.vue
src/templates/social-idps-block/index.vue
src/tests/services/social-idps-services/list-social-idps-service.test.js
src/views/Login/LoginView.vue
src/views/Signup/SignupView.vue

- Create social idps block
- Add skeleton to loading state
- Create tests
- Hide social idps block when api does not return results 
- Implement new block in signup and logins forms
https://github.com/aziontech/azion-console-kit/assets/95643165/74a97613-745b-4b1f-a90c-67ff07e9d502
https://github.com/aziontech/azion-console-kit/assets/95643165/82017bec-cc02-4658-a4dc-a82441689402

[ENG-28072] feat: display social idps in signup and login views

---

src/services/edge-functions-services/load-edge-functions-service.js
src/tests/services/edge-functions-services/load-edge-functions-service.test.js
src/views/EdgeFunctions/FormFields/FormFieldsEditEdgeFunctions.vue
src/views/EdgeFunctions/components/code-editor.vue

[ENG-28276]
WHY:
feat:  block editing edge functions that are from the marketplace
[ENG-28276]: https://aziontech.atlassian.net/browse/ENG-28276?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ENG-28276] feat:  block editing edge functions that are from the marketplace

---

src/templates/switch-account-block/index.vue

[UXE-1217] style: include truncated text

---

src/assets/themes/scss/themes/azion-dark/_extensions.scss
src/assets/themes/scss/themes/azion-dark/extended-components/_picklist.scss
src/assets/themes/scss/themes/azion-light/_extensions.scss
src/assets/themes/scss/themes/azion-light/extended-components/_picklist.scss
src/views/TeamsPermissions/FormFields/FormFieldsTeamPermissions.vue

Apenas customiza os elementos para _picklist.

[UXE-1175] theme ajuste em pick list

---

src/templates/list-table-block/index.vue
src/templates/list-table-block/no-header.vue
src/templates/list-table-block/with-lazy-and-dropdown-filter.vue
src/templates/switch-account-block/index.vue
src/views/Credentials/ListView.vue
src/views/DataStreaming/ListView.vue
src/views/DigitalCertificates/ListView.vue
src/views/Domains/ListView.vue
src/views/EdgeApplications/ListView.vue
src/views/EdgeApplicationsCacheSettings/ListView.vue
src/views/EdgeApplicationsDeviceGroups/ListView.vue
src/views/EdgeApplicationsFunctions/ListView.vue
src/views/EdgeApplicationsOrigins/ListView.vue
src/views/EdgeApplicationsRulesEngine/ListView.vue
src/views/EdgeFirewall/ListView.vue
src/views/EdgeFunctions/ListView.vue
src/views/EdgeNode/ListView.vue
src/views/EdgeNode/ListViewTabServices.vue
src/views/EdgeServices/ListView.vue
src/views/EdgeServices/ListViewTabResources.vue
src/views/IntelligentDNS/EditView.vue
src/views/IntelligentDNS/ListView.vue
src/views/NetworkLists/ListView.vue
src/views/PersonalTokens/ListView.vue
src/views/RealTimePurge/ListView.vue
src/views/TeamsPermissions/ListView.vue
src/views/Users/ListView.vue
src/views/Variables/ListView.vue

- Refactor table components to use composition API
- Add a prop called emptyListMessage
- Set a value to the given prop in components that use those table-blocks

[ENG-28718] feat: empty list improvements

---

src/services/social-idps-services/list-social-idps-service.js
src/templates/social-idps-block/index.vue
src/tests/services/social-idps-services/list-social-idps-service.test.js

- Add `?console=true` to loginUrl which comes from the service;
- Refactor tests;
- Add loading animation
https://github.com/aziontech/azion-console-kit/assets/95643165/4a926f55-29d1-456a-9904-55103a259ae3

[ENG-28073] feat: add console query string to url

---

src/assets/themes/scss/themes/azion-dark/extended-components/_picklist.scss
src/assets/themes/scss/themes/azion-light/extended-components/_picklist.scss
src/router/routes/waf-rules-routes/index.js
src/services/waf-rules-services/create-waf-rules-service.js
src/services/waf-rules-services/index.js
src/services/waf-rules-services/list-waf-rules-service.js
src/tests/services/waf-rules-services/create-waf-rules-service.test.js
src/views/WafRules/CreateView.vue
src/views/WafRules/FormFields/FormFieldsWafRules.vue

[ENG-28919]
WHY
feat: create waf rules
[ENG-28919]: https://aziontech.atlassian.net/browse/ENG-28919?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
https://github.com/aziontech/azion-console-kit/assets/110847590/b9169426-9371-424b-89c0-014e44ed40c3

[ENG-28919] feat: create waf rules

---

src/views/DigitalCertificates/CreateView.vue
src/views/DigitalCertificates/FormFields/FormFieldsCreateDigitalCertificates.vue
src/views/DigitalCertificates/FormFields/FormFieldsEditDigitalCertificates.vue
src/views/Domains/FormFields/FormFieldsCreateDomains.vue
src/views/Domains/FormFields/FormFieldsEditDomains.vue

- Labels and placeholders for digital certificate views
- Order of form radio in create view
- Oder of form element name in edit view
- Label in domains view

[EDU-3781] refactor: uxw digital certificates

---

src/views/RealTimePurge/CreateView.vue

- Add inline message to create purge view.

chore: add purge inline message

---

src/services/account-settings-services/make-account-settings-base-url.js
src/services/users-services/load-user-service.js
src/services/users-services/make-user-base-url.js
src/templates/activity-history-block/index.vue
src/tests/services/account-settings-services/get-account-settings-service.test.js
src/tests/services/account-settings-services/make-account-settings-base-url.test.js
src/tests/services/account-settings-services/update-account-settings-service.test.js
src/tests/services/users-services/edit-users-service.test.js
src/tests/services/users-services/load-user-service.test.js
src/views/AccountSettings/FormFields/FormFieldsAccountSettings.vue
src/views/DigitalCertificates/FormFields/FormFieldsEditDigitalCertificates.vue
src/views/EdgeApplications/TabsView.vue
src/views/RealTimePurge/CreateView.vue
src/views/YourSettings/EditView.vue

I have read the CLA Document and I hereby sign the CLA

fix: wrong service base urls

---

src/services/edge-application-error-responses-services/edit-error-responses-service.js
src/services/edge-application-error-responses-services/list-error-responses-service.js
src/services/edge-application-error-responses-services/make-edge-application-error-responses-base-url.js
src/tests/services/edge-application-error-responses/edit-error-responses-services.test.js
src/tests/services/edge-application-error-responses/list-error-responses-service.test.js
src/views/DigitalCertificates/FormFields/FormFieldsEditDigitalCertificates.vue
src/views/EdgeApplications/TabsView.vue
src/views/EdgeApplicationsErrorResponses/EditView.vue
src/views/EdgeApplicationsErrorResponses/FormFields/FormFieldsErrorResponses.vue
src/views/RealTimePurge/CreateView.vue

[NO-ISSUE] fix: change error response api service to parse correctly api errors and change validation of fields

---

src/views/YourSettings/FormFields/FormFieldsYourSettings.vue

extra: fix bugs in YourSettingsView

[ENG-28888]fix: remove loose close tag from code and orientation text on FormFieldsYourSettings

---

LICENSE
src/services/edge-application-error-responses-services/list-error-responses-service.js

Update license model to AGPL 3.0 instead MIT.

[NO-ISSUE] chore: update license model

---

src/views/CreateNew/CreateView.vue
src/views/CreateNew/DeployView.vue

Retorna para a tela inicial quando há um cancelamento no formulário do fluxo de create

[ENG-28972] fix: return to home when create form is canceled

---

src/router/routes/edge-application-routes/index.js
src/services/edge-application-functions-services/create-function-service.js
src/services/edge-application-functions-services/delete-function-service.js
src/services/edge-application-functions-services/edit-function-service.js
src/services/edge-application-functions-services/index.js
src/services/edge-application-functions-services/list-edge-application-functions-service.js
src/services/edge-application-functions-services/list-edge-functions-service.js
src/services/edge-application-functions-services/list-functions-service.js
src/services/edge-application-functions-services/loader-function-service.js
src/services/edge-application-functions-services/make-edge-functions-base-url.js
src/tests/services/edge-application-functions-services/create-edge-application-functions-service.test.js
src/tests/services/edge-application-functions-services/delete-edge-application-functions-service.test.js
src/tests/services/edge-application-functions-services/list-edge-application-functions-service.test.js
src/tests/services/edge-application-functions-services/list-functions-service.test.js
src/tests/services/edge-application-functions-services/load-function-service.test.js
src/tests/services/edge-functions-services/load-edge-functions-service.test.js
src/views/EdgeApplicationsFunctions/Drawer/index.vue
src/views/EdgeApplicationsFunctions/FormFields/FormFieldsEdgeApplicationsFunctions.vue
src/views/EdgeApplicationsFunctions/FormFields/FormFieldsEdgeApplicationsOrigins.vue
src/views/EdgeApplicationsFunctions/ListView.vue

[ENG-28788] feat: create function and edit fuction

---

src/views/EdgeFunctions/FormFields/FormFieldsCreateEdgeFunctions.vue
src/views/EdgeFunctions/FormFields/FormFieldsEditEdgeFunctions.vue

[NO-ISSUE] fix: adjust icon lock in edge function

---

src/templates/signup-block/page-with-form-block.vue
src/views/Signup/AdditionalDataView.vue

[NO-ISSUE] fix: signup button showing on additional data

---

src/services/edge-application-error-responses-services/edit-error-responses-service.js
src/tests/services/edge-application-functions-services/list-functions-service.test.js
src/views/EdgeApplicationsErrorResponses/FormFields/FormFieldsErrorResponses.vue
src/views/EdgeFirewall/FormFields/FormFieldsEdgeFirewall.vue

[ENG-27546] refactor: remove placeholder in input

---

src/templates/create-modal-block/LoadingListTemplate.vue
src/templates/create-modal-block/index.vue
src/templates/template-engine-block/FormLoading.vue
src/templates/template-engine-block/index.vue
src/views/CreateNew/CreateView.vue
src/views/Marketplace/components/ListSolutions.vue
src/views/Marketplace/drawer/IntegrationInstall.vue

Certainly! Here are the summaries for each product change:
- Added alt text to enhance accessibility for the `ListSolutions` component.
- Improved code readability by using the route name for redirection from `create-modal-block`.
- Refactored code, switching from options API to composition API in the `create-modal` component.
- Simplified the conditional render logic in `create-modal-block`.
- Fixed conditional render to display the template section in `create-modal-block`.
- Renamed a variable to provide more context within the `IntegrationInstall` view.
- Removed clickable skeleton from the `LoadingListTemplate` component.
- Eliminated a duplicated `div` tag in the `LoadingListTemplate` component.
- Eliminated unnecessary comments from the codebase.
- Ensured the creation and …

[ENG-28888] fix: template validation on create new journey

---

src/templates/list-table-block/dialog/delete-dialog.vue

fix: divider, paddings and buttons responsive
Uploading Gravação de Tela 2024-01-17 às 09.34.01.mov…

[UXE-1578] styles: Remove pt of Delete Modal

---

src/helpers/azion-documentation-catalog.js
src/router/routes/waf-rules-routes/index.js
src/services/waf-rules-services/create-waf-rules-allowed-service.js
src/services/waf-rules-services/create-waf-rules-service.js
src/services/waf-rules-services/delete-waf-rules-allowed-service.js
src/services/waf-rules-services/edit-waf-rules-allowed-service.js
src/services/waf-rules-services/edit-waf-rules-service.js
src/services/waf-rules-services/index.js
src/services/waf-rules-services/list-waf-rules-allowed-service.js
src/services/waf-rules-services/load-waf-rules-allowed-service.js
src/services/waf-rules-services/load-waf-rules-service.js
src/services/waf-rules-services/make-waf-rules-allowed-base-url.js
src/templates/create-form-block/form-horizontal.vue
src/templates/edit-drawer-block/index.vue
src/tests/services/waf-rules-services/create-waf-rules-allowed-service.test.js
src/tests/services/waf-rules-services/create-waf-rules-service.test.js
src/tests/services/waf-rules-services/delete-waf-rules-allowed-service.test.js
src/tests/services/waf-rules-services/edit-waf-rules-allowed-service.test.js
src/tests/services/waf-rules-services/edit-waf-rules-service.test.js
src/tests/services/waf-rules-services/list-waf-rules-allowed-service.test.js
src/tests/services/waf-rules-services/load-waf-rules-allowed-sevice.test.js
src/tests/services/waf-rules-services/load-waf-rules-service.test.js
src/tests/services/waf-rules-services/make-waf-rules-allowed.test.js
src/views/WafRules/EditView.vue
src/views/WafRules/FormFields/FormFieldsAllowed.vue
src/views/WafRules/FormFields/FormFieldsWafRules.vue
src/views/WafRules/ListWafRulesAllowed.vue
src/views/WafRules/TabsView.vue

[ENG-28939] 
why:
feat: edit waf rules only main settings and allowed rules
https://github.com/aziontech/azion-console-kit/assets/110847590/03326268-f14f-45c3-be9d-5f34fac65516
[ENG-28939]: https://aziontech.atlassian.net/browse/ENG-28939?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ENG-28939] feat: edit waf rules only main settings and allowed rules

---

src/templates/list-table-block/dialog/delete-dialog.vue
src/templates/navbar-block/switch-account.vue
src/tests/services/metrics-services/search-domains-metrics-service.test.js

translate texts at switch account modal to english

[ENG-28979] fix: texts at switch account modal

---

src/assets/themes/scss/themes/azion-dark/extended-components/_divider.scss
src/assets/themes/scss/themes/azion-light/extended-components/_divider.scss

Only apply padding for divider content.

[NO-ISSUE] style: include padding inline for Dividers

---

package.json
src/templates/edit-drawer-block/index.vue

Preparing the version for deploy.

Update version 1.7.0

---

src/views/EdgeApplications/EditView.vue
src/views/EdgeApplications/TabsView.vue
src/views/EdgeApplicationsFunctions/Drawer/index.vue
src/views/EdgeApplicationsFunctions/ListView.vue
src/views/EdgeFirewall/EditView.vue
src/views/EdgeFirewall/TabsView.vue

- correction in the UX of tabs
- removed unused props
- add import. forgotten component
- add prop. of forgotten documentation

[NO-ISSUE] fix: correction in the UX of tabs

---

src/router/routes/edge-firewall-routes/index.js
src/services/edge-firewall-functions-services/create-function-service.js
src/services/edge-firewall-functions-services/delete-function-service.js
src/services/edge-firewall-functions-services/edit-function-service.js
src/services/edge-firewall-functions-services/index.js
src/services/edge-firewall-functions-services/list-edge-firewall-functions-service.js
src/services/edge-firewall-functions-services/list-edge-functions-service.js
src/services/edge-firewall-functions-services/list-functions-service.js
src/services/edge-firewall-functions-services/loader-function-service.js
src/services/edge-firewall-functions-services/make-edge-firewall-base-url.js
src/services/edge-firewall-functions-services/make-edge-functions-base-url.js
src/tests/services/edge-firewall-functions-services/create-edge-firewall-functions-service.test.js
src/tests/services/edge-firewall-functions-services/delete-edge-firewall-functions-service.test.js
src/tests/services/edge-firewall-functions-services/list-functions-service.test.js
src/tests/services/edge-firewall-functions-services/load-function-service.test.js
src/views/EdgeFirewall/TabsView.vue
src/views/EdgeFirewallFunctions/Drawer/index.vue
src/views/EdgeFirewallFunctions/FormFields/FormFieldsEdgeApplicationsFunctions.vue
src/views/EdgeFirewallFunctions/ListView.vue

https://github.com/aziontech/azion-console-kit/assets/92529166/04162252-766f-4ae3-9d8c-c3936729cd4f

[ENG-27745] feat: create tab function in edge firewall

---

src/services/edge-application-rules-engine-services/edit-rules-engine-service.js
src/services/edge-application-rules-engine-services/load-rules-engine-service.js
src/services/edge-application-services/make-edge-application-base-url.js
src/templates/create-modal-block/index.vue
src/tests/services/edge-application-rules-engine-services/create-rules-engine-service.test.js
src/tests/services/edge-application-rules-engine-services/delete-rules-engine-service.test.js
src/tests/services/edge-application-rules-engine-services/edit-rules-engine-service.test.js
src/tests/services/edge-application-rules-engine-services/load-rules-engine-service.test.js
src/tests/services/edge-firewall-functions-services/list-functions-service.test.js
src/views/EdgeFirewall/TabsView.vue
src/views/EdgeFirewallFunctions/ListView.vue

add unit tests to all services on Rules Engine

[NO-ISSUE] tests: add rules engine unit tests

---

src/services/auth-services/get-login-method-service.js
src/services/auth-services/make-auth-method-base-url.js
src/templates/sign-in-block/index.vue
src/tests/services/auth-services/get-login-method-service.test.js
vite.config.js

Checa se o email selecionado é do tipo federado, caso sim, redireciona para a url do login federado

[ENG-29052] feat: federated login

---

src/services/auth-services/make-auth-method-base-url.js
src/templates/sign-in-block/index.vue
src/tests/services/auth-services/get-login-method-service.test.js

inclui o parametro &console=true na query de redirecionamento do login federado

[NO-ISSUE] fix: change url redirection when is federated login

---

package.json

[NO-ISSUE] chore: update package version

---

src/views/EdgeApplicationsRulesEngine/Drawer/index.vue
src/views/EdgeApplicationsRulesEngine/FormFields/FormFieldsEdgeApplicationsRulesEngine.vue
src/views/EdgeApplicationsRulesEngine/ListView.vue

* added autocomplete to criteria variable
* delete conditional and criteria level function
* delete behavior level function
* UI style adjusts

[ENG-28097] feat: added autocomplete to criteria variable and delete conditional

---

src/views/EdgeApplicationsRulesEngine/FormFields/FormFieldsEdgeApplicationsRulesEngine.vue

[NO-ISSUE] fix: is not first criteria adjust

---

src/assets/svg/illustration-layers.vue
src/assets/themes/scss/themes/azion-dark/extended-components/_selectbutton.scss
src/assets/themes/scss/themes/azion-light/extended-components/_selectbutton.scss
src/templates/create-modal-block/index.vue
src/templates/form-fields-inputs/fieldTextArea.vue
src/templates/list-table-block/index.vue
src/templates/list-table-block/no-header.vue
src/views/EdgeApplicationsRulesEngine/Drawer/index.vue
src/views/EdgeApplicationsRulesEngine/FormFields/FormFieldsEdgeApplicationsRulesEngine.vue
src/views/EdgeApplicationsRulesEngine/ListView.vue

* missing empty slot at table list block templates
* autoResize prop added to fieldTextArea template
* drawer phase option by selected phase

[NO-ISSUE] fix: empty block slot added

---

src/services/sidebar-menus-services/menus.js

Apenas ajusta os icones e a ordem dos items de navegação

[UXE-1622] chore: change icons and order of nav items

---

src/templates/list-table-block/index.vue

Apenas remove o padding nesse elemento

[UXE-1646] style: remove padding of overlaymenu

---

src/assets/themes/scss/themes/azion-dark/extended-components/_selectbutton.scss
src/assets/themes/scss/themes/azion-light/extended-components/_selectbutton.scss
src/templates/create-modal-block/index.vue

Ajustes para resolver um código que estava em SelectButton para afetar o createModal que estava com umas classes desnecessárias.
Antes:
Depois:

[NO-ISSUE] Fix SelectButton and CreateModal

---

src/views/CliCallback/FailView.vue
src/views/CliCallback/SuccessView.vue

Modified cli auth callback pages

[EDU-3886] chore: review cli callback uxw

---

src/views/EdgeApplicationsFunctions/FormFields/FormFieldsEdgeApplicationsFunctions.vue
src/views/EdgeFirewall/CreateView.vue
src/views/EdgeFirewall/FormFields/FormFieldsEdgeFirewall.vue
src/views/EdgeFirewallFunctions/FormFields/FormFieldsEdgeApplicationsFunctions.vue

[NO-ISSUE] fix: adjust modules edge firewall

---

src/services/domains-services/list-domains-service.js
src/tests/services/domains-services/list-domains-service.test.js

[ENG-28461] feat: add name edge application to list domains

---

src/services/domains-services/list-domains-service.js
src/tests/services/domains-services/list-domains-service.test.js
src/views/Domains/ListView.vue

https://github.com/aziontech/azion-console-kit/assets/92529166/f35809ca-1348-4cd4-8bd1-74e23bf60879

[ENG-28462] fix: add filter in column status two list domains

---

src/views/EdgeApplicationsFunctions/FormFields/FormFieldsEdgeApplicationsFunctions.vue

Modified UX writing for functions instances in edge application.

[NO-ISSUE] feat: add edge function descriptions

---

src/views/WafRules/Drawer/index.vue
src/views/WafRules/FormFields/FormFieldsAllowed.vue
src/views/WafRules/ListView.vue
src/views/WafRules/ListWafRulesAllowed.vue

[ENG-28990] 
WHY:
fix: fix warning code
[ENG-28990]: https://aziontech.atlassian.net/browse/ENG-28990?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ENG-28990] fix: fix warning code

---

src/services/edge-service-resources-services/make-resources-base-url.js
src/tests/services/edge-service-resources-services/create-resources-services.test.js
src/tests/services/edge-service-resources-services/delete-resources-services.test.js
src/tests/services/edge-service-resources-services/edit-resources-services.test.js
src/tests/services/edge-service-resources-services/list-resources-services.test.js
src/tests/services/edge-service-resources-services/load-resources-services.test.js
src/tests/services/edge-service-resources-services/make-resources-base-url.test.js
src/views/EdgeApplicationsFunctions/FormFields/FormFieldsEdgeApplicationsFunctions.vue

The URL path was changed to avoid the 404 error. Added the 'v3' folder to path.

[NO-ISSUE] fix: edge services resources

---

src/assets/themes/scss/themes/azion-dark/extended-components/_dropdownitem.scss
src/assets/themes/scss/themes/azion-light/extended-components/_dropdownitem.scss
src/views/EdgeApplications/FormFields/FormFieldsCreateEdgeApplications.vue
src/views/EdgeApplicationsFunctions/FormFields/FormFieldsEdgeApplicationsFunctions.vue
src/views/WafRules/CreateView.vue
src/views/WafRules/Dialog/index.vue
src/views/WafRules/Drawer/index.vue
src/views/WafRules/EditView.vue
src/views/WafRules/FormFields/FormFieldsAllowed.vue
src/views/WafRules/FormFields/FormFieldsWafRules.vue
src/views/WafRules/ListWafRulesAllowed.vue
src/views/WafRules/ListWafRulesTuning.vue
src/views/WafRules/TabsView.vue

[ENG-29171]
WHY:
fix: fix  layout
[ENG-29171]: https://aziontech.atlassian.net/browse/ENG-29171?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ENG-29171] fix: fix  layout

---

src/templates/create-modal-block/index.vue

Added "description" attribute to CREATE -> Resources.

[ENG-29203] feat: add independent description for each resource card

---

src/templates/list-table-block/index.vue
src/templates/list-table-block/no-header.vue

https://github.com/aziontech/azion-console-kit/assets/92529166/b61555b4-6bae-49b3-8dd5-0c062529e7e2

[UXE-1587] fix: delete button stopped working when deleting an item

---

src/services/data-streaming-services/create-data-streaming-service.js
src/services/data-streaming-services/edit-data-streaming-service.js

* adjusted getHeaders function to accept new values in custom headers

[UXE-1643] fix: custom header dont accept two colon

---

src/views/EdgeApplicationsRulesEngine/Drawer/index.vue
src/views/EdgeApplicationsRulesEngine/FormFields/FormFieldsEdgeApplicationsRulesEngine.vue

[UXE-1672] fix: remove required of description field in rules engine forms

---

src/assets/c3.scss
src/main.js
src/views/Metrics/blocks/dashboard-panel-block.vue
src/views/Metrics/components/chart/bar-chart/bar-chart.vue
src/views/Metrics/components/chart/line-chart/line-chart.vue
src/views/Metrics/components/chart/spline-chart/spline-chart.vue

[ENG-29231] feat: display report chart

---

src/main.js

[NO-ISSUE] fix: [main] revert imports sort

---

src/templates/list-table-block/index.vue
src/templates/list-table-block/no-header.vue
src/views/Credentials/ListView.vue
src/views/Domains/ListView.vue
src/views/EdgeApplications/ListView.vue
src/views/EdgeApplicationsDeviceGroups/ListView.vue
src/views/EdgeApplicationsFunctions/ListView.vue
src/views/EdgeApplicationsOrigins/ListView.vue
src/views/EdgeApplicationsRulesEngine/ListView.vue
src/views/EdgeFirewall/ListView.vue
src/views/EdgeFunctions/ListView.vue
src/views/EdgeNode/ListViewTabServices.vue
src/views/EdgeServices/ListView.vue
src/views/IntelligentDNS/ListView.vue
src/views/Users/ListView.vue
src/views/Variables/ListView.vue

https://github.com/aziontech/azion-console-kit/assets/92529166/48db4be1-e135-4fef-b9ec-eeac662949a6

[UXE-1608] fix: bug search in list table block

---

src/services/data-streaming-services/create-data-streaming-service.js
src/services/data-streaming-services/edit-data-streaming-service.js
src/views/DigitalCertificates/FormFields/FormFieldsCreateDigitalCertificates.vue
src/views/WafRules/Drawer/index.vue
src/views/WafRules/ListWafRulesTuning.vue

[ENG-29175] 
WHY:
feat: add search by path to the tuning waf drawer
[ENG-29175]: https://aziontech.atlassian.net/browse/ENG-29175?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
https://github.com/aziontech/azion-console-kit/assets/110847590/7456cd1c-f97b-4ca0-93cd-3745df74081f

[ENG-29175] feat: add search by path to the tuning waf drawer

---

src/views/DataStreaming/CreateView.vue
src/views/DataStreaming/Dialog/SamplingDialog.vue
src/views/DataStreaming/EditView.vue
src/views/DataStreaming/FormFields/FormFieldsDataStreaming.vue
src/views/DataStreaming/ListView.vue
src/views/EdgePulse/FormFields/FormFieldsTag.vue

Modifications:
* Added correct Data Streaming labels, descriptions, placeholders, helper texts.
* Added Edge Pulse correct text for Pre-loading Tag tab.

[NO-ISSUE] refactor: readding data streaming and edge pulse texts

---

package.json

[NO-ISSUE] chore: update package to deploy

---

src/views/DataStreaming/FormFields/FormFieldsDataStreaming.vue
src/views/Users/FormsFields/FormFieldsUsers.vue

* User data reload on creation
* also in Data Streaming

[UXE-1701] fix: form data reload with async fields

---

src/templates/edit-drawer-block/index.vue
src/views/EdgeApplicationsRulesEngine/Drawer/index.vue
src/views/EdgeApplicationsRulesEngine/FormFields/FormFieldsEdgeApplicationsRulesEngine.vue

* remove unusual item to edit prop
* refactor some functions in Rules Engine form

[NO-ISSUE] fix: remove item to edit in edit drawer block and refactor rules engine

---

src/services/intelligent-dns-records-services/load-records-service.js
src/tests/services/intelligent-dns-records-services/load-records-service.test.js

https://aziontech.atlassian.net/jira/software/c/projects/UXE/boards/296?assignee=unassigned&assignee=615e202cc5388b00698ccfee&selectedIssue=UXE-1655

[UXE-1655] fix: adjust load infor qtype mx in records service

---

src/templates/list-table-block/no-header.vue
src/templates/list-table-block/with-lazy-and-dropdown-filter.vue
src/templates/switch-account-block/index.vue

Only remove padding and shadow of Menu on Switch Account

[NO-ISSUE] style: include pt for remove shadow and padding

---

src/templates/create-drawer-block/index.vue
src/views/EdgeApplicationsRulesEngine/FormFields/FormFieldsEdgeApplicationsRulesEngine.vue

[UXE-1676]
WHY:
feat: hiding the form when the phase value is default
[UXE-1676]: https://aziontech.atlassian.net/browse/UXE-1676?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[UXE-1676] feat: hiding the form when the phase value is default

---

src/services/edge-application-services/create-edge-application-service.js
src/services/edge-application-services/list-edge-applications-service.js
src/tests/services/edge-application-services/create-edge-application-service.test.js
src/tests/services/edge-application-services/list-edge-applications-service.test.js
src/views/EdgeApplications/CreateView.vue
src/views/EdgeApplications/FormFields/FormFieldsCreateEdgeApplications.vue
src/views/EdgeApplications/ListView.vue

[UXE-1677] fix: add field debug rules in create edge application

---

src/services/data-streaming-services/create-data-streaming-service.js
src/templates/list-table-block/no-header.vue
src/templates/list-table-block/with-lazy-and-dropdown-filter.vue
src/templates/switch-account-block/index.vue
src/tests/services/edge-application-services/create-edge-application-service.test.js
src/views/EdgeFirewall/CreateView.vue
src/views/EdgeFirewall/FormFields/FormFieldsEdgeFirewall.vue

[UXE-1647] 
WHY:
feat: low skelleton loader no multiselect de domains em edge firewall
[UXE-1647]: https://aziontech.atlassian.net/browse/UXE-1647?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[UXE-1647] feat: low skelleton loader no multiselect de domains em edge firewall

---

src/templates/empty-results-block/index.vue

[UXE-1660] change font-size and font-weight of empty-block

---

src/services/data-streaming-services/create-data-streaming-service.js
src/templates/list-table-block/no-header.vue
src/templates/list-table-block/with-lazy-and-dropdown-filter.vue
src/templates/switch-account-block/index.vue
src/tests/services/edge-application-services/create-edge-application-service.test.js
src/views/WafRules/Drawer/index.vue
src/views/WafRules/TabsView.vue

[ENG-29175]
WHY:
feat:  layout adjustment when the drawer is on the
[ENG-29175]: https://aziontech.atlassian.net/browse/ENG-29175?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ENG-29175] feat:  layout adjustment when the drawer is visible

---

src/templates/list-table-block/index.vue
src/templates/list-table-block/no-header.vue
src/templates/loading-block/index.vue

Only change sizes of the search inputs on table.

[UXE-1662] style: change search field size of table

---

src/router/routes/waf-rules-routes/index.js
src/views/WafRules/CreateView.vue
src/views/WafRules/Drawer/index.vue
src/views/WafRules/FormFields/FormFieldsAllowed.vue
src/views/WafRules/FormFields/FormFieldsWafRules.vue
src/views/WafRules/ListView.vue
src/views/WafRules/ListWafRulesAllowed.vue
src/views/WafRules/ListWafRulesTuning.vue

[EDU-2964] chore: review waf rules views

---

src/views/EdgeApplicationsFunctions/FormFields/FormFieldsEdgeApplicationsFunctions.vue
src/views/EdgeApplicationsRulesEngine/FormFields/FormFieldsEdgeApplicationsRulesEngine.vue
src/views/EdgeFirewall/CreateView.vue
src/views/EdgeFirewall/FormFields/FormFieldsEdgeFirewall.vue
src/views/EdgeFirewall/ListView.vue
src/views/EdgeFirewallFunctions/Drawer/index.vue
src/views/EdgeFirewallFunctions/FormFields/FormFieldsEdgeApplicationsFunctions.vue
src/views/EdgeFirewallFunctions/ListView.vue
src/views/EdgeFirewallRulesEngine/Drawer/index.vue
src/views/EdgeFirewallRulesEngine/FormFields/FormFieldsEdgeFirewallRulesEngine.vue
src/views/EdgeFirewallRulesEngine/ListView.vue

Modified firewall UI texts.
Changed some edge app texts for consistency.

[EDU-2963] chore: review edge firewall uxw

---

src/views/EdgeApplicationsRulesEngine/FormFields/FormFieldsEdgeApplicationsRulesEngine.vue

* refactor some variables
* refactor addNewCriteria function (equal to edge firewall)
* added a limit to add criterias and conditionals

[UXE-1697] fix: added criteria and conditional limit

---

src/views/YourSettings/EditView.vue

- remove unnecessary reset on email value
- call form submit after email comparison
https://github.com/aziontech/azion-console-kit/assets/95643165/82f3a592-1fad-4537-b677-8826c9673b07

[UXE-1759] fix: remove unnecessary email reset before submit

---

src/templates/navbar-block/index.vue

When user select Forgot Password feature it's possible back to home when click's at the Azion logo in the header.
https://github.com/aziontech/azion-console-kit/assets/25899/93408ada-9f55-4e72-9db0-076757918088

[UXE-1619] fix: clicking the logo with the same router should reload the page

---

src/views/WafRules/FormFields/FormFieldsWafRules.vue

https://github.com/aziontech/azion-console-kit/assets/110847590/495eb89d-e0df-44d9-a47d-de918e9a289e
fix: fix input name it is not working

[NO-ISSUE ]  fix: fix input name it is not working

---

src/services/digital-certificates-services/create-digital-certificates-csr-service.js
src/services/digital-certificates-services/create-digital-certificates-service.js
src/services/digital-certificates-services/edit-digital-certificates-service.js
src/services/digital-certificates-services/msg-error.js

[UXE-1755]
WHY:
feat: validation error msg in digital certificate
[UXE-1755]: https://aziontech.atlassian.net/browse/UXE-1755?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
https://github.com/aziontech/azion-console-kit/assets/110847590/fa2054e3-76f3-4572-ae94-19c48a2aad81

[UXE-1755] feat: validation error msg in digital certificate

---

src/services/metrics-services/constants/dashboards.js
src/services/metrics-services/constants/reports.js
src/stores/metrics-store/actions/index.js
src/stores/metrics-store/actions/load-report-variation.js
src/stores/metrics-store/actions/load-report-with-meta.js
src/stores/metrics-store/actions/load-reports-data-by-selected-dashboard.js
src/stores/metrics.js
src/templates/graphs-card-block/components/aggregation-info.vue
src/templates/graphs-card-block/index.vue

- replace bigint with string in ids for reports and dashboards
- create load-report-variation action to handle requests and set report variation to store
- retrieve report variation from store
*** The differences in variation values seen on the preview is acceptable for short periods, due to the amount of events and the diference in time between requests. This difference should be 0, when periods are large and a few events more or less do not impact the total variation.
** consider short periods values between 'last hour' and 'last seven days'
https://github.com/aziontech/azion-console-kit/assets/95643165/cac9230d-587d-43b7-a710-866849b937bf

[ENG-29254] feat: integrate feedback tags

---

src/templates/mfa-authenticate-block/index.vue

[UXE-1592] 
WHY:
feat: dynamically delete entered codes 
[UXE-1592]: https://aziontech.atlassian.net/browse/UXE-1592?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
https://github.com/aziontech/azion-console-kit/assets/110847590/477eb6f4-5726-4533-9612-b873c9ac18a1

[UXE-1592] fix: dynamically delete entered codes 

---

src/templates/footer-block/index.vue
src/templates/mfa-authenticate-block/index.vue
src/tests/services/edge-application-services/create-edge-application-service.test.js
src/tests/services/edge-application-services/edit-edge-application-service.test.js
src/views/EdgeApplications/CreateView.vue
src/views/EdgeApplications/FormFields/FormFieldsCreateEdgeApplications.vue

[UXE-1790] 
WHY:
feat: change copyright text
[UXE-1790]: https://aziontech.atlassian.net/browse/UXE-1790?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[UXE-1790] feat: change copyright text

---

src/templates/content-block/banner.vue
src/templates/content-block/index.vue

Update terms to use Experimental instead Preview.

[UXE-1797] fix: preview term to experimental

---

src/templates/profile-block/index.vue

[UXE-1791] 
WHY:
feat: Open Billing & Subscriptions in RTM 
Uploading Gravação de Tela 2024-02-12 às 14.00.04.mov…
[UXE-1791]: https://aziontech.atlassian.net/browse/UXE-1791?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[UXE-1791] feat: Open Billing & Subscriptions in RTM 

---

src/templates/mfa-setup-block/index.vue

[NO-ISSUE] 
WHY:
fix: MFA code in setup page

[NO-ISSUE] fix: MFA code in setup page

---

src/templates/profile-block/index.vue
src/views/Home/HomeView.vue

[UXE-1791] 
WHY:
fix: add open rtm billing on the home page
[UXE-1791]: https://aziontech.atlassian.net/browse/UXE-1791?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[UXE-1791][UXE-1802] fix: add open rtm billing in the home page

---

src/templates/profile-block/index.vue
src/views/Home/HomeView.vue

[NO-ISSUE] 
WHY
fix: add new address link and check MODE env

[NO-ISSUE] fix: add new address link and check MODE env

---

src/router/routes/password-routes/index.js
src/services/auth-services/index.js
src/services/auth-services/make-password-setting-service-base-url.js
src/services/auth-services/password-setting-service.js
src/templates/sign-in-block/reset-password.vue
src/tests/services/auth-services/password-setting-service.test.js
src/views/NewPassword/NewPasswordView.vue

Related issues:
[ENG-29049]
[ENG-29050]
[ENG-29051]
Update /password/new to handle urls coming from `add user` on console kit
https://github.com/aziontech/azion-console-kit/assets/95643165/ee217e23-7fb4-44eb-adcf-3b31de24d103
[ENG-29049]: https://aziontech.atlassian.net/browse/ENG-29049?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[ENG-29050]: https://aziontech.atlassian.net/browse/ENG-29050?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[ENG-29051]: https://aziontech.atlassian.net/browse/ENG-29051?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ENG-29050] feat: handle password reset

---

src/templates/dialog-unsaved-block/index.vue
src/templates/edit-form-block/index.vue
src/views/EdgeApplications/TabsView.vue
src/views/EdgeFirewall/TabsView.vue
src/views/EdgeNode/TabsView.vue
src/views/EdgeServices/TabsView.vue
src/views/WafRules/TabsView.vue

https://github.com/aziontech/azion-console-kit/assets/92529166/f0fe4560-a84a-4df6-88c0-d749afa38c24

[UXE-1713] feat: add modal unsaved to tabs

---

package.json
src/templates/navbar-block/feedback-fish.vue
src/templates/navbar-block/index.vue
yarn.lock

Implementation of Feedback Fish tool inside the Console.
It's only a POC, so we need to adjust the UX/UI of this feature.
https://github.com/aziontech/azion-console-kit/assets/25899/80017d26-88a0-49e1-ab31-abc22bc69f85

[UXE-1800] feat: add feedback fish to menu

---

src/views/EdgeFirewallRulesEngine/FormFields/FormFieldsEdgeFirewallRulesEngine.vue
src/views/Home/HomeView.vue

[UXE-1799] fix: [edge firewall] update criteria list validation and values in drawer dropdown

---

src/views/Home/HomeView.vue

The whitespace before the period is causing a minor issue in line break

[NO-ISSUE] refactor: remove whitespace before period in disclaimer text

---

src/templates/list-table-block/no-header.vue

https://github.com/aziontech/azion-console-kit/assets/92529166/3a8f8187-c0ae-4670-b426-f4e264f87913

[UXE-1806] fix: inappropriate checkbox behavior

---

src/views/EdgeFirewallFunctions/FormFields/FormFieldsEdgeApplicationsFunctions.vue

[UXE-1801] chore: functions instances firewall description

---

src/router/hooks/beforeEachRoute.js
src/router/hooks/redirectToManager.js
src/router/index.js
src/services/contract-services/index.js
src/services/contract-services/load-contract-service-plan.js
src/services/contract-services/make-contract-base-url.js
src/stores/account.js
src/templates/dialog-unsaved-block/index.vue
src/templates/edit-form-block/index.vue
src/templates/list-table-block/no-header.vue
src/tests/services/contract-services/load-contract-service-plan.test.js
src/tests/services/contract-services/make-contract-base-url.test.js
src/views/EdgeNode/TabsView.vue
vite.config.js

should redirect every account that is not kind Band and from Azion, or that is not an developer support type. To ensure a control access to console kit v1 launch.
tests:

[UXE-1903] feat: redirect users from console to manager

---

src/templates/advanced-filter/dialog-filter.vue
src/templates/footer-block/index.vue
src/templates/form-fields-inputs/fieldDropdown.vue
src/templates/profile-block/index.vue
src/templates/signup-block/additional-data-form-block.vue
src/templates/switch-account-block/index.vue
src/views/AccountSettings/FormFields/FormFieldsAccountSettings.vue
src/views/DataStreaming/FormFields/FormFieldsDataStreaming.vue
src/views/Domains/FormFields/FormFieldsCreateDomains.vue
src/views/Domains/FormFields/FormFieldsEditDomains.vue
src/views/EdgeApplications/FormFields/FormFieldsCreateEdgeApplications.vue
src/views/EdgeApplicationsErrorResponses/FormFields/FormFieldsErrorResponses.vue
src/views/EdgeApplicationsFunctions/FormFields/FormFieldsEdgeApplicationsFunctions.vue
src/views/EdgeApplicationsOrigins/FormFields/FormFieldsEdgeApplicationsOrigins.vue
src/views/EdgeFirewallFunctions/FormFields/FormFieldsEdgeApplicationsFunctions.vue
src/views/EdgeNode/FormFields/FormFieldsDrawerService.vue
src/views/Home/FormFields/FormFieldsHome.vue
src/views/IntelligentDNS/FormFields/FormFieldsRecords.vue
src/views/Marketplace/drawer/IntegrationInstall.vue
src/views/Metrics/blocks/interval-filter-block.vue
src/views/Metrics/blocks/tabs-page-block.vue
src/views/NetworkLists/FormFields/FormFieldsCreateNetworkLists.vue
src/views/NetworkLists/FormFields/FormFieldsEditNetworkLists.vue
src/views/PersonalTokens/FormFields/FormFieldsPersonalToken.vue
src/views/Users/FormsFields/FormFieldsUsers.vue
src/views/WafRules/FormFields/FormFieldsAllowed.vue
src/views/WafRules/FormFields/FormFieldsWafRules.vue
src/views/WafRules/ListWafRulesTuning.vue
src/views/YourSettings/FormFields/FormFieldsYourSettings.vue

- add prop "appendTo='self'" to dropdown components to override default behavior which is "appendTo='body'"

[UXE-1798] fix: [dropdowns] add appendTo=self to fix list being scrolled with page

---

src/templates/profile-block/index.vue

- add reactivity to theme select in profile menu
https://github.com/aziontech/azion-console-kit/assets/95643165/9af567af-3c5b-4c19-b2f2-71b1806acb58
https://github.com/aziontech/azion-console-kit/assets/95643165/3f71b2d8-37be-49d1-b59a-74a4ff3bd9c8

[UXE-1979] fix: [profile-menu] update theme value in menu on change

---

src/services/data-streaming-services/list-data-streaming-domains-service.js
src/services/data-streaming-services/load-data-streaming-service.js

[UXE-1895] 
WHY
fix: add page_size 2000 in domains
[UXE-1895]: https://aziontech.atlassian.net/browse/UXE-1895?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[UXE-1895] fix: add page_size 2000 in domains

---

src/templates/sidebar-block/index.vue

https://github.com/aziontech/azion-console-kit/assets/92529166/4ac4c3e9-f85b-4a01-8e31-1b38db177094

[NO-ISSUE] feat: open menu sidebar in new tab with keyboard key

---

src/templates/create-drawer-block/index.vue
src/templates/dialog-unsaved-block/index.vue
src/templates/edit-drawer-block/index.vue
src/views/EdgeApplications/TabsView.vue

https://github.com/aziontech/azion-console-kit/assets/92529166/e727a8dd-9222-41b8-bdc8-6e1c09f3a6c7

[UXE-1696] fix: add modal unsaved to drawer

---

src/router/hooks/redirectToManager.js

- remove redirect to azion access, to enable full access to console kit

[NO-ISSUE] fix: avoid redirects to azion access

---

src/helpers/generate-timestamp.js
src/services/network-lists-services/list-network-list-service.js
src/templates/create-drawer-block/index.vue
src/templates/create-modal-block/index.vue
src/templates/dialog-unsaved-block/index.vue
src/templates/edit-drawer-block/index.vue
src/tests/services/marketplace-services/list-solutions-service.test.js
src/tests/services/network-lists-services/list-network-list-service.test.js
src/views/EdgeApplications/TabsView.vue
src/views/IntelligentDNS/EditView.vue

[UXE-1919]
WHY:
fix: template selector is coming up empty
[UXE-1919]: https://aziontech.atlassian.net/browse/UXE-1919?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[UXE-1919] fix: template selector with start state empty

---

src/services/edge-application-origins-services/create-origin-service.js
src/templates/dialog-unsaved-block/index.vue
src/tests/services/edge-application-origins-services/create-origin-service.test.js
src/views/Credentials/FormFields/FormFieldsCreateCredentials.vue
src/views/Credentials/FormFields/FormFieldsEditCredentials.vue
src/views/DigitalCertificates/FormFields/FormFieldsEditDigitalCertificates.vue
src/views/Domains/FormFields/FormFieldsCreateDomains.vue
src/views/Domains/FormFields/FormFieldsEditDomains.vue
src/views/EdgeApplicationsOrigins/FormFields/FormFieldsEdgeApplicationsOrigins.vue
src/views/PersonalTokens/Dialog/CopyTokenDialog.vue
src/views/PersonalTokens/FormFields/FormFieldsPersonalToken.vue

- improved leave/keep editing toast message
- fixed placeholder for path field in Origins
- fixed origin toast capitalization
- copy to clipboard buttons are now labeled `copy`

[EDU-4162] chore: bug hunting build uxw adjustments

---

src/templates/form-fields-inputs/fieldDropdown.vue
src/views/EdgeApplicationsRulesEngine/FormFields/FormFieldsEdgeApplicationsRulesEngine.vue

https://github.com/aziontech/azion-console-kit/assets/92529166/e2755974-7a1e-4d2c-9a6d-f54dd506f130

[UXE-1980] fix: disabling the fields for default rules

---

src/templates/dialog-unsaved-block/index.vue
src/templates/info-drawer-block/index.vue
src/views/Domains/ListView.vue
src/views/RealTimeEventsActivityHistory/Drawer/index.vue
src/views/RealTimeEventsDataStreaming/Drawer/index.vue
src/views/RealTimeEventsEdgeFunctions/Drawer/index.vue
src/views/RealTimeEventsEdgeFunctionsConsole/Drawer/index.vue
src/views/RealTimeEventsHTTPRequests/Drawer/index.vue
src/views/RealTimeEventsImageProcessor/Drawer/index.vue
src/views/RealTimeEventsIntelligentDNS/Drawer/index.vue
src/views/RealTimeEventsL2Cache/Drawer/index.vue

[UXE-2034] refactor: update styles for info-drawers

---

src/views/RealTimeEvents/TabsView.vue
src/views/RealTimeEvents/blocks/interval-filter-block.vue
src/views/RealTimeEventsActivityHistory/ListView.vue
src/views/RealTimeEventsDataStreaming/ListView.vue
src/views/RealTimeEventsEdgeFunctions/ListView.vue
src/views/RealTimeEventsEdgeFunctionsConsole/ListView.vue
src/views/RealTimeEventsHTTPRequests/ListView.vue
src/views/RealTimeEventsImageProcessor/ListView.vue
src/views/RealTimeEventsIntelligentDNS/ListView.vue
src/views/RealTimeEventsL2Cache/ListView.vue

[UXE-2033] 
WHY:
fix: filter date remains with the same value when switching tabs
[UXE-2033]: https://aziontech.atlassian.net/browse/UXE-2033?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[UXE-2033] fix: filter date remains with the same value when switching tabs

---

src/router/hooks/beforeEachRoute.js
src/services/help-center-services/get-help-center-documentation-service.js
src/services/metrics-services/constants/dashboards-texts.js
src/services/metrics-services/constants/help-center-urls.js
src/services/metrics-services/constants/reports.js
src/stores/help-center.js
src/stores/metrics-store/actions/load-reports-data-by-selected-dashboard.js
src/templates/graphs-card-block/components/more-options-menu.vue
src/templates/graphs-card-block/helpers/c3-charts.js
src/templates/graphs-card-block/index.vue
src/templates/help-center-block/index.vue
src/templates/profile-block/index.vue
src/tests/services/help-center-services/get-help-center-documentation-service.test.js

- adjust font size in profile menu "theme" label
- update helpcenter store
- fix helpcenter behaviors
- close helpcenter on route change
- convert slidein block code to options api
- implement helpcenter in real-time-metrics
- improve helpcenter tests
- fix meanline watcher
https://github.com/aziontech/azion-console-kit/assets/95643165/da54eb5d-41c7-401f-a57b-e0d3813d10ee

[UXE-2015] feat: implement helpcenter in metrics

---

src/templates/dialog-unsaved-block/index.vue
src/templates/info-drawer-block/info-labels/big-number.vue
src/templates/info-drawer-block/info-labels/text-info.vue
src/views/Domains/ListView.vue

[UXE-2039] 
WHY:
fix: review events low gaveta labels
[UXE-2039]: https://aziontech.atlassian.net/browse/UXE-2039?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[UXE-2039] fix: review events low gaveta labels

---

src/templates/help-center-block/index.vue

- replace min-height with height, so the content can be scrollable if greater than vh

[NO-ISSUE] fix: [slide-in] adjust content height

---

src/views/RealTimeEventsActivityHistory/ListView.vue

[UXE-2148] fix: add expand-text component to title header

---

src/services/real-time-events-service/intelligent-dns/list-intelligent-dns.js
src/templates/info-drawer-block/info-labels/big-number.vue
src/views/RealTimeEventsActivityHistory/Drawer/index.vue
src/views/RealTimeEventsDataStreaming/Drawer/index.vue
src/views/RealTimeEventsEdgeFunctions/Drawer/index.vue
src/views/RealTimeEventsEdgeFunctionsConsole/Drawer/index.vue
src/views/RealTimeEventsHTTPRequests/Drawer/index.vue
src/views/RealTimeEventsIntelligentDNS/Drawer/index.vue
src/views/RealTimeEventsL2Cache/Drawer/index.vue

[UXE-2035] 
WHY:
fix: adjusting component sizes and alignments 
[UXE-2035]: https://aziontech.atlassian.net/browse/UXE-2035?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[UXE-2035] fix: adjusting component sizes and alignments 

---

src/services/metrics-services/constants/dashboards-texts.js

Modified:
* A few texts in Real-Time Metrics reports to match the aggregation being used.

[EDU-3643] refactor: update metrics reports texts

---

.github/PULL_REQUEST_TEMPLATE.md

[NO-ISSUE] chore: add pull request template

---

src/plugins/adapters/AnalyticsTrackerAdapter.js
src/templates/sign-in-block/index.vue
src/tests/plugins/adapters/AnalyticsTrackerAdapter.test.js

[UXE-2102]
added User Signed In event tracker
No
<hr />
[UXE-2102]: https://aziontech.atlassian.net/browse/UXE-2102?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[UXE-2102] feat:  user signed in

---

src/plugins/adapters/AnalyticsTrackerAdapter.js
src/templates/sign-in-block/index.vue
src/tests/plugins/adapters/AnalyticsTrackerAdapter.test.js

[UXE-2103]
added a tracker that occurs when the sign in returns error
<hr />
[UXE-2103]: https://aziontech.atlassian.net/browse/UXE-2103?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[UXE-2103] feat: add User Failed to Sign In

---

src/plugins/adapters/AnalyticsTrackerAdapter.js
src/tests/plugins/adapters/AnalyticsTrackerAdapter.test.js
src/views/EdgeApplications/CreateView.vue
src/views/EdgeApplications/FormFields/FormFieldsCreateEdgeApplications.vue

Add new event to track when a product is created
No
No
<hr />

[UXE-1883] feat: create event edge application created

---

src/templates/info-drawer-block/info-labels/big-number.vue

* changed big number weight to bold
* changed sufix text color

[UXE-2040] fix: changed big number weight

---

src/plugins/adapters/AnalyticsTrackerAdapter.js
src/templates/signup-block/account-activation.vue
src/templates/signup-block/additional-data-form-block.vue
src/templates/signup-block/form-signup-block.vue
src/tests/plugins/adapters/AnalyticsTrackerAdapter.test.js

* new tracker event User Signed Up
* unit tests to this event

[UXE-2097] feat: add track event User Signed Up

---

src/plugins/adapters/AnalyticsTrackerAdapter.js
src/templates/signup-block/additional-data-form-block.vue
src/tests/plugins/adapters/AnalyticsTrackerAdapter.test.js

* track event submitted additional data
No
<hr />

[UXE-2100] feat: added track event submitted additional data

---

src/templates/info-drawer-block/info-section/index.vue

Updated the tag element in the "section-info" component
[Link to Figma](https://www.figma.com/file/HlUNxyUS30FEwItAnhvEXf/Application-Blocks-(BACKUPS)?type=design&node-id=1814-54474&mode=design&t=1oK3wgF5jcQ1MLOR-0)
<hr />

[UXE-2046] fix: update element tag in info-section component

---

src/services/metrics-services/constants/reports.js
src/services/real-time-events-service/activity-history/load-activity-history.js
src/templates/info-drawer-block/info-section/index.vue
src/views/EdgeApplications/FormFields/FormFieldsCreateEdgeApplications.vue
src/views/EdgeApplicationsCacheSettings/FormFields/FormFieldsEdgeApplicationCacheSettings.vue
src/views/RealTimeEvents/FormFields/FormFieldsCreateEdgeApplications.vue
src/views/RealTimeEvents/TabsView.vue
src/views/RealTimePurge/FormFields/FormFieldsCreateRealTimePurge.vue

- Modified texts for old module names l2 and edge caching

[EDU-4208] chore: replace edge caching and l2 texts with edge cache and tiered cache

---

src/services/metrics-services/constants/dashboards-texts.js
src/views/DigitalCertificates/FormFields/FormFieldsEditDigitalCertificates.vue

* Updated a few aggregation types in Real-Time Metrics reports.
* Added information regarding Digital Certificates, specifying certificates and keys aren't shown in Edit screen for security purposes.
No
<hr />

[UXE-2182] refactor: update uxw digital certificate

---

src/plugins/adapters/AnalyticsTrackerAdapter.js
src/templates/navbar-block/create.vue
src/tests/plugins/adapters/AnalyticsTrackerAdapter.test.js
src/views/Home/HomeView.vue

[UXE-2104]
added a tracker when clicking on create in header and home
<hr />
[UXE-2104]: https://aziontech.atlassian.net/browse/UXE-2104?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[UXE-2104] feat: added a tracker when clicking on create in header and home

---

src/views/RealTimeEventsL2Cache/Drawer/index.vue

* added cache key value in l2 cache drawer

[UXE-2050] fix: added cache key value in l2 cache drawer

---

src/plugins/adapters/AnalyticsTrackerAdapter.js
src/templates/signup-block/form-signup-block.vue
src/tests/plugins/adapters/AnalyticsTrackerAdapter.test.js

[UXE-2098] feat: added track event User Failed to Sign Up

---

src/plugins/adapters/AnalyticsTrackerAdapter.js
src/templates/signup-block/additional-data-form-block.vue
src/tests/plugins/adapters/AnalyticsTrackerAdapter.test.js
src/views/EdgeApplications/FormFields/FormFieldsCreateEdgeApplications.vue
src/views/EdgeApplicationsCacheSettings/FormFields/FormFieldsEdgeApplicationCacheSettings.vue
src/views/RealTimeEvents/FormFields/FormFieldsCreateEdgeApplications.vue

added track event failed submit additional data
No
<hr />

[UXE-2101] feat: added track event failed submit additional data

---

src/plugins/adapters/AnalyticsTrackerAdapter.js
src/templates/create-form-block/index.vue
src/tests/plugins/adapters/AnalyticsTrackerAdapter.test.js
src/views/EdgeApplications/CreateView.vue
src/views/EdgeApplications/FormFields/FormFieldsCreateEdgeApplications.vue
src/views/EdgeApplicationsCacheSettings/FormFields/FormFieldsEdgeApplicationCacheSettings.vue
src/views/RealTimeEvents/FormFields/FormFieldsCreateEdgeApplications.vue
src/views/RealTimeEventsL2Cache/Drawer/index.vue

add new track event to track an product failure when try to create. Add first to the Create view of edge application
No
<hr />

[UXE-1884] feat: create event failed to create edge application

---

src/templates/info-drawer-block/info-labels/big-number.vue

sufix big number font size 14px
No
<hr />

[NO-ISSUE] fix: sufix big number font size

---

src/templates/info-drawer-block/info-section/index.vue
src/views/RealTimeEventsEdgeFunctions/Drawer/index.vue

Altera o tamanho do time stamp e icone no drawer de functions em real time events.
<hr />

[UXE-2038] fix: change the icon and ts size in real time events time stamp

---

src/assets/c3.scss
src/templates/graphs-card-block/constants/color-patterns.js

- add new colors to metrics charts according to theme
- use variables in css props to match theme
- refactor c3 color constants array
Before:
After: 
[Link to Figma](https://www.figma.com/file/0TY2pcUTBsndMlrs0ZUvQf/Console-Kit-UI?type=design&node-id=12295-26825&mode=design&t=JURjP6OpJ297rDdK-0)
<hr />

[UXE-1959] refactor: adjust metrics theme config

---

src/services/real-time-events-service/http-request/load-http-request.js

temporarily commented code
<hr />

[NO-ISSUE] fix: temporarily commented code

---

src/helpers/azion-documentation-catalog.js
src/router/routes/real-time-events-routes/index.js

Updated the documentation links within the tabs of each table in the real-time-evetnts view of the "learn more" button
NO
NO
<hr />

[UXE-2041] refactor: update view events documentation links

---

src/assets/c3.scss
src/plugins/adapters/AnalyticsTrackerAdapter.js
src/templates/create-modal-block/index.vue
src/tests/plugins/adapters/AnalyticsTrackerAdapter.test.js
src/views/Home/HomeView.vue

[UXE-2105]
added tracker event when clicking on a template 
<hr />
[UXE-2105]: https://aziontech.atlassian.net/browse/UXE-2105?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[UXE-2105] feat: added tracker event when clicking on a template 

---

src/assets/c3.scss
src/templates/list-table-block/index.vue

adjust table actions did not work after filtering the columns
no
https://github.com/aziontech/azion-console-kit/assets/92529166/f16ed75f-a0bb-4f98-a22e-209e73ef4bd4
<hr />

[UXE-2217] fix: adjust table actions did not work after filtering the columns

---

src/assets/c3.scss
src/plugins/adapters/AnalyticsTrackerAdapter.js
src/tests/plugins/adapters/AnalyticsTrackerAdapter.test.js
src/views/EdgeApplications/EditView.vue

Add to tracker adapter a method to enable tracking products with successfully edit
No
<hr />

[UXE-1886] feat: add event edited product with success

---

src/services/real-time-events-service/http-request/load-http-request.js
src/views/RealTimeEvents/blocks/interval-filter-block.vue
src/views/RealTimeEventsHTTPRequests/Drawer/index.vue

Removed commented code for testing from the httpRequest tab, and added the serverProcol and upstreamCacheStatus tags.
[Link to Figma](https://www.figma.com/file/0TY2pcUTBsndMlrs0ZUvQf/Console-Kit-UI?type=design&node-id=7976-164209&mode=design&t=Aa6xpLKrpkShJ2dA-0)
<hr />
◊◊

[UXE-2286] fix: add new properties to adaptResponse function

---

src/plugins/adapters/AnalyticsTrackerAdapter.js
src/tests/plugins/adapters/AnalyticsTrackerAdapter.test.js
src/views/CreateNew/CreateView.vue

[UXE-2106]
add tracker when clicked to view more details on template
I changed from Options API to Composition API, because inject wouldn't work with Options API and this can cause errors
https://github.com/aziontech/azion-console-kit/assets/110847590/f4cd597a-bda5-4c02-b5fe-f3901bf95674
<hr />
[UXE-2106]: https://aziontech.atlassian.net/browse/UXE-2106?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[UXE-2106] feat: add tracker when clicked to view more details on template

---

src/plugins/adapters/AnalyticsTrackerAdapter.js
src/tests/plugins/adapters/AnalyticsTrackerAdapter.test.js
src/views/Login/LoginView.vue

* added track event activated account
* test to new event
* refactor LoginView to Composition API
* Login view (refactor)
https://github.com/aziontech/azion-console-kit/assets/109550332/13c0739d-8f99-4efe-b3bc-ea73ef071eca
No
<hr />

[UXE-2099] feat: added track event activated account

---

src/plugins/adapters/AnalyticsTrackerAdapter.js
src/templates/template-engine-block/index.vue
src/tests/plugins/adapters/AnalyticsTrackerAdapter.test.js

[UXE-2107]
add deployed tracker
<hr />
[UXE-2107]: https://aziontech.atlassian.net/browse/UXE-2107?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[UXE-2107] feat: add deployed tracker

---

src/plugins/adapters/AnalyticsTrackerAdapter.js
src/templates/template-engine-block/index.vue
src/tests/plugins/adapters/AnalyticsTrackerAdapter.test.js
src/views/CreateNew/DeployView.vue

[UXE-2108]
failed to deploy
<hr />
[UXE-2108]: https://aziontech.atlassian.net/browse/UXE-2108?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[UXE-2108] feat: failed to deploy

---

src/plugins/factories/analytics-tracking-factory.js

add production key for segment plugin in analytics client
Add new write key to production environment for tracking integration trough segment
No.
No.
<hr />

[NO-ISSUE] feat: add production key for segment in analytics factory to ensure production integration

---

package.json

upgrade project version to 1.9.0
No
No
<hr />

chore: upgrade project version from 1.8.8 to 1.9.0

---

src/views/RealTimeEventsDataStreaming/Drawer/index.vue
src/views/RealTimeEventsHTTPRequests/Drawer/index.vue
src/views/RealTimeEventsImageProcessor/Drawer/index.vue
src/views/RealTimeEventsL2Cache/Drawer/index.vue

adjust style big numbers
no
no
<hr />

[UXE-2037] fix: adjust style big numbers

---

src/views/RealTimePurge/FormFields/FormFieldsCreateRealTimePurge.vue

Update l2 caching to tiered cache 
<hr />

[UXE-2163] feat: update l2 caching to tiered cache

---

src/plugins/adapters/AnalyticsTrackerAdapter.js
src/tests/plugins/adapters/AnalyticsTrackerAdapter.test.js
src/views/EdgeApplicationsOrigins/Drawer/index.vue

[UXE-1888] 
add clicked to create origin event 
<hr />
[UXE-1888]: https://aziontech.atlassian.net/browse/UXE-1888?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[UXE-1888] feat: add clicked to create origin event 

---

src/tests/plugins/adapters/AnalyticsTrackerAdapter.test.js
src/views/CreateNew/CreateView.vue
src/views/EdgeApplicationsOrigins/Drawer/index.vue
src/views/EdgeApplicationsOrigins/ListView.vue

[UXE-1889]
add created origin event tracker
<hr />
[UXE-1889]: https://aziontech.atlassian.net/browse/UXE-1889?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[UXE-1889] feat: add created origin event tracker

---

src/plugins/adapters/AnalyticsTrackerAdapter.js
src/services/signup-services/signup-service.js
src/templates/signup-block/form-signup-block.vue
src/tests/plugins/adapters/AnalyticsTrackerAdapter.test.js

* added props to user failed signin track event
<hr />

feat: added props to user failed signin track event

---

src/views/WafRules/FormFields/FormFieldsAllowed.vue

Bug fix
- [] Tags are added to the PR

[NO-ISSUE] fix: using the right match zones for WAF allowed rules

---

src/views/RealTimePurge/FormFields/FormFieldsCreateRealTimePurge.vue

fix typo in input value related to tiered cache. From tired_cache to tiered_cache.
No
No
<hr />

[UXE-2163] fix: tiered cache typo in form fields of real time purge

---

package.json

upgrade project version to enable deploy of version 1.9.1
No
No
No
<hr />

[NO-ISSUE] chore: upgrade project version from version 1.9.0 to 1.9.1

---

package.json
src/plugins/adapters/AnalyticsTrackerAdapter.js
src/services/signup-services/signup-service.js
src/templates/signup-block/form-signup-block.vue
src/tests/plugins/adapters/AnalyticsTrackerAdapter.test.js
src/views/CreateNew/CreateView.vue
src/views/EdgeApplicationsOrigins/Drawer/index.vue
src/views/EdgeApplicationsOrigins/ListView.vue
src/views/RealTimeEventsDataStreaming/Drawer/index.vue
src/views/RealTimeEventsHTTPRequests/Drawer/index.vue
src/views/RealTimeEventsImageProcessor/Drawer/index.vue
src/views/RealTimeEventsL2Cache/Drawer/index.vue
src/views/RealTimePurge/FormFields/FormFieldsCreateRealTimePurge.vue
src/views/WafRules/FormFields/FormFieldsAllowed.vue

Reverts aziontech/azion-console-kit#847

Revert "DEPLOY 2024.03.06"

---

src/tests/services/real-time-purge/create-real-time-purge.test.js
src/tests/services/real-time-purge/list-real-time-purge.test.js
src/views/RealTimePurge/CreateView.vue

fix initial values for create real time purge.
No
No
<hr />

[NO-ISSUE] fix: typo in realtime purge create view initial values

---

src/plugins/adapters/AnalyticsTrackerAdapter.js
src/tests/plugins/adapters/AnalyticsTrackerAdapter.test.js
src/views/EdgeApplicationsOrigins/Drawer/index.vue

[UXE-1890]
failed to create origin
<hr />
[UXE-1890]: https://aziontech.atlassian.net/browse/UXE-1890?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[UXE-1890] feat: failed to create origin

---

src/views/DataStreaming/FormFields/FormFieldsDataStreaming.vue
src/views/DataStreaming/ListView.vue

* Improved UXW for the Delete modal and added a missing word in Data Streaming form.
No
<hr />

[UXE-2185] [UXE-2186] refactor: uxw data streaming

---

src/views/NetworkLists/FormFields/FormFieldsCreateNetworkLists.vue
src/views/NetworkLists/FormFields/FormFieldsEditNetworkLists.vue

* Updated Network Lists placeholder when creating and editing an IP/CIDR list.
No
<hr />

[UXE-2183] refactor: update network list placeholder

---

src/views/EdgeApplicationsOrigins/ListView.vue

[UXE-1891]
add event tracker clicked to edit origin
<hr />
[UXE-1891]: https://aziontech.atlassian.net/browse/UXE-1891?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[UXE-1891] feat: add event tracker clicked to edit origin

---

src/views/EdgeApplicationsOrigins/Drawer/index.vue
src/views/NetworkLists/FormFields/FormFieldsCreateNetworkLists.vue
src/views/NetworkLists/FormFields/FormFieldsEditNetworkLists.vue

[UXE-1904]
add event tracker edited origin
<hr />
[UXE-1904]: https://aziontech.atlassian.net/browse/UXE-1904?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[UXE-1904] feat: add event tracker edited origin

---

src/router/routes/data-streaming-routes/index.js
src/router/routes/intelligent-dns-routes/index.js
src/services/metrics-services/constants/dashboards-texts.js
src/services/metrics-services/constants/dashboards.js
src/services/metrics-services/constants/reports.js
src/services/sidebar-menus-services/menus.js
src/templates/create-modal-block/index.vue
src/views/DataStreaming/CreateView.vue
src/views/DataStreaming/EditView.vue
src/views/DataStreaming/FormFields/FormFieldsDataStreaming.vue
src/views/DataStreaming/ListView.vue
src/views/EdgeApplications/FormFields/FormFieldsCreateEdgeApplications.vue
src/views/EdgeFirewall/FormFields/FormFieldsEdgeFirewall.vue
src/views/IntelligentDNS/CreateView.vue
src/views/IntelligentDNS/EditView.vue
src/views/IntelligentDNS/FormFields/FormFieldsRecords.vue
src/views/IntelligentDNS/ListView.vue
src/views/RealTimeEvents/FormFields/FormFieldsCreateEdgeApplications.vue
src/views/RealTimeEvents/TabsView.vue
src/views/RealTimeEventsDataStreaming/ListView.vue
src/views/RealTimeEventsIntelligentDNS/ListView.vue

* Updated product names with new names in labels, descriptions, titles, and comments.
No
<hr />

[EDU-4249] feat: product naming

---

src/plugins/adapters/AnalyticsTrackerAdapter.js
src/tests/plugins/adapters/AnalyticsTrackerAdapter.test.js
src/views/EdgeApplicationsOrigins/Drawer/index.vue

[UXE-1906]
event tracker failed to edit origin
<hr />
[UXE-1906]: https://aziontech.atlassian.net/browse/UXE-1906?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[UXE-1906] feat: event tracker failed to edit origin

---

src/App.vue
src/views/RealTimeEventsIntelligentDNS/ListView.vue

Add full name to traits sent on each tracking event after identify track has been made.
No
No
<hr />

[UXE-2053] feat: add to tracking traits account full name

---

src/views/RealTimeEventsL2Cache/Drawer/index.vue

Cache key added label and fixed alignment of copy button
<hr />

[UXE-2050] fix: cache key info alignment

---

src/router/index.js
src/router/routes/edge-dns-routes/index.js
src/services/intelligent-dns-records-services/create-records-service.js
src/services/intelligent-dns-services/create-intelligent-dns-service.js
src/services/sidebar-menus-services/menus.js
src/stores/solution-create.js
src/views/IntelligentDNS/EditView.vue
src/views/IntelligentDNS/ListView.vue
src/views/RealTimeEventsIntelligentDNS/ListView.vue

Troca todas as rotas de intelligent dns para edge dns
<hr />

[UXE-2406] refactor: change edge dns routes

---

src/stores/metrics-store/actions/load-reports-data-by-selected-dashboard.js
src/stores/metrics-store/helpers/convert-report-meta-to-gql.js
src/tests/store/metrics-store/helpers/fixtures/convert-report-fixtures.js

Remove resample from gql query to align with realtime-metrics-ui in production
No UI changes
No
<hr />

[ENG-2436] fix: [metrics] remove resample param from gql query

---

src/plugins/adapters/AnalyticsTrackerAdapter.js
src/stores/solution-create.js
src/tests/plugins/adapters/AnalyticsTrackerAdapter.test.js
src/views/CreateNew/CreateView.vue
src/views/CreateNew/DeployView.vue

Adiciona ao tracker as propriedades necessáras nos eventos de falha no deploy e sucesso no deploy
<hr />

[UXE-2144] feat: add params to deploy failure and success events measurement

---

package.json
src/tests/plugins/adapters/AnalyticsTrackerAdapter.test.js
src/views/EdgeApplicationsOrigins/Drawer/index.vue
src/views/EdgeApplicationsOrigins/FormFields/FormFieldsEdgeApplicationsOrigins.vue

Increase project version
Lint fixes
<hr />

[NO-ISSUE] chore: upgrade project version from version 1.9.1 to 1.10.0

---

src/services/edge-application-origins-services/create-origin-service.js
src/services/edge-application-origins-services/edit-origin-service.js

checking the value of the prefix when it is of type object storage
no
no
<hr />

[NO-ISSUE] fix: checking the value of the prefix

---

src/services/edge-application-services/edit-edge-application-service.js
src/tests/services/edge-application-services/edit-edge-application-service.test.js
src/views/EdgeApplications/FormFields/FormFieldsCreateEdgeApplications.vue

error when i try to change the minimum TLS version
https://github.com/aziontech/azion-console-kit/assets/92529166/440c74ee-aa17-4bd3-ad06-d661017928ab
<hr />

[UXE-2494] fix: error when i try to change the minimum TLS version

---

src/services/edge-application-origins-services/create-origin-service.js
src/services/edge-application-origins-services/edit-origin-service.js
src/views/EdgeApplicationsOrigins/Drawer/index.vue

fix validation fields in origin
<hr />

[NO-ISSUE] fix: validation fields in origin

---

src/views/EdgeNode/ListView.vue

edge node list was not listing the data
<hr />

[NO-ISSUE] fix: edge node list was not listing the data

---

src/plugins/adapters/AnalyticsTrackerAdapter.js
src/templates/template-engine-block/index.vue
src/tests/plugins/adapters/AnalyticsTrackerAdapter.test.js
src/views/CreateNew/CreateView.vue

Add the event "Clicked to Deploy" and its properties to the tracker
https://docs.google.com/spreadsheets/d/1BfsifK7165BzpO60_a585HqF8Gi_jDiyu6s_TqkQcv0/edit?pli=1#gid=0
No
No
<hr />

[UXE-2218] feat: add clicked to deploy event

---

src/templates/content-block/banner.vue
src/templates/content-block/index.vue

[EDU-4297]: https://aziontech.atlassian.net/browse/EDU-4297?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
Modify text and remove button from preview banner.
<hr />

[EDU-4297] fix: banner from experimental to preview and remove button

---

src/plugins/adapters/AnalyticsTrackerAdapter.js
src/router/routes/signup-routes/index.js
src/stores/account.js
src/templates/signup-block/form-signup-block.vue
src/templates/signup-block/social-signup-block.vue
src/templates/social-idps-block/index.vue
src/tests/plugins/adapters/AnalyticsTrackerAdapter.test.js

* added sso methods properties to signup tracking event
<hr />

[UXE-2097] feat: added sso methods to signup tracking

---

src/templates/info-drawer-block/info-labels/big-number.vue
src/views/DataStream/FormFields/FormFieldsDataStream.vue
src/views/EdgeFirewall/FormFields/FormFieldsEdgeFirewall.vue
src/views/TeamsPermissions/FormFields/FormFieldsTeamPermissions.vue

removing focus in desktop
<hr />

[UXE-2036] fix: disabling button in desktop

---

src/services/metrics-services/constants/dashboards-texts.js
src/services/metrics-services/constants/help-center-urls.js
src/services/metrics-services/constants/reports.js

* Updated Real-Time Metrics Help Center paths to match articles.
<hr />

[EDU-4301] refactor: update metrics urls

---

src/services/metrics-services/constants/help-center-urls.js
src/services/metrics-services/constants/reports.js

Update l2-cache to tiered-cache in constant files
Extended from [this PR](https://github.com/aziontech/azion-console-kit/pull/904)
No
No
<hr />

[EDU-4301] refactor: update helpcenter urls on metrics

---

src/services/metrics-services/constants/help-center-urls.js

Update intelligent-dns and data streaming url names in constant files
Extended from [this PR](https://github.com/aziontech/azion-console-kit/pull/904)
No
No
<hr />

[EDU-4301] refactor: update edge-dns and data-stream helpcenter urls on metrics

---

package.json

Update project version from 1.10.0 to 1.11.0
No
No
<hr />

[NO-ISSUE] chore: update project version to 1.11.0

---

src/services/edge-application-services/edit-edge-application-service.js
src/templates/edit-form-block/index.vue
src/tests/services/edge-application-services/edit-edge-application-service.test.js
src/views/DataStream/FormFields/FormFieldsDataStream.vue
src/views/EdgeApplications/EditView.vue
src/views/EdgeFirewall/FormFields/FormFieldsEdgeFirewall.vue
src/views/TeamsPermissions/FormFields/FormFieldsTeamPermissions.vue

[UXE-2111]
Inserting properties in the edge application failed event
<hr />
[UXE-2111]: https://aziontech.atlassian.net/browse/UXE-2111?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[UXE-2111] feat: inserting properties in the edge application failed event

---

src/services/edge-node-service-services/create-service-edge-node-service.js
src/templates/empty-results-block/empty-edge-node.vue
src/tests/services/edge-node-service-services/create-service-edge-node-service.test.js
src/views/EdgeNode/FormFields/FormFieldsEdgeNode.vue

- Changed some labels for the edge nodes view
- Corrected a modal's text
No
<hr />

[EDU-4326] chore: final uxw check for edge nodes

---

src/plugins/analytics/trackers/SignUpTracker.js
src/router/routes/signup-routes/index.js
src/tests/plugins/analytics/AnalyticsTrackerAdapter.test.js

* created the authorized sso tracking event
<hr />

[UXE-2427] feat: authorized sso tracking event

---

src/views/WafRules/TabsView.vue

unsaved alert even after clicking save button
https://github.com/aziontech/azion-console-kit/assets/92529166/f872f5cb-54bf-469d-baec-e1681f9fa542
<hr />

fix: unsaved alert even after clicking save button

---

src/templates/footer-block/index.vue
src/templates/system-status-bar-block/index.vue

https://github.com/aziontech/azion-console-kit/assets/95422158/9cd2d4dc-0c54-4c4b-91d9-2de74c5fd113
<hr />

[UXE-1811] alinhamento dos itens do footer

---

src/templates/content-block/banner.vue
src/templates/content-block/index.vue

Changes preview stage warning
<hr />

[no-issue] chore: modify preview stage warning

---

src/helpers/account-expired.js
src/router/hooks/beforeEachRoute.js
src/tests/helpers/account-expired.test.js

[UXE-2433] 
fix: not validating account expiration
<hr />
[UXE-2433]: https://aziontech.atlassian.net/browse/UXE-2433?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[UXE-2433] fix: not validating account expiration

---

src/templates/info-drawer-block/info-labels/text-info.vue
src/views/RealTimeEventsTieredCache/Drawer/index.vue

* fixed spacing and alignment of copy cache key button in real time events tiered cache drawer
Mobile:
<hr />

[UXE-2050] fix: spacing and alignment of copy cache key button

---

src/templates/list-table-block/no-header.vue

listings without deletion action
<hr />

[UXE-2633] fix: listings without deletion action

---

src/views/EdgeApplicationsRulesEngine/FormFields/FormFieldsEdgeApplicationsRulesEngine.vue

overwrite the z-index of the divider component
no
<hr />
- [ x Commits are tagged with the right word (fix, feat, test, etc)

[UXE-2513] fix: overwrite z-index

---

src/templates/list-table-block/no-header.vue

[UXE-1948] 
fix: different looking column
<hr />
[UXE-1948]: https://aziontech.atlassian.net/browse/UXE-1948?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[UXE-1948] fix: different looking column

---

src/assets/themes/scss/themes/azion-dark/variables/_form.scss
src/assets/themes/scss/themes/azion-light/variables/_form.scss
src/views/Playground/PlaygroundView.vue

Apply custom values for variables inside the theme, the goal its pair the design with the code of `<Password>` element
https://github.com/aziontech/azion-console-kit/assets/95422158/e005f8f1-3dbe-4e25-bf56-cbbeb7fec8ef
https://www.figma.com/file/GvpnDYOyV6KnK6ib0jYJVw/Dev-Journey?type=design&node-id=743%3A1123&mode=design&t=0PL8X7wj8FCHKk8j-1
<hr />

feat: custom theme values for password

---

src/services/edge-application-origins-services/list-origins-service.js

[UXE-1945] 
fix: Origin not loading in error response
https://github.com/aziontech/azion-console-kit/assets/110847590/b4a8844d-0563-4677-8f27-2cb2ca503651
<hr />
[UXE-1945]: https://aziontech.atlassian.net/browse/UXE-1945?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[UXE-1945] fix: Origin not loading in error response

---

src/assets/themes/scss/themes/azion-dark/variables/_form.scss
src/assets/themes/scss/themes/azion-light/variables/_form.scss
src/views/EdgeApplicationsRulesEngine/FormFields/FormFieldsEdgeApplicationsRulesEngine.vue

behaviors loading incorrectly
yes
https://github.com/aziontech/azion-console-kit/assets/92529166/56a514d2-f67e-4f0a-91b3-25930f6640f9
<hr />

[UXE-1966] behaviors loading incorrectly

---

src/stores/metrics.js
src/templates/graphs-card-block/components/aggregation-info.vue
src/templates/graphs-card-block/components/more-options-menu.vue
src/templates/graphs-card-block/index.vue

- replace direct store use in more-options-menu component with toRef
- replace direct store use in aggregation-info component with props
- remove unused method from store
No UI changes. Video to show behavior:
https://github.com/aziontech/azion-console-kit/assets/95643165/bc3f7257-f479-46ce-aa06-f85c1cb83f08
No
<hr />

[UXE-2301] refactor: remove store use from card components

---

src/views/EdgeServices/EditView.vue
src/views/EdgeServices/TabsView.vue

[UXE-2560] 
fix: Entity name is missing on edition
https://github.com/aziontech/azion-console-kit/assets/110847590/1303de29-58ab-44b8-95cd-0e8299e9498a
<hr />
[UXE-2560]: https://aziontech.atlassian.net/browse/UXE-2560?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[UXE-2560] fix: Entity name is missing on edition

---

src/templates/advanced-filter/component/fields/float-filter.vue
src/templates/advanced-filter/component/fields/float-range-filter.vue
src/templates/advanced-filter/component/fields/multiselect-filter.vue
src/templates/advanced-filter/component/fields/number-filter.vue
src/templates/advanced-filter/component/fields/number-range-filter.vue
src/templates/advanced-filter/component/fields/text-filter.vue
src/templates/advanced-filter/dialog-filter.vue

* added responsive layout to advanced filter in metrics layout
<hr />

[UXE-2399] feat: added responsive layout to advanced filter in metrics layout

---

src/views/RealTimeEventsHTTPRequests/Drawer/index.vue

* stacktrace real time events field case fix
<hr />

[UXE-2254] fix: stacktrace field case fix

---

src/views/RealTimeEventsHTTPRequests/ListView.vue

* Fixed named of a field in Real-Time Events table.
<hr />

[NO-ISSUE] fix: events field name

---

src/router/routes/signup-routes/index.js

* fixed incorrect tracking event chaining in sign up methods
<hr />

[NO-ISSUE] fix: incorrect tracking event chaining in sign up methods

---

src/views/TeamsPermissions/FormFields/FormFieldsTeamPermissions.vue

* permissions: map of undefined in team permissions load
<hr />

[UXE-2002] fix: map of undefined in team permissions load

---

src/views/Home/HomeView.vue

[NO-ISSUE] feat: change icons in home cards

---

src/assets/main.css

[UXE-2488]
Captcha off-screen
<hr />
[UXE-2488]: https://aziontech.atlassian.net/browse/UXE-2488?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[UXE-2488] fix: captcha off-screen

---

package.json

Update project version to 1.12.0
No
No
<hr />

chore: update project version

---

src/assets/themes/scss/themes/azion-dark/extended-components/_datatable.scss
src/assets/themes/scss/themes/azion-light/extended-components/_datatable.scss

* fix: scroll disables when the mouse is on the table
https://github.com/aziontech/azion-console-kit/assets/109550332/57b3e4fc-4eb1-4357-ab55-5197ae9d3e3b
<hr />

[UXE-2514] fix: scroll disables when the mouse is on the table

---

src/templates/content-block/banner.vue
src/templates/content-block/index.vue
src/views/Marketplace/MarketplaceHomeView.vue

Apply md: breakpoint into main-content and related views
##
https://github.com/aziontech/azion-console-kit/assets/95422158/61dd9589-b899-4ad2-b2ba-0b837fe962d1
No
<hr />

[NO-ISSUE] fix: main-content layout

---

src/router/index.js
src/router/routes/import-github-routes/index.js
src/templates/create-modal-block/index.vue
src/views/ImportGitHub/ImportStaticView.vue

* added import from github section in create modal
<hr />

[UXE-2552] feat: added import from github section in create modal

---

src/views/Home/HomeView.vue

* Changed verb from `edit` to `build` to match the documentation the link redirects to.
<hr />

[UXE-1985] refactor: change verb in application banner home

---

src/services/version-control-system-integration-services/make-version-control-system-base-url.js
src/tests/services/version-control-system-integration-services/list-integrations-service.test.js
src/tests/services/version-control-system-integration-services/list-platforms-service.test.js
src/tests/services/version-control-system-integration-services/post-callback-url-service.test.js
src/views/ImportGitHub/ImportStaticView.vue

[NO-ISSUE] fix: endpoint url of version control system service to use v4 api

---

src/templates/profile-block/index.vue
tailwind.config.js

Apply icon `pi-pi-user` to "Profile Menu"
<hr />

[UXE-2729]feat-apply-icon-profile-to-menu

---

src/services/edge-application-cache-settings-services/create-cache-settings-service.js
src/services/edge-application-cache-settings-services/edit-cache-settings-service.js
src/services/edge-application-cache-settings-services/list-cache-settings-service.js
src/services/edge-application-cache-settings-services/load-cache-settings-service.js
src/tests/services/edge-application-cache-settings-services/create-cache-settings-service.test.js
src/tests/services/edge-application-cache-settings-services/edit-cache-settings-service.test.js
src/tests/services/edge-application-cache-settings-services/list-cache-settings-service.test.js
src/views/EdgeApplications/TabsView.vue
src/views/EdgeApplicationsCacheSettings/Drawer/index.vue
src/views/EdgeApplicationsCacheSettings/FormFields/FormFieldsEdgeApplicationCacheSettings.vue
src/views/EdgeApplicationsCacheSettings/ListView.vue
src/views/ImportGitHub/ImportStaticView.vue

[UXE-1760]
add Tiered Cache to cache settings
https://github.com/aziontech/azion-console-kit/assets/110847590/41e368cd-75b7-474b-b5f3-3785cb05440e
<hr />
[UXE-1760]: https://aziontech.atlassian.net/browse/UXE-1760?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[UXE-1760] feat: add Tiered Cache to cache settings

---

src/router/hooks/beforeEachRoute.js
src/services/account-settings-services/index.js
src/services/account-settings-services/load-account-job-role-service.js
src/templates/create-modal-block/create-modal-block-loading-state.vue
src/templates/create-modal-block/index.vue
src/templates/create-modal-block/make-create-modal-block.vue
src/templates/navbar-block/create.vue
src/templates/profile-block/index.vue
src/tests/services/account-settings-services/load-account-job-role-service.test.js

⚠️ Note: When additional data for new screens is released, another PR will be introduced to integrate with the currently loaded job role values, avoiding unnecessary hard-coded comparisons for job roles
- When the user clicks the "Create" button in the navbar, this PR loads a recommended template based on the user's job role. For legacy users without a specified job role or users with outdated job role names, the same templates will be presented as those shown to users with a job role of 'other'.
- The job role information will be shared via the account store.
Let me know if you need any further adjustments or have additional information to include!
No Ui changes, only a filtered result based on job role:
<hr />

[UXE-2732] feat: recommend templates by user job role

---

src/templates/signup-block/client-testimonials-block.vue
src/templates/signup-block/form-signup-block.vue
src/views/Signup/SignupView.vue

Adjust style signup page
https://github.com/aziontech/azion-console-kit/assets/92529166/8a944328-03ad-41bf-b806-71cb27a33785
<hr />

[UXE-2339] fix: adjust style signup page

---

src/services/edge-application-rules-engine-services/list-rules-engine-service.js
src/templates/list-table-block/no-header.vue
src/templates/profile-block/index.vue

[UXE-2684] 
fix: default rule must be the first in the list and has no sort icon
https://github.com/aziontech/azion-console-kit/assets/110847590/bd34a2ae-dec5-4f83-bf9f-920bbbca9780
<hr />
[UXE-2684]: https://aziontech.atlassian.net/browse/UXE-2684?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[UXE-2684] fix: default rule must be the first in the list and has no sort icon

---

src/templates/form-fields-inputs/fieldGroupCheckbox.vue
src/templates/form-fields-inputs/fieldGroupRadio.vue
src/templates/form-fields-inputs/fieldGroupSwitch.vue
src/templates/selector-block/index.vue
src/views/Playground/PlaygroundView.vue

Adjust the imports of the selector components in the playground and added css to the scenario when there is a listing with a divider
[Link to Figma](https://www.figma.com/file/y7j6SxH5xXZWQPwRa8igsO/Console-Kit-Blocks?type=design&node-id=87-21912&mode=design&t=QDemL1WwAf3uc9Gy-0) 
<hr />

[UXE-1769] refactor: adjusted imports and css in selectors

---

src/templates/signup-block/login-with-email-block.vue
src/views/Login/LoginView.vue

add trigger event sign up
yes
<hr />

feat: add trigger event sign up

---

src/templates/signup-block/login-with-email-block.vue
src/views/EdgeApplicationsCacheSettings/Drawer/index.vue
src/views/EdgeApplicationsCacheSettings/FormFields/FormFieldsEdgeApplicationCacheSettings.vue

remove url chars from generated full name on signup. Also remove extra spaces generated by cleaning the special chars.
This will avoid the following error:
<hr />

[NO-ISSUE] fix: remove url chars from name signup

---

src/templates/signup-block/form-signup-block.vue
src/views/Signup/SignupView.vue

Adjust view signup
https://www.figma.com/file/GvpnDYOyV6KnK6ib0jYJVw/Dev-Journey?type=design&node-id=281-6993&mode=design&t=k9AGwLu4wWkfwou5-0
<hr />

[UXE-2339] fix: adjust view signup

---

src/views/EdgeFirewall/ListView.vue

Create clicked to create edge firewall event
feat: Create clicked to create edge firewall event
<hr />

[UXE-2609] feat:  Create clicked to create edge firewall event

---

src/templates/form-fields-inputs/fieldDropdown.vue
src/templates/navbar-block/create.vue
src/templates/template-engine-block/index.vue
src/views/ImportGitHub/ImportStaticView.vue

- fix the behavior to  show create journey on mobile devices
- fix the dropdown to add the  multiple Github scopes in template-engine-block.
No
<hr />

[UXE-2792] fix: add option to add more scopes and fix create journey for mobile devices

---

src/views/EdgeApplicationsErrorResponses/FormFields/FormFieldsErrorResponses.vue

[UXE-2752]
fix: changed the height of the dropdown
https://github.com/aziontech/azion-console-kit/assets/110847590/9431288c-b0ab-4fc1-88fa-a2016ea18cc0
<hr />

[UXE-2752] fix: changed the height of the dropdown

---

src/helpers/go-to-classic-interface.js
src/templates/content-block/banner.vue
src/templates/content-block/index.vue

Redirect user to classic interface rtm
https://github.com/aziontech/azion-console-kit/assets/92529166/5bc91fe0-674d-424b-a951-5dc608ecd251
<hr />

[UXE-2790] feat: redirect to classic interface rtm

---

src/views/EdgeApplications/TabsView.vue
src/views/EdgeApplicationsRulesEngine/Drawer/index.vue
src/views/EdgeApplicationsRulesEngine/FormFields/FormFieldsEdgeApplicationsRulesEngine.vue
src/views/EdgeApplicationsRulesEngine/ListView.vue

[UXE-2643]
fix: remove requires application acceleration from description
https://github.com/aziontech/azion-console-kit/assets/110847590/e1739607-0786-4157-9045-ab9f6c2c871d
<hr />
[UXE-2643]: https://aziontech.atlassian.net/browse/UXE-2643?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[UXE-2643] fix: remove requires application acceleration from description

---

src/templates/form-fields-inputs/fieldGroupCheckbox.vue
src/templates/form-fields-inputs/fieldGroupRadio.vue
src/templates/form-fields-inputs/fieldGroupSwitch.vue
src/templates/selector-block/index.vue
src/views/Playground/PlaygroundView.vue

adjust the style and props of the selectors
[Link to Figma](https://www.figma.com/file/y7j6SxH5xXZWQPwRa8igsO/Console-Blocks?type=design&node-id=0-1&mode=design&t=Hxflbk2PgjeQ8iGE-0)
<hr />

[UXE-1769] refactor: adjusted props and design selectores

---

src/helpers/go-to-classic-interface.js
src/views/EdgeApplications/TabsView.vue
src/views/EdgeApplicationsRulesEngine/Drawer/index.vue
src/views/EdgeApplicationsRulesEngine/FormFields/FormFieldsEdgeApplicationsRulesEngine.vue
src/views/EdgeApplicationsRulesEngine/ListView.vue

disable behavior optimize images
https://github.com/aziontech/azion-console-kit/assets/92529166/5c695269-5cfc-48a0-9930-ba3c1d53edbe
<hr />

[UXE-2644] feat: disable behavior optimize images

---

src/templates/profile-block/index.vue

Removed z-index from profileMenu
NO
<hr />

[UXE-1609] fix: removed z-index from profileMenu

---

src/router/routes/create-new-routes/index.js
src/templates/signup-block/client-testimonials-block.vue

- Add  real testimonial text to signup view
No
No
No
<hr />

feat: add client testimonial text to signup view

---

src/views/EdgeApplicationsRulesEngine/FormFields/FormFieldsEdgeApplicationsRulesEngine.vue

Refactor function update options requires in rules engine
<hr />

[NO-ISSUE] refactor: function update options requires in rules engine

---

src/views/Login/LoginView.vue

add track to the signup event to be trigger immediately
<hr />

[NO-ISSUE] feat: add track to the signup event to be trigger immediately

---

src/App.vue
src/helpers/azion-onboarding-window-opener.js
src/helpers/index.js
src/main.js
src/templates/dialogs-block/dialog-onboarding-scheduling.vue
src/tests/helpers/azion-onboarding-window-opener.test.js
src/views/Home/HomeView.vue

created dialog for scheduling onboarding additional data 
<hr />

[UXE-2757] feat: created dialog for scheduling onboarding additional data 

---

src/services/edge-application-rules-engine-services/edit-rules-engine-service.js
src/tests/services/edge-application-rules-engine-services/edit-rules-engine-service.test.js

[UXE-2636] 
fix: rules engine with message problems
https://github.com/aziontech/azion-console-kit/assets/110847590/093abc52-7a4a-4e46-954c-1358b0744109
<hr />
[UXE-2636]: https://aziontech.atlassian.net/browse/UXE-2636?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[UXE-2636] fix: rules engine with message problems

---

src/templates/signup-block/form-signup-block.vue
src/templates/signup-block/login-with-email-block.vue

refactor signup and login process
NO
<hr />

[NO-ISSUE] refactor: refactor signup and login process

---

src/views/RealTimePurge/FormFields/FormFieldsCreateRealTimePurge.vue

[UXE-2753]
fix: tiered cache options purge
https://github.com/aziontech/azion-console-kit/assets/110847590/3373bc8c-fef8-4999-a475-1ba72ce922b4
<hr />
[UXE-2753]: https://aziontech.atlassian.net/browse/UXE-2753?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[UXE-2753] fix: tiered cache options purge

---

src/views/EdgeApplicationsFunctions/FormFields/FormFieldsEdgeApplicationsFunctions.vue
src/views/EdgeFirewallFunctions/FormFields/FormFieldsEdgeApplicationsFunctions.vue

[UXE-1944]
fix: function instance editor is using javascript lint in json-args
https://github.com/aziontech/azion-console-kit/assets/110847590/f27f96bf-8f66-493f-a48f-e1e8e157abea
<hr />
[UXE-1944]: https://aziontech.atlassian.net/browse/UXE-1944?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[UXE-1944] fix: add json language in vue monaco editor

---

src/templates/template-engine-block/index.vue
src/views/Signup/AdditionalDataView.vue

- remove skeleton from additional data
<hr />

[NO-ISSUE] fix: remove skeleton from additional data

---

package.json

Increase project version to deploy from 1.12.0 to 1.13.0
No
No.
No.
<hr />

[NO-ISSUE] chore: upgrade project version from 1.12.0 to 1.13.0

---

src/templates/template-engine-block/index.vue

- avoid to call service of integration for non Github templates.
- clear event listener after template engine block has been unmounted
No
No
No
<hr />

[NO-ISSUE] fix: ensure to call integrations only with github integration field on input schema

---

package.json

improve project version from 1.13.0 to 1.13.1

[NO-ISSUE] chore: improve project version from 1.13.0 to 1.13.1

---

src/views/Login/LoginView.vue

adjusting the triggering of the user activated account event
<hr />

[NO-ISSUE] fix: adjusting the triggering of the user activated account event

---

src/utils/errorHandlingTracker.js
src/views/EdgeApplications/CreateView.vue
src/views/EdgeApplications/EditView.vue
src/views/EdgeApplicationsOrigins/Drawer/index.vue
src/views/EdgeFirewall/CreateView.vue

[UXE-2127]
[UXE-2079]
feat:  failed to create edge firewall tracker and created edge firewall tracker
<hr />
[UXE-2127]: https://aziontech.atlassian.net/browse/UXE-2127?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[UXE-2079]: https://aziontech.atlassian.net/browse/UXE-2079?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[UXE-2127] fix: failed to create edge firewall

---

src/views/EdgeApplicationsCacheSettings/Drawer/index.vue

[UXE-1760]
fix: correcting field validation
https://github.com/aziontech/azion-console-kit/assets/110847590/e174ae22-6835-4433-8eb2-3b7099fff22d
<hr />
[UXE-1760]: https://aziontech.atlassian.net/browse/UXE-1760?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[UXE-1760] fix: add minimum value to input

---

src/templates/profile-block/index.vue

The only way I found to inject CSS was by using inline styling, via the prop itself.
Why did I use inline styling? By default, this component uses "position: absolute". If I globally changed it to "position: fixed", it would impact other use cases of the button, so I dismissed that option. Using "position: absolute" through inline styling gains more importance, even if I have to use "!important" to ensure it takes precedence. Therefore, in this instance of the component, the only option left to me was inline styling, which will have higher priority and allows the use of "position: fixed" at this level. This resolves the issue.
Does this PR intr
https://github.com/aziontech/azion-console-kit/assets/95422158/ead69154-a3b7-415f-b9f2-f8a48fc0c9e3
No, no Figma
<hr />

[UXE-2730] fix: apply fixed position for profile menu

---

src/templates/template-engine-block/index.vue

Adjusting journey github template
1 - The “Repository Name” field should only appear after the integration is done.
2 - Repository is already selected in the dropdown.
3 - The maximum dropdown width is 320px
https://github.com/aziontech/azion-console-kit/assets/92529166/31afb4ae-80cc-4ca9-a356-4774a3889cb1
<hr />

[UXE-2871] fix: adjusting journey github template

---

src/assets/themes/scss/themes/azion-dark/extended-components/_dialog.scss
src/assets/themes/scss/themes/azion-light/extended-components/_dialog.scss
src/templates/create-modal-block/create-modal-block-loading-state.vue
src/templates/create-modal-block/index.vue
src/templates/dialog-unsaved-block/index.vue
src/templates/dialogs-block/dialog-onboarding-scheduling.vue
src/templates/list-table-block/dialog/delete-dialog.vue
src/templates/navbar-block/create.vue

Apply classes for better responsive behavior of dialogs, also removes redundant classes in the main console dialogs: Unsaved Changes, Create, Schedule Onboarding Session, Delete Dialog.
https://github.com/aziontech/azion-console-kit/assets/95422158/f7961f46-9a54-47c9-a8ef-7ccad5ef1d92
No Figma
<hr />

[NO-ISSUE] fix: responsive dialogs

---

package.json
src/views/ImportGitHub/ImportGithubView.vue

improve project version to 1.14.1
No
No
No
<hr />

[NO-ISSUE] chore: improve project version from 1.14.0 to 1.14.1

---

src/views/EdgeApplicationsRulesEngine/FormFields/FormFieldsEdgeApplicationsRulesEngine.vue

fix: requires delivery protocol with https
https://github.com/aziontech/azion-console-kit/assets/110847590/61266b1c-2fbd-4c77-9080-61d44f23ba88
<hr />

[UXE-2855] fix: requires delivery protocol with https

---

src/views/CreateNew/DeployView.vue

[UXE-2886] 
fix: add redirect to real time metrics
https://github.com/aziontech/azion-console-kit/assets/110847590/0fed51b2-1403-4635-a8ca-65aa86b078a6
<hr />
[UXE-2886]: https://aziontech.atlassian.net/browse/UXE-2886?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[UXE-2886] fix: add redirect to real time metrics

---

src/services/signup-services/update-account-info-service.js
src/templates/signup-block/additional-data-form-block.vue
src/tests/services/signup-services/update-account-info-service.test.js

- Ensure to update job role after additional data has been submitted 
No
No
No
<hr />

[NO-ISSUE] fix: ensure to update account job role after additional data submitted

---

src/templates/sign-in-block/index.vue

Reset the loading state on login mount when rejecting social login
No
No
<hr />

[UXE-2774] fix: reset loading state on login mount

---

package.json

- improve project version from 1.14.2 to 1.14.3
<hr />

[NO-ISSUE] chore: improve project version from 1.14.2 to 1.14.3

---

src/services/vulcan-services/list-vulcan-presets-service.js
src/tests/services/vulcan-services/list-vulcan-presets-service.test.js
src/views/ImportGitHub/FormFields/FormFieldsImportGithub.vue
src/views/ImportGitHub/ImportGithubView.vue

* added root directory env to template engine
* added some regex to invalid root
* remove vite option from vulcan presets
<hr />

[NO-ISSUE] feat: added root directory env to template engine and added some regex to invalid paths

---

src/templates/create-modal-block/index.vue

* removed static name of import github template card
<hr />

[NO-ISSUE] refactor: removed static name of import github template card

---

src/views/EdgeApplications/FormFields/FormFieldsCreateEdgeApplications.vue

* default value of tls version on change the delivery protocol in main settings (edge application)
<hr />

[NO-ISSUE] fix: default value of tls version on change the delivery protocol

---

src/templates/create-form-block/form-horizontal.vue
src/views/CreateNew/DeployView.vue
src/views/ImportGitHub/FormFields/FormFieldsImportGithub.vue

- add azion link to fork projects and help user to get valid projects for the import from github journey.
- add slot description to form horizontal block 
https://github.com/aziontech/azion-console-kit/assets/101186721/290d08b7-3561-4ba1-9178-36ace92942a8
No.
<hr />

[NO-ISSUE] feat: add azion samples link to fork at GitHub form

---

package.json

improve project version from 1.14.3 to 1.14.4

chore: improve project version from 1.14.3 to 1.14.4

---

src/templates/signup-block/additional-data-form-block.vue

- Send user to home view even on request error in additional data
No
No
<hr />

[NO-ISSUE] fix: send user to home view even on request error

---

src/views/EdgeFirewallRulesEngine/FormFields/FormFieldsEdgeFirewallRulesEngine.vue

[UXE-2432]
fix: remove tag event on the edge firewall
https://github.com/aziontech/azion-console-kit/assets/110847590/c2f47375-7c81-44b0-b2a8-7bc307c98054
<hr />
[UXE-2432]: https://aziontech.atlassian.net/browse/UXE-2432?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[UXE-2432] fix: remove tag event on the edge firewall

---

src/services/edge-dns-records-services/list-records-service.js
src/tests/services/edge-dns-records-services/list-records-service.test.js
src/views/EdgeDNS/EditView.vue

[UXE-2537] 
fix: displaying the list of entries in idns records
https://github.com/aziontech/azion-console-kit/assets/110847590/7c43ffcb-b21f-4e06-81a2-a577605810c9
<hr />
[UXE-2537]: https://aziontech.atlassian.net/browse/UXE-2537?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[UXE-2537] fix: displaying the list of entries in idns records

---

src/templates/help-center-block/index.vue

In help center menu remove the changelogs hyperlink and add release notes.
<hr />

[UXE-2539] refactor: remove changelogs from help center and add release notes hyperlink

---

src/views/Signup/AdditionalDataView.vue
src/views/Signup/SignupView.vue

adjust breakpont signup and additional data
https://github.com/aziontech/azion-console-kit/assets/92529166/2c8438c7-d69d-40df-862d-4049836c152d
<hr />

[UXE-2879] fix: adjust breakpont signup and additional data

---

src/templates/help-center-block/index.vue

Change the way release notes option on help center menu is written (descaptalize first letter)
<hr />

[UXE-2539] fix: remove typo from release notes menu

---

src/templates/help-center-block/index.vue

Remove typo in help center menu AGAIN, it was supposed to be release notes and i merged it as realease note
<hr />

[NO-ISSUE] fix: remove typo in release notes

---

src/router/routes/import-github-routes/index.js

Change import from git hub page breadcrumb hyperlink
<hr />

[UXE-2904] fix: change import from github page breadcumb hyperlink

---

src/views/EdgeDNS/FormFields/FormFieldsRecords.vue

* removed wrong text in form fields records
<hr />

[NO-ISSUE] fix: remove wrong text in form fields records

---

package.json

[NO-ISSUE] chore: Bump version from 1.14.4 to 1.14.5

---

package.json

[NO-ISSUE] chore: Bump from 1.14.5 to 1.15.0

---

src/templates/template-engine-block/oauth-github.vue

* github connection popup size changed to fullscreen
https://github.com/aziontech/azion-console-kit/assets/109550332/5e8633e3-b7a6-4a9c-b959-32f1512f6837
<hr />

[UXE-2925] refactor: github connection popup changed to fullscreen

---

src/views/EdgeApplications/FormFields/FormFieldsCreateEdgeApplications.vue
src/views/RealTimeEvents/FormFields/FormFieldsCreateEdgeApplications.vue

- Add a helper text for the "Type" field in the "Default Origin" section. 
n/a.
<hr />
- [x ] Commits are tagged with the right word (fix, feat, test, etc)

[UXE-1600] chore: add helper for origin type

---

src/services/waf-rules-services/create-waf-rules-allowed-tuning-service.js
src/tests/services/waf-rules-services/create-waf-rules-allowed-tuning-service.test.js
src/views/WafRules/ListWafRulesTuning.vue

[UXE-2818]
fix: match zone is path does not work
https://github.com/aziontech/azion-console-kit/assets/110847590/a6cfa2f9-6565-4f3d-8e22-6d6cf70d5e69
<hr />
[UXE-2818]: https://aziontech.atlassian.net/browse/UXE-2818?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[UXE-2818] fix: match zone is path does not work

---

src/services/real-time-purge/create-real-time-purge-service.js
src/tests/services/real-time-purge/create-real-time-purge.test.js
src/views/RealTimePurge/ListView.vue

add message purge is execution queue
<hr />

[UXE-2498] feat: add message purge is execution queue

---

src/services/version-control-system-integration-services/list-repositories-service.js
src/tests/services/version-control-system-integration-services/list-repositories-service.test.js

* added default ordering by name in list vcs repositories service
* test updated
<hr />

[UXE-3131] feat: added default ordering by name in list vcs repositories service

---

src/assets/themes/scss/themes/azion-dark/extended-components/_inlinemessage.scss
src/assets/themes/scss/themes/azion-light/extended-components/_inlinemessage.scss
src/views/Playground/PlaygroundView.vue

Improve text styles, spacing and responsive behavior for InlineMessages
https://github.com/aziontech/azion-console-kit/assets/95422158/3610a6e7-c702-49e0-b256-972b1458654d
https://www.figma.com/file/2hNLUK00QbkDeQSYSC6DDW/PrimeOne-%5B2.0.0%5D-%5BVue%5D?type=design&node-id=393%3A38871&mode=design&t=21o2lkmqCyoaCn4n-1
<hr />

[UXE-3133] Theming: Improve text style, spacing and responsive behavior for inline messages

---

src/views/ImportGitHub/FormFields/FormFieldsImportGithub.vue
src/views/ImportGitHub/ImportGithubView.vue

updating name and label of the edge application name field to application name
https://github.com/aziontech/azion-console-kit/assets/92529166/86932860-c0cd-4cd7-965c-aae92080a98b
<hr />

[UXE-3112] feat: updating name and label of the edge application name

---

src/services/real-time-purge/create-real-time-purge-service.js
src/tests/services/real-time-purge/create-real-time-purge.test.js

add new description to create real time purge
<hr />

feat: add new description to create real time purge

---

src/services/version-control-system-integration-services/list-integrations-service.js
src/tests/services/real-time-purge/create-real-time-purge.test.js
src/tests/services/version-control-system-integration-services/list-integrations-service.test.js

[UXE-2937]
fix: allow more than 30 scopes
https://github.com/aziontech/azion-console-kit/assets/110847590/725e3f1f-d9c3-4124-98ff-46ae787cc071
<hr />
[UXE-2937]: https://aziontech.atlassian.net/browse/UXE-2937?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[UXE-2937] fix: allow more than 30 scopes

---

src/views/CreateNew/DeployView.vue

Change deploy timer to show time in minutes and seconds in format 1m20s
<hr />

[UXE-2930] refactor: change timer to show time in minutes and seconds

---

package.json

upgrade project version from 1.15.0 to 1.15.1
<hr />

[NO-ISSUE] chore: upgrade project version from 1.15.0 to 1.15.1

---

src/templates/script-runner-block/index.vue
src/tests/services/script-runner-services/get-script-runner-logs-service.test.js
src/views/CreateNew/DeployView.vue

* check to ensure polling is performed one at a time
* removed wrong key string in deploy timer
* set interval 3000 to 7000
<hr />

[UXE-2935] refactor: added a check to ensure polling is performed one at a time

---

src/views/ImportGitHub/ImportGithubView.vue

* remove unnecessary variables of import from github instantiate
<hr />

[UXE-3114] fix: remove unnecessary variables of import from github instantiate

---

package.json

upgrade project version from 1.15.1 to 1.15.2

chore: upgrade project version from 1.15.1 to 1.15.2

---

src/views/CreateNew/DeployView.vue

- Add new message to fail text on deploy view
new message: 'There was an issue during the deployment. Check the Deploy Log for more details.'
<hr />

[NO-ISSUE] chore: change fail message text for deploy at DeployView

---

src/views/EdgeFirewallRulesEngine/FormFields/FormFieldsEdgeFirewallRulesEngine.vue
src/views/ImportGitHub/FormFields/FormFieldsImportGithub.vue
src/views/Variables/FormFields/FormFieldsVariables.vue

* conditional fixed network list request in rules engine edge firewall
* filter added to networks dropdown
* cleaned criteria value in variable change
<hr />

[UXE-2807] fix: network list too many requests in rules engine edge firewall

---

src/templates/form-fields-inputs/fieldGroupRadio.vue
src/templates/form-fields-inputs/fieldRadioBlock.vue
src/templates/form-fields-inputs/fieldSwitchBlock.vue
src/templates/selector-block/index.vue
src/templates/signup-block/additional-data-form-block.vue

Replace default components with custom blocks in additional data
No visible changes
No
<hr />

[UXE-2877] refactor: replace old selectors with new ones in additional data

---

src/views/EdgeFirewall/EditView.vue

[UXE-2083]
feat: add event tracker failed edit edge firewall
<hr />
[UXE-2083]: https://aziontech.atlassian.net/browse/UXE-2083?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[UXE-2083] feat: add event tracker failed edit edge firewall

---

src/templates/create-drawer-block/index.vue
src/templates/create-form-block/index.vue
src/templates/create-modal-block/index.vue
src/templates/edit-drawer-block/index.vue
src/templates/edit-form-block/index.vue
src/templates/edit-form-block/no-header.vue
src/templates/signup-block/account-activation.vue
src/templates/signup-block/additional-data-form-block.vue
src/tests/services/script-runner-services/get-script-runner-logs-service.test.js
src/utils/constants.js
src/views/AccountSettings/FormFields/FormFieldsAccountSettings.vue
src/views/Domains/CreateView.vue
src/views/EdgeApplicationsOrigins/Drawer/index.vue
src/views/RealTimeEventsTieredCache/Drawer/index.vue
src/views/WafRules/Drawer/index.vue

[UXE-1392]
fix: add seconds for the toast to disappear
https://github.com/aziontech/azion-console-kit/assets/110847590/88056aa6-f042-4435-9b7f-e97b119c94a8
<hr />
[UXE-1392]: https://aziontech.atlassian.net/browse/UXE-1392?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[UXE-1392] fix: add seconds for the toast to disappear

---

src/services/real-time-events-service/activity-history/list-activity-history.js
src/services/real-time-events-service/data-stream/list-data-stream.js
src/services/real-time-events-service/edge-dns/list-edge-dns.js
src/services/real-time-events-service/edge-functions-console/list-edge-functions-console.js
src/services/real-time-events-service/edge-functions/list-edge-functions.js
src/services/real-time-events-service/http-request/list-http-request.js
src/services/real-time-events-service/image-processor/list-image-processor.js
src/services/real-time-events-service/tiered-cache/list-tiered-cache.js
src/tests/services/real-time-events-service/activity-history/list-activity-history.test.js
src/tests/services/real-time-events-service/data-stream/list-data-stream.test.js
src/tests/services/real-time-events-service/edge-dns/list-edge-dns.test.js
src/tests/services/real-time-events-service/edge-functions-console/list-edge-functions-console.test.js
src/tests/services/real-time-events-service/edge-functions/list-edge-functions.test.js
src/tests/services/real-time-events-service/http-request/list-http-request.test.js
src/tests/services/real-time-events-service/image-processor/list-image-processor.test.js
src/tests/services/real-time-events-service/tiered-cache/list-tiered-cache.test.js
src/views/RealTimeEventsActivityHistory/ListView.vue
src/views/RealTimeEventsDataStream/ListView.vue
src/views/RealTimeEventsEdgeDNS/ListView.vue
src/views/RealTimeEventsEdgeFunctions/ListView.vue
src/views/RealTimeEventsEdgeFunctionsConsole/ListView.vue
src/views/RealTimeEventsHTTPRequests/ListView.vue
src/views/RealTimeEventsImageProcessor/ListView.vue
src/views/RealTimeEventsTieredCache/ListView.vue

Adjust the columns of the realtime events view tables
[Link to Figma](https://www.figma.com/design/0TY2pcUTBsndMlrs0ZUvQf/Console-UI?node-id=13288-15907&t=NnrvId78yuYEAdbp-0)
<hr />

[UXE-2009] refactore: Adjust the columns of the realtime events view tables

---

src/modules/real-time-metrics/filters/extract-filters-and-variables.js
src/views/CreateNew/DeployView.vue

request time filter with between operator breaks the query
<hr />

[UXE-2891] fix: request time filter with between operator breaks the query

---

package.json

updated project version from 1.15.2 to  1.15.3

chore: updated version package json from 1.15.2 to 1.15.3

---

src/views/DataStream/FormFields/FormFieldsDataStream.vue

* data stream selectors changed to new blocks
* Radio
* Switch
https://www.figma.com/design/0TY2pcUTBsndMlrs0ZUvQf/Console-UI?node-id=10658-140794&t=cmQKabmM34A8OhnE-0
<hr />

[UXE-3234] refactor: data stream selectors switch and radio changed to new blocks

---

src/plugins/analytics/AnalyticsTrackerAdapter.js
src/views/EdgeFunctions/ListView.vue

Add clicked to create and clicked to edit event trackers to edge functions
<hr />

[UXE-2084] feat: add clicked to create and clicked to edit functions event

---

src/services/domains-services/load-domain-service.js
src/tests/services/domains-services/load-domain-service.test.js
src/views/Domains/FormFields/FormFieldsCreateDomains.vue
src/views/Domains/FormFields/FormFieldsEditDomains.vue

* domain selectors changed to new blocks (Edit and Create)
* Radio
* Switch
* bug where mtls_enabled key was incorrect in load service
[Link to Figma](https://www.figma.com/design/0TY2pcUTBsndMlrs0ZUvQf/Console-UI?node-id=10635-45389&t=nH0s5eLy1GvDX7wn-0)
<hr />

[UXE-3251] refactor: domains selectors radio and switch changed to new blocks

---

src/views/DigitalCertificates/CreateView.vue
src/views/DigitalCertificates/FormFields/FormFieldsCreateDigitalCertificates.vue

* data stream selectors changed to new blocks
* Radio
* added require field to SAN
[Link to Figma](https://www.figma.com/design/0TY2pcUTBsndMlrs0ZUvQf/Console-UI?node-id=10635-45389&t=nH0s5eLy1GvDX7wn-0)
<hr />

[UXE-3250] refactor: digital certificate selectors radio changed to new blocks

---

src/services/real-time-purge/create-real-time-purge-service.js
src/services/real-time-purge/list-real-time-purge-service.js
src/tests/services/real-time-purge/list-real-time-purge.test.js
src/views/EdgeFunctions/ListView.vue
src/views/RealTimePurge/Dialog/index.vue

[UXE-2342]
feat: pending action reappears
https://github.com/aziontech/azion-console-kit/assets/110847590/da546265-8352-476c-a1e3-1c62a9a29b99
<hr />
[UXE-2342]: https://aziontech.atlassian.net/browse/UXE-2342?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[UXE-2342] feat: pending action reappears

---

src/templates/create-drawer-block/index.vue
src/templates/edit-drawer-block/index.vue
src/templates/info-drawer-block/index.vue
src/templates/navbar-block/create.vue
src/templates/navbar-block/feedback-fish.vue
src/views/CreateNew/CreateView.vue
src/views/CreateNew/DeployView.vue
src/views/EdgeFunctions/components/mobile-code-preview.vue
src/views/Marketplace/drawer/CreateEdgeApplication.vue
src/views/Marketplace/drawer/IntegrationInstall.vue
src/views/WafRules/Drawer/index.vue

add the feedbackfish button from the drawers to the header.
<hr />

[UXE-2541] feat: add the feedbackfish button from the drawers to the header.

---

src/helpers/azion-documentation-catalog.js
src/tests/helpers/azion-documentation-catalog-product-guide.test.js
src/views/EdgeDNS/FormFields/FormFieldsRecords.vue

- Add dynamic tip text to value field based on the selected record type
- Add window opener to documentation
- Add dynamic placeholders for value field
- Create tests for documentation catalog
https://github.com/aziontech/azion-console-kit/assets/95643165/c386ed23-cc75-4507-b185-2e6670375740
No
<hr />

[UXE-3188] refactor: change description for settings and add tip to name field

---

src/templates/create-modal-block/index.vue
src/views/EdgeFunctions/CreateView.vue
src/views/EdgeFunctions/ListView.vue

Add created function event to tracker
<hr />

[UXE-2130] feat: add created function tracker

---

src/views/RealTimeMetrics/blocks/content-filter-block.vue

Reset filter before updating them to clean old state
https://github.com/aziontech/azion-console-kit/assets/95643165/38b7bfaa-dcd5-490b-98f2-8ef4033571c3
No
<hr />

[UXE-2888] fix: reset filters before update

---

src/views/EdgeDNS/FormFields/FormFieldsRecords.vue

Adjust simple grammar mistake in edge DNS record description
No
<hr />

[NO-ISSUE] refactor: update text in settings description in edgeDns

---

src/templates/advanced-filter/component/display/chips-default-display.vue
src/templates/advanced-filter/component/fields/text-filter.vue
src/templates/advanced-filter/dialog-filter.vue

- Update filter to handle zero values, so empty strings and 0 are not replaced by default object.
- Create formatter to display empty string in chips
- Remove unnecessary `*` where value is optional
No
<hr />

[UXE-2890] fix: resolve zero value causing bad request

---

src/views/EdgeFirewall/EditView.vue
src/views/EdgeFirewallFunctions/Drawer/index.vue
src/views/EdgeFirewallRulesEngine/Drawer/index.vue

add tracker event in rules and functions in edge firewall
https://github.com/aziontech/azion-console-kit/assets/110847590/00ab3e53-d9d2-41fe-8a1e-9373685682d0
<hr />

[UXE-2129] feat: add tracker event in rules and functions in edge firewall

---

src/views/RealTimePurge/Dialog/index.vue

refactor: change text color and the spaces
<hr />

[UXE-2342] refactor: change text color and the spaces in Realtime Purge Dialog

---

src/views/EdgeFirewall/FormFields/FormFieldsEdgeFirewall.vue

adjustment max size component pick list
<hr />

[UXE-2934] fix: adjustment max size component pick list

---

src/views/EdgeApplicationsOrigins/FormFields/FormFieldsEdgeApplicationsOrigins.vue

* edge app origins drawer selectors radio and switch changed to new blocks
* Radio
* Switch
[Link to Figma](https://www.figma.com/design/0TY2pcUTBsndMlrs0ZUvQf/Console-UI?node-id=10635-45389&t=nH0s5eLy1GvDX7wn-0)
<hr />

[UXE-3297] refactor: edge app origins drawer selectors radio and switch changed to new blocks

---

.github/PULL_REQUEST_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE/bug.md
.github/PULL_REQUEST_TEMPLATE/default.md
.github/PULL_REQUEST_TEMPLATE/deploy.md

Create new templates for pull requests
No
No
<hr />

[UXE-3321] doc: create pr templates

---

src/views/CreateNew/DeployView.vue
src/views/PersonalTokens/CreateView.vue
src/views/PersonalTokens/Dialog/CopyTokenDialog.vue
src/views/PersonalTokens/FormFields/FormFieldsPersonalToken.vue

improvement in the confirmation dialog display for personal token creation.
[figma](https://www.figma.com/proto/0TY2pcUTBsndMlrs0ZUvQf/Console-UI?page-id=6084%3A152129&type=design&node-id=6084-152131&viewport=4%2C511%2C0.22&t=yiG84UQeriO8I1IM-8&scaling=min-zoom&starting-point-node-id=6084%3A152131&show-proto-sidebar=1&hide-ui=1)
<hr />

[UXE-2279] feat: improvement in the confirmation dialog display for personal token creation.

---

src/services/edge-functions-services/edit-edge-functions-service.js
src/views/EdgeFunctions/EditView.vue

Add edited and failed to edit edge functions events to tracker
<hr />

[UXE-2088] feat: add edited edge functions event tracker

---

src/services/edge-functions-services/create-edge-functions-service.js
src/views/EdgeFunctions/CreateView.vue

Add failed to create edge function event to tracker
<hr />

[UXE-2131] feat: add failed to create function event to tracker

---

src/services/edge-functions-services/edit-edge-functions-service.js
src/templates/list-table-block/index.vue
src/templates/list-table-block/no-header.vue
src/views/EdgeFunctions/EditView.vue

[UXE-3315]
add life in toast in reorder request
https://github.com/aziontech/azion-console-kit/assets/110847590/8ff881e8-974f-4e09-949e-49928655ba9c
<hr />
[UXE-3315]: https://aziontech.atlassian.net/browse/UXE-3315?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[UXE-3315] refactor: add life in toast in reorder request

---

src/views/Domains/CreateView.vue
src/views/Domains/EditView.vue
src/views/Domains/ListView.vue

[UXE-2093]
domains create clicked event to edit domain
<hr />
[UXE-2093]: https://aziontech.atlassian.net/browse/UXE-2093?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[UXE-2093] feat:  domains create clicked event to edit domain

---

src/services/data-stream-services/create-data-stream-service.js
src/services/data-stream-services/edit-data-stream-service.js
src/services/data-stream-services/list-data-stream-service.js
src/services/data-stream-services/list-data-stream-template-service.js
src/services/data-stream-services/load-data-stream-service.js
src/tests/services/data-stream-services/create-data-stream-service.test.js
src/tests/services/data-stream-services/edit-data-stream-service.test.js
src/views/DataStream/FormFields/FormFieldsDataStream.vue

Adding custom template option for data stream.
https://github.com/aziontech/azion-console-kit/assets/92529166/d4d8d1bc-ea42-4bd9-82dc-1e7a6a62811e
<hr />

[UXE-2927] fix: adding custom template option for data stream

---

src/templates/create-form-block/form-horizontal.vue
src/templates/form-fields-inputs/fieldGroupRadio.vue
src/views/DataStream/FormFields/FormFieldsDataStream.vue
src/views/RealTimePurge/FormFields/FormFieldsCreateRealTimePurge.vue

* removed overflow-auto from form-horizontal because it is breaking the radio cards and its not causing any changes to the forms in question
* new radio selectors in create time purge
[FIGMA LINK](https://www.figma.com/design/0TY2pcUTBsndMlrs0ZUvQf/Console-UI?node-id=10658-173358&t=JrILk34uKxTSYUE6-0)
<hr />

[UXE-3299] refactor: real time purge radios selectors changed to new blocks

---

src/services/domains-services/create-domain-service.js
src/tests/services/domains-services/create-domain-service.test.js
src/views/Domains/CreateView.vue

The "Failed to Create Domain" tracker event was created and the error return from the domain creation service was adjusted, tests were also added to adjust the service.
NO
<hr />

[UXE-2134] feat: add event track failed to create domain

---

src/templates/form-fields-inputs/fieldSwitchBlock.vue
src/tests/services/data-stream-services/create-data-stream-service.test.js
src/tests/services/data-stream-services/edit-data-stream-service.test.js
src/views/EdgeApplications/FormFields/FormFieldsCreateEdgeApplications.vue
src/views/EdgeServices/FormFields/FormFieldsDrawerResource.vue
src/views/Home/HomeView.vue

When user fill all invite your team form fields with valid data, the submit button should be enable. When user forgot or not fill all required data, the button should stay disabled.
No.
<hr />

[NO-ISSUE] fix: invite your team home page

---

src/views/Domains/CreateView.vue
src/views/Domains/EditView.vue
src/views/Domains/ListView.vue

refactor: rename Domains to Domain in tracker event
<hr />

refactor: rename Domains to Domain in tracker event

---

package.json
src/views/Domains/CreateView.vue

- Upgrade project version from 1.15.3 to 1.15.4.
No
No
<hr />

[NO-ISSUE] chore: improve project version from 1.15.3 to 1.15.4

---

src/templates/form-fields-inputs/fieldDropdown.vue
src/views/Domains/CreateView.vue

Add autoFilterFocus prop in fieldDropdown block and bind it to filter prop to reduce clicks from user
https://github.com/aziontech/azion-console-kit/assets/95643165/39280cac-245d-4e23-8d22-1ca76b60dac6
No
<hr />

[UXE-3244] feat: set autofocus in repository search

---

src/views/Variables/CreateView.vue
src/views/Variables/EditView.vue

Added regex to yup validation to key field in variables to validate new rule defined by the issue
https://github.com/aziontech/azion-console-kit/assets/95643165/900cdea6-2782-4412-8c22-5eadef310065
<hr />

[UXE-3246] fix: add regex validation to key field in variables form

---

src/helpers/index.js
src/helpers/remove-html-tag-from-text.js
src/tests/helpers/remove-html-tags-from-text.test.js
src/views/Home/HomeView.vue

Update card section title to include Edge into product naming.
Also remove regex with Redos issue from Home page. 
Manage Applications -> Manage Edge Applications
<hr />

[UXE-1951] fix: home card section title to mach correct Azion product naming

---

src/views/ImportGitHub/FormFields/FormFieldsImportGithub.vue

add autoFilterFocus to framework preset dropdown in view import-github
NO
<hr />

[UXE-3244] feat: add autofilterfocus to dropdown in import github

---

src/templates/form-fields-inputs/fieldDropdown.vue
src/views/EdgeServices/FormFields/FormFieldsDrawerResource.vue

This commit updates the UI by replacing the type radio group with a dropdown menu in Edge Services > Resources.
https://github.com/aziontech/azion-console-kit/assets/109550332/ec6c007d-6d92-4ad6-a42e-7353f417f07a
[FIGMA LINK](https://www.figma.com/design/0TY2pcUTBsndMlrs0ZUvQf/Console-UI?node-id=10635-45389&t=YevmZ64qtHeN6ufO-0)
<hr />

[UXE-3363] refactor: change edge services resources type radio group to dropdown

---

src/services/solutions-services/index.js
src/services/solutions-services/list-solutions-service.js
src/services/solutions-services/make-solutions-base-url.js
src/templates/create-modal-block/index.vue
src/templates/create-modal-block/make-create-modal-block.vue
src/templates/navbar-block/create.vue
src/tests/services/solutions-services/list-solutions-service.test.js

Create search input to find solutions by several keys as name, id, updated at, etc.
Add query params to each solutions api call to improve edge caching
**Fix: resolve issue with `/solutions` being called twice
https://github.com/aziontech/azion-console-kit/assets/95643165/9bd296fa-3e8d-404d-bd96-dfd3315443eb
https://www.figma.com/design/0TY2pcUTBsndMlrs0ZUvQf/Console-UI?node-id=13433-59961&t=EfJwLnAEnE156dZQ-0
<hr />

[UXE-3113] feat: add search filter create modal

---

src/templates/create-modal-block/index.vue
src/templates/form-fields-inputs/fieldGroupRadio.vue

Remove search field from `Import from Github` tab
** Extra refactoring to variable accesses and names
https://www.figma.com/design/0TY2pcUTBsndMlrs0ZUvQf/Console-UI?node-id=6520-2&t=b7DwxxOp34myQrQv-0
<hr />

[UXE-3113] refactor: remove search field from import from github tab

---

package.json

New project version, from 1.15.4 to 1.15.5
No.
No.
<hr />

[NO-ISSUE] chore: upgrade project version from 1.15.4 to 1.15.5

---

package.json

Improve project version from 1.15.5 to 1.15.6
No
No
<hr />

[NO-ISSUE] chore: upgrade project version from 1.15.5 to 1.15.6

---

package.json
src/templates/create-modal-block/index.vue
src/templates/form-fields-inputs/fieldGroupRadio.vue
src/templates/info-drawer-block/info-labels/big-number.vue
src/views/WafRules/Drawer/index.vue

- **Onboarding fix**: Set  default onboarding header filter to list correct solutions templates at onboarding.
<hr />

DEPLOY 2024.06.05

---

src/services/personal-tokens-services/create-personal-tokens-service.js
src/tests/services/personal-tokens-services/create-personal-tokens-service.test.js
src/views/PersonalTokens/Dialog/CopyTokenDialog.vue

<hr />
- [x ] Tags are added to the PR

[EDU-4692] chore: review content in Personal Token modal

---

src/templates/form-fields-inputs/fieldDropdown.vue
src/views/EdgeServices/FormFields/FormFieldsDrawerResource.vue

* removed wrong div in fieldDropdown input block
<hr />

[UXE-3468] fix: remove div classes in field dropdown input block

---

src/views/EdgeApplications/CreateView.vue
src/views/EdgeApplications/EditView.vue
src/views/EdgeApplications/FormFields/FormFieldsCreateEdgeApplications.vue
src/views/PersonalTokens/Dialog/CopyTokenDialog.vue

fix: added validation to http and https inputs in edge application
https://github.com/aziontech/azion-console-kit/assets/110847590/6e2eabd4-b457-4fbc-a243-99bfd5d39a96
<hr />

[UXE-3355] fix: added validation to http and https inputs in edge application

---

package.json

Improve project version from 1.15.6 to 1.15.7
NO
NO
<hr />

[NO-ISSUE] chore: upgrade project version from 1.15.6 to 1.15.7

---

src/templates/advanced-filter/dialog-filter.vue
src/templates/advanced-filter/index.vue
src/views/RealTimeMetrics/RealTimeMetricsView.vue
src/views/RealTimeMetrics/blocks/content-filter-block.vue

Change +Filter button size in mobile and the divs and gaps of the filter area
<hr />

[UXE-2398] fix: change sizes of filter area in real time metrics

---

src/views/EdgeApplicationsRulesEngine/FormFields/FormFieldsEdgeApplicationsRulesEngine.vue

* phase options is now showing in rules engine create
<hr />

[NO-ISSUE] fix: phase options showing in rules engine create

---

src/views/AccountSettings/FormFields/FormFieldsAccountSettings.vue
src/views/EdgeApplicationsFunctions/FormFields/FormFieldsEdgeApplicationsFunctions.vue
src/views/EdgeFirewallFunctions/FormFields/FormFieldsEdgeApplicationsFunctions.vue
src/views/EdgeNode/FormFields/FormFieldsDrawerService.vue
src/views/Marketplace/drawer/IntegrationInstall.vue
src/views/Users/FormsFields/FormFieldsUsers.vue
src/views/WafRules/ListWafRulesTuning.vue
src/views/YourSettings/FormFields/FormFieldsYourSettings.vue

Add property `autoFilterFocus` to dropdowns with filter
No
No
<hr />

[UXE-3391] feat: add auto focus to dropdowns with filter

---

package.json

upgrade project version from 1.15.7 to 1.15.8
no
no
<hr />

[NO-ISSUE] chore: upgrade project version from 1.15.7 to 1.15.8

---

src/templates/profile-block/index.vue

The account menu gets lost in the anchoring and appears incorrectly after scrolling the screen, a vertical positioning value was added next to the style so that it stays fixed at that point on the screen, I tested via passthrough and class and it didn't work. returned the expected behavior, just via style.
https://github.com/aziontech/azion-console-kit/assets/44036260/c5c1cb57-71ec-40ac-9155-2e792823a537
<hr />

[UXE-3328] bug: profile menu position

---

src/views/EdgeApplications/FormFields/FormFieldsCreateEdgeApplications.vue
src/views/EdgeNode/FormFields/FormFieldsEdgeNode.vue
src/views/NetworkLists/FormFields/FormFieldsCreateNetworkLists.vue
src/views/NetworkLists/FormFields/FormFieldsEditNetworkLists.vue
src/views/Users/CreateView.vue
src/views/Users/EditView.vue
src/views/Users/FormsFields/FormFieldsUsers.vue

Added validation to Users form to force a team selection when user is not account owner. 
** Included in this PR: add autoFilterFocus to multiselect fields with filter - continuation of UXE-3244
https://github.com/aziontech/azion-console-kit/assets/95643165/77f96e47-66ca-4215-92e7-ed9cdde3cf41
<hr />

[UXE-3314] fix: update validation in users form

---

src/services/users-services/load-another-user-service.js
src/services/users-services/load-user-service.js
src/views/Users/FormsFields/FormFieldsUsers.vue
src/views/YourSettings/FormFields/FormFieldsYourSettings.vue

fixed early validation in the PhoneNumber fields in Your Settings and Users
<hr />

[UXE-3324] fix: fixed early validation in the PhoneNumber fields in Your Settings and Users

---

src/views/Home/FormFields/FormFieldsHome.vue
src/views/Home/HomeView.vue

add validation to field full name and change o name do field to full name
https://github.com/aziontech/azion-console-kit/assets/92529166/a89d1ecd-a2de-4720-aa53-81ade40c373f
<hr />

[UXE-3326] add validation to field full name and change o name do field to full name"

---

src/views/DigitalCertificates/FormFields/FormFieldsCreateDigitalCertificates.vue

Change label for Trusted CA certificate field
No.
<hr />

[UXE-3460] fix: update label of import a Trusted CA certificate field

---

src/views/DigitalCertificates/FormFields/FormFieldsCreateDigitalCertificates.vue

Fix typo in a label of an create digital certificate field.
No.
<hr />

[UXE-3459] fix: typo in subtitle of an create digital certificates field

---

src/services/data-stream-services/create-data-stream-service.js
src/services/data-stream-services/edit-data-stream-service.js

Adjust methods that handle error message to work with any key sent by API
https://github.com/aziontech/azion-console-kit/assets/95643165/cd9af40c-618e-48fc-a00f-e682bb6c36c5
<hr />

[UXE-3589] fix: adjust extractApiError method to handle any key

---

.github/workflows/assign-pr.yml
.github/workflows/e2e-tests.yml

- Fix workflows file to use correct command to generate coverage report.
- Add better naming to workflows run that auto assign author PR name to the PR.
NO
<hr />

[NO-ISSUE] fix: workflow e2e test running step

---

src/services/edge-firewall-services/load-edge-firewall-service.js
src/tests/services/edge-firewall-services/load-edge-firewall-service.test.js
src/views/EdgeFirewall/CreateView.vue
src/views/EdgeFirewall/FormFields/FormFieldsEdgeFirewall.vue
src/views/EdgeFirewallRulesEngine/FormFields/FormFieldsEdgeFirewallRulesEngine.vue

feat: edge firewall change to new selectors
https://github.com/aziontech/azion-console-kit/assets/110847590/55f94dd5-23e3-4f85-8156-d8eff6b49717
<hr />

[UXE-3580] feat: edge firewall change to new selectors

---

src/views/Domains/FormFields/FormFieldsCreateDomains.vue
src/views/EdgeFunctions/FormFields/FormFieldsCreateEdgeFunctions.vue
src/views/EdgeFunctions/FormFields/FormFieldsEditEdgeFunctions.vue

[UXE-3581] feat: edge functions change to new selectors
https://github.com/aziontech/azion-console-kit/assets/110847590/7e6fb8f0-3908-4d63-8bd8-1a5c28b3e3a1
<hr />
[UXE-3581]: https://aziontech.atlassian.net/browse/UXE-3581?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[UXE-3581] chore: edge functions change to use switch field block

---

src/views/EdgeDNS/FormFields/FormFieldsEdgeDns.vue

[UXE-3582] feat: add FieldSwitchBlock in edge dns
https://github.com/aziontech/azion-console-kit/assets/110847590/1d095141-d614-4b68-9e3b-be53d96e4e93
<hr />
[UXE-3582]: https://aziontech.atlassian.net/browse/UXE-3582?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[UXE-3582] feat: add FieldSwitchBlock in edge dns

---

src/helpers/get-static-urls-by-environment.js
src/tests/helpers/get-static-urls-by-environment.test.js

Change add payment method redirect URL  at billing menu option.
<hr />

[UXE-3329] fix: change billing redirect url

---

src/views/Domains/CreateView.vue
src/views/Domains/Dialog/CopyDomainDialog.vue
src/views/Domains/FormFields/FormFieldsCreateDomains.vue
src/views/Home/HomeView.vue

adding modal to copy the created domain
https://jam.dev/c/22fe1bb0-1d69-4930-821b-95da3bfe8a83
<hr />

[UXE-3476] feat: adding modal to copy the created domain

---

src/views/DataStream/FormFields/FormFieldsDataStream.vue

Swap the fields help text that were wrong 
<hr />

[UXE-3591] fix: change fields help text order

---

src/services/users-services/list-users-service.js
src/tests/services/users-services/list-users-service.test.js
src/views/Users/ListView.vue

* remove logged user from list using store user id
* refactor map list user service adapt function
* inverted the Script code with the Template code to standardize views
* added tests for some cases of the list users service, including the removal of the logged user
https://github.com/aziontech/azion-console-kit/assets/109550332/369096e8-525a-4621-9760-1b8b8c03690a
<hr />

[UXE-3609] fix: remove logged user from users management list

---

src/helpers/get-static-urls-by-environment.js
src/services/data-stream-services/create-data-stream-service.js
src/services/data-stream-services/edit-data-stream-service.js
src/services/data-stream-services/load-data-stream-service.js
src/tests/helpers/get-static-urls-by-environment.test.js
src/tests/services/data-stream-services/create-data-stream-service.test.js
src/tests/services/data-stream-services/edit-data-stream-service.test.js
src/views/DataStream/CreateView.vue
src/views/DataStream/EditView.vue
src/views/DataStream/FormFields/FormFieldsDataStream.vue

Add variable biding to useTls options in datastreaming form
https://github.com/aziontech/azion-console-kit/assets/107002324/003e7434-3728-4f9a-8e69-8b655e74470b
<hr />

[UXE-3593] fix: add binding to useTls option in datastreaming

---

src/views/AccountSettings/AccountSettingsView.vue
src/views/AccountSettings/FormFields/FormFieldsAccountSettings.vue

adjusting the focus on the error in the account settings view
NO
NO
<hr />

[UXE-1816] feat: adjusted account settings for focus error

---

src/views/YourSettings/EditView.vue

- Content review for a confirmation toast in the **Change email** flow. 
<hr />

[EDU-4734] chore: review toast - Change email in Your Settings

---

src/views/CreateNew/DeployView.vue

* deploy project timer is showing a wrong time
* timer is not be cleared correctly
* timer is being calculated with "null" value
<hr />

[UXE-3633] fix: adjusted wrong timer in deploy project view

---

src/templates/form-fields-inputs/fieldSwitchBlock.vue
src/views/YourSettings/EditView.vue
src/views/YourSettings/FormFields/FormFieldsYourSettings.vue

replace on your setting switch to use field switch 
https://github.com/aziontech/azion-console-kit/assets/110847590/d3fdcecd-7cad-476e-bbed-e581efade868
<hr />

[UXE-3587] refactor: replace on your setting page switch to use field switch

---

src/views/YourSettings/EditView.vue
src/views/YourSettings/FormFields/FormFieldsYourSettings.vue

Added focus error feature to view your settings
no
no
<hr />

[UXE-1816] feat: implemented the focus error feature in the view your settings

---

src/views/Variables/CreateView.vue
src/views/Variables/EditView.vue
src/views/Variables/FormFields/FormFieldsVariables.vue

Added focus error feature to view variables
no
no
<hr />

[UXE-1816] feat: implemented the focus error feature in the view variables

---

src/views/Users/CreateView.vue
src/views/Users/EditView.vue
src/views/Users/FormsFields/FormFieldsUsers.vue

Added focus error feature to view user management
no
no
<hr />

[UXE-1816] feat: implemented the focus error feature in the view user management

---

src/views/Credentials/CreateView.vue
src/views/Credentials/EditView.vue
src/views/Credentials/FormFields/FormFieldsCreateCredentials.vue
src/views/Credentials/FormFields/FormFieldsEditCredentials.vue

Added focus error feature to view credentials
no
no
<hr />

[UXE-1816] feat: implemented the focus error feature in the view credentials

---

src/views/PersonalTokens/CreateView.vue
src/views/PersonalTokens/FormFields/FormFieldsPersonalToken.vue

Added focus error feature to view personal tokens
no
no
<hr />

[UXE-1816] feat: implemented the focus error feature in the view personal tokens

---

src/views/Domains/CreateView.vue
src/views/Domains/Dialog/CopyDomainDialog.vue
src/views/Domains/EditView.vue
src/views/Domains/FormFields/FormFieldsCreateDomains.vue
src/views/Domains/FormFields/FormFieldsEditDomains.vue

open dialog to copy domain created after save
https://jam.dev/c/b9b0634c-0691-47e9-bb3f-5fdc30175f59
https://www.figma.com/design/0TY2pcUTBsndMlrs0ZUvQf/Console-UI?node-id=13866-70318&t=VHEvN2QHdiRdRmfl-0
<hr />

[UXE-3476] feat: open dialog to copy domain created after save

---

src/services/team-permission/list-team-permission-service.js
src/tests/services/team-permission-services/list-team-permission-service.test.js
src/views/TeamsPermissions/FormFields/FormFieldsTeamPermissions.vue

* changed switch to new selector
* added query params to the list team permission service and tests
<hr />

[UXE-3579] refactor: changed switch input to new selector in team permissions

---

src/services/data-stream-services/create-data-stream-service.js
src/services/data-stream-services/edit-data-stream-service.js
src/tests/services/data-stream-services/create-data-stream-service.test.js
src/tests/services/data-stream-services/edit-data-stream-service.test.js
src/views/YourSettings/EditView.vue

Add JSON formatting to data set field in Data Stream
https://github.com/aziontech/azion-console-kit/assets/95643165/d70d877a-0f34-4743-b8b7-057c36e2dd95
<hr />

[UXE-3615] fix: dataset field not formatting

---

src/views/Users/FormsFields/FormFieldsUsers.vue

replace on users page switch to use field switch block
https://github.com/aziontech/azion-console-kit/assets/110847590/59701b7e-3ae8-4ee9-99fd-383d69cc3f52
<hr />

[UXE-3584] refactor: replace on users page switch to use field switch block

---

src/templates/form-fields-inputs/fieldTextArea.vue
src/views/NetworkLists/CreateView.vue
src/views/NetworkLists/EditView.vue
src/views/NetworkLists/FormFields/FormFieldsCreateNetworkLists.vue
src/views/NetworkLists/FormFields/FormFieldsEditNetworkLists.vue

* focus error in network lists fields
* migrate inputs to our field blocks
no
<hr />

[UXE-3667] feat: implemented the focus error feature in the view network lists

---

src/views/EdgeApplicationsRulesEngine/FormFields/FormFieldsEdgeApplicationsRulesEngine.vue

Revert behavior introduced by [#1314](https://github.com/aziontech/azion-console-kit/pull/1314) as it needs further design definitions
No
No
<hr />

[UXE-3308] chore: revert divider addition in rules engine/criteria

---

src/templates/create-drawer-block/index.vue
src/templates/edit-drawer-block/index.vue
src/views/EdgeServices/CreateView.vue
src/views/EdgeServices/EditView.vue
src/views/EdgeServices/FormFields/FormFieldsDrawerResource.vue
src/views/EdgeServices/FormFields/FormFieldsEdgeService.vue

* focus error in create edge services and resources tab
no
<hr />

[UXE-3667] feat: implemented the focus error feature in the edge services and resources tab

---

src/templates/create-form-block/index.vue
src/templates/edit-form-block/index.vue
src/views/Domains/CreateView.vue
src/views/Domains/EditView.vue
src/views/Domains/FormFields/FormFieldsCreateDomains.vue
src/views/Domains/FormFields/FormFieldsEditDomains.vue

Added focus error feature to view domains
no
no
<hr />

[UXE-1816] feat: implemented the focus error feature in the view domains

---

src/templates/create-drawer-block/index.vue
src/templates/create-form-block/index.vue
src/templates/edit-drawer-block/index.vue
src/templates/edit-form-block/index.vue

Improvement in the focus error method
NO
NO
<hr />

[UXE-1816] feat: improvement in the focus error method

---

src/views/Playground/PlaygroundView.vue

add toast to playground to check the toast lifespan
https://github.com/aziontech/azion-console-kit/assets/110847590/0d319d56-27c8-4b83-b1a2-847f4393d075
<hr />

[NO-ISSUE] feat: add toast to playground to check the toast lifespan

---

src/views/EdgeFirewall/CreateView.vue

implemented the focus error feature in the create edge firewall
<hr />

[UXE-3667] feat: implemented the focus error feature in the create edge firewall

---

src/templates/form-fields-inputs/fieldText.vue
src/views/DigitalCertificates/CreateView.vue
src/views/DigitalCertificates/EditView.vue
src/views/DigitalCertificates/FormFields/FormFieldsCreateDigitalCertificates.vue
src/views/DigitalCertificates/FormFields/FormFieldsEditDigitalCertificates.vue

* inputs changed to our blocks
* implemented focus on error
* refactor of some computed props
* new icon props to fieldText (image below)
no
<hr />

[UXE-3667] feat: implemented the focus error feature in the digital certificates

---

src/views/WafRules/CreateView.vue
src/views/WafRules/EditView.vue
src/views/WafRules/FormFields/FormFieldsAllowed.vue
src/views/WafRules/ListWafRulesAllowed.vue

refactor: implemented the focus error feature on the waf product
https://github.com/aziontech/azion-console-kit/assets/110847590/055b9237-19e3-4eca-85b5-2538ee6ad90f
<hr />

[UXE-3722] refactor: implemented the focus error feature on the waf product

---

src/composables/useScrollToError.js
src/templates/create-drawer-block/index.vue
src/templates/create-form-block/index.vue
src/templates/edit-drawer-block/index.vue
src/templates/edit-form-block/index.vue

Centralization of the scroll focus error method in a composoble
NO
NO
<hr />

[UXE-1816] feat: centralization of the scroll focus error method in a composoble

---

src/views/WafRules/FormFields/FormFieldsAllowed.vue

… in Regex field on the waf page
replace the description from FormHorizontal to FieldSwitchBlock
<hr />

[UXE-3586] refactor: replace the description from FormHorizontal to FieldSwitchBlock

---

package.json

chore: upgrade project version from 1.15.8 to 1.15.9
no
<hr />

[NO-ISSUE] chore: upgrade project version from 1.15.8 to 1.15.9

---

src/views/EdgeApplicationsCacheSettings/FormFields/FormFieldsEdgeApplicationCacheSettings.vue

adjust is enable appication accelerator
no
<hr />

[NO-ISSUE] fix: adjust is enable appication accelerator

---

package.json

upgrade project version from 1.15.9 to 1.16.0
<hr />

chore: upgrade project version from 1.15.9 to 1.16.0

---

src/views/AccountSettings/FormFields/FormFieldsAccountSettings.vue

refactor: replace inputSwitch to FieldGroupSwitch
<hr />

[UXE-3735] refactor: replace inputSwitch to FieldGroupSwitch

---

src/views/EdgeNode/Drawer/index.vue
src/views/EdgeNode/EditView.vue
src/views/EdgeNode/FormFields/FormFieldsDrawerService.vue
src/views/EdgeNode/FormFields/FormFieldsEdgeNode.vue
src/views/EdgeNode/TabsView.vue

refactor: automatic focus on required fields edge nodes
https://github.com/aziontech/azion-console-kit/assets/110847590/7d0ad1d1-677a-4a7c-ab60-d0d52839bc0b
<hr />

[UXE-3729] refactor: automatic focus on required fields edge nodes

---

src/assets/themes/scss/themes/azion-dark/variables/_message.scss
src/assets/themes/scss/themes/azion-light/variables/_message.scss
src/templates/create-drawer-block/index.vue
src/templates/create-form-block/index.vue
src/templates/create-modal-block/index.vue
src/templates/edit-drawer-block/index.vue
src/templates/edit-form-block/index.vue
src/templates/edit-form-block/no-header.vue
src/templates/list-table-block/index.vue
src/templates/list-table-block/no-header.vue
src/templates/sign-in-block/forgot-password.vue
src/templates/signup-block/account-activation.vue
src/templates/signup-block/login-with-email-block.vue
src/templates/toast-block/index.vue
src/tests/utils/constants.test.js
src/utils/constants.js
src/views/AccountSettings/FormFields/FormFieldsAccountSettings.vue
src/views/Domains/CreateView.vue
src/views/EdgeApplicationsOrigins/Drawer/index.vue
src/views/EdgeNode/Dialog/Authorize.vue
src/views/EdgePulse/ListView.vue
src/views/Marketplace/SolutionView.vue
src/views/Playground/PlaygroundView.vue
src/views/RealTimeEventsTieredCache/Drawer/index.vue
src/views/RealTimePurge/ListView.vue
src/views/WafRules/Drawer/index.vue
src/views/YourSettings/EditView.vue

[UXE-3145] and [UXE-3526]
Adjust behavior rules and styling for toasts:
- spacing
- life time
- text length
https://github.com/aziontech/azion-console-kit/assets/95643165/937659bb-2d70-4c99-a04b-c1c432be451e
[Toasts](https://www.figma.com/design/y7j6SxH5xXZWQPwRa8igsO/Console-Kit-Blocks?node-id=1-13479&t=fYyufmT65mgmF3ZT-0)
<hr />
[UXE-3145]: https://aziontech.atlassian.net/browse/UXE-3145?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[UXE-3526]: https://aziontech.atlassian.net/browse/UXE-3526?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[UXE-3145] refactor: review toasts rules and styles

---

src/views/EdgeNode/FormFields/FormFieldsEdgeNode.vue
src/views/RealTimePurge/CreateView.vue
src/views/RealTimePurge/FormFields/FormFieldsCreateRealTimePurge.vue

refactor: automatic focus on required fields real time purge
https://github.com/aziontech/azion-console-kit/assets/110847590/69de50da-6134-426a-ba89-06018dbba158
<hr />

[UXE-3736] refactor: automatic focus on required fields real time purge

---

src/views/EdgeApplicationsRulesEngine/FormFields/FormFieldsEdgeApplicationsRulesEngine.vue

adjust load in radio of the request and response phase
https://jam.dev/c/249b8fc3-0b66-4b66-87a2-e3ef2a606b84
<hr />

[UXE-3745] fix: adjust load in radio of the request and response phase

---

src/templates/form-fields-inputs/fieldNumber.vue
src/views/DataStream/CreateView.vue
src/views/DataStream/EditView.vue
src/views/DataStream/FormFields/FormFieldsDataStream.vue

add erro focus on the data stream page
https://github.com/aziontech/azion-console-kit/assets/110847590/0fe7408c-6398-4869-b991-486f5398b334
<hr />

refactor: add erro focus on the data stream page

---

src/views/EdgeDNS/CreateView.vue
src/views/EdgeDNS/EditView.vue
src/views/EdgeDNS/ListView.vue

- Adjust DNS copy button to be more clear.
n/a.

[No-issue] chore: adjust DNS button

---

src/composables/useScrollToError.js
src/templates/create-drawer-block/index.vue
src/templates/edit-drawer-block/index.vue
src/templates/form-fields-inputs/fieldDropdown.vue
src/templates/form-fields-inputs/fieldInputGroup.vue
src/templates/form-fields-inputs/fieldText.vue
src/templates/form-fields-inputs/fieldTextArea.vue
src/views/AccountSettings/FormFields/FormFieldsAccountSettings.vue
src/views/EdgeDNS/CreateView.vue
src/views/EdgeDNS/EditView.vue
src/views/EdgeDNS/FormFields/FormFieldsEdgeDns.vue
src/views/EdgeDNS/FormFields/FormFieldsRecords.vue

Improvement in the focus error in view edge dns
NO
NO
<hr />

[UXE-1816] feat: improvement in the focus error edge dns

---

src/services/edge-application-error-responses-services/list-error-responses-service.js

Check if originId is null before doing toString on it
<hr />

[NO-ISSUE] fix: test if origin id is not null or undefined before using toString

---

src/plugins/analytics/AnalyticsTrackerAdapter.js
src/plugins/factories/analytics-tracking-factory.js
src/tests/plugins/analytics/AnalyticsTrackerAdapter.test.js

Change segment token and add application property to all the events 
No
<hr />

[UXE-3692] chore: change segment token

---

cypress/README.md

README defined e2e test development
No
No
<hr />
- [N/A] Application responsiveness was tested to different screen sizes
N/A

[QA-2030] test: add README defined e2e test development

---

src/views/DataStream/FormFields/FormFieldsDataStream.vue

add value props in the FieldText component
<hr />

fix: data stream focus error in submit

---

package.json

chore: upgrade project version from 1.16.1 to 1.16.2
<hr />

chore: upgrade project version from 1.16.1 to 1.16.2

---

src/plugins/factories/analytics-tracking-factory.js

[NO-ISSUE] chore: update segment token

---

package.json

chore: upgrade project version from 1.16.2 to 1.16.3
<hr />

[NO-ISSUE] chore: upgrade project version from 1.16.2 to 1.16.3

---

package.json
src/plugins/factories/analytics-tracking-factory.js

**CHORE**
- [NO-ISSUE] chore: upgrade project version from 1.16.2 to 1.16.3
- [NO-ISSUE] chore: change segment token
<hr />

DEPLOY 2024.06.28

---

cypress/e2e/network-lists.cy.js
cypress/support/selectors.js
src/views/NetworkLists/FormFields/FormFieldsCreateNetworkLists.vue

[QA-2032] test: add network lists E2E test

---

package.json

chore: upgrade project version from 1.16.3 to 1.17.0
<hr />

chore: upgrade project version from 1.16.3 to 1.17.0

---

cypress/e2e/edge-firewall.cy.js
cypress/support/selectors.js
src/views/EdgeFirewall/FormFields/FormFieldsEdgeFirewall.vue

https://github.com/aziontech/azion-console-kit/assets/81633584/4813e472-93e8-4385-b476-d27106e0e5f0
<hr />

[QA-2038] test: add Edge Firewall E2E test

---

cypress/e2e/credentials.cy.js
cypress/e2e/digital-certificates.cy.js
cypress/e2e/edge-application.cy.js
cypress/e2e/network-lists.cy.js
cypress/e2e/teams-permissions.cy.js
cypress/e2e/variables.cy.js
cypress/e2e/waf.cy.js
cypress/support/commands.js
cypress/support/selectors.js

Putting e2e tests into the project standard
<hr />

[NO-ISSUE] fix: adjusting e2e tests to default

---

cypress/e2e/functions.cy.js
cypress/support/selectors.js

[NO-ISSUE] test: add functions E2E test

---

cypress/e2e/credentials.cy.js
cypress/e2e/edge-pulse.cy.js
cypress/e2e/personal-token.cy.js
src/templates/advanced-filter/component/fields/multiselect-filter.vue
src/templates/advanced-filter/index.vue
src/templates/list-table-block/dialog/delete-dialog.vue
src/templates/sign-in-block/index.vue
src/views/CreateNew/DeployView.vue
src/views/Credentials/CreateView.vue
src/views/Credentials/EditView.vue
src/views/DigitalCertificates/FormFields/FormFieldsEditDigitalCertificates.vue
src/views/Domains/CreateView.vue
src/views/Domains/EditView.vue
src/views/EdgeApplicationsOrigins/Drawer/index.vue
src/views/EdgeApplicationsRulesEngine/FormFields/FormFieldsEdgeApplicationsRulesEngine.vue
src/views/EdgeDNS/CreateView.vue
src/views/EdgeDNS/EditView.vue
src/views/EdgeNode/Dialog/Authorize.vue
src/views/EdgePulse/ListView.vue
src/views/EdgeServices/TabsView.vue
src/views/ImportGitHub/FormFields/FormFieldsImportGithub.vue
src/views/PersonalTokens/CreateView.vue
src/views/Users/EditView.vue
src/views/WafRules/TabsView.vue

[EDU-4780] chore: review toasts

---

.github/workflows/e2e-tests.yml

[NO-ISSUE] chore: upload e2e coverage html report

---

cypress/e2e/data-stream.cy.js
cypress/e2e/users-management.cy.js
cypress/e2e/your-settings.cy.js
cypress/e2mock/your-settings.cy.js
cypress/support/selectors.js
src/templates/form-fields-inputs/fieldDropdown.vue
src/templates/form-fields-inputs/fieldGroupRadio.vue
src/templates/form-fields-inputs/fieldNumber.vue
src/templates/form-fields-inputs/fieldSwitchBlock.vue
src/views/DataStream/FormFields/FormFieldsDataStream.vue
src/views/NetworkLists/FormFields/FormFieldsCreateNetworkLists.vue
src/views/YourSettings/FormFields/FormFieldsYourSettings.vue

- Create base e2e test for `data stream`
https://github.com/aziontech/azion-console-kit/assets/95643165/1fe8cbb6-621e-49ea-863b-667ad0aebbbf
No
<hr />

[UXE-3779] test: create e2e test for data stream

---

src/templates/list-table-block/action-column.vue
src/templates/list-table-block/dialog/delete-dialog-new.vue
src/templates/list-table-block/new.vue

add button to action column in table component
https://github.com/aziontech/azion-console-kit/assets/92529166/9cd349a7-ad8f-4e7a-98cf-9f43955de015
no
<hr />

[UXE-3769] refactor: add button to action column in table component

---

.github/workflows/e2e-tests.yml

[NO-ISSUE] chore: remove lcov-report folder before upload e2e artifacts

---

.github/workflows/e2e-tests.yml

[NO-ISSUE] chore: remove yarn ci to speedup e2e workflow

---

azion.config.cjs

Bypass cache for query strings.
Not.
<hr />

[NO-ISSUE] fix: cache varies by query string

---

.github/workflows/e2e-tests.yml

[NO-ISSUE] chore: zip coverage folder before upload

---

cypress/e2e/credentials.cy.js
cypress/support/commands.js
cypress/support/selectors.js
src/templates/list-table-block/action-column.vue
src/templates/list-table-block/dialog/delete-dialog-new.vue
src/views/Credentials/ListView.vue

add action button to credentials
https://jam.dev/c/9a578fad-9402-4a54-aadc-dde45caae9a6
no
<hr />

[UXE-3769] refactor: add action button to credentials

---

.github/workflows/cla.yml

[NO-ISSUE] fix: workflow CLA to run on latest ubuntu version with latest CLA assistant  version

---

src/views/EdgeFirewall/EditView.vue
src/views/EdgeFirewall/ListView.vue
src/views/EdgeFirewall/TabsView.vue

Adjusted method edit in edge firewall
https://github.com/aziontech/azion-console-kit/assets/101672576/33528639-78bd-4c8e-8f45-e54a6dec44f6
<hr />

[UXE-3966] fix: adjusted method edit in edge firewall

---

README.md

Small fixes in README.md to keep it consistent.
No
No
<hr />

[NO-ISSUE] docs: update README.md

---

src/helpers/convert-date.js
src/helpers/payment-method.js
src/services/billing-services/list-payment-service.js
src/tests/helpers/convert-date.test.js
src/tests/helpers/payment-method.test.js
src/tests/services/billing-services/list-payment-service.test.js
src/views/Billing/PaymentListView.vue

add search and sort in the payment list
https://github.com/aziontech/azion-console-kit/assets/110847590/fcaec974-3256-4d57-bdc4-3ef228c73991
<hr />

[UXE-2762] refactor: add search and sort in the payment list

---

src/views/DataStream/FormFields/FormFieldsDataStream.vue

fix: fix bug in the select domain field with pick list component
https://github.com/aziontech/azion-console-kit/assets/110847590/bac38960-f09b-40d2-992d-6c778dbcab44
<hr />

[UXE-3658] fix: fix bug in the select domain field with pick list component

---

src/router/hooks/beforeEachRoute.js

add account status blocked check before redirecting to billing page
<hr />

[UXE-3677] feat: add account status check before redirecting to billing page

---

src/router/hooks/beforeEachRoute.js

Remove redirect to billing, causing problems to Console navigation.
No
<hr />

[NO-ISSUE] fix: remove redirect to billing in beforeEachHook that causes effect on github integration

---

cypress.config.js
cypress/README.md
cypress/e2e/credentials.cy.js
cypress/e2e/data-stream.cy.js
cypress/e2e/digital-certificates.cy.js
cypress/e2e/domains.cy.js
cypress/e2e/edge-application.cy.js
cypress/e2e/edge-dns.cy.js
cypress/e2e/edge-firewall.cy.js
cypress/e2e/edge-services.cy.js
cypress/e2e/functions.cy.js
cypress/e2e/network-lists.cy.js
cypress/e2e/personal-token.cy.js
cypress/e2e/purge.cy.js
cypress/e2e/teams-permissions.cy.js
cypress/e2e/users-management.cy.js
cypress/e2e/variables.cy.js
cypress/e2e/waf.cy.js
cypress/support/commands.js
cypress/support/selectors.js

- Update delete entity commands in cypress to avoid unnecessary page loads 
- Update documentation
- Add cy.session to reduce new logins
*Breaking changes have already been fixed*
Big refactor. Video would be too long 
<hr />

[UXE-3970] refactor: adjust delete commands to avoid unnecessary page loads

---

src/templates/add-payment-method-block/index.vue

[NO-ISSUE] Stripe input theme

---

src/views/EdgeApplicationsRulesEngine/FormFields/FormFieldsEdgeApplicationsRulesEngine.vue

fix: adding the correct add response value
https://github.com/aziontech/azion-console-kit/assets/110847590/98627623-98f0-47df-b52d-5178bc9a2a17
<hr />

[UXE-3634] fix: adding the correct add response value

---

src/plugins/factories/stripe-integration-factory.js

[NO-ISSUE] chore: debug environment

---

azion/stage/azion.json

updated the value production in env for stage
<hr />

[NO-ISSUE] chore: updated the value production in env for stage

---

cypress/e2e/domains.cy.js
cypress/e2e/edge-application.cy.js
cypress/support/utils.js
src/templates/add-payment-method-block/index.vue

adjusting the deletion process of an edgeApp and correcting the flow of domains
No
No
<hr />

[NO-ISSUE] tooling defect: adjusting the deletion process of an edgeApp and correcting the flow of domains

---

src/views/EdgeFunctions/CreateView.vue
src/views/EdgeFunctions/FormFields/FormFieldsCreateEdgeFunctions.vue
src/views/EdgeFunctions/FormFields/FormFieldsEditEdgeFunctions.vue

fix: add initiatorType field in edge functions
https://github.com/aziontech/azion-console-kit/assets/110847590/86ae73a6-bd9f-413c-99f3-518094aad748
<hr />

[UXE-3944] fix: add initiatorType field in edge functions

---

.github/workflows/deploy-production.yml
.github/workflows/deploy-stage.yml
azion.config.cjs
src/helpers/get-environment.js

[NO-ISSUE] chore: updated env actions deploy

---

src/assets/themes/scss/themes/azion-dark/_variables.scss
src/assets/themes/scss/themes/azion-dark/variables/_data.scss
src/assets/themes/scss/themes/azion-light/_variables.scss
src/assets/themes/scss/themes/azion-light/variables/_data.scss
tailwind.config.js

- Fixed table border, cells and rows to consume the correct border token.
- Fixed hover color token to sync with azion site theme and avoid multi color surface problems.
- Fixed hover color header menu.
Before:
After:
<hr />

[NO-ISSUE] fix: theme table border + hover color

---

.github/workflows/deploy-production.yml
.github/workflows/deploy-stage.yml
azion.config.cjs
azion/stage/azion.json
src/helpers/get-environment.js
vite.config.js

rename prop env MODE in action for VITE_ENVIRONMENT
NO
NO
<hr />

[NO-ISSUE] chore: update environment variables for production and stage deployments

---

azion.config.cjs
src/helpers/get-environment.js

Chore urls stage

---

.github/workflows/deploy-production.yml
src/helpers/get-environment.js
src/plugins/factories/stripe-integration-factory.js
vite.config.js

update environment variables for production and stage deployments
NO
NO
<hr />

[UXE-4029] chore: update environment variables for production and stage deployments

---

src/helpers/account-expired.js
src/helpers/get-static-urls-by-environment.js
src/templates/navbar-block/switch-account.vue
src/templates/profile-block/index.vue
src/tests/helpers/get-static-urls-by-environment.test.js

adjusted redirect billing in production and stage
no
no
<hr />

[UXE-4029] fix: adjusted redirect billing in production and stage

---

src/services/billing-services/index.js
src/services/billing-services/load-current-invoice-service.js
src/services/billing-services/make-billing-base-url.js
src/tests/services/billing-services/list-current-invoice-service.test.js
src/tests/services/billing-services/make-billing-base-url.test.js
vite.config.js

implements new service current invoice
NO
<hr />

[UXE-2761] feat: implements new service current invoice

---

src/helpers/account-expired.js
src/helpers/get-static-urls-by-environment.js
src/templates/navbar-block/switch-account.vue
src/templates/profile-block/index.vue
src/tests/helpers/get-static-urls-by-environment.test.js
src/views/Billing/PaymentListView.vue

adjust redirect billing in production and stage
no
no
<hr />

[UXE-4029] fix: adjust redirect billing in production and stage

---

package.json

upgrade project version from 1.17.0 to 1.18.0
no
no
<hr />

[NO-ISSUE] chore: upgrade project version from 1.17.0 to 1.18.0

---

cypress/support/commands.js

[NO-ISSUE] test: store e2e session across specs

---

cypress/e2e/network-lists.cy.js
cypress/support/selectors.js
src/views/NetworkLists/FormFields/FormFieldsCreateNetworkLists.vue
src/views/NetworkLists/FormFields/FormFieldsEditNetworkLists.vue

Add test E2E to network lists creation page
<hr />

[UXE-3951] test: create countries and ip/cidr network lists

---

src/views/EdgeFunctions/FormFields/FormFieldsCreateEdgeFunctions.vue
src/views/EdgeFunctions/FormFields/FormFieldsEditEdgeFunctions.vue

Revised texts in Initiator Type fields.
https://www.figma.com/design/0TY2pcUTBsndMlrs0ZUvQf/Console-UI?node-id=5893-35787&t=deRwlaD6uf2MOcc4-4
<hr />

[UXE-3944] chore: texts revisions in Initiator Type

---

cypress/e2e/account-settings.cy.js
cypress/e2e/edge-application.cy.js
cypress/e2e/functions.cy.js

[NO-ISSUE] test: remove cypress delay when typing

---

src/router/routes/billing-routes/index.js
src/services/billing-services/load-current-invoice-service.js
src/tests/services/billing-services/list-current-invoice-service.test.js
src/views/Billing/InvoiceDetailsView.vue
src/views/EdgeApplications/TabsView.vue

create UI invoice details
https://www.figma.com/design/0TY2pcUTBsndMlrs0ZUvQf/Console-UI?node-id=14076-78175&t=cZRy9snTEN3N6iqi-0
<hr />

[UXE-4012] feat: create UI invoice details

---

cypress/e2e/edge-services.cy.js
cypress/support/selectors.js
src/templates/list-table-block/index.vue
src/views/EdgeServices/FormFields/FormFieldsDrawerResource.vue
src/views/EdgeServices/FormFields/FormFieldsEdgeService.vue
src/views/EdgeServices/ListViewTabResources.vue
src/views/EdgeServices/TabsView.vue

- Add data-testid selectors related to edge
- Create e2e for edit resource in edge service
https://github.com/user-attachments/assets/49ec3ef5-e43a-4afc-a0c9-7ed57a259e8b
No
<hr />

[UXE-3953] test: e2e for edit resource in edge service

---

src/templates/create-modal-block/index.vue
src/views/CreateNew/CreateView.vue
src/views/Marketplace/components/ListSolutions.vue

Fixed a visual error that some images appears with a white corners border.
<hr />

[UXE-4041] fix: template imgs borders

---

cypress/e2e/edge-services.cy.js
cypress/support/selectors.js

- Add assertion to verify persistence of values in edge service creation
- Skip creation test until UXE-4094 is resolved
No
<hr />

[UXE-3953] test: update e2e for better assertion of edge service creation

---

cypress/e2mock/activity-history.cy.js
cypress/fixtures/activity-history.json
cypress/support/selectors.js

Add e2mock test to activity history list page
<hr />

[UXE-3790] test: add e2mock test for activity history list

---

vite.config.js

Remove limitation on presenting logs on terminal when in development mode. This ensure to display the localhost url that the project is running on.
Without localhost log :
With correct behavior:
NO
<hr />

[UXE-4112] chore: remove log level config from vite config file to show localhost url on dev script execution

---

.github/workflows/dev-e2e-tests.yml
.github/workflows/manual-e2e-tests.yml

Set log level to warn in e2e workflow to reduce verbosity 
No
<hr />

[NO-ISSUE] chore: add log level to e2e workflow

---

src/templates/add-payment-method-block/index.vue
src/views/Billing/BillsView.vue
src/views/Billing/Drawer/index.vue
src/views/Billing/FormFields/FormFieldsCreateCredit.vue
src/views/Billing/InvoiceDetailsView.vue
src/views/Billing/PaymentListView.vue
src/views/Billing/TabsView.vue

[UXE-3281] chore: review content in Billing pages

---

.github/workflows/dev-e2e-tests.yml
.github/workflows/prod-e2e-tests.yml
.github/workflows/stage-e2e-tests.yml
cypress/e2e/account-settings.cy.js
package.json

adjustment to e2e test coverage and addition of @xfail in the account settings test
No
No
<hr />

[NO-ISSUE] fix: adjustment to e2e test coverage and addition of @xfail in the account settings test

---

cypress/support/commands.js

remove console log from cypress command file and replace it by cy.log() 
<hr />

[NO-ISSUE] chore: replace console log on Cypress commands for Cy.log() function

---

cypress/e2e/edge-application.cy.js
cypress/support/selectors/product-selectors/edge-application.js
src/views/EdgeApplicationsRulesEngine/FormFields/FormFieldsEdgeApplicationsRulesEngine.vue

- Create e2e for edition of rules engine in edge applications
- Update selectors for rules engine
https://github.com/user-attachments/assets/a84318e4-8439-4151-9549-2a5124d14223
No
<hr />

[UXE-3961] test: create e2e for edition of rules engine in edge applications

---

cypress/e2e/data-stream.cy.js
src/views/Billing/BillsView.vue
src/views/Billing/Components/Notification-payment.vue
src/views/Billing/TabsView.vue

- Refactor in section payment
[figma](https://www.figma.com/design/0TY2pcUTBsndMlrs0ZUvQf/Console-UI?node-id=14163-136039&t=n10LEeG3iXsrhI0y-4)
<hr />

[UXE-4015] refactor: adjusted section card payment

---

azion.config.cjs

Add rules route for billing in config vulcan
NO
<hr />

[UXE-4111] chore: add rules route for billing in config vulcan

---

azion.config.cjs

Add rules route for billing in config vulcan
NO
<hr />

[UXE-4111] chore: rename rules route for billing in config vulcan

---

src/templates/list-table-block/columns/credit-card-column.vue
src/templates/list-table-block/index.vue
src/views/Billing/BillsView.vue
src/views/Billing/PaymentListView.vue
src/views/Billing/TabsView.vue

- improve card payment section and update button download
<hr />

[UXE-4028] refactor: improve card payment section and update button download

---

.github/workflows/deploy-stage.yml

Update azion deploy command to include debug flag
<hr />

[NO-ISSUE] chore: update azion deploy command to include debug flag

---

cypress/e2e/account-settings.cy.js

- Replace api wait with time wait due to env inconsistency
No
No
<hr />

[UXE-4117] test: replace api wait with time wait

---

src/router/routes/billing-routes/index.js
src/services/billing-services/index.js
src/services/billing-services/load-current-invoice-service.js
src/services/billing-services/load-invoice-data-service.js
src/tests/services/billing-services/load-current-invoice-service.test.js
src/tests/services/billing-services/load-invoice-data-service.test.js
src/views/Billing/BillsView.vue
src/views/Billing/InvoiceDetailsView.vue
src/views/Billing/TabsView.vue

adjust validation issues
<hr />

[NO-ISSUE] fix: adjust validation issues

---

src/services/billing-services/load-current-invoice-service.js
src/services/billing-services/load-invoice-data-service.js
src/services/billing-services/load-your-service-plan-service.js
src/tests/services/billing-services/load-your-service-plan-service.test.js
src/views/Billing/BillsView.vue

add default card number in your service plan card
<hr />

[UXE-3698] refactor: add default card number in your service plan card

---

src/services/billing-services/list-payment-methods-service.js
src/tests/services/billing-services/list-payment-methods-service.test.js
src/views/Billing/PaymentListView.vue

Correction applied to the search functionality for card numbers in payment methods.
https://github.com/user-attachments/assets/4363f22a-85a3-427b-940b-405aa0dbc208
NO
<hr />

[UXE-4157] refactor: update card number search in list-payment-methods-service

---

src/router/hooks/beforeEachRoute.js
src/router/routes/billing-routes/index.js
src/services/billing-services/load-your-service-plan-service.js
src/templates/add-payment-method-block/index.vue
src/tests/services/billing-services/create-payment-method-service.test.js
src/views/Billing/Drawer/DrawerPaymentMethod.vue
src/views/Billing/TabsView.vue

Adjusted the redirect to handle forced tabs and conditions during login.
NO
NO
<hr />

[UXE-4029] refactore: adjusted the redirect to handle forced tabs and conditions during login

---

README.md
vite.config.js

Compare vite environment value with  lower case environment constant, to ensure correct project url in vite config file
NO
NO
<hr />

[NO-ISSUE] chore: fixing environments in lowercase

---

cypress/e2e/edge-application.cy.js
cypress/e2e/edge-functions.cy.js
cypress/e2e/functions.cy.js
cypress/support/selectors/product-selectors/edge-application.js
src/templates/form-fields-inputs/fieldDropdown.vue
src/views/EdgeApplicationsFunctions/FormFields/FormFieldsEdgeApplicationsFunctions.vue
src/views/EdgeApplicationsFunctions/ListView.vue
src/views/EdgeApplicationsRulesEngine/FormFields/FormFieldsEdgeApplicationsRulesEngine.vue

* edge app functions major test cases
* edge app function instance in rules engine
no
no
<hr />

[UXE-3955] test: e2e edge app functions major cases

---

src/router/routes/waf-rules-routes/index.js
src/views/WafRules/EditView.vue
src/views/WafRules/TabsView.vue

Add updated redirect to Waf Edit Pages
https://github.com/user-attachments/assets/bffe1721-2590-4743-82b3-461560a317e3
<hr />

[UXE-3917] fix: waf allowed rules cancel button redirect url

---

src/templates/list-table-block/index.vue
src/views/Billing/BillsView.vue

feat: clicking on payment history should open the invoice details
https://github.com/user-attachments/assets/ea518605-4a32-4dc6-ba53-34b681bc65ee
<hr />

[UXE-4155] feat: clicking on payment history should open the invoice details

---

src/services/billing-services/load-payment-method-default-service.js
src/templates/skeleton-block/index.vue
src/views/Billing/BillsView.vue
src/views/Billing/Drawer/DrawerPaymentMethod.vue
src/views/Billing/TabsView.vue
src/views/WafRules/EditView.vue
src/views/WafRules/TabsView.vue

- add skeleton block component for loading state
- Adjusted lint in files
NO
<hr />

[UXE-4203] feat: add skeleton block component for loading state

---

src/services/billing-services/list-payment-history-service.js
src/templates/list-table-block/columns/text-with-tag-column.vue
src/tests/services/billing-services/list-payment-history-service.test.js
src/views/Billing/BillsView.vue
src/views/Billing/Components/Notification-payment.vue
src/views/Billing/Drawer/DrawerAddCredit.vue
src/views/Billing/FormFields/FormFieldsDrawerCredit.vue
src/views/Billing/InvoiceDetailsView.vue
src/views/Billing/PaymentListView.vue
src/views/Billing/TabsView.vue

billing view design adjustments
<hr />

[UXE-4215] fix: billing view design adjustments

---

package.json

chore: revert upgrade project version to 1.18.0
No
No
<hr />

[NO-ISSUE] chore: revert upgrade project version to 1.18.0

---

src/views/Marketplace/MarketplaceHomeView.vue

fix: screen goes white when clicking on active marketplace category
https://github.com/user-attachments/assets/13b917f8-9141-422d-9f2d-a486db9cae05
<hr />

[UXE-3455] fix: screen goes white when clicking on active marketplace category

---

cypress/e2e/billing.cy.js
cypress/support/selectors/product-selectors/billing.js
src/services/billing-services/delete-payment-service.js
src/services/digital-certificates-services/create-digital-certificates-csr-service.js
src/services/digital-certificates-services/create-digital-certificates-service.js
src/services/digital-certificates-services/edit-digital-certificates-service.js
src/tests/services/digital-certificates-services/create-digital-certificates-csr-service.test.js
src/tests/services/digital-certificates-services/create-digital-certificates-service.test.js
src/tests/services/digital-certificates-services/edit-digital-certificates-service.test.js
src/views/Billing/TabsView.vue

* showing the response API message
<hr />

[UXE-4301] fix: show the message about deleting a payment method correctly

---

.github/workflows/deploy-production.yml
.github/workflows/deploy-stage.yml
src/plugins/StripeIntegrationPlugin.js
src/plugins/factories/stripe-integration-factory.js
src/services/digital-certificates-services/create-digital-certificates-csr-service.js
src/services/digital-certificates-services/create-digital-certificates-service.js
src/services/digital-certificates-services/edit-digital-certificates-service.js
src/tests/plugins/factories/stripe-integration-factory.test.js
src/tests/services/digital-certificates-services/create-digital-certificates-csr-service.test.js
src/tests/services/digital-certificates-services/create-digital-certificates-service.test.js
src/tests/services/digital-certificates-services/edit-digital-certificates-service.test.js

* added stripe tokens to workflows and vite env
* new unit test to the missing stripe token error
<hr />

[UXE-4303] chore: stripe token added to github secrets env

---

.github/workflows/deploy-stage.yml

chore: Bump CLI version for stage deploy

---

.github/workflows/deploy-stage.yml

chore: Update CLI version

---

src/helpers/convert-date.js
src/router/routes/billing-routes/index.js
src/services/billing-services/index.js
src/services/billing-services/load-invoice-last-updated-service.js
src/tests/services/billing-services/load-invoice-last-updated-service.test.js
src/views/Billing/TabsView.vue

add last updated to billing
<hr />

[UXE-4300] feat: add last updated to billing

---

.github/workflows/deploy-production.yml
.github/workflows/deploy-stage.yml
README.md
src/plugins/StripeIntegrationPlugin.js
src/plugins/factories/stripe-integration-factory.js
src/tests/plugins/factories/stripe-integration-factory.test.js

* readme section to stripe
* updated missing stripe keys message
no
<hr />

[UXE-4303] chore: update readme with stripe env info

---

.gitignore
azion/stage/azion.json
azion/stage/files.json

How to fix:
```
rm -rf azion/stage
azion deploy  --debug --config-dir azion/stage
```

[NO-ISSUE] fix: recreating  stage console configuration with vulkan
