aziontech/azion-console-kit

src/assets/themes/scss/themes/azion-dark/_variables.scss, src/assets/themes/scss/themes/azion-light/_variables.scss, src/router/hooks/beforeEachRoute.js, src/router/index.js, src/router/routes/cli-callback-routes/index.js, src/views/CliCallback/FailView.vue, src/views/CliCallback/SuccessView.vue
Implemented two statics pages to be called after the CLI auth process:
These pages don't have any logic, so the content and the texts are static.
Success Page (console.azion.com/cli-callback-success):
Fail Page (console.azion.com/cli-callback-fail):
=> [ENG-28766] CLI callback page

src/templates/sidebar-block/index.vue
- This alteration ensures that the product menu, situated to the left of the application's navbar, is displayed only when the logged-in account is of the 'client' type.
=> [ENG-28869 feat: implementing access control to the menu

src/templates/sidebar-block/index.vue
fix import name from Prime vue to use Tag component in sidebar-block
=> [ENG-28869] fix: adjusted import tag in sidebar block

src/services/edge-application-cache-settings-services/create-cache-settings-service.js, src/services/edge-application-cache-settings-services/delete-cache-settings-service.js, src/services/edge-application-cache-settings-services/edit-cache-settings-service.js, src/templates/content-block/banner.vue, src/templates/content-block/index.vue, src/tests/services/edge-application-cache-settings-services/create-cache-settings-service.test.js, src/tests/services/edge-application-cache-settings-services/delete-cache-settings-service.test.js, src/tests/services/edge-application-cache-settings-services/edit-cache-settings-service.test.js, src/views/PersonalTokens/Dialog/CopyTokenDialog.vue, vitest.config.js
- Ensure delete cache settings service calls the API with correct params.
- Merged the 'dev' into 'feat-cache-settings-tab-edge-application-drawers'.
- Ensure create cache settings service calls the API with correct params.
- Ensure edit cache settings service calls the API with correct params.
- Text message update on CopyTokenDialog block.
=> [ENG-28093] feat: add unit tests to cache settings services

src/services/edge-application-cache-settings-services/list-cache-settings-service.js, src/tests/services/edge-application-cache-settings-services/list-cache-settings-service.test.js, src/tests/services/edge-application-cache-settings-services/load-cache-settings-service.test.js, vitest.config.js
Only add necessary unit tests to the cache settings services, such as load service and list service.
As a bonus this PR also introduce a new coverage threshold with a percentagem of 91 as the default value.
=> [ENG-28094] test: add cache settings unit tests to load service

src/assets/themes/scss/themes/azion-dark/extended-components/_divider.scss, src/assets/themes/scss/themes/azion-light/extended-components/_divider.scss
Just apply z-index to dividers. This fix avoid break the scroll of the pages.
=> [NO-ISSUE] change z-index on extensions

src/services/digital-certificates-services/list-digital-certificates-service.js, src/tests/services/digital-certificates-services/list-digital-certificates-service.test.js
old:
new name (TLS Certificate intead of Edge Certificate)
=> [EDU-3781] chore: change mapper of digital certificates list to use TLS name

.eslintrc.cjs, src/helpers/parse-api-body.js, src/router/hooks/beforeEachRoute.js, src/router/routes/signup-routes/index.js, src/router/routes/switch-account-routes/index.js, src/services/users-services/list-users-service.js, src/templates/mfa-authenticate-block/index.vue, src/templates/mfa-setup-block/index.vue, src/templates/search-block/index.vue, src/templates/template-engine-block/index.vue, src/templates/toast-block/index.vue, src/tests/services/credentials-services/list-credentials-service.test.js, src/tests/services/edge-application-services/list-edge-applications-service.test.js, src/tests/services/edge-functions-services/list-edge-functions-service.test.js, src/tests/services/edge-node-service-services/list-service-edge-node-service.test.js, src/tests/services/edge-service-resources-services/list-resources-services.test.js, src/tests/services/edge-service-services/list-edge-service-services.test.js, src/tests/services/personal-tokens-services/list-personal-tokens-service.test.js, src/tests/services/real-time-purge/list-real-time-purge.test.js, src/tests/utils/localeMock.js, src/views/IntelligentDNS/EditView.vue, src/views/Marketplace/MarketplaceHomeView.vue, src/views/Marketplace/drawer/IntegrationInstall.vue, src/views/PersonalTokens/FormFields/FormFieldsPersonalToken.vue, src/views/YourSettings/FormFields/FormFieldsYourSettings.vue
Avoid using variables that are only 1 character long to encourage developers to use more descriptive and meaningful names in the project code.
=> [ENG-28979] refactor: improve code readability with eslint variable name rule

src/assets/themes/scss/themes/azion-dark/extended-components/_selectbutton.scss, src/assets/themes/scss/themes/azion-light/extended-components/_selectbutton.scss, src/templates/create-modal-block/index.vue
Only include padding-inline for buttons in Create.
=> [NO-ISSUE] style: include padding-inline

src/assets/themes/scss/themes/azion-light/extended-components/_selectbutton.scss
Padding fix for selectbutton on light mode.
Antes:
Depois:
=> [NO-ISSUE] Selectbutton padding fix.

src/services/edge-application-functions-services/list-edge-functions-service.js, src/services/edge-firewall-functions-services/list-edge-functions-service.js
Add configuration to JSON.stringfy to format the code on Monaco Editor.
=> [NO-ISSUE] chore: indent function args on monaco

src/templates/list-table-block/dialog/delete-dialog.vue
Versão em Português:
* Bloqueio ao pressionar rapidamente a tecla 'Enter' no Dialog de exclusão.
English Version:
* Stoped quickly pressing 'Enter' in the delete dialog.
=> [ENG-1588] fix: stop quickly press enter in delete dialog

src/services/edge-application-functions-services/loader-function-service.js, src/services/edge-firewall-functions-services/loader-function-service.js, src/tests/services/edge-application-functions-services/load-function-service.test.js, src/tests/services/edge-firewall-functions-services/load-function-service.test.js, src/views/EdgeApplicationsFunctions/FormFields/FormFieldsEdgeApplicationsFunctions.vue, src/views/EdgeFirewall/TabsView.vue
Fix indentation when the Function Instance is edited in Edge Application or Firewall.
=> [NO-ISSUE] fix: json parse indent functions

src/templates/create-drawer-block/index.vue, src/templates/create-modal-block/index.vue, src/templates/edit-drawer-block/index.vue, src/templates/edit-form-block/no-header.vue
[UXE-1678]
WHY: 
feat: Line break in toast text does not respect close button on Intelligent DNS screen
[UXE-1678]: https://aziontech.atlassian.net/browse/UXE-1678?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [UXE-1678] feat: Line break in toast text does not respect close button on Intelligent DNS screen

src/views/Domains/FormFields/FormFieldsCreateDomains.vue
[UXE-1712] 
WHY:
feat: add .value in cnameAccessOnly and fix the problem
[UXE-1712]: https://aziontech.atlassian.net/browse/UXE-1712?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [UXE-1712] feat: add .value in cnameAccessOnly and fix the problem

src/views/Domains/FormFields/FormFieldsEditDomains.vue
[UXE-1712] 
WHY:
feat: add nameAccessOnly.value in edit domain
[UXE-1712]: https://aziontech.atlassian.net/browse/UXE-1712?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [UXE-1712] feat: add nameAccessOnly.value in edit domain

src/services/edge-application-services/edit-edge-application-service.js, src/services/edge-application-services/index.js, src/tests/services/edge-application-services/edit-edge-application-service.test.js, src/views/EdgeApplications/FormFields/FormFieldsCreateEdgeApplications.vue
-  Enable toggle functionality at edge application - edit -main settings
- handle error when users had no access to this product and try to use it.
- Add custom message when error user_has_no_product is found on returned API validation
- Add unit test cases to document behaviors of editing an edge application
=> [UXE-27512] fix: L2 cache module  at edge application 

src/views/WafRules/CreateView.vue
https://github.com/aziontech/azion-console-kit/assets/110847590/85be6db2-9217-4479-9ae6-a445a3453601
[UXE-1796] 
WHY:
fix: WAF should come with services all connected in medium
[UXE-1796]: https://aziontech.atlassian.net/browse/UXE-1796?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [UXE-1796] fix: WAF should come with services all connected in medium

src/views/DataStreaming/FormFields/FormFieldsDataStreaming.vue
Fix options to Monaco Editor display the code values better:
=> [UXE-1795] fix: data streaming code editor indent

src/views/EdgeApplications/CreateView.vue
WHY:
Add a default option to HTTPS ports in edge application main settings
=> [NO-ISSUE] fix: add default selection to https port

src/views/EdgeFirewallFunctions/Drawer/index.vue
WHY:
Existia um typo na tela de functions em edge firewall que estava ocorrendo pois lá era importado a tela de edge functions de edge firewall
=> [UXE-1801] fix: typo in edge firewall functions

src/templates/list-table-block/no-header.vue
WHY:
WAF rules tunning não possuí deleção de registros, por tanto precisa que a action fique desabilitada
=> [UXE-1807] fix: remove action delete to list tables that dont have delete service

src/assets/main.css
Fix the following behavior
https://github.com/aziontech/azion-console-kit/assets/95643165/ca78cac2-46e9-4246-a28b-2746034b1987
=> [UXE-1798] fix: [global] apply overscroll-behavior-contain to all elements

src/templates/list-table-block/no-header.vue, src/views/WafRules/ListWafRulesTuning.vue
[UXE-1806] fix: adding cursor point to the table in the header and validating the api return in waf
https://github.com/aziontech/azion-console-kit/assets/92529166/4f69e296-8767-4063-a9f7-54767934878b
[UXE-1806]: https://aziontech.atlassian.net/browse/UXE-1806?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [UXE-1806] fix: adding cursor point to the table in the header

src/services/domains-services/list-domains-service.js, src/tests/services/domains-services/list-domains-service.test.js, src/views/Domains/ListView.vue
[UXE-1817]
WHY:
fix: add expand-column in cnames
[UXE-1817]: https://aziontech.atlassian.net/browse/UXE-1817?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
https://github.com/aziontech/azion-console-kit/assets/110847590/7c32aa49-50db-423d-a704-3e2680194535
=> [UXE-1817] fix: add expand-column in cnames

src/views/RealTimeEventsActivityHistory/Drawer/index.vue
WHY:
Havia um typo na ui, onde mostrava o User ID a label estava como Client ID
=> [UXE-2149] fix: remove typo in activity history property name

src/services/real-time-events-service/activity-history/load-activity-history.js
WHY:
As tags de type dentro do drawer de activity history estavam com o texto inteiro em letras minusculas.
=> [UXE-2150] fix: capitalize activity history type first letter

src/plugins/adapters/AnalyticsTrackerAdapter.js, src/services/real-time-events-service/activity-history/load-activity-history.js, src/templates/info-drawer-block/info-section/index.vue, src/templates/list-table-block/index.vue, src/tests/plugins/adapters/AnalyticsTrackerAdapter.test.js, src/views/EdgeApplications/ListView.vue
This PR introduces:
- new tracker event called clickToCreate
- unit tests related to this new event
- a new emitter on list-table-block, called n-before-go-to-add-page
- a event handle on listView to track the event Click to Create with the product name provided as Edge Application.
=> [UXE-1882] feat: add track event Click To Create

src/services/marketplace-services/load-solution-service.js
WHY:
Na tela de launch das solutions, solutions do tipo bring your own license não estavam apresentando o card de instalação correto
=> [UXE-2173] fix: Show bring your own license solution installation card

src/views/Metrics/blocks/interval-filter-block.vue, src/views/RealTimeEvents/blocks/constants/date-time-interval.js, src/views/RealTimeEvents/blocks/interval-filter-block.vue
- limit the custom filter to seven days prior to today
- change dropdown options
=> [UXE-2158] refactor: replace RTE datetime filter options

src/services/digital-certificates-services/list-digital-certificates-service.js, src/tests/services/digital-certificates-services/list-digital-certificates-service.test.js
Adiciona na tela de listagem de digital certificates o status do certificado, não apenas se esta inativo ou ativo
<hr />
=> [UXE-2219] fix: show digital certificate status

src/views/EdgeApplicationsRulesEngine/FormFields/FormFieldsEdgeApplicationsRulesEngine.vue
* phase button hidden at edit rules engine
Before:
After:
<hr />
=> [UXE-2562] fix: phase button hidden in edit rules engine

src/services/script-runner-service/get-script-runner-results-service.js, src/tests/services/script-runner-services/get-script-runner-results-serice.test.js
Change the service to catch the errors in Script Runner results.
<hr />
=> [UXE-2534] fix: make service catch when there is a error in the results of a script

src/templates/content-block/index.vue, src/templates/create-drawer-block/index.vue, src/templates/edit-drawer-block/index.vue
[UXE-2648]
fix: action bar is being overlapped by other components
<hr />
[UXE-2648]: https://aziontech.atlassian.net/browse/UXE-2648?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [UXE-2648] fix: action bar is being overlapped by other components

src/templates/list-table-block/columns/text-with-clipboard-column.vue, src/templates/list-table-block/index.vue, src/templates/list-table-block/no-header.vue
Apply the same action button style for tables
Apply top position for buttons tooltip in `templates/list-table`
https://github.com/aziontech/azion-console-kit/assets/95422158/74305508-1680-44ab-8f03-2d6b09f88c9e
https://www.figma.com/file/2hNLUK00QbkDeQSYSC6DDW/PrimeOne-%5B2.0.0%5D-%5BVue%5D?type=design&node-id=3318%3A222516&mode=design&t=OUz1Ql7VwcchlUQa-1
<hr />
=> [NO-ISSUE] style: apply the same action button style for tables

src/stores/metrics.js
Replace the incorrect prop name "currentGroupPage" with "group.current", which caused the dropdown to not work properly
No
https://github.com/aziontech/azion-console-kit/assets/95643165/4b5764f4-fd2a-48e6-bd7c-7f6df748f33f
<hr />
=> [NO-SSUE] fix: resolve incorrect prop access

src/router/routes/create-new-routes/index.js, src/services/script-runner-service/get-script-runner-results-service.js, src/services/script-runner-service/index.js, src/services/script-runner-service/load-script-runner-execution-results-service.js, src/services/template-engine-services/instantiate-template.js, src/templates/script-runner-block/index.vue, src/templates/template-engine-block/index.vue, src/tests/services/script-runner-services/get-script-runner-results-serice.test.js, src/views/ImportGitHub/ImportStaticView.vue
Here are your sentences with corrected English:
1. Fixes incorrect behavior when deployment fails while creating an edge application using the template "journey".
2. Fixes pooling to prevent infinite calls when the script runner is no longer mounted on the view.
3. Enhances code readability by using more cohesive names for variables, functions, and files related to instantiating a template using the script runner.
Fixed and correct behaviour when  deploy fail:
No
<hr />
=> [NO-ISSUE] fix: view behavior and toast message when deploy fails

src/services/digital-certificates-services/create-digital-certificates-service.js, src/tests/services/digital-certificates-services/create-digital-certificates-service.test.js
- Add validation scenarios when either certificate ou privateKey is not set
- Add tests
Old
New
No
<hr />
=> [UXE-1720] fix: add validations when certificate or private key are empty strings

src/services/edge-application-origins-services/create-origin-service.js, src/tests/services/edge-application-origins-services/create-origin-service.test.js
- add weight key to address only when originType is 'load balance'
- add tests for different originType scenarios
No
<hr />
=> [UXE-2759] fix: add validation to weight field based on originType

src/views/EdgeFirewall/FormFields/FormFieldsEdgeFirewall.vue
Filter domains list in edge firewall create and edit forms to show only domains that haven't been used yet
Uploading Screenshare - 2024-04-08 4_20_02 PM.mp4…
<hr />
=> [UXE-1770] fix: filter domains that already have an edge firewall instancied

src/services/domains-services/edit-domain-service.js, src/services/domains-services/load-domain-service.js, src/tests/services/domains-services/edit-domain-service.test.js, src/tests/services/domains-services/load-domain-service.test.js, src/views/Domains/EditView.vue, src/views/Domains/FormFields/FormFieldsEditDomains.vue
* incorrect loading of digital certificates status on the edit domains screen
https://github.com/aziontech/azion-console-kit/assets/109550332/422dfaab-ae84-44bd-930f-cbff801f97b5
<hr />
=> [UXE-2401] fix: incorrect loading of digital certificates status on the edit domains screen

src/assets/icons/azionicons.scss, src/templates/signup-block/client-testimonials-block.vue, src/templates/signup-block/form-signup-block.vue, src/templates/signup-block/login-with-email-block.vue, src/tests/services/domains-services/load-domain-service.test.js, src/views/Domains/FormFields/FormFieldsEditDomains.vue
- removes the auto complete behavior from signup form fields.
- removes infinite loop from the Carousel of testimonials.
- remove full name field, since it should me used only in the new additional data page.
- full name will be send by extraction of the first part of the email. Ex: john.doe@gmail.com -> will be john.doe. 
No
Yes, remove Full Name field. It will be move to additional data page.
No.
<hr />
=> [UXE-2339] fix: remove autocomplete from sign up form and display only one testimonial

src/templates/template-engine-block/index.vue
Escape the use of ${} in template fields error messages, that was resulting in undefined in some templates
<hr />
=> [UXE-2833] fix: escape  special use in error message of template fields

src/assets/themes/scss/themes/azion-dark/extended-components/_sidebar.scss, src/assets/themes/scss/themes/azion-light/extended-components/_sidebar.scss, src/templates/action-bar-block/go-back.vue, src/templates/action-bar-block/index.vue, src/templates/create-drawer-block/index.vue, src/templates/edit-drawer-block/index.vue
Fix design issues for the action bar. Now, the action bar is fixed at the bottom of the drawer, using a `'z-index' `higher than other elements inside the drawer. This improves scroll usability and resolves layout issues where the action bar was floating without respecting the boundaries of the drawer.
https://github.com/aziontech/azion-console-kit/assets/95422158/651be27f-512a-49e0-a68a-06c542c8c9a8
No Figma 
<hr />
=> [UXE-2654] fix: fixed-position-to-action-bar-drawer

src/templates/sign-in-block/index.vue
- implement method to verify for `error_description` in login url
- show error description in the toast
No
<hr />
=> [UXE-2885] fix: add method to verify error_description query in login url

src/services/edge-application-origins-services/list-origins-service.js
default rule presents set origin behavior with empty value
https://github.com/aziontech/azion-console-kit/assets/92529166/3192eff7-67c3-462d-b67b-bdedfd2883fe
<hr />
=> [UXE-2830] fix: default rule presents set origin behavior with empty value

src/templates/template-engine-block/index.vue
[UXE-2892]
fix: save button not enabled in some templates
https://github.com/aziontech/azion-console-kit/assets/110847590/24776fd4-b0fb-412d-b164-e14b0d1ef2ff
<hr />
[UXE-2892]: https://aziontech.atlassian.net/browse/UXE-2892?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [UXE-2892] fix: save button not enabled in some templates

src/assets/themes/scss/themes/azion-dark/variables/_form.scss, src/assets/themes/scss/themes/azion-light/variables/_form.scss
Change color for $inputPlaceholderTextColor token, now the color has aspect of "empty"
No Figma
<hr />
=> [UXE-2896] Change color for $inputPlaceholderTextColor token

src/templates/edit-form-block/index.vue, src/views/EdgeApplications/EditView.vue
onsaved dialog being opened even after saving changes
https://github.com/aziontech/azion-console-kit/assets/92529166/365ab6f5-597f-4bc3-a59f-5ebed6700dea
<hr />
=> [UXE-2809] fix: onsaved dialog being opened even after saving changes

src/templates/sign-in-block/index.vue, src/templates/social-idps-block/index.vue
Resets login page state if is cached by [bfcache](https://web.dev/articles/bfcache)
> It was not exactly tested, because the behavior does not happen in local env.
> Applying the response header `Cache Control: 'no-cache'` to the rule engine only worked in chrome
No
No
<hr />
=> [UXE-2774] fix: reset page state if page is cached by browser

src/views/EdgeFunctions/EditView.vue, src/views/EdgeFunctions/FormFields/FormFieldsEditEdgeFunctions.vue, src/views/EdgeFunctions/components/code-editor.vue, src/views/EdgeFunctions/components/mobile-code-preview.vue
- Hide preview for lua functions in edit view
- Add lua as supported language by code-editor-block to improve lint
https://github.com/aziontech/azion-console-kit/assets/95643165/a259d800-ded5-43c0-a398-575fca084110
No
<hr />
=> [UXE-2578] refactor: hide frame preview for lua functions

src/tests/services/edge-dns-records-services/create-records-service.test.js, src/views/EdgeDNS/FormFields/FormFieldsRecords.vue
* added a default value for ttl field in edge dns records field based in RTM.
* for ANAME type the value is 20
* field now is showing for this type
* added test case for default value in aname type
https://github.com/aziontech/azion-console-kit/assets/109550332/d07b3122-37b9-4802-82dd-83c538580bfb
<hr />
=> [UXE-2806] fix: added a default value for ttl field in edge dns records field

src/services/waf-rules-services/list-waf-rules-tuning-attacks-service.js, src/services/waf-rules-services/list-waf-rules-tuning-service.js, src/tests/services/waf-rules-services/list-waf-rules-tuning-service.test.js, src/views/WafRules/ListWafRulesTuning.vue
[UXE-2817]
Creating Allowed Rule through Tuning is creating with wrong ruleId
https://github.com/aziontech/azion-console-kit/assets/110847590/c242ed6f-c53f-4ec6-8045-287a03f81199
<hr />
[UXE-2817]: https://aziontech.atlassian.net/browse/UXE-2817?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [UXE-2817] fix: Creating Allowed Rule through Tuning is creating with wrong ruleId

src/views/EdgeApplicationsCacheSettings/FormFields/FormFieldsEdgeApplicationCacheSettings.vue
Rename values for `inputId` and `for` in both radio and label in edgeApplicationCacheSettings form fields. The click on `Cache By Cookie` and `Adaptative Delivery` labels were triggering change in `Cache by Query String`.
https://github.com/aziontech/azion-console-kit/assets/95643165/54756e18-d319-413f-ac31-cb6b325e95d9
No
<hr />
=> [UXE-2812] fix: adjust radio inputs with unexpected behavior

src/assets/themes/scss/themes/azion-dark/extended-components/_dialog.scss, src/assets/themes/scss/themes/azion-dark/extended-components/_sidebar.scss, src/assets/themes/scss/themes/azion-light/extended-components/_dialog.scss, src/assets/themes/scss/themes/azion-light/extended-components/_sidebar.scss
Remove sidebar and dialog fixed height to fit content correctly in template more details page
https://github.com/aziontech/azion-console-kit/assets/107002324/6103d603-d481-4b7e-ac8b-0a69b675a9a3
<hr />
=> [UXE-1874] fix: change more details box header in template page to fit content correctly

src/services/marketplace-services/list-solutions-service.js, src/tests/services/marketplace-services/list-solutions-service.test.js, src/views/ImportGitHub/FormFields/FormFieldsImportGithub.vue, src/views/Variables/FormFields/FormFieldsVariables.vue
adding ordering of templates by name
templates are not ordered A > Z
https://github.com/aziontech/azion-console-kit/assets/92529166/e549bf90-0bc8-480e-91c4-9dda7b5bb609
<hr />
=> [UXE-3096] fix: adding ordering of templates by name

src/templates/create-form-block/index.vue, src/templates/form-fields-inputs/fieldText.vue, src/views/ImportGitHub/FormFields/FormFieldsImportGithub.vue, src/views/ImportGitHub/ImportGithubView.vue
- Add validation to key field for each variable created on import from Github journey to avoid invalid keys
- No longer display an  success toast after initialize the integration from Github  
https://github.com/aziontech/azion-console-kit/assets/101186721/0ffdf25a-5752-41cc-bf2f-d0598446e162
<hr />
=> [UXE-3122] fix: remove unnecessary toast from import from Github to deploy view and add variable key validation

src/views/EdgeApplicationsErrorResponses/EditView.vue
- replace the default router.go(-1) behavior in the error responses form with router.push() to return to list on canceling.
https://github.com/aziontech/azion-console-kit/assets/95643165/e82d3547-f2aa-4461-90a2-02c4ff16aa85
No
<hr />
=> [ENG-2765] fix: return to list on EdgeApplicationErrorResponses cancel

src/views/ImportGitHub/ImportGithubView.vue
- Ensure to catch correctly the fail event when creating variables before call the service of instantiate a project from github. This ensure to only show one fail event and avoid the redirection to the deploy view.
No
https://github.com/aziontech/azion-console-kit/assets/101186721/d9758b3e-3093-4c74-bab9-c78fba0c3e4d
NO.
<hr />
=> [UXE-3135] fix: ensure to only catch once the fail creation of an variable

src/views/EdgeFirewall/ListView.vue
[UXE-2081]
feat: add event tracker click to edit edge firewall
<hr />
[UXE-2081]: https://aziontech.atlassian.net/browse/UXE-2081?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [UXE-2081] feat: add event tracker click to edit edge firewall

src/services/signup-services/make-resend-email-base-url.js, src/tests/services/signup-services/resend-email-service.test.js
Update the url for resend email to avoid users being redirected to RTM. 
https://github.com/aziontech/azion-console-kit/assets/95643165/9d488fbb-6d0e-4db1-8cbd-0b25fa3d2f41
No
<hr />
=> [UXE-2931] fix: update resend email endpoint

src/views/EdgeFirewall/EditView.vue, src/views/EdgeFirewallFunctions/Drawer/index.vue, src/views/EdgeFirewallRulesEngine/Drawer/index.vue
[UXE-2081]
feat: add event tracker in edit edge firewall
<hr />
[UXE-2081]: https://aziontech.atlassian.net/browse/UXE-2081?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [UXE-2081] feat: add event tracker in edit edge firewall

src/templates/template-engine-block/index.vue
When a input is empty and it is not required, it should not be tested by its regular expression.
https://github.com/aziontech/azion-console-kit/assets/107002324/43adecff-dba0-4382-91fb-136b73f0a6e6
<hr />
=> [UXE-2881] fix: escape validation in template engine empty not requied fields

src/stores/deploy.js, src/templates/template-engine-block/index.vue, src/views/CreateNew/DeployView.vue
Add deploy start time to store to persist deploy timer when page is reloaded 
https://github.com/aziontech/azion-console-kit/assets/107002324/8892303d-fc12-4d9c-87c2-0e2c75e2aab0
<hr />
=> [UXE-3179] refactor: change deploy timer to persist when the page is reloaded

src/modules/real-time-metrics/filters/extract-filters-and-variables.js
request time filter with between operator breaks the query
https://github.com/aziontech/azion-console-kit/assets/92529166/d0a44f2d-c85b-48a9-a290-9450c7d9e8d0
<hr />
=> [UXE-2891] fix: request time filter with between operator breaks the query

src/views/EdgeApplicationsRulesEngine/FormFields/FormFieldsEdgeApplicationsRulesEngine.vue, src/views/EdgeApplicationsRulesEngine/ListView.vue
* rules engine page selectors changed to new blocks
* Radio
* Switch
* solved bug in [UXE-3302](https://aziontech.atlassian.net/browse/UXE-3302) Ordering does not appear for the first item in the Response Phase listing
[Link to Figma](https://www.figma.com/design/0TY2pcUTBsndMlrs0ZUvQf/Console-UI?node-id=10635-45389&t=nH0s5eLy1GvDX7wn-0)
<hr />
[UXE-3302]: https://aziontech.atlassian.net/browse/UXE-3302?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [UXE-3301] refactor: edge app rules engine page selectors radio and switch changed to new blocks

src/views/RealTimePurge/Dialog/index.vue
[UXE-2342]
refactor: rename the tittle of repurge dialog to Confirm Repurge
<hr />
[UXE-2342]: https://aziontech.atlassian.net/browse/UXE-2342?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [UXE-2342] refactor: rename the tittle of repurge dialog to Confirm Repurge

src/templates/navbar-block/feedback-fish.vue, src/templates/navbar-block/index.vue
An adjustment was made to the classes of the FeedbackFish button to make it generic, and the possibility of editing was added. We implemented a different version only in the header, where it always remains black.
<hr />
=> [UXE-3330] fix: refactor feedbackfish component styling

src/views/DataStream/FormFields/FormFieldsDataStream.vue
The height of the Monaco editor has been increased to display up to 15 lines without scrolling on the data stream screen.
NO
<hr />
=> [UXE-1784] feat: increased lines in monaco on dataStream view

src/templates/create-form-block/form-horizontal.vue
Fixed the responsiveness of the Monaco editor with the Help Center open in resolutions where resizing occurs.
<hr />
=> [UXE-3360] fix: adjusted resize monaco editor in data stream

src/views/Domains/CreateView.vue
The name field in domains form should be filled only with ascii carachteres. 
Current regex validation Redos check:
<hr />
=> [UXE-1709] fix: change domain name validation to only ascii caracteres

src/templates/mfa-setup-block/index.vue
Improve camera readability. Using a white background, always is better to camera readability. Now in light or dark mode, the background of QR Code -MFA is white.
yes but it could not be copied and paste here, due the QR code contain  real MFA.
<hr />
=> [NO-ISSUE] fix: add fixed white background to improve qr code camera readability

src/tests/utils/constants.test.js, src/utils/constants.js, src/views/Domains/CreateView.vue, src/views/EdgeDNS/EditView.vue, src/views/EdgeDNS/FormFields/FormFieldsRecords.vue
[UXE-2868] fix: all types of Records limited to 3600, change to 604800
Change the maximum value of the TTL input on the records page
https://github.com/aziontech/azion-console-kit/assets/110847590/3df0a898-050b-4bd4-bee6-2b519f23b2ef
<hr />
[UXE-2868]: https://aziontech.atlassian.net/browse/UXE-2868?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [UXE-2868] fix: all types of Records limited to 3600, change to 604800

src/templates/form-fields-inputs/fieldGroupRadio.vue, src/templates/selector-block/index.vue, src/views/RealTimePurge/FormFields/FormFieldsCreateRealTimePurge.vue
* This commit updates the card component styles to maintain full text color intensity when a selector is included. The change enhances text readability and visual consistency across different card states.
* Hide v-show feature added to radioGroup
https://github.com/aziontech/azion-console-kit/assets/109550332/b532a5e4-0dba-4ae4-88d8-8a6d717fee25
<hr />
=> [NO-ISSUE] refactor: remove text opacity from card text when selector is present

src/views/EdgeApplicationsRulesEngine/Drawer/index.vue, src/views/EdgeApplicationsRulesEngine/FormFields/FormFieldsEdgeApplicationsRulesEngine.vue
* Resolved an issue where the image optimization setting was not being correctly propagated to the edit interface of the rules engine. This fix ensures that the state of the image optimization toggle is accurately reflected when editing rules.
https://github.com/aziontech/azion-console-kit/assets/109550332/95a9a55f-e919-4c27-b775-1b50c6b28c9e
<hr />
=> [UXE-3296] fix: ensure image optimization option is passed to rules engine edit

src/assets/themes/scss/themes/azion-dark/variables/_form.scss, src/assets/themes/scss/themes/azion-light/variables/_form.scss
Alterado o estilo da célula de today nos calendários afim de garantir todos os estados de interação quando a célula estiver sendo marcada ou desabilitada.
Foi necessário alterar o estilo que antes com o fundo preenchido para borda, para que não fosse necessário alteração em extend, assim o problema foi resolvido apenas com a camada de variables do primevue.
**Bug:**
https://github.com/aziontech/azion-console-kit/assets/44036260/7ed8bb91-906b-4944-8870-1de556f9cc67
**Resolução:**
https://github.com/aziontech/azion-console-kit/assets/44036260/911f7646-02e8-4c4c-9998-21bd253eb7c7
<hr />
=> [UXE-2391] fix: adjusted the colors of the today color calendar

src/assets/themes/scss/themes/azion-dark/variables/_general.scss, src/assets/themes/scss/themes/azion-light/variables/_general.scss
Adjustment in opacity of disabled elements 
The opacity in disabled elements was too low, harming monitors and users with low vision. An adjustment was made to maintain identification and facilitate reading of disabled elements.
<hr />
=> [UXE-2579] fix: adjustment in opacity of disabled elements

src/services/edge-dns-records-services/load-records-service.js, src/tests/services/edge-dns-records-services/load-records-service.test.js
edit records in second page
When the user is on the second page, they can't change
https://github.com/aziontech/azion-console-kit/assets/44036260/117ec964-6bc7-45fc-a528-f184109addb2
<hr />
=> [UXE-2869] fix: edit records in second page

index.html
Now, when the user interacts with a form field that has a font size of less than 16px, the browser will not zoom in to the form field.
<hr />
=> [UXE-2266] fix: add meta tag user-scale to avoid zoom-in when user clicks on form fields

src/templates/help-center-block/index.vue
Remove from help-center footer links the 'send feedback' link, since it is moved to the application top header bar.
<hr />
=> [UXE-2496] fix: remove send feedback from help-center footer link options

src/views/EdgeApplicationsRulesEngine/FormFields/FormFieldsEdgeApplicationsRulesEngine.vue
the loop was fixed when trying to open the drawer of a rule engine that was of the default rule type
https://github.com/aziontech/azion-console-kit/assets/92529166/4ceaf03a-9a39-4a4c-9bca-47c4483e9c8e
<hr />
=> [UXE-3394] fix: loop when trying to load the default rule engine in edge app

src/views/EdgeFirewallFunctions/Drawer/index.vue
[UXE-3307] fix: it is closing the drawer when an error occurs
https://github.com/aziontech/azion-console-kit/assets/110847590/57b1d771-099e-4827-a15e-bcefffac43dd
<hr />
[UXE-3307]: https://aziontech.atlassian.net/browse/UXE-3307?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [UXE-3307] fix: it is closing the drawer when an error occurs

src/views/AccountSettings/FormFields/FormFieldsAccountSettings.vue
* Now, the subsequent field remains disabled, waiting for the previous field to be filled.
https://github.com/aziontech/azion-console-kit/assets/109550332/fdf8a6c1-6dce-4b9b-8157-154439b6d95e
<hr />
=> [UXE-1871] refactor: account settings infinite loading in city and region fields

src/services/edge-firewall-rules-engine-services/create-edge-firewall-rules-engine-service.js, src/services/edge-firewall-rules-engine-services/edit-edge-firewall-rules-engine-service.js
When creating an rule engine in edge firewall product, the payload related to the behavior "set custom response" is now correctly passed inside a object property "argument". This will fix the create and edit service for edge firewall rules engine journey.
https://github.com/aziontech/azion-console-kit/assets/101186721/5012a0ea-c813-4a7d-b8f0-5528c6dc5e70
<hr />
=> [NO-ISSUE] fix: ensure to create edge firewall with correct params with custom response rule engine

src/views/EdgeApplicationsRulesEngine/FormFields/FormFieldsEdgeApplicationsRulesEngine.vue
show enabled the  behavior section fields in the default rule to enable to user edit an default rule.
https://github.com/aziontech/azion-console-kit/assets/92529166/dc03b5d7-272a-4974-83f8-69a3e8e635af
<hr />
=> [UXE-2859] fix: releasing behavior selection in the default rule

src/views/EdgeFirewall/FormFields/FormFieldsEdgeFirewall.vue
the domain selection field is adapting incorrectly when there are domains with long names and when there are no domains in the selection.
Uploading Compartilhamento de tela - 2024-06-03 10h53min47s.mp4…
<hr />
=> [UXE-2934] fix: domain selection is adapting incorrectly

src/services/real-time-purge/list-real-time-purge-service.js, src/templates/form-fields-inputs/fieldCheckboxBlock.vue, src/templates/form-fields-inputs/fieldGroupRadio.vue, src/templates/list-table-block/index.vue, src/views/EdgeApplicationsCacheSettings/FormFields/FormFieldsEdgeApplicationCacheSettings.vue, src/views/RealTimePurge/FormFields/FormFieldsCreateRealTimePurge.vue
Fix: Address issues with checkbox, radio, and service data in Real Time Purge
This commit resolves several issues:
1. The checkbox was incorrectly toggling even when disabled. This has been fixed to ensure the checkbox remains static when disabled.
2. Adde tag to the disabled radio button in the Real Time Purge for better identification.
3. Resolved an error in the listing component that occurred when no data was received from the service. 
The component now handles empty data scenarios gracefully.
https://github.com/aziontech/azion-console-kit/assets/109550332/8dd56836-6eda-42aa-b11e-b36983a7b264
<hr />
=> [UXE-3264] fix: issues with checkbox disabled, tag in radio and empty list in real time purge

src/templates/empty-results-block/index.vue, src/templates/error-page-block/index.vue, src/views/ActivityHistory/ListView.vue, src/views/EdgeApplicationsCacheSettings/ListView.vue, src/views/EdgeApplicationsDeviceGroups/ListView.vue, src/views/EdgeApplicationsFunctions/ListView.vue, src/views/EdgeApplicationsOrigins/ListView.vue, src/views/EdgeApplicationsRulesEngine/ListView.vue, src/views/EdgeDNS/EditView.vue, src/views/EdgeFirewallFunctions/ListView.vue, src/views/EdgeFirewallRulesEngine/ListView.vue, src/views/EdgeNode/ListViewTabServices.vue, src/views/EdgeServices/ListViewTabResources.vue, src/views/PersonalTokens/ListView.vue, src/views/RealTimeEventsDataStream/ListView.vue, src/views/RealTimeEventsEdgeDNS/ListView.vue, src/views/RealTimeEventsEdgeFunctions/ListView.vue, src/views/RealTimeEventsEdgeFunctionsConsole/ListView.vue, src/views/RealTimeEventsHTTPRequests/ListView.vue, src/views/RealTimeEventsImageProcessor/ListView.vue, src/views/WafRules/ListWafRulesAllowed.vue, src/views/WafRules/ListWafRulesTuning.vue
Adjusted the UI of the empty block component following figma, and the width of the buttons in the mobile version
[Figma](https://www.figma.com/design/y7j6SxH5xXZWQPwRa8igsO/Console-Kit-Blocks?node-id=1-12528&t=xlD3LYZhij5N0dBu-4)
<hr />
=> [UXE-2051] refactor: adjusted empty block component ui following figma

src/templates/info-drawer-block/info-labels/big-number.vue, src/views/WafRules/Drawer/index.vue
[UXE-2500] fix: add font-medium in waf drawer and big number block
<hr />
[UXE-2500]: https://aziontech.atlassian.net/browse/UXE-2500?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [UXE-2500] fix: add font-medium in waf drawer and big number block

src/templates/page-heading-block-tabs/index.vue, src/templates/page-heading-block/index.vue
The "whitespace-nowrap" class was added to avoid line breaks in the breadcrumb in older mobile applications
<hr />
=> [UXE-2265] fix: add class to prevent line break in breadcrumb

src/views/RealTimeMetrics/blocks/dashboard-panel-block.vue
Add scroll to navigation tabs in metrics and add nowrap to whitespaces
<hr />
=> [UXE-2396] fix: add scroll when tabs are bigger than screen

src/templates/form-fields-inputs/fieldDropdown.vue, src/views/Users/FormsFields/FormFieldsUsers.vue, src/views/YourSettings/FormFields/FormFieldsYourSettings.vue
A class named "w-full" was added to the dropdown to fix the bug affecting the search input width.
<hr />
=> [UXE-3311] fix: add width in input filter for dropdown

src/views/RealTimeMetrics/blocks/interval-filter-block.vue
Change metrics time range selector responsiveness when screen is medium
<hr />
=> [UXE-2397] fix: remove space between buttons when screend is medium

src/services/domains-services/list-domains-service.js, src/tests/services/domains-services/list-domains-service.test.js
Azion console show Azion (SAN) for domain with default digital certificate. Those domains with a custom  digital certificate ( digital certificate create by the user) will show the domain ID.
Yes,
<hr />
=> [UXE-2751] fix: ensure to display Azion SAN certificate for domains without certificate on domain list

src/views/EdgePulse/FormFields/FormFieldsDefault.vue, src/views/EdgePulse/FormFields/FormFieldsTag.vue
Add `p-disabled` custom class and support text to code editors in edge pulse tabs as they are read-only.
** The extra div and the w-[99.9%] were needed to handle responsiveness, as monaco editor behaves a little too strange in this aspect
https://github.com/aziontech/azion-console-kit/assets/95643165/be56e935-eb88-46b6-a301-5582f3bf8948
<hr />
=> [UXE-1673] fix: apply read only behavior edge pulse editors

src/views/EdgeApplicationsRulesEngine/FormFields/FormFieldsEdgeApplicationsRulesEngine.vue
Add button show be enabled when the latest behavior isn't a 'final behavior'. This show behave on adding a new behavior and also removing or editing a behavior on the list.
https://github.com/aziontech/azion-console-kit/assets/101186721/49d5d5d1-f5ae-4c97-9c71-0df50bdff142
<hr />
=> [UXE-2647] fix: add button behavior disabled value based on latest behavior

src/services/users-services/edit-users-service.js, src/views/YourSettings/EditView.vue
- Change email confirmation toast from warning to info type
- Better handling of error and success toasts
- Displays only email info toast when only email is changed 
https://github.com/aziontech/azion-console-kit/assets/95643165/5d06b314-3ac8-4e87-865a-120714653ad1
<hr />
=> [UXE-3351] fix: handle toast in submit method in your settings

src/views/DigitalCertificates/ListView.vue
Add sortField prop to `status` column in Digital Certificates list to allow sorting
https://github.com/aziontech/azion-console-kit/assets/95643165/bc05d97d-950d-4afa-91d3-a3361a451e35
<hr />
=> [UXE-3463] fix: add sortField property to status column

src/views/RealTimeEventsHTTPRequests/Drawer/index.vue
* changed sufix -> ms to bytes 
<hr />
=> [UXE-3470] fix: changed sufix in events request and response data section

src/views/Variables/FormFields/FormFieldsVariables.vue
This PR add the switch field block to variables create page to increase maintainability.
https://github.com/aziontech/azion-console-kit/assets/110847590/e877785c-9eda-4145-9838-bb8a83cfffcb
<hr />
[UXE-3585]: https://aziontech.atlassian.net/browse/UXE-3585?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [UXE-3585] refactor: replace on variables product switch to use field switch block 

src/views/DataStream/FormFields/FormFieldsDataStream.vue
Hide sampling section from datastreaming form
<hr />
=> [UXE-3616] fix: Hide sampling section from datastreaming form

src/views/EdgeApplications/TabsView.vue, src/views/EdgeApplicationsRulesEngine/ListView.vue
* now the add button in list open the drawer by the selected phase
https://github.com/aziontech/azion-console-kit/assets/109550332/29834468-31ae-44ad-a6e6-83a861d9acd4
<hr />
=> [UXE-3614] fix: add button in rules engine list open the drawer by the current phase

src/helpers/azion-documentation-catalog.js, src/router/routes/digital-certificates-routes/index.js, src/tests/helpers/azion-documentation-catalog-product-guide.test.js, src/views/DigitalCertificates/EditView.vue, src/views/DigitalCertificates/FormFields/FormFieldsEditDigitalCertificates.vue
- Display an message to inform to the final user that Lets Encrypt Certificates, should not be able to be edited. 
-  Ensure to block action bar submit button and display as read-only the digital certificate name field.
- Add documentation service with new Url to  the lets encrypt documentation guide.
YES,
https://github.com/aziontech/azion-console-kit/assets/101186721/6d17b2fc-82f4-478a-a40c-0d72e9580b8b
<hr />
=> [UXE-3462] fix: lets encrypt certificate editing validation

src/views/DataStream/FormFields/FormFieldsDataStream.vue
dataset does not load custom a template in data stream
https://jam.dev/c/d8f82dbb-d47d-4674-a856-57e9545cbae2
<hr />
=> [UXE-3590] fix: dataset does not load custom a template in data stream

src/views/DigitalCertificates/EditView.vue
- Hide action bar on edit view for  digital certificate of type Lets Encrypt.
<hr />
=> [UXE-3462] fix: hide action bar for lets encrypt  certificate on Edit Digital Certificate view

src/views/EdgeApplicationsRulesEngine/FormFields/FormFieldsEdgeApplicationsRulesEngine.vue
loop when trying to load the default rule engine in edge app
no
<hr />
=> [NO-ISSUE] fix: loop when trying to load the default rule engine in edge app

src/views/EdgeApplicationsRulesEngine/FormFields/FormFieldsEdgeApplicationsRulesEngine.vue
Add `AND` divider to improve user experience while adding criteria in rules engine.
<hr />
=> [UXE-3308] fix: add divider to improve user experience in rules engine

src/views/DataStream/FormFields/FormFieldsDataStream.vue
default values not load in edit data stream
https://jam.dev/c/a798a26d-f10b-454c-94cd-560293be5b10
<hr />
=> [UXE-3594] fix: default values not load in edit data stream

src/views/RealTimeEvents/blocks/interval-filter-block.vue, src/views/RealTimeMetrics/blocks/interval-filter-block.vue
Change max date from timerange selector to update in real time
(Time in console is different of mac due to the offset)
<hr />
=> [UXE-3477] fix: change max date timerange limit to updated time

src/views/EdgeApplicationsRulesEngine/FormFields/FormFieldsEdgeApplicationsRulesEngine.vue
loop when trying to load the default rule engine in edge app
<hr />
=> [UXE-3745] fix: loop when trying to load the default rule engine in edge app

cypress/e2e/edge_application.cy.js, src/templates/list-table-block/index.vue, src/templates/list-table-block/no-header.vue
* If there is only one filtered record in the table, the toggle menu does not work.
* Individual menu references were created for each record.
https://github.com/aziontech/azion-console-kit/assets/109550332/069338d0-5fce-4817-9e2e-4ea492095bf0
<hr />
=> [UXE-3823] fix: toggle menu with filtered table

src/services/edge-application-error-responses-services/list-error-responses-service.js, src/tests/services/edge-application-error-responses/list-error-responses-service.test.js
Load correctly the origin id field in edge application error responses tab
https://github.com/aziontech/azion-console-kit/assets/107002324/be11ba64-703d-4bcc-99fb-ae7150d0c410
<hr />
=> [UXE-3762] fix: load originId field in error responses edition

cypress/e2e/teams-permissions.cy.js, src/views/TeamsPermissions/CreateView.vue, src/views/TeamsPermissions/EditView.vue, src/views/TeamsPermissions/FormFields/FormFieldsTeamPermissions.vue, src/views/TeamsPermissions/ListView.vue
- Add data-testid to teams permissions elements in views
- Create e2e test for creation e deletion of teams permissions 
No
https://github.com/aziontech/azion-console-kit/assets/95643165/0d2d920d-a697-4f27-975f-80aa2a3a2f15
No
<hr />
=> [UXE-3791] test: create e2e test for team permissions

cypress/e2e/edge_application.cy.js, cypress/support/e2e.js, cypress/support/utils.js
Dynamically define names of entities to be created by E2E tests to avoid collisions
No
No
<hr />
=> [QA-2018] test: dynamically define names of entities to be created by E2E

cypress/README.md, cypress/e2e/credentials.cy.js, cypress/e2e/digital-certificates.cy.js, cypress/e2e/edge-application.cy.js, cypress/e2e/teams-permissions.cy.js, cypress/e2e/your-settings.cy.js, cypress/e2mock/your-settings.cy.js, cypress/support/commands.js, src/templates/form-fields-inputs/fieldText.vue, src/templates/form-fields-inputs/fieldTextArea.vue, src/templates/toast-block/index.vue, src/views/Credentials/CreateView.vue, src/views/Credentials/EditView.vue, src/views/Credentials/FormFields/FormFieldsCreateCredentials.vue, src/views/Credentials/FormFields/FormFieldsEditCredentials.vue, src/views/Credentials/ListView.vue, src/views/YourSettings/FormFields/FormFieldsYourSettings.vue
- Add data-testid to credentials related blocks and views
- Create e2e tests creation and deletion of credential 
- Create verifyToast command to verify text and auto close it
- Refactor other tests to use created utils and commands
- Document added command
https://github.com/aziontech/azion-console-kit/assets/95643165/6d7e2f27-fb74-47f9-ad9a-cd92a40f1ffa
No
<hr />
=> [UXE-3789] test: create e2e test for credentials

cypress/e2e/personal-token.cy.js, src/templates/list-table-block/index.vue, src/templates/list-table-block/no-header.vue, src/templates/list-table-block/with-lazy-and-dropdown-filter.vue, src/views/PersonalTokens/Dialog/CopyTokenDialog.vue, src/views/PersonalTokens/FormFields/FormFieldsPersonalToken.vue
* tests to create and delete personal tokens
* added data-testid to empty message in datatables
https://github.com/aziontech/azion-console-kit/assets/109550332/b6063326-859e-4540-b46b-53fcde155515
<hr />
=> [UXE-3793] test: e2e personal tokens crud

cypress/e2e/edge-services.cy.js, src/views/EdgeServices/FormFields/FormFieldsEdgeService.vue
* e2e test to create and delete an edge services 
https://github.com/aziontech/azion-console-kit/assets/109550332/970b77d7-2c35-4429-a6aa-c00c0b4117fd
<hr />
=> [UXE-3247] test: e2e edge services crud

src/assets/themes/scss/themes/azion-dark/_variables.scss, src/assets/themes/scss/themes/azion-light/_variables.scss
Alterado a cor da borda para evitar tanto destaque para bordas em geral, principalmente no dark que estava ficando bem chamativo. Mudança solicitada pelo Rafael e aprovada pelo Caio.
Antes:
Depois:
Antes:
Depois:
<hr />
=> [NO-ISSUE] chore: changed border color

cypress/e2e/data-stream.cy.js, cypress/support/selectors.js, src/services/data-stream-services/create-data-stream-service.js, src/services/data-stream-services/edit-data-stream-service.js, src/views/DataStream/FormFields/FormFieldsDataStream.vue
*Fix*
- Resolve Error.message in create-data-stream service
*Test*
- Add data-testid and selectors related to data stream
- Add e2e test for kafka connector in data stream
- Add e2e test for s3 connector in data stream
- Add e2e test for bigquery connector in data stream
- Add e2e test for elasticsearch connector in data stream
- Add e2e test for splunk connector in data stream
- Add e2e test for kinesis connector in data stream
- Add e2e test for datadog connector in data stream
- Add e2e test for qradar connector in data stream
- Add e2e test for azure monitor connector in data stream
- Add e2e test for azure blob storage connector in data stream
https://github.com/aziontech/azion-console-kit/assets/95643165/57aafb59-c1b4-4a2e-a5fa-5ac8b0b3532d
No
<hr />
=> [UXE-3941] test: create e2e test for new selectors in data stream

azion.config.cjs
This PR changes the edge application configuration to use Security header that enable the use of window.opener() method, that is only defined in window object if the COOP is not set as 'same-orgin'.
<q>If a cross-origin document with COOP is opened in a new window, the opening document will not have a reference to it, and the [window.opener](https://developer.mozilla.org/en-US/docs/Web/API/Window/opener) property of the new window will be null. This allows you to have more control over references to a window than [rel=noopener](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/rel/noopener), which only affects outgoing navigations.</q>
Documentation about COOP:
[COOP Header , read here](
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cross-Origin-Opener-Policy)
<hr …
=> [UXE-3943] fix: change Secure Headers Cross Origin Opener Policy from same-origin to same-origin-allow-popups

cypress/e2e/edge-dns.cy.js, cypress/support/commands.js, cypress/support/selectors.js, src/templates/list-table-block/no-header.vue, src/templates/list-table-block/with-lazy-and-dropdown-filter.vue, src/views/EdgeDNS/EditView.vue, src/views/EdgeDNS/FormFields/FormFieldsRecords.vue
- Add data-testid selectors related to edge dns test flow
- Create cypress command to delete entity from loaded table
- Create e2e for `record type A`
- Create e2e for `record type AAAA`
- Create e2e for `record type ANAME`
- Create e2e for `record type CAA`
- Create e2e for `record type CNAME`
- Create e2e for `record type DS`
- Create e2e for `record type MX`
- Create e2e for `record type NS`
- Create e2e for `record type PTR`
- Create e2e for `record type SRV`
- Create e2e for `record type TXT`
https://github.com/aziontech/azion-console-kit/assets/95643165/19f39938-a1f6-43bb-8162-172ea80acfab
<hr />
=> [UXE-3962] test: create e2e for edge dns records

azion.config.cjs
Fix problem with github integration pop-up. Since the COOP policy was blocking the postMassage communication between Console and opened pop-up.
<hr />
=> [UXE-3943] fix: change Cross-Origin-Opener-Policy to unsafe-none to avoid blockin Github pop-up

src/templates/list-table-block/columns/text-full-with-clipboard-column.vue
Removed define props since it is global and generate a console warning in local environments
Not necessary
<hr />
=> [NO-ISSUE] chore: remove unnecessary import of define props at text-full-width-clipboard column

cypress/e2e/teams-permissions.cy.js, cypress/support/selectors.js
- Add e2e teams permissions (view only)
- Update selectors
https://github.com/aziontech/azion-console-kit/assets/95643165/de4658ff-593b-41f5-906c-f98b8791d808
No
<hr />
=> [UXE-3946] test: add e2e teams permissions (view only)

cypress.config.js, cypress/e2e/variables.cy.js, cypress/support/selectors.js, src/views/Variables/FormFields/FormFieldsVariables.vue
- Create e2e for editing variable flow
https://github.com/aziontech/azion-console-kit/assets/95643165/3a9d50de-3ddc-4afd-a5b8-98266244f9bb
<hr />
=> [UXE-3957] test: e2e for variable edition with secrets

cypress/e2e/waf.cy.js, cypress/support/selectors.js, src/views/WafRules/FormFields/FormFieldsWafRules.vue
- Refactor base waf test to receive more scenarios
- Create e2e for waf rules with some threat types enabled
[Manual workflow execution](https://github.com/aziontech/azion-console-kit/actions/runs/9894154294)
https://github.com/aziontech/azion-console-kit/assets/95643165/f722046e-c189-4d4a-88de-8f53c53ee905
No
<hr />
=> [UXE-3948] test: create e2e for waf rule with some threat types

src/templates/content-block/banner.vue, src/templates/content-block/index.vue, src/templates/content-block/project-stage-message-block.vue
move project access stage message to its own block to avoid DRY between Content block and Banner Block ( only used in Marketplace)
No.
https://github.com/user-attachments/assets/7a4bc57f-4c18-4d17-bcd6-71123258c4d4
<hr />
=> [NO-ISSUE] refactor: move preview message to its own block

src/tests/helpers/azion-documentation-window-opener.test.js
This is a required refactor of the unit tests for the Azion Documentation helper. It ensures that when a developer changes the destination URL, the related unit tests and their functions will fail. This will show the developer the impact of changing a URL, helping to avoid introducing incorrect behaviors by not understanding the related points to that URL.
NO
NO
<hr />
=> [NO-ISSUE] test: ensure to use fixed string to show url change impacts on azion documentation helper function

src/views/Billing/PaymentListView.vue, src/views/Billing/TabsView.vue
[UXE-3698] refactor: load the default credit card when bill tab it is active
<hr />
[UXE-3698]: https://aziontech.atlassian.net/browse/UXE-3698?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [UXE-3698] refactor: load the default credit card when bill tab it is active

src/views/DataStream/FormFields/FormFieldsDataStream.vue, src/views/EdgeNode/Drawer/index.vue
1) Rename drawer title to correct text. 
2) Add max and min values to Data streaming payload size field to improve UX by avoiding to use numbers outside of the valid range of payload size.
yes, in Data Streaming only:
Data Streaming :
https://github.com/user-attachments/assets/dfa5a5f5-8897-4722-9303-b45606bef906
<hr />
=> [UXE-3318] fix: rename edge node drawer title to Bind Service

src/views/DataStream/FormFields/FormFieldsDataStream.vue
Remove add button when there is already 5 custom headers (api doesnt accept more than 5)
<hr />
=> [UXE-3592] fix: limit custom header in 5 items

src/services/digital-certificates-services/create-digital-certificates-csr-service.js, src/services/digital-certificates-services/create-digital-certificates-service.js, src/services/digital-certificates-services/edit-digital-certificates-service.js, src/tests/services/digital-certificates-services/create-digital-certificates-csr-service.test.js, src/tests/services/digital-certificates-services/create-digital-certificates-service.test.js, src/tests/services/digital-certificates-services/edit-digital-certificates-service.test.js
Parse correctly digital certificate error message
<hr />
=> [UXE-3804] fix: format correctly digital certificates error messages

src/views/Signup/SignupView.vue
Change spaces in sign up page to fit responsiveness in bigger screens
<hr />
=> [UXE-3686] fix: change spaces in sign up page

src/views/Marketplace/MarketplaceHomeView.vue
remove the category query when the filter is all
<hr />
=> [UXE-3455] fix: remove the category query when the filter is all

src/templates/list-table-block/index.vue, src/tests/services/billing-services/load-your-service-plan-service.test.js, src/views/EdgeApplicationsRulesEngine/ListView.vue, src/views/EdgeFirewallRulesEngine/ListView.vue
Ensure that  the Edge application - Rules Engine - Response phase list is updated after a successfully creation .
- Fix empty search results message
- fix flaky test implementation of load-your-service-plan-service, by using vitest fake timers instead of the production code using JS Date Class.
- remove dead code inside list-template-block by removing unused slot 
Yes
https://github.com/user-attachments/assets/af87bba6-74d2-428f-ac05-5c4e1b6376c8
<hr />
=> [UXE-4335] fix: update rules engine list response phase after success creation

src/views/Variables/FormFields/FormFieldsVariables.vue, src/views/Variables/ListView.vue
Block edit redirection when a variable is a secret and add a message to the form informing that secrets are not editable
https://github.com/user-attachments/assets/aa1bd302-f28e-4eb1-9860-e4851d6cd9ce
<hr />
=> [UXE-4039] fix: Unable edit to secret variables

src/services/edge-application-origins-services/create-origin-service.js, src/services/edge-application-origins-services/edit-origin-service.js, src/tests/services/edge-application-origins-services/create-origin-service.test.js, src/tests/services/edge-application-origins-services/edit-origin-service.test.js, src/views/EdgeApplicationsOrigins/Drawer/index.vue
Remove / from prefix field in edge application origins forms
<hr />
=> [UXE-4165] fix: double / from prefix field in Edge App Edge Storage Origins

src/templates/advanced-filter/dialog-filter.vue, src/templates/advanced-filter/index.vue, src/views/RealTimeMetrics/blocks/content-filter-block.vue, src/views/RealTimeMetrics/blocks/interval-filter-block.vue
[UXE-3625]
add h-[2.323rem] in px(37) in the advanced filter component
<hr />
[UXE-3625]: https://aziontech.atlassian.net/browse/UXE-3625?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [UXE-3625] refactor: add h-[2.323rem] in px(37) in the advanced filter component

src/services/waf-rules-services/create-waf-rules-allowed-tuning-service.js, src/tests/services/waf-rules-services/create-waf-rules-allowed-tuning-service.test.js
fix: add the cookie value to zone_input when the attack is a cookie
https://github.com/user-attachments/assets/c15186dc-7ddd-47fc-aaa2-f38665fafe72
<hr />
=> [UXE-3366] fix: set cookie value to zone_input when the attack is a cookie

cypress/e2mock/teams-permissions.cy.js, src/services/team-permission/load-team-permission-service.js, src/templates/edit-form-block/index.vue, src/tests/services/team-permission-services/load-team-permission-service.test.js, src/views/TeamsPermissions/EditView.vue
Block users withous permission of acessing team permissions edit page
https://github.com/user-attachments/assets/ee67cef1-c50d-4f4b-8924-b3880f7267ac
<hr />
=> [UXE-4473] fix: block users without permission of acessing team permissions edit page

src/views/Domains/ListView.vue
Remove digital certificate colum from domains list
<hr />
=> [UXE-4503] fix: remove digital certificate column from domains list view

src/services/edge-firewall-rules-engine-services/load-edge-firewall-rules-engine-service.js, src/tests/services/edge-firewall-rules-engine-services/load-edge-firewall-rules-engine-service.test.js
[UXE-4291] 
fix: convert the argument type from criteria to string
https://github.com/user-attachments/assets/ad6dd26b-7f3a-43ac-b0df-ac7b12a9d8d6
<hr />
[UXE-4291]: https://aziontech.atlassian.net/browse/UXE-4291?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [UXE-4291] fix: convert the argument type from criteria to string on the edge firewall rules engine

src/views/Domains/FormFields/FormFieldsCreateDomains.vue, src/views/Domains/FormFields/FormFieldsEditDomains.vue
Remove beta tag from lets encrypt options in domains
<hr />
=> [UXE-4638] feat: remove beta tag from lets encrypt

src/views/EdgeApplicationsRulesEngine/FormFields/FormFieldsEdgeApplicationsRulesEngine.vue
Open accordions with field with errors inside to focus on it.
<hr />
https://github.com/user-attachments/assets/6e810c04-d452-4202-8852-5297df785e73
=> [NO-ISSUE] fix: open accordion when there is error in fields inside it

src/helpers/metrics-playground-opener.js, src/services/edge-application-device-groups-services/create-device-group-service.js, src/services/edge-application-device-groups-services/edit-device-group-service.js, src/views/EdgeApplicationsDeviceGroups/Drawer/index.vue
* create and edit track event - Edge Application -> Device Groups
* failed to create and edit track event - Edge Application -> Device Groups
* fix playground metrics url
* [UXE-2204](https://aziontech.atlassian.net/browse/UXE-2204)
<hr />
[UXE-2204]: https://aziontech.atlassian.net/browse/UXE-2204?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [UXE-1908] feat: added create and edit track events in edge applications device groups

src/views/EdgeApplicationsDeviceGroups/ListView.vue
* added clicked to create and clicked to edit in edge app -> device groups list
<hr />
=> [UXE-1907] [UXE-1910] feat: added clicked to create and edit track events in device groups

src/views/EdgeApplicationsCacheSettings/ListView.vue, src/views/EdgeApplicationsDeviceGroups/ListView.vue
* click to create and edit track events in cache settings
<hr />
=> [UXE-2060][UXE-2063] feat: added clicked to create and edit track events in edge applications cache settings

src/templates/info-drawer-block/info-labels/big-number.vue, src/views/RealTimeEvents/Blocks/tab-panel-block.vue, src/views/RealTimeEvents/Drawer/httpRequests.vue
- update styles for big-number and tab-panel-block components
https://www.figma.com/design/0TY2pcUTBsndMlrs0ZUvQf/Console-UI?node-id=7976-158788&node-type=FRAME&t=yPO1vEFPTKQfKkBB-0
<hr />
=> [UXE-4857] fix: update styles for big-number and tab-panel-block components

src/templates/list-table-block/index.vue
the sorting was not working the behavior is that when moving the rules the sorting works
https://jam.dev/c/d49236ba-3603-450f-882c-720031a024f3
<hr />
=> [UXE-4901] fix: reorder rules engine list table block

package.json, yarn.lock
The dependencie below it is not more used.
``` json
{
"primevue-sass-theme": "git+https://github.com/primefaces/primevue-sass-theme.git#3.39.0",
}
```
We stop the use with the [azion-theme](https://github.com/aziontech/azion-theme) migration.
=> [NO-ISSUE] chore: remove unused dependencie

src/services/edge-application-error-responses-services/make-edge-application-error-responses-base-url.js, src/tests/services/edge-application-error-responses/edit-error-responses-services.test.js, src/tests/services/edge-application-error-responses/list-error-responses-service.test.js, src/views/EdgeApplicationsErrorResponses/EditView.vue, src/views/EdgeApplicationsErrorResponses/FormFields/FormFieldsErrorResponses.vue
enable the origin field only when the page path is filled
https://jam.dev/c/af34c383-bb41-4d8f-a0ec-cc1c2211dc8b
<hr />
=> [UXE-4867] fix: enable the origin field only when the page path is filled

package.json, src/modules/real-time-metrics/constants/reports.js, src/tests/modules/real-time-metrics/constants/reports.test.js, src/tests/modules/real-time-metrics/reports/fixtures/gql-fixtures.js
Adjust bot traffic report query limit from 5000 to 10000. As the API returns an array of items, the chart displays the incorrect amount of points.
`24 hours * 60 min = 1440 ts points * 4 itens per point = 5760 items`
<hr />
=> [UXE-5056] fix: resolve limit in gql

package.json, src/modules/real-time-metrics/constants/reports.js, src/modules/real-time-metrics/reports/convert-beholder-to-chart.js, src/modules/real-time-metrics/reports/load-report-variation.js, src/services/real-time-purge/make-real-time-purge-service.js, src/templates/graphs-card-block/components/chart/big-numbers-chart.vue, src/tests/modules/real-time-metrics/constants/reports.test.js, src/tests/modules/real-time-metrics/reports/fixtures/gql-fixtures.js, src/tests/services/real-time-purge/create-real-time-purge.test.js, src/tests/services/real-time-purge/make-real-time-purge.test.js, src/views/AccountSettings/AccountSettingsView.vue, src/views/RealTimePurge/Dialog/index.vue, src/views/RealTimePurge/ListView.vue, src/views/WafRules/ListWafRulesAllowed.vue
- [NO-ISSUE] chore: update project version to 1.22.2
- [UXE-4923] feat: add account settings events to tracker
- [ISSUE-4838] feat: adding compare-with-azion POC product
- [UXE-4912] feat: add WAF Allowed rules events to tracker
- [UXE-4767] fix: console re purge toast shown without confirm click
- [UXE-5056] fix: resolve limit in gql
- [UXE-4805] fix: table button redirecting to home when the drawer is being loaded
- [UXE-4867] fix: enable the origin field only when the page path is filled
- [UXE-5059] fix: resolve general validation issues in bot manager dashboard
- [UXE-5080] fix: adjusting the real time purge product api contract
- [NO-ISSUE] refactor: general changes in bot manager reports
<hr />
[UXE-4923]: https://aziontech.atlassian.net/browse/UXE-4923?atlOrigin=eyJpIjoiNWRkNTljNzY …
=> DEPLOY 2024.09.24

src/services/compare-with-azion/get-test-from-webpagetest.js, src/services/compare-with-azion/get-test.js, src/views/CompareWithAzion/CompareView.vue, src/views/CompareWithAzion/blocks/data-block.vue, src/views/CompareWithAzion/blocks/grade-block.vue, src/views/CompareWithAzion/blocks/retry-message.vue, src/views/CompareWithAzion/blocks/security-block.vue, src/views/CompareWithAzion/utils/convert-ms-sec.js, src/views/CompareWithAzion/utils/result-data-parse.js
- Invalid Client Id Message
- Message when it is propagating data in the Edge SQL, the consolidation information. But if the invalid ID too will maintain the same message because we cant know the difference until fix the propagation.
- Test Retry during Testing
- params renamed
- let to const
- computed
- removed unused functions prepared functions, can not mantain helpers for future
> TODO: in the next refactor we will adjust the services
=> [UXE-5079] feat: retry counter and button to Compare With Azion

src/services/billing-services/list-payment-history-service.js, src/tests/services/billing-services/list-payment-history-service.test.js
This pull request includes changes to the `list-payment-history-service` in both the implementation and its corresponding tests. The main modifications involve renaming a key in the API response from `data` to `results`.
<hr />
=> [NO-ISSUE] fix: improvement parse contract for service billing

src/plugins/analytics/trackers/ProductTracker.js, src/tests/plugins/analytics/AnalyticsTrackerAdapter.test.js, src/tests/services/data-stream-services/list-data-stream-domains-service.test.js, src/tests/services/data-stream-services/list-data-stream-template-service.test.js, src/tests/services/edge-application-functions-services/create-edge-application-functions-service.test.js, src/tests/services/edge-firewall-functions-services/edit-function-service.test.js, src/tests/services/edge-firewall-rules-engine-services/delete-edge-firewall-rules-engine-service.test.js, src/views/EdgeFunctions/ListView.vue, src/views/NetworkLists/ListView.vue, src/views/PersonalTokens/ListView.vue, src/views/RealTimePurge/CreateView.vue, src/views/RealTimePurge/ListView.vue, src/views/TeamsPermissions/ListView.vue, src/views/Users/ListView.vue, src/views/Variables/ListView.vue, src/views/WafRules/ListView.vue
[UXE-5133] feat: add purge tracker events
Foram adicionados eventos de tracker "Clicked to" em várias listagem nas quais não há itens, e o bloco "empty" é exibido nas seguintes telas:
- Edge Functions
- Network List
- Personal Token
- Teams Permissões
- Users
- Variables
- WAF
<hr />
[UXE-5133]: https://aziontech.atlassian.net/browse/UXE-5133?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [UXE-5133] feat: add purge tracker events

cypress/e2e/domains/create-domain-edge-application.cy.js, src/services/edge-application-services/create-edge-application-service.js, src/views/Domains/FormFields/FormFieldsCreateDomains.vue, src/views/Domains/FormFields/FormFieldsEditDomains.vue, src/views/EdgeApplications/Drawer/index.vue
Select Created app when the drawer is closed
<hr />
=> [UXE-4538] fix: select created app when drawer close

azion/stage/azion.json
This pull request includes changes to the `azion/stage/azion.json` file, focusing on cleaning up unused origins and rules. The most important changes involve the removal of specific origins and rules that are no longer necessary.
Cleanup of unused origins and rules:
* [`azion/stage/azion.json`](diffhunk://#diff-7d0327cdd86a77f061f2dea4f5dbe068a42499bfd8e8624d68329caa992611b2L71-L75): Removed the "origin-console-ai" origin entry.
* [`azion/stage/azion.json`](diffhunk://#diff-7d0327cdd86a77f061f2dea4f5dbe068a42499bfd8e8624d68329caa992611b2L160-L164): Removed the "Route Send Message to Copilot" rule entry.
=> [NO-ISSUE] chore: remove unused origin and rule from azion json for ai

src/modules/azion-ai-chat/azion-ai-chat-header-block.vue, src/modules/azion-ai-chat/azion-ai-chat-mobile.vue
This pull request includes changes to the `azion-ai-chat` module to update the status message of the Copilot feature from "Experimental" to "Preview" and simplify the related code.
Updates to status message:
* [`src/modules/azion-ai-chat/azion-ai-chat-header-block.vue`](diffhunk://#diff-de62b9a090d9c598a1d43b8edf01f5f4984828d841631e4eb84a8b49bc3e2e20R8-L11): Changed the `PrimeTag` value from "Experimental" to "Preview" and updated the tooltip message to reflect the new status.
* [`src/modules/azion-ai-chat/azion-ai-chat-mobile.vue`](diffhunk://#diff-cde0ed04cbd814c5545964291d71f71e04d307ac85454f44f3e7757fdbde3172L19-R23): Updated the `PrimeTag` value and tooltip message to indicate that Copilot is now in "Preview" mode instead of "Experimental".
Code simplification:
* …
=> [UXE-4942] feat: update Copilot tooltip message in AI Chat components

src/modules/azion-ai-chat/azion-ai-chat-block.vue
This pull request includes a small but important change to the `src/modules/azion-ai-chat/azion-ai-chat-block.vue` file. The change ensures that credentials are included in the request to the AI chat service.
* [`src/modules/azion-ai-chat/azion-ai-chat-block.vue`](diffhunk://#diff-32bfa2b2e4460fc0b3c1e942acb6259c3c89b7c6a5b4343f4241fa0fbdc6397aL86-R87): Added `credentials: 'include'` to the `DEEP_CHAT_CONFIG_REQUEST` to ensure that credentials are sent with the request.
=> [NO-ISSUE] feat: add credentials option to DEEP_CHAT_CONFIG_REQUEST

src/templates/empty-results-block/index.vue, src/views/WafRules/ListWafRulesTuning.vue
fix: adjust loop requests waf filter
must perform the filter without the requests loop
https://jam.dev/c/220e26de-bc07-4fc1-8dc7-b8cc27fc9608
<hr />
=> [UXE-5512] fix: adjust loop requests waf filter

src/services/billing-services/list-service-and-products-changes.js
invoice details section not load values service and product charges
should render the list with values service and product charges
<hr />
=> [UXE-4355] fix: invoice details section not load values service and product charges

cypress/e2mock/edge-application/list-edge-applications.cy.js, cypress/fixtures/edge-application/edge-applications-paginated.json, cypress/support/selectors/block-selectors/list-table-block.js, src/templates/list-table-block/with-fetch-ordering-and-pagination.vue, src/views/EdgeApplicationsRulesEngine/ListView.vue
This pull request fixes a bug in the `with-fetch-ordering-and-pagination.vue` file where pagination was not working correctly. 
- **Pagination Fix**: Added the `firstItemIndex` parameter to track the index of the first item on the current page and adjusted the `reload` function to include this parameter. 
- **Search Adjustment**: Improved the search functionality to only trigger when `props.lazy` is `true`.
- **Code Refactoring**: Refactored the `moveItem` function by renaming the `originalArray` parameter to `originalData` and creating a copy of the original array for better clarity.
- **Rule Reordering Logic**: Simplified the rule reordering logic in `ListView.vue` by removing redundant checks and ensuring that the default rule cannot be reordered.
<hr />
=> [NO-ISSUE] fix: correction in pagination in tables with api v4

src/templates/content-block/banner.vue
[UXE-5748](https://aziontech.atlassian.net/browse/UXE-5748) fix: Marketplace view broken
[[UXE-5721]: https://aziontech.atlassian.net/browse/UXE-5721?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ](https://aziontech.atlassian.net/browse/UXE-5748)
[UXE-5748]: https://aziontech.atlassian.net/browse/UXE-5748?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [UXE-5748] fix: Marketplace view

src/views/EdgeApplicationsCacheSettings/FormFields/FormFieldsEdgeApplicationCacheSettings.vue
When editing an a cache setting with large file optimization enabled, trying to disable it, the payload was being sent without the slice_edge_caching_enabled causing an error
<hr />
=> [UXE-5716] fix: send payload correctly when large file optimization is not enabled

cypress/e2mock/edge-application/list-edge-applications.cy.js, cypress/fixtures/edge-application/edge-applications-ordering-name.json, cypress/fixtures/edge-application/edge-applications.json, src/templates/list-table-block/with-fetch-ordering-and-pagination.vue
The issue where pagination was not reset when changing the sorting order in the with-fetch-ordering-and-pagination.vue component has been fixed. Now, when the sorting criteria are modified, the first page index is reset, ensuring users are directed to the first page of the sorted results. Additionally, tests were improved with more realistic datasets, increasing from 4 to 100 entries with diverse names and dates to better simulate real-world scenarios. Cypress tests were updated to validate pagination and sorting functionality, checking the active page state and ensuring results are displayed correctly.
https://github.com/user-attachments/assets/33e455e8-d803-4b64-974a-6990d29bf11d
<hr />
=> [NO-ISSUE] fix: resolve pagination issue when sorting columns

src/services/waf-rules-services/create-waf-rules-allowed-tuning-service.js, src/tests/services/waf-rules-services/create-waf-rules-allowed-tuning-service.test.js, src/views/WafRules/Dialog/index.vue, src/views/WafRules/ListWafRulesTuning.vue
[UXE-5779] fix: create allowed rules by tuning page
https://github.com/user-attachments/assets/46a02cc3-db4e-4687-a32c-39a9220fc932
<hr />
[UXE-5779]: https://aziontech.atlassian.net/browse/UXE-5779?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [UXE-5779] fix: create allowed rules by tuning page

src/services/domains-services/v4/list-domain-service.js, src/services/waf-rules-services/create-waf-rules-service.js, src/tests/services/domains-services/v4/list-domain-service.test.js, src/tests/services/waf-rules-services/create-waf-rules-service.test.js
[UXE-5138] fix: waf rules not triggering toast error
https://github.com/user-attachments/assets/98b2636d-3824-4018-af05-72aed4f4b41c
<hr />
[UXE-5138]: https://aziontech.atlassian.net/browse/UXE-5138?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [UXE-5138] fix: waf rules not triggering toast error

src/services/edge-firewall-rules-engine-services/v4/load-edge-firewall-rules-engine-service.js, src/tests/services/edge-firewall-rules-engine-services/v4/load-edge-firewall-rules-engine-service.test.js
https://github.com/user-attachments/assets/649d4903-1d0d-43c7-972e-8082c1dd1a91
<hr />
=> [UXE-5760] fix: update edge firewall rules engine to use 'active' property instead of 'is_active'

src/stores/account.js, src/views/DataStream/EditView.vue, src/views/DataStream/FormFields/FormFieldsDataStream.vue, src/views/DataStream/ListView.vue
Ao ter permissão de VIEW para Data Stream, todos os botões/inputs são desativados e uma mensagem é exibida.
Melhoria na concorrência de loading da página de Data Stream, afim de evitar erros de execução do JavaScript.
<hr />
=> [UXE-5850] feat: Data Stream - disable inputs/buttons for users without edit permissions

src/templates/form-fields-inputs/fieldDropdownLazyLoader.vue, src/views/EdgeApplicationsFunctions/FormFields/FormFieldsEdgeApplicationsFunctions.vue, src/views/EdgeFirewallFunctions/FormFields/FormFieldsEdgeApplicationsFunctions.vue
feat: add disable first render prop to lazy loader for improved control over initial emit behavior
should not emit args on first load for edge firewall function instance and edge application function instance
https://jam.dev/c/926f51ed-8fc7-4019-89f7-37af9b0f2986
<hr />
=> [UXE-5953] fix: Edge Function Instance Json Args is overwritten

src/services/edge-application-rules-engine-services/v4/edit-rules-engine-service.js, src/services/edge-application-rules-engine-services/v4/helper-criteria.js, src/tests/services/edge-application-rules-engine-services/v4/create-rules-engine-service.test.js, src/tests/services/edge-application-rules-engine-services/v4/edit-rules-engine-service.test.js
incorrect argument when saving criteria rules engine
should save exists and do_not_exists criteria without errors and without arguments
NO
<hr />
=> [UXE-5966] fix: incorrect argument when saving criteria rules engine

src/views/EdgeFirewallRulesEngine/FormFields/FormFieldsEdgeFirewallRulesEngine.vue
This pull request includes a minor correction in the `FormFieldsEdgeFirewallRulesEngine.vue` file. The change corrects a typo in one of the label values to ensure consistency and accuracy.
* [`src/views/EdgeFirewallRulesEngine/FormFields/FormFieldsEdgeFirewallRulesEngine.vue`](diffhunk://#diff-c5cb401b82e409e087ec860087ce449709bd715129595ada980cc377b6391d9fL106-R106): Corrected the label value from `does_not_starts_with` to `does_not_start_with`.
<hr />
=> [UXE-5976] fix: correct typo in 'does not start with' label on edge firewall

src/templates/empty-results-block/empty-edge-node.vue, src/tests/services/edge-application-rules-engine-services/v4/edit-rules-engine-service.test.js
[UXE-5739] Fix: adjusting the layout of the buttons on the empty block edge node
<hr />
[UXE-5739]: https://aziontech.atlassian.net/browse/UXE-5739?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [UXE-5739] Fix: adjusting the layout of the buttons on the empty block edge node

src/views/EdgeFunctions/EditView.vue, src/views/EdgeFunctions/FormFields/FormFieldsEditEdgeFunctions.vue
Foi alterado o título da página de Edit Edge Functions para receber o nome da function, no lugar do label genérico "Edit Edge Functions"
No.
<hr />
=> [UXE-5366] fix: standardize  edge functions titles to display item names instead of product names

src/router/routes/real-time-purge/index.js
O nome da real-time-purge estava conflitando com o primeiro item do array, fazendo o Vite renderizar o primeiro hit, o qual não tem uma página associada. 
<hr />
=> [UXE-5824] fix: real-time-purge route name conflict

src/services/edge-firewall-rules-engine-services/v4/create-edge-firewall-rules-engine-service.js, src/services/edge-firewall-rules-engine-services/v4/edit-edge-firewall-rules-engine-service.js, src/services/edge-firewall-rules-engine-services/v4/load-edge-firewall-rules-engine-service.js, src/services/edge-firewall-rules-engine-services/v4/parser-utils.js, src/templates/form-fields-inputs/fieldDropdownIcon.vue, src/tests/services/edge-firewall-rules-engine-services/v4/edit-edge-firewall-rules-engine-service.test.js, src/tests/services/edge-firewall-rules-engine-services/v4/load-edge-firewall-rules-engine-service.test.js, src/tests/services/edge-firewall-rules-engine-services/v4/parser-utils.test.js, src/views/EdgeFirewallRulesEngine/FormFields/FormFieldsEdgeFirewallRulesEngine.vue
This pull request includes several changes to the edge firewall rules engine services and related components. The main changes involve adding a new `parseCriteria` function to handle criteria parsing, updating criteria variable names to use template literals, and enhancing test coverage for these changes.
* Added `parseCriteria` function to transform criteria arguments based on their variables in `create-edge-firewall-rules-engine-service.js` and `edit-edge-firewall-rules-engine-service.js` [[1]](diffhunk://#diff-b389e71e4ade07de541111799faf035dc8f5626147318b11d476f6ed6b584a80R71-R94) [[2]](diffhunk://#diff-b206e511bbe034d351bf8ca437056d9673e0f36b4d99ab5df5be82937411c4f2R72-R94).
* Updated criteria variable names to use template literals in `load-edge-firewall-rules-engine-service.js`.
* …
=> [HOTFIX][NO-ISSUE] fix: correct label typo, improve criteria parsing, and enhance tests in Edge Firewall Rules Engine

cypress/e2mock/edge-application/list-edge-applications.cy.js, src/templates/list-table-block/with-fetch-ordering-and-pagination.vue, src/tests/services/edge-application-rules-engine-services/v4/edit-rules-engine-service.test.js
Paginação não estava resetando ao atualizar a Data Table com novos dados após o delete. Agora, após o update da DOM, a Data Table checará os dados para garantir que a paginação está correta.
No.
<hr />
- [] Application responsiveness was tested to different screen sizes
=> [UXE-5943] fix: reset page firstElement when Data Table is updated  @lfsigreja

cypress/e2e/edge-application/add-origin.cy.js, cypress/e2e/edge-application/edit-origin.cy.js, cypress/e2e/edge-application/rules-engine/create-rule-engine-set-origin.cy.js, cypress/support/selectors/product-selectors/edge-application.js, src/templates/dialog-copy-key/index.vue, src/views/EdgeApplicationsOrigins/Drawer/index.vue, src/views/EdgeApplicationsOrigins/FormFields/FormFieldsEdgeApplicationsOrigins.vue
Foi removido o campo Origin Key do drawer de criação de uma nova Origin. 
EDIT MODE:
CREATE MODE:
<hr />
- [] New tests are added to prevent the same issue from happening again
=> [UXE-5045] fix: remove origin key from origin creation via drawer

src/helpers/get-static-urls-by-environment.js, src/plugins/analytics/trackers/ProductTracker.js, src/tests/helpers/get-static-urls-by-environment.test.js, src/tests/plugins/analytics/AnalyticsTrackerAdapter.test.js, src/views/Home/HomeView.vue
This pull request introduces new functionality to track user interactions and updates the URLs for different environments. The key changes include adding a new section for manager EOL URLs, implementing a new tracking method for user clicks, and updating the HomeView component to reflect these changes.
The HomeView component now depends on the `managerEOL` URLs and the new `clickedTo` tracking method. Ensure the updated methods and URLs are available in all environments to prevent issues.
https://github.com/user-attachments/assets/3416d04c-5ea7-43b1-9c82-8b1c7d36a482
Yes, the HomeView component now includes an inline message with a button for RTM deprecation that navigates to the `managerEOL` URL and tracks click events.
No specific Figma link is provided for these changes.
---
=> [UXE-6013] feat: add Manager EOL URLs and User Interaction Tracking in HomeView

src/router/routes/switch-account-routes/index.js, src/services/users-services/list-teams-service.js, src/tests/services/users-services/list-teams-service.test.js, src/views/Users/FormsFields/FormFieldsUsers.vue
This pull request includes several changes to improve the functionality and user experience of the application. The primary improvements include enhancements to the account switching logic, updates to the `listTeamsService`, adjustments to related test cases, and user interface improvements for form fields.
**Enhancements to account switching logic:**
- Reformatted the parameters of the `switchAccountFromSocialIdp` function call for better readability.  
File: [`src/router/routes/switch-account-routes/index.js`](diffhunk://#diff-fa24f855ab1e1cf7480f920d2ec159bfe76562c762c37904ff054a5081d26f30L22-R26)
**Improvements to `listTeamsService`:**
- Added support for query parameters such as `fields`, `ordering`, `page`, `pageSize`, and `search` to allow more flexible API requests.  
File: …
=> [UXE-6069] fix: add account owner option to UI and adjust team listing behavior in view users

src/helpers/account-handler.js, src/router/routes/switch-account-routes/index.js, src/services/users-services/list-teams-service.js, src/stores/account.js, src/tests/services/users-services/list-teams-service.test.js, src/views/DataStream/EditView.vue, src/views/DataStream/FormFields/FormFieldsDataStream.vue, src/views/DataStream/ListView.vue, src/views/Users/FormsFields/FormFieldsUsers.vue
[UXE-5342] MFA for Azion SSO being requested for federated users
[UXE-6073] Edit Data Stream when user is account owner, but don’t have edit permission
[​​UXE-5975] Unable to Edit Data Stream existing endpoints
[UXE-6069] Unable/disable account owner for users on Console
<hr />
[UXE-5342]: https://aziontech.atlassian.net/browse/UXE-5342?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[UXE-6073]: https://aziontech.atlassian.net/browse/UXE-6073?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[UXE-6069]: https://aziontech.atlassian.net/browse/UXE-6069?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> DEPLOY 2025-01-21

cypress/e2e/edge-firewall/create-edge-firewall-network-list.cy.js, cypress/support/selectors/product-selectors/edge-firewall.js, src/router/routes/edge-firewall-routes/index.js, src/router/routes/switch-account-routes/index.js, src/services/network-lists-services/v4/index.js, src/services/network-lists-services/v4/list-network-list-service.js, src/services/network-lists-services/v4/load-network-list-service.js, src/templates/form-fields-inputs/fieldDropdownLazyLoaderDinaminc.vue, src/tests/services/network-lists-services/v4/load-network-list-service.test.js, src/views/EdgeFirewall/TabsView.vue, src/views/EdgeFirewallRulesEngine/Drawer/index.vue, src/views/EdgeFirewallRulesEngine/FormFields/FormFieldsEdgeFirewallRulesEngine.vue, src/views/EdgeFirewallRulesEngine/ListView.vue
fix: criteria empty argument in edge firewall rules engine
should load arguments in edge firewall rules engine
https://jam.dev/c/3f302aa3-b026-45b2-a340-94c11c284782
<hr />
=> [UXE-6083] fix: empty criteria argument for network lists in edge firewall rules engine

src/router/routes/edge-functions-routes/index.js, src/services/edge-functions-services/v4/create-edge-functions-service.js, src/services/edge-functions-services/v4/edit-edge-functions-service.js, src/services/edge-functions-services/v4/index.js, src/services/edge-functions-services/v4/load-edge-function-service.js, src/tests/services/edge-functions-services/v4/create-edge-functions-service.test.js, src/tests/services/edge-functions-services/v4/edit-edge-functions-service.test.js, src/tests/services/edge-functions-services/v4/load-edge-function-service.test.js, src/views/EdgeFunctions/CreateView.vue, src/views/EdgeFunctions/Drawer/index.vue, src/views/EdgeFunctions/EditView.vue, src/views/EdgeFunctions/FormFields/FormFieldsCreateEdgeFunctions.vue, src/views/EdgeFunctions/FormFields/FormFieldsEditEdgeFunctions.vue
Migrate edge function create, edit and get by id services to api v4
<hr />
=> [UXE-5890][UXE-5891] feat: migrate edge functions create/edit pages to api v4

cypress/e2e/network-lists/create-network-list-asn.cy.js, cypress/e2e/network-lists/create-network-list-countries.cy.js, cypress/e2e/network-lists/create-network-list-ip-cidr.cy.js, cypress/e2e/network-lists/edit-network-list-asn.cy.js, cypress/e2e/network-lists/edit-network-list-countries.cy.js, cypress/e2e/network-lists/edit-network-list-ip-cidr.cy.js, cypress/e2e/network-lists/network-lists.cy.js, src/router/routes/network-lists-routes/index.js, src/services/network-lists-services/v4/edit-network-list-service.js, src/services/network-lists-services/v4/index.js, src/services/network-lists-services/v4/load-network-list-service.js, src/tests/services/network-lists-services/v4/edit-network-list-service.test.js, src/tests/services/network-lists-services/v4/load-network-list-service.test.js
migrate network lists creation to api v4
<hr />
=> [UXE-6002] feat: migrate network lists edit to api v4

src/templates/form-fields-inputs/fieldDropdown.vue, src/templates/form-fields-inputs/fieldDropdownLazyLoader.vue, src/templates/form-fields-inputs/fieldDropdownLazyLoaderDinaminc.vue, src/views/EdgeFirewallRulesEngine/FormFields/FormFieldsEdgeFirewallRulesEngine.vue
fix: adjust alignment fields of criteria in edge firewall rules engine
should render with alignment correct
<hr />
=> [UXE-6039] fix: adjust alignment fields of criteria in edge firewall rules engine

src/services/data-stream-services/list-data-stream-service.js, src/services/digital-certificates-services/v4/list-digital-certificates-service.js, src/tests/services/digital-certificates-services/v4/list-digital-certificates-service.test.js
fix: checking if the fields exist in the edge certificates return
should render view digital certificates no erros
NO
<hr />
=> [UXE-6022] fix: checking if the fields exist in the edge certificates return

src/templates/form-fields-inputs/fieldDropdownLazyLoader.vue
fix: args is not being loaded in edge firewall and edge application
Should render correct arguments in edge firewall and edge application
<hr />
=> [UXE-6217] fix: args is not being loaded in edge firewall and edge app

src/services/contract-services/index.js, src/services/contract-services/load-products-list-service.js, src/services/edge-application-origins-services/create-origin-service.js, src/services/edge-application-origins-services/edit-origin-service.js, src/services/edge-application-origins-services/list-origins-service.js, src/services/edge-application-origins-services/load-origin-service.js, src/tests/services/edge-application-origins-services/create-origin-service.test.js, src/tests/services/edge-application-origins-services/edit-origin-service.test.js, src/tests/services/edge-application-origins-services/list-origins-service.test.js, src/views/EdgeApplicationsOrigins/Drawer/index.vue, src/views/EdgeApplicationsOrigins/FormFields/FormFieldsEdgeApplicationsOrigins.vue
add origin type live_ingest form to origin pages
<hr />
=> [UXE-6266] feat: add origin type live_ingest form to origin pages

.github/workflows/pre-merge.yml
=> [NO-ISSUE] chore: Disable e2e tests

src/modules/real-time-metrics/constants/help-center-urls.js, src/modules/real-time-metrics/constants/reports-texts.js, src/modules/real-time-metrics/constants/reports.js, src/tests/modules/real-time-metrics/constants/reports.test.js, src/tests/modules/real-time-metrics/reports/fixtures/gql-fixtures.js
add chart average request time
<hr />
=> [UXE-6129] feat: add chart average request time

src/router/routes/edge-dns-routes/index.js, src/services/data-stream-services/list-data-stream-service.js, src/services/edge-dns-records-services/v4/index.js, src/services/edge-dns-records-services/v4/list-records-service.js, src/services/edge-dns-records-services/v4/make-edge-dns-records-base-url.js, src/templates/list-table-block/with-fetch-ordering-and-pagination.vue, src/tests/services/edge-dns-records-services/v4/list-records-service.test.js, src/tests/services/edge-dns-records-services/v4/make-edge-dns-records-base-url.test.js, src/views/EdgeDNS/EditView.vue
migrate edge dns records list to api v4
<hr />
=> [UXE-6155] feat: migrate edge dns records list to api v4

src/modules/real-time-metrics/constants/help-center-urls.js, src/modules/real-time-metrics/constants/reports-texts.js, src/modules/real-time-metrics/constants/reports.js, src/modules/real-time-metrics/reports/convert-beholder-to-chart.js, src/templates/graphs-card-block/components/chart/list-chart.vue, src/templates/list-table-block/graphic.vue, src/templates/list-table-block/index.vue, src/tests/modules/real-time-metrics/constants/reports.test.js, src/tests/modules/real-time-metrics/reports/fixtures/gql-fixtures.js
- add Requests by Status and Upstream 
<hr />
=> [UXE-6134] feat: add Requests by Status and Upstream

src/views/Billing/BillsView.vue
fix: adjust check disable invoice details
should I disable the button only when the invoice id is empty or null
<hr />
=> [UXE-6373] fix: adjust check disable invoice details

.github/workflows/deploy-stage.yml
This pull request includes a change to the `.github/workflows/deploy-stage.yml` file to update the version of the Azion CLI being downloaded and installed.
* Updated the Azion CLI version from `2.5.3` to `1.36.1` in the `jobs:` section of the `.github/workflows/deploy-stage.yml` file.
=> [UXE-5949] chore: downgrade Azion CLI version to 1.36.1 in deployment workflow

src/stores/account.js, src/views/Home/HomeView.vue
This pull request includes changes to the `src/stores/account.js` and `src/views/Home/HomeView.vue` files. The main focus of these changes is to introduce a new feature flag and utilize it to control the visibility of a banner on the home view.
Feature flag additions and usage:
* [`src/stores/account.js`](diffhunk://#diff-5ed700a1574dab2e3c695a0c0d661d6e97c4f9d389a12fc15e3f94a9ad8bd4cbL24-R25): Added a new feature flag `FORCE_REDIRECT_TO_CONSOLE` to the `flags` object and implemented a new getter `isBannerVisible` to determine the visibility of a banner based on this flag. [[1]](diffhunk://#diff-5ed700a1574dab2e3c695a0c0d661d6e97c4f9d389a12fc15e3f94a9ad8bd4cbL24-R25) [[2]](diffhunk://#diff-5ed700a1574dab2e3c695a0c0d661d6e97c4f9d389a12fc15e3f94a9ad8bd4cbR65-R68)
Home view modifications:
* …
=> [UXE-6402] feat: implement banner visibility logic based on FORCE_REDIRECT_TO_CONSOLE flag

src/services/domains-services/v4/create-domain-service.js, src/services/domains-services/v4/edit-domain-service.js, src/services/domains-services/v4/load-domain-service.js, src/tests/services/domains-services/v4/edit-domain-service.test.js, src/views/Domains/FormFields/FormFieldsCreateDomains.vue, src/views/Domains/FormFields/FormFieldsEditDomains.vue
[UXE-6411] refactor: add null value to cipher suite option and minimum tls version
https://github.com/user-attachments/assets/763ecc90-2a6a-42b4-914c-7e3af56d6021
<hr />
[UXE-6411]: https://aziontech.atlassian.net/browse/UXE-6411?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [UXE-6411] refactor:  add null value to cipher suite option and minimum tls version

src/helpers/browser-back-button.js, src/helpers/index.js, src/templates/dialog-unsaved-block/index.vue, src/tests/helpers/browser-back-button.test.js
[UXE-6389] Fix: disable browser back in the edge app config page
https://github.com/user-attachments/assets/a1d625af-1cb4-4017-88f4-f3ce355f6582
<hr />
- [] Application responsiveness was tested to different screen sizes
[UXE-6389]: https://aziontech.atlassian.net/browse/UXE-6389?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [UXE-6389] Fix: disable browser back in the edge app config page

azion/production/azion.json
This pull request includes updates to the `azion/production/azion.json` file to enhance routing and cookie rewriting configurations. The most important changes include the removal of the `mode` property and the addition of several new routing rules.
Configuration updates:
* Removed the `mode` property from the configuration.
Routing rules enhancements:
* Added new routing rules for various phases, including requests and responses. These rules cover routing for SIEM Azion (BB) and rewriting cookies (`azrt`, `azsid`, `azat`) for both `azion.com` and `azionedge.net` domains.
NO
NO
<hr />
=> [NO-ISSUE] chore: add rules engine manually in IAC

.github/workflows/deploy-production.yml
This pull request includes a minor change to the deployment workflow configuration in the `.github/workflows/deploy-production.yml` file. The change adds a debug flag to the `azion deploy` command to enable more detailed logging during the deployment process.
* [`.github/workflows/deploy-production.yml`](diffhunk://#diff-99ce179d261b73100b5672f064452b508820755c8e043e7ea4de36b9ec943d94L34-R34): Added `--debug` flag to the `azion deploy` command to enable detailed logging.
=> [NO-ISSUE] chore: add debug flag to deployment command in production workflow

azion/production/azion.json
This pull request includes a change to the `azion/production/azion.json` file, adding a new rule to the rules engine configuration.
Configuration Update:
* [`azion/production/azion.json`](diffhunk://#diff-833eec6e5fc3266bdc84658afe15142471143bc31f5f7d60ad5f29668b94fadbR75-R79): Added a new rule with ID 269747 to enable gzip during the response phase.
=> [NO-ISSUE] feat: add gzip enable rule to rules engine configuration

src/router/hooks/guards/billingGuard.js
This pull request includes a small change to the `billingGuard` function in the `src/router/hooks/guards/billingGuard.js` file. The change allows navigation to the 'account-settings' route even if a payment review is pending.
* [`src/router/hooks/guards/billingGuard.js`](diffhunk://#diff-a0954bd42eccb244c3dbac572b222e158217edfff9a88c9485befe7d4f41466dR29-R31): Added a condition to allow access to the 'account-settings' route when `paymentReviewPending` is true.
<hr />
=> [UXE-6467] fix: allow account settings access during payment review

azion.config.mjs, vite.config.js
This pull request includes changes to improve the handling of environment-specific configurations and domain transformations in the project. The most important changes include modifying the `azion.config.mjs` file to handle stage-specific domain transformations more effectively and updating the `vite.config.js` file to dynamically set domain suffixes based on the environment.
Improvements to environment-specific configurations:
* [`azion.config.mjs`](diffhunk://#diff-ebc6e887876c44245c813b133d1625750c81b15fa29591b239a6c220aefc35c7L4-R19): Enhanced the `addStagePrefix` function to handle stage-specific domain transformations, including a special case for the 'cities.azion.com' domain.
Updates to domain handling in configuration:
* …
=> [NO-ISSUE] refactor: enhance stage environment handling for origin cities

src/services/waf-rules-services/list-waf-rules-tuning-service.js, src/tests/services/waf-rules-services/list-waf-rules-tuning-service.test.js, src/views/WafRules/ListWafRulesTuning.vue
add total records found tag in waf rules tunning page
<hr />
=> [UXE-6354] feat: add total records found tag in waf rules tunning page

azion/stage/azion.json
This pull request includes several changes to the `azion/stage/azion.json` file, focusing on modifying routing rules and removing the `mode` property. The most important changes are summarized below:
Changes to routing rules:
* Removed the routing rule for "GraphQL Billing Queries to Manager Origin".
* Removed the routing rule for "GraphQL Accounting Queries to Manager Origin".
* Added a new routing rule for "API Version 4 Routing".
Other changes:
* Removed the `mode` property from the configuration.
=> [NO-ISSUE] chore: remove GraphQL Billing and Accounting route configurations

src/services/real-time-events-service/get-total-records.js, src/tests/services/real-time-events-service/get-total-records.test.js
This pull request includes updates to the `getTotalRecords` function and its corresponding test to add a `baseURL` parameter to the HTTP request configuration.
Changes include:
* [`src/services/real-time-events-service/get-total-records.js`](diffhunk://#diff-0527528c5005aa009de9b4ab881d3fe3282f7d72509876817f49a4310231e1f1R14): Added `baseURL: '/'` to the HTTP request configuration in the `getTotalRecords` function.
* [`src/tests/services/real-time-events-service/get-total-records.test.js`](diffhunk://#diff-b4f87b5372e7f3b3cb325b0ed6140ed35a889d4e533cfcb98500fb2c84d005d2R59): Added `baseURL: '/'` to the expected HTTP request configuration in the `getTotalRecords` test.
=> [NO-ISSUE] fix: update getTotalRecords service with baseURL configuration

azion/production/azion.json
This pull request includes changes to the `azion/production/azion.json` file, focusing on the routing configurations for various GraphQL queries and API requests. The most important changes include the removal of specific GraphQL query routes and the addition of a new API routing configuration.
Changes to routing configurations:
* Removed routing configuration for "Route GraphQL Billing Queries to Manager Origin"
* Removed routing configuration for "Route GraphQL Accounting Queries to Manager Origin"
* Added new routing configuration for "API Version 4 Routing"
=> [NO-ISSUE] chore: add API Version 4 routing configuration

azion/production/azion.json, src/services/real-time-events-service/get-total-records.js, src/tests/services/real-time-events-service/get-total-records.test.js
=> DEPLOY 2025-02-25 2

src/App.vue
This pull request includes changes to the `src/App.vue` file to enhance the tracking of account information by adding more detailed traits. The most important changes are:
* Expanded the destructuring assignment of `accountStore.account` to include `company_name`, `kind`, `full_name`, and `status`.
* Updated the `defaultTraits` object to include additional properties: `client_name`, `account_company_name`, `account_name`, `account_type`, and `client_status`.
NO
<hr />
=> [UXE-6322] feat: add new properties for identify tracking

src/services/real-time-events-service/http-request/list-http-request.js, src/tests/services/real-time-events-service/http-request/list-http-request.test.js
Most of the time, Errors on GraphQL events API  occours because timeout or size of the response in list of http events.
There is no need to fetch 10.000 lines with no filter and show in a UI. No user will search manually through 100 pages of 100 records.
So If there is no good argument for this limit be 10k, let's reduce it to 1k. That means: 100 pages of 10 records or 10  pages of 100. If the user need to find something specific, he will use filters.
No
No
<hr />
=> [NO-ISSUE] chore: Reduce Real Time Events limits (Http Requests)

src/templates/form-fields-inputs/fieldDropdownLazyLoaderDinaminc.vue, src/views/EdgeFirewallRulesEngine/Drawer/index.vue, src/views/EdgeFirewallRulesEngine/FormFields/FormFieldsEdgeFirewallRulesEngine.vue
Allow users without waf permissions to edit a rule that has a set waf rule behavior
<hr />
=> [UXE-6469] fix: allow users without WAF or NL permissions to edit Rule in EF

src/helpers/convert-gql.js, src/views/RealTimeEvents/Blocks/azion-query-language.js
the behavior of the not contains operator was working the same as contains
<hr />
=> [UXE-6718] fix: behavior not contains in Real Time Events

src/router/routes/waf-rules-routes/index.js, src/views/WafRules/ListWafRulesTuning.vue
- Replace FieldMultiselectLazyLoader with MultiSelect component for domains filter
- Use WAF Rules domain service (v3) instead of Domains service (v4)
- Add comments about future migration back to v4 API
- Keep v4 implementation commented for future reference
<hr />
=> [UXE-6742] revert: domains filter back to API v3 in WAF Tuning

src/services/edge-application-services/v4/list-edge-applications-service.js, src/views/Domains/FormFields/FormFieldsCreateDomains.vue, src/views/Domains/FormFields/FormFieldsEditDomains.vue
In domains create or edit form, on the edge application selector, when you open the options is showing an js object instead of the name of the options, this pr fix this problem and parse object correctly to show only the name on dropdown
<hr />
=> [NO-ISSUE] fix: remove object view on domains edge application dropdown

src/templates/form-fields-inputs/fieldDropdownLazyLoaderDinaminc.vue, src/views/EdgeFirewallRulesEngine/FormFields/FormFieldsEdgeFirewallRulesEngine.vue
the network list dropdown is not loading as soon as it is enabled
It should load the network list dropdown as soon as it is enabled.
<hr />
=> [UXE-6492] fix: Edge Firewall Rules Engine - Network Lists no loading

src/helpers/convert-gql.js
fix: adjust format filter to fields that end with i
must filter correctly in real time metrics
<hr />
=> [UXE-6789] fix: Real Time Events - Unable to filter by Request URI Contains

src/views/EdgeApplicationsErrorResponses/FormFields/FormFieldsErrorResponses.vue
fix: change the origin id to null when there is no error response
must change the origin id to null when there are no response errors
<hr />
=> [UXE-6093] fix: change the origin id to null when there is no error response

src/helpers/convert-gql.js
fix: format filter query in convertGQLTotalRecords function
<hr />
=> [NO-ISSUE] fix: format filter query in convertGQLTotalRecords function

src/views/EdgeApplicationsCacheSettings/FormFields/FormFieldsEdgeApplicationCacheSettings.vue
fix: add watch for browser cache settings to reset maximum TTL value
must enter the correct values ​​when selecting No Cache
NO
<hr />
=> [UXE-6406] fix: add watch for browser cache settings to reset maximum TTL value

src/views/WafRules/ListWafRulesTuning.vue
add domain names to more details in waf tuning details drawer
<hr />
=> [UXE-6731] fix: add domain names to more details drawer in waf tuning

src/services/edge-firewall-rules-engine-services/v4/list-edge-firewall-rules-engine-service.js, src/tests/services/edge-firewall-rules-engine-services/v4/list-edge-firewall-rules-engine-service.test.js
[UXE-6797] Fix: timezone applied to the last modified column
<hr />
[UXE-6797]: https://aziontech.atlassian.net/browse/UXE-6797?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [UXE-6797] fix: timezone applied to Edge Firewall Rules Engine last modified column

.github/workflows/deploy-production.yml, .github/workflows/deploy-stage.yml, src/services/waf-rules-services/list-waf-rules-service.js, src/tests/services/waf-rules-services/list-waf-rules-service.test.js
This pull request includes changes to the `listWafRulesService` function and its corresponding test to increase the page size parameter from 200 to 2000. This adjustment ensures that more data is retrieved in a single request, improving efficiency.
Changes to `listWafRulesService`:
* [`src/services/waf-rules-services/list-waf-rules-service.js`](diffhunk://#diff-92e22065074c85d7b862a4fe589cc53e0d86f31fa2f6c0640bd1153da483f365L6-R6): Updated the `url` parameter in the `AxiosHttpClientAdapter.request` call to use `page_size=2000` instead of `page_size=200`.
Corresponding test updates:
* [`src/tests/services/waf-rules-services/list-waf-rules-service.test.js`](diffhunk://#diff-7df7be7c97fa220a48bf6bee63b2e4cf0f02d0cad72c6c4e343798e2d1be8686L81-R81): Modified the expected `url` in the test to …
=> [UXE-6870] hotfix: increase WAF rules page size to 2000 to fetch all rules

azion.config.mjs
This pull request focuses on enhancing the `createCookieRewriteRule` function in the `azion.config.mjs` file to support an optional `hasConfigMaxAge` parameter and refactors the way cookie rewrite rules are created.
Enhancements and refactoring:
* Modified `createCookieRewriteRule` function to accept an object parameter, including a new optional `hasConfigMaxAge` property.
* Updated the `setCookie` and `filterCookie` properties within `createCookieRewriteRule` to conditionally include `Max-Age` and `filterCookie` based on the `hasConfigMaxAge` property.
* Refactored the creation of cookie rewrite rules to use the new object parameter format, including specifying the `hasConfigMaxAge` property for each rule.
<hr />
=> [UXE-6834] chore: remove config max-age in azsid

src/templates/empty-drawer/index.vue
close waf tuning drawer when esc is pressed
<hr />
=> [UXE-6657] fix: close waf tuning drawer when esc is pressed

src/services/data-stream-services/load-data-stream-service.js, src/services/domains-services/load-domain-service.js, src/services/edge-application-origins-services/load-origin-service.js, src/services/edge-node-service-services/load-service-edge-node-service.js, src/services/edge-node-services/load-edge-node-service.js, src/services/edge-service-services/load-edge-service-services.js, src/services/users-services/load-user-service.js, src/services/variables-services/load-variable-service.js, src/tests/services/domains-services/load-domain-service.test.js, src/tests/services/edge-application-origins-services/load-origin-service.test.js, src/tests/services/edge-node-service-services/load-service-edge-node-service.test.js, src/tests/services/edge-node-services/load-edge-node-service.test.js, src/tests/services/edge-service-services/load-edge-service-services.test.js, src/tests/services/users-services/load-user-service.test.js, src/tests/services/variables-services/load-variable-service.test.js
[UXE-6131] fix: show correct message when returning status other than 200 
https://github.com/user-attachments/assets/8f4ec9ee-3daf-4767-b62f-54a2067c37fd
<hr />
[UXE-6131]: https://aziontech.atlassian.net/browse/UXE-6131?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [UXE-6131] fix: show correct message when returning status other than 200 

src/views/RealTimeEvents/Blocks/content-filter-block.vue
we need to check if the filter is custom before executing the instructions of the update time function which is only for days filter and not custom
NO
<hr />
=> [UXE-6816] fix: Real Time Events custom date not working properly

src/views/RealTimeEvents/Blocks/azion-query-language.vue
fix: prevent query execution when errors are present in the query
NO
<hr />
=> [UXE-6733] fix: prevent query execution when errors are present in the query

CODEOWNERS
This pull request includes a change to the `CODEOWNERS` file, updating the ownership assignments.
* [`CODEOWNERS`](diffhunk://#diff-fcf14c4b7b34fe7a11916195871ae66a59be87a395f28db73e345ebdc828085bL15-R15): Updated the ownership from `@aziontech/uxe-engineering @aziontech/qa` to `@vinigfer @HerbertJulio @aloisio-m-bastian`.
=> [NO-ISSUE] chore: Update CODEOWNERS

cypress/e2mock/edge-firewall/rules-engine/network-in-list.cy.js, cypress/support/selectors/product-selectors/edge-firewall.js, src/templates/form-fields-inputs/fieldDropdownLazyLoaderDinaminc.vue
fix error when loading an edge firewall rule that has a network lists criteria when getById request promise is resolved before the request to list all
<hr />
=> [UXE-6874] fix: edge firewall rule with network lists criteria not loading correctly

cypress/e2mock/feedback.cy.js, cypress/support/commands.js, cypress/support/selectors.js, cypress/support/selectors/block-selectors/header-block.js, src/layout/components/navbar/feedback.vue
This PR includes two main improvements to the feedback functionality:
- Added automatic form field reset after successful feedback submission
- Fields affected: type dropdown and description textarea
- Improves user experience by ensuring clean state for next submission
Added comprehensive E2E tests to ensure feedback form reliability:
- Test successful feedback submission flow
- Verify form reset functionality on dialog reopen
- Mock API responses for consistent test execution
- Follow best practices with fixtures and selectors
```javascript
✓ should submit feedback successfully
✓ should reset form fields when reopening the dialog
```
<hr />
=> [UXE-6702] fix: clear form fields after submission feedback

src/services/waf-rules-services/v4/list-waf-rules-service.js, src/views/EdgeFirewallRulesEngine/FormFields/FormFieldsEdgeFirewallRulesEngine.vue
[UXE-6879] Refactor: Return only name and ID when fetching WAF rules
<hr />
[UXE-6879]: https://aziontech.atlassian.net/browse/UXE-6879?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [UXE-6879] Refactor: Return only name and ID when fetching WAF rules

src/services/vulcan-services/list-vulcan-presets-service.js, src/tests/services/vulcan-services/list-vulcan-presets-service.test.js, src/views/ImportGitHub/FormFields/FormFieldsImportGithub.vue
remove mock data implementation for Vulcan presets
<hr />
=> [UXE-6986] revert: remove mock data implementation for Vulcan presets

src/services/v2/adapters/edge-dns-records-adapter.js, src/services/v2/edge-dns-records-service.js
[UXE-7575] fix: creating edge dns records with multiple value
<hr />
[UXE-7575]: https://aziontech.atlassian.net/browse/UXE-7575?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [UXE-7575] fix: creating edge dns records with multiple value

src/helpers/format-strings.js, src/helpers/index.js, src/services/v2/adapters/digital-certificates-adapter.js, src/services/v2/utils/adapter/parse-status-utils.js
[UXE-7724] fix: correct certificate status display when actual status is "failed"
<hr />
[UXE-7724]: https://aziontech.atlassian.net/browse/UXE-7724?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [UXE-7724] fix: correct certificate status display when actual status is "failed"

src/views/DigitalCertificates/FormFields/FormFieldsEditDigitalCertificates.vue
Alterado o texto do placeholder do campo
<hr />
=> [UXE-7726] fix: Digital Certificates - correct placeholder text for private key field

cypress/e2mock/edge-application/tabs-visibility.cy.js, cypress/fixtures/account/info/workload_flags.json, cypress/fixtures/edge-application/edge-application-item-v3.json, cypress/fixtures/edge-application/edge-application-item-v4.json, cypress/support/selectors/product-selectors/edge-application.js, src/views/EdgeApplications/TabsView.vue
- on Edge Application, conditionally show Origins and Error Responses tabs 
- add tests e2mock for validation
<hr />
=> [UXE-7498] feat: conditionally show Origins and Error Responses tabs

src/views/EdgeApplicationsFunctions/Drawer/index.vue, src/views/EdgeApplicationsFunctions/FormFields/FormFieldsEdgeApplicationsFunctions.vue, src/views/EdgeFirewallFunctions/Drawer/index.vue, src/views/EdgeFirewallFunctions/FormFields/FormFieldsEdgeApplicationsFunctions.vue, src/views/EdgeFunctions/CreateView.vue, src/views/EdgeFunctions/EditView.vue, src/views/EdgeFunctions/FormFields/FormFieldsCreateEdgeFunctions.vue, src/views/EdgeFunctions/FormFields/FormFieldsEditEdgeFunctions.vue
Issue:
https://aziontech.atlassian.net/browse/UXE-9029
On this pull request it is to blocking request update function instance in the Application and Firewall instance functions.
Block request submission for Application and Firewall instance functions when form validation fails.
Current Implementation Analysis
- Form submission is not being blocked when validation errors exist
- Application and Firewall functions can send invalid data to the server
- No proper feedback mechanism for validation states
=> [UXE-9029] fix: integration validation Form Builder blocking send request data

src/layout/components/navbar/share-url.vue, src/templates/edit-drawer-block/index.vue, src/views/EdgeApplicationsFunctions/Drawer/index.vue, src/views/EdgeFirewallFunctions/Drawer/index.vue
**Issue:**
https://aziontech.atlassian.net/browse/UXE-7843
**Figma:**
https://www.figma.com/design/0TY2pcUTBsndMlrs0ZUvQf/Console-UI--Migration-06-2024---06-2025-?node-id=18998-322760&t=vZWgoYP2M7FKU0no-0
Implemented the possibility to visual copy the current url with the query string params.
Tooltip on click
- Facilitate the share url with a visual indicator
- new file layout/navibar/share-url.vue
- added showShareUrl param to edit-drawer-block
=> [UXE-7843] feat: share block on Edit Function Instance

src/services/v2/utils/adapter/domainAdapter.js
fix load workload when has asterics in subdomain
<hr />
=> [UXE-9094] fix: asterisks as subdomain in workloads

src/services/v2/edge-connectors/edge-connectors-adapter.js
rename Edge Storage type to Object Storage in edge connectors
rename Edge Storage type to Object Storage in edge connectors
<hr />
=> chore: rename Edge Storage type to Object Storage in edge connectors
